In [2]:
library("lme4")
library("margins")
library("stargazer")
library("emmeans")
library("ggeffects")
library("broom")
library("broom.mixed")
library("MASS")
library("pscl")
library("fixest")
library("marginaleffects")
library("modelsummary")
library("glmmTMB")
library("dplyr")

In [3]:
packageVersion("marginaleffects")

[1] ‘0.25.1’

In [4]:
main_path <- "/home/20250114zmz_kd/"
data <- read.csv(paste0(main_path, "GraduationPaper/RevisetoJournal/9991-MergedData_similarity.csv"))
dim(data)

[1] 317275    103

In [5]:
print(names(data))

  [1] "X"
  [2] "work_id"
  [3] "PublishedYear"
  [4] "Facility"
  [5] "num_fac"
  [6] "paper_type"
  [7] "paper_language"
  [8] "novel_uzzi"
  [9] "novel_uzzi_bin"
 [10] "num_fac_scientist"
 [11] "ratio_fac_scientist"
 [12] "bin_fac_scientist"
 [13] "text_fac_scientist"
 [14] "fac_scientist_team"
 [15] "num_leader"
 [16] "ratio_leader"
 [17] "bin_leader"
 [18] "fac_scientist_lead_relratio"
 [19] "fac_scientist_lead_num"
 [20] "fac_scientist_lead_ratio"
 [21] "fac_scientist_lead_bin"
 [22] "fac_scientist_lead_text"
 [23] "CoType"
 [24] "CoType_Collaboration"
 [25] "CoType_Participation"
 [26] "CoType_Service"
 [27] "lnnum_author"
 [28] "lnnum_inst"
 [29] "lnnum_country"
 [30] "international"
 [31] "lnnum_reference"
 [32] "open_access"
 [33] "RaoStirling"
 [34] "SDG"
 [35] "lntimescited5"
 [36] "lntimescited10"
 [37] "lntimescitedall"
 [38] "lnab_length"
 [39] "lnmean_career_age"
 [40] "lnex_ld_avg_avgimpact"
 [41] "lnex_ld_avg_insthindex"
 [42] "ex_ld_bin_gs"
 [43] "ex_ld_ratio_gs"
 [44] "ex_ld_bin_sameC"
 [45] "ex_ld_ratio_sameC"
 [46] "lnex_ld_avg_before_year_prod_fac"
 [47] "lnex_ld_avg_before_year_with_ih"
 [48] "ex_ld_ratio_before_year_with_ih_bin"
 [49] "ex_ld_max_before_year_with_ih_bin"
 [50] "lnex_ld_avg_before_year_participation"
 [51] "ex_ld_ratio_before_year_participation_bin"
 [52] "ex_ld_max_before_year_participation_bin"
 [53] "lnex_ld_avg_before_year_co_lead"
 [54] "ex_ld_ratio_before_year_co_lead_bin"
 [55] "ex_ld_max_before_year_co_lead_bin"
 [56] "Agricultural.and.Biological.Sciences"
 [57] "Arts.and.Humanities"
 [58] "Biochemistry..Genetics.and.Molecular.Biology"
 [59] "Business..Management.and.Accounting"
 [60] "Chemical.Engineering"
 [61] "Chemistry"
 [62] "Computer.Science"
 [63] "Decision.Sciences"
 [64] "Dentistry"
 [65] "Earth.and.Planetary.Sciences"
 [66] "Economics..Econometrics.and.Finance"
 [67] "Energy"
 [68] "Engineering"
 [69] "Environmental.Science"
 [70] "Health.Professions"
 [71] "Immunology.and.Microbiology"
 [72] "Materials.Science"
 [73] "Mathematics"
 [74] "Medicine"
 [75] "Neuroscience"
 [76] "Nursing"
 [77] "Pharmacology..Toxicology.and.Pharmaceutics"
 [78] "Physics.and.Astronomy"
 [79] "Psychology"
 [80] "Social.Sciences"
 [81] "Veterinary"
 [82] "domain_Health.Sciences"
 [83] "domain_Life.Sciences"
 [84] "domain_Physical.Sciences"
 [85] "domain_Social.Sciences"
 [86] "sum"
 [87] "num_author"
 [88] "num_inst"
 [89] "num_country"
 [90] "num_reference"
 [91] "timescited5"
 [92] "timescited10"
 [93] "timescitedall"
 [94] "ab_length"
 [95] "mean_career_age"
 [96] "ex_ld_avg_avgimpact"
 [97] "ex_ld_avg_insthindex"
 [98] "ex_ld_avg_before_year_prod_fac"
 [99] "ex_ld_avg_before_year_with_ih"
[100] "ex_ld_avg_before_year_co_lead"
[101] "ex_ld_avg_before_year_participation"
[102] "knowledge_proximity_mean"
[103] "knowledge_proximity_max"

In [6]:
colSums(is.na(data))

                                           X
                                           0
                                     work_id
                                           0
                               PublishedYear
                                           0
                                    Facility
                                           0
                                     num_fac
                                           0
                                  paper_type
                                           0
                              paper_language
                                           0
                                  novel_uzzi
                                        2532
                              novel_uzzi_bin
                                           0
                           num_fac_scientist
                                           0
                         ratio_fac_scientist
                                           0
                           bin_fac_scientist
                                           0
                          text_fac_scientist
                                           0
                          fac_scientist_team
                                           0
                                  num_leader
                                           0
                                ratio_leader
                                           0
                                  bin_leader
                                           0
                 fac_scientist_lead_relratio
                                           0
                      fac_scientist_lead_num
                                           0
                    fac_scientist_lead_ratio
                                           0
                      fac_scientist_lead_bin
                                           0
                     fac_scientist_lead_text
                                           0
                                      CoType
                                           0
                        CoType_Collaboration
                                           0
                        CoType_Participation
                                           0
                              CoType_Service
                                           0
                                lnnum_author
                                           0
                                  lnnum_inst
                                           0
                               lnnum_country
                                           0
                               international
                                           0
                             lnnum_reference
                                           0
                                 open_access
                                           0
                                 RaoStirling
                                           0
                                         SDG
                                           0
                               lntimescited5
                                       14695
                              lntimescited10
                                       12880
                             lntimescitedall
                                           0
                                 lnab_length
                                           0
                           lnmean_career_age
                                           0
                       lnex_ld_avg_avgimpact
                                           0
                      lnex_ld_avg_insthindex
                                           0
                                ex_ld_bin_gs
                                           0
                              ex_ld_ratio_gs
                                           0
                             ex_ld_bin_sameC
                                           0
                           ex_ld_ratio_sameC
                                           0
            lnex_ld_avg_before_year_prod_fac
                                           0
             lnex_ld_avg_before_year_with_ih
                                           0
         ex_ld_ratio_before_year_with_ih_bin
                                           0
           ex_ld_max_before_year_with_ih_bin
                                           0
       lnex_ld_avg_before_year_participation
                                           0
   ex_ld_ratio_before_year_participation_bin
                                           0
     ex_ld_max_before_year_participation_bin
                                           0
             lnex_ld_avg_before_year_co_lead
                                           0
         ex_ld_ratio_before_year_co_lead_bin
                                           0
           ex_ld_max_before_year_co_lead_bin
                                           0
        Agricultural.and.Biological.Sciences
                                           0
                         Arts.and.Humanities
                                           0
Biochemistry..Genetics.and.Molecular.Biology
                                           0
         Business..Management.and.Accounting
                                           0
                        Chemical.Engineering
                                           0
                                   Chemistry
                                           0
                            Computer.Science
                                           0
                           Decision.Sciences
                                           0
                                   Dentistry
                                           0
                Earth.and.Planetary.Sciences
                                           0
         Economics..Econometrics.and.Finance
                                           0
                                      Energy
                                           0
                                 Engineering
                                           0
                       Environmental.Science
                                           0
                          Health.Professions
                                           0
                 Immunology.and.Microbiology
                                           0
                           Materials.Science
                                           0
                                 Mathematics
                                           0
                                    Medicine
                                           0
                                Neuroscience
                                           0
                                     Nursing
                                           0
  Pharmacology..Toxicology.and.Pharmaceutics
                                           0
                       Physics.and.Astronomy
                                           0
                                  Psychology
                                           0
                             Social.Sciences
                                           0
                                  Veterinary
                                           0
                      domain_Health.Sciences
                                           0
                        domain_Life.Sciences
                                           0
                    domain_Physical.Sciences
                                           0
                      domain_Social.Sciences
                                           0
                                         sum
                                           0
                                  num_author
                                           0
                                    num_inst
                                           0
                                 num_country
                                           0
                               num_reference
                                           0
                                 timescited5
                                       14695
                                timescited10
                                       12880
                               timescitedall
                                           0
                                   ab_length
                                           0
                             mean_career_age
                                           0
                         ex_ld_avg_avgimpact
                                           0
                        ex_ld_avg_insthindex
                                           0
              ex_ld_avg_before_year_prod_fac
                                           0
               ex_ld_avg_before_year_with_ih
                                           0
               ex_ld_avg_before_year_co_lead
                                           0
         ex_ld_avg_before_year_participation
                                           0
                    knowledge_proximity_mean
                                           0
                     knowledge_proximity_max
                                           0

In [7]:
# 把所有无限值替换成 NA
data[sapply(data, is.infinite)] <- NA

In [8]:
# data <- data %>% filter(!is.na(mean_career_age))
# data <- data %>% filter(!is.na(frac_hype_words))
# data <- data %>% filter(!is.na(source_hindex))
# data <- data %>% filter(!is.na(open_access))
# dim(data)

In [9]:
# 找出所有包含无限值的行和列
inf_mask <- sapply(data, function(col) is.infinite(col))
rows_with_inf <- apply(inf_mask, 1, any)  # 哪些行至少有一个Inf
cols_with_inf <- colnames(data)[apply(inf_mask, 2, any)]  # 哪些列有Inf

# 打印包含无限值的行数和列名
cat("包含无限值的行数:", sum(rows_with_inf), "\n")
cat("包含无限值的列名:", paste(cols_with_inf, collapse = ", "), "\n")

# 查看这些行具体内容
data_filt_with_inf <- data[rows_with_inf, c(cols_with_inf), drop=FALSE]
print(data_filt_with_inf)

包含无限值的行数: 0
包含无限值的列名:
data frame with 0 columns and 0 rows

In [10]:
data$Facility <- as.factor(data$Facility)

In [11]:
data$CoType <- factor(data$CoType)
data <- within(data, CoType <- relevel(CoType, ref = 'Service'))
data$paper_type <- factor(data$paper_type)
data <- within(data, paper_type <- relevel(paper_type, ref = 'review'))
data$text_fac_scientist <- factor(data$text_fac_scientist)
data <- within(data, text_fac_scientist <- relevel(text_fac_scientist, ref = 'NonStaffPart'))
data$fac_scientist_lead_text <- factor(data$fac_scientist_lead_text)
data <- within(data, fac_scientist_lead_text <- relevel(fac_scientist_lead_text, ref = 'NonStaffLead'))
data$open_access <- factor(data$open_access)
data <- within(data, open_access <- relevel(open_access, ref = 'False'))
data$SDG <- factor(data$SDG)
data <- within(data, SDG <- relevel(SDG, ref = 'False'))
data$ex_ld_bin_sameC <- factor(data$ex_ld_bin_sameC)
data <- within(data, ex_ld_bin_sameC <- relevel(ex_ld_bin_sameC, ref = 'NonSame'))
data$ex_ld_bin_gs <- factor(data$ex_ld_bin_gs)
data <- within(data, ex_ld_bin_gs <- relevel(ex_ld_bin_gs, ref = 'GlobalSouth'))
data$ex_ld_max_before_year_with_ih_bin <- factor(data$ex_ld_max_before_year_with_ih_bin)
data <- within(data, ex_ld_max_before_year_with_ih_bin <- relevel(ex_ld_max_before_year_with_ih_bin, ref = 'False'))
data$ex_ld_max_before_year_participation_bin <- factor(data$ex_ld_max_before_year_participation_bin)
data <- within(data, ex_ld_max_before_year_participation_bin <- relevel(ex_ld_max_before_year_participation_bin, ref = 'False'))
data$ex_ld_max_before_year_co_lead_bin <- factor(data$ex_ld_max_before_year_co_lead_bin)
data <- within(data, ex_ld_max_before_year_co_lead_bin <- relevel(ex_ld_max_before_year_co_lead_bin, ref = 'False'))
data$international <- factor(data$international)
data <- within(data, international <- relevel(international, ref = 'domestic'))

In [12]:
paper_level <- "lnnum_author + international + lnnum_reference + num_fac + SDG + lnmean_career_age"
ex_controls <- "lnex_ld_avg_avgimpact + lnex_ld_avg_insthindex + ex_ld_bin_gs + ex_ld_bin_sameC + knowledge_proximity_mean"
moderating <- "lnex_ld_avg_before_year_prod_fac + ex_ld_max_before_year_with_ih_bin"
moderating2 <- "lnex_ld_avg_before_year_prod_fac + ex_ld_max_before_year_participation_bin"
moderating3 <- "lnex_ld_avg_before_year_prod_fac + ex_ld_max_before_year_co_lead_bin"
disciplines <- "Agricultural.and.Biological.Sciences + Arts.and.Humanities + Biochemistry..Genetics.and.Molecular.Biology + Business..Management.and.Accounting + Chemical.Engineering + 
 Chemistry + Computer.Science + Decision.Sciences + Dentistry + Earth.and.Planetary.Sciences + 
Economics..Econometrics.and.Finance + Energy + Engineering + Environmental.Science + Health.Professions + 
Immunology.and.Microbiology + Materials.Science + Mathematics + Medicine + Neuroscience + Nursing +
Pharmacology..Toxicology.and.Pharmaceutics + Physics.and.Astronomy + Psychology + Social.Sciences + Veterinary "

In [13]:
paper_vars <- c("lnnum_author", "international", "lnnum_reference", "num_fac", "SDG", "lnmean_career_age")
ex_vars <- c("lnex_ld_avg_avgimpact", "lnex_ld_avg_insthindex", "ex_ld_bin_gs", "ex_ld_bin_sameC", "knowledge_proximity_mean")
moderating_var <- c("lnex_ld_avg_before_year_prod_fac", "ex_ld_max_before_year_with_ih_bin")
moderating2_var <- c("lnex_ld_avg_before_year_prod_fac", "ex_ld_max_before_year_participation_bin")
moderating3_var <- c("lnex_ld_avg_before_year_prod_fac", "ex_ld_max_before_year_co_lead_bin")
disciplines_vars <- c("Agricultural.and.Biological.Sciences", "Arts.and.Humanities", "Biochemistry..Genetics.and.Molecular.Biology", "Business..Management.and.Accounting",
                 "Chemical.Engineering", "Chemistry", "Computer.Science", "Decision.Sciences", "Dentistry",
                 "Earth.and.Planetary.Sciences", "Economics..Econometrics.and.Finance", "Energy", "Engineering",
                 "Environmental.Science + Health.Professions", "Immunology.and.Microbiology", "Materials.Science", "Mathematics",
                 "Medicine", "Neuroscience", "Nursing", "Pharmacology..Toxicology.and.Pharmaceutics", "Physics.and.Astronomy",
                 "Psychology", "Social.Sciences", "Veterinary")

In [14]:
cor_data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0),]
dim(cor_data)

[1] 294879    103

In [17]:
# 假设你要计算相关的变量都在 cor_data 里
# 找出一个包含你所有目标变量的列表
var_list <- c("novel_uzzi_bin", "bin_fac_scientist", "CoType_Collaboration", 
              "CoType_Participation", "CoType_Service", "lnnum_author", 
              "international", "lnnum_reference", "num_fac", "SDG", 
              "lnmean_career_age", "lnex_ld_avg_avgimpact", 
              "lnex_ld_avg_insthindex", "ex_ld_bin_gs", "ex_ld_bin_sameC", 
              "knowledge_proximity_mean", "lnex_ld_avg_before_year_prod_fac", 
              "ex_ld_max_before_year_with_ih_bin")

# 提取子集
cor_subset <- data[, var_list]

# 批量将因子转换为数值 (如果你有普通的字符型，建议先按你的代码转成 factor)
for (col in names(cor_subset)) {
  if (is.factor(cor_subset[[col]])) {
    # 将因子转为数字 (1, 2)，然后减去1变成 (0, 1)
    cor_subset[[col]] <- as.numeric(cor_subset[[col]]) - 1
  } else if (is.character(cor_subset[[col]])) {
    # 如果有遗漏的字符型，强制转为因子再转数值
    cor_subset[[col]] <- as.numeric(as.factor(cor_subset[[col]])) - 1
  }
}

# 检查一下是否全部变成了 numeric
str(cor_subset)

'data.frame':	317275 obs. of  18 variables:
 $ novel_uzzi_bin                   : num  1 1 0 0 0 1 0 1 0 0 ...
 $ bin_fac_scientist                : int  1 0 0 0 0 0 0 0 1 0 ...
 $ CoType_Collaboration             : int  1 0 0 0 0 0 0 0 1 0 ...
 $ CoType_Participation             : int  0 0 0 0 0 0 0 0 0 0 ...
 $ CoType_Service                   : int  0 1 1 1 1 1 1 1 0 1 ...
 $ lnnum_author                     : num  2.2 1.39 1.79 2.2 2.2 ...
 $ international                    : num  1 1 1 1 1 1 0 0 1 0 ...
 $ lnnum_reference                  : num  3.47 3.78 3.14 3.5 3.5 ...
 $ num_fac                          : num  1 1 1 2 2 1 1 1 1 1 ...
 $ SDG                              : num  1 0 0 1 1 0 0 1 1 0 ...
 $ lnmean_career_age                : num  3.59 3.09 3.29 3.1 3.1 ...
 $ lnex_ld_avg_avgimpact            : num  3.12 2.58 4.03 3.67 3.67 ...
 $ lnex_ld_avg_insthindex           : num  5.52 6.04 6.56 6.38 6.38 ...
 $ ex_ld_bin_gs                     : num  1 1 1 1 1 1 0 1 1 1 ...
 $ ex_ld_bin_sameC                  : num  0 0 1 1 1 0 0 0 0 1 ...
 $ knowledge_proximity_mean         : num  0 0.808 0.794 0.775 0.789 ...
 $ lnex_ld_avg_before_year_prod_fac : num  2.08 2.16 2.74 3.23 3.23 ...
 $ ex_ld_max_before_year_with_ih_bin: num  1 1 1 1 1 0 0 1 1 1 ...

In [20]:
# 第一步：指定北京大学（PKU）CRAN 镜像源进行安装
# install.packages("Hmisc", repos = "https://mirrors.pku.edu.cn/CRAN/")

# 第二步：安装完成后，加载它
library(Hmisc)

In [21]:
library(Hmisc)
# rcorr 要求输入为矩阵格式
res <- rcorr(as.matrix(cor_subset), type = "spearman")

# 查看相关系数
res$r 

# 查看显著性 P 值
res$P

                                  novel_uzzi_bin bin_fac_scientist
novel_uzzi_bin                     1.000000000   -0.0083476266
bin_fac_scientist                 -0.008347627    1.0000000000
CoType_Collaboration               0.004189531    0.7754436220
CoType_Participation              -0.018778700    0.5124924040
CoType_Service                     0.008347627   -1.0000000000
lnnum_author                      -0.030007947    0.2063308354
international                     -0.032332434    0.2792443403
lnnum_reference                    0.017926301   -0.0009084163
num_fac                            0.001110746    0.1922516541
SDG                                0.051631454   -0.0354879872
lnmean_career_age                 -0.011702665    0.0492260820
lnex_ld_avg_avgimpact             -0.026622022   -0.0182129260
lnex_ld_avg_insthindex            -0.013106378   -0.1040611328
ex_ld_bin_gs                       0.031214885   -0.0072156230
ex_ld_bin_sameC                   -0.001855764   -0.2220686926
knowledge_proximity_mean          -0.013366574    0.0055720809
lnex_ld_avg_before_year_prod_fac  -0.059692024    0.0562334083
ex_ld_max_before_year_with_ih_bin -0.005939797    0.2172964998
                                  CoType_Collaboration CoType_Participation
novel_uzzi_bin                     0.004189531         -0.0187786997
bin_fac_scientist                  0.775443622          0.5124924040
CoType_Collaboration               1.000000000         -0.1447834455
CoType_Participation              -0.144783446          1.0000000000
CoType_Service                    -0.775443622         -0.5124924040
lnnum_author                       0.080675599          0.2136169464
international                      0.192976993          0.1751525930
lnnum_reference                   -0.039007943          0.0516250973
num_fac                            0.138422930          0.1130209694
SDG                               -0.021691303         -0.0261125776
lnmean_career_age                  0.056201059          0.0007095452
lnex_ld_avg_avgimpact             -0.042053530          0.0286498499
lnex_ld_avg_insthindex            -0.078637170         -0.0561270917
ex_ld_bin_gs                       0.006964019         -0.0207779396
ex_ld_bin_sameC                   -0.161267214         -0.1286788813
knowledge_proximity_mean          -0.017202870          0.0321266909
lnex_ld_avg_before_year_prod_fac   0.014551187          0.0683319044
ex_ld_max_before_year_with_ih_bin  0.149604442          0.1370613249
                                  CoType_Service lnnum_author international
novel_uzzi_bin                     0.0083476266  -0.03000795  -0.03233243
bin_fac_scientist                 -1.0000000000   0.20633084   0.27924434
CoType_Collaboration              -0.7754436220   0.08067560   0.19297699
CoType_Participation              -0.5124924040   0.21361695   0.17515259
CoType_Service                     1.0000000000  -0.20633084  -0.27924434
lnnum_author                      -0.2063308354   1.00000000   0.33247460
international                     -0.2792443403   0.33247460   1.00000000
lnnum_reference                    0.0009084163   0.18781822   0.06634588
num_fac                           -0.1922516541   0.20025890   0.14622598
SDG                                0.0354879872   0.01499731  -0.02514283
lnmean_career_age                 -0.0492260820   0.04097890   0.04397100
lnex_ld_avg_avgimpact              0.0182129260   0.31959180   0.06892244
lnex_ld_avg_insthindex             0.1040611328  -0.01007819  -0.11219925
ex_ld_bin_gs                       0.0072156230  -0.03776225  -0.09908722
ex_ld_bin_sameC                    0.2220686926  -0.08091232  -0.43780826
knowledge_proximity_mean          -0.0055720809   0.10799314   0.05210381
lnex_ld_avg_before_year_prod_fac  -0.0562334083   0.16822636   0.12697388
ex_ld_max_before_year_with_ih_bin -0.2172964998   0.23393791   0.20712089
                                  lnnum_reference num_fac      SDG
novel_uzzi_bin                     0.0179263014    0.001110746  0.051631454
bin_fac_scientist                 -0.0009084163    0.192251654 -0.035487987
CoType_Collaboration              -0.0390079428    0.138422930 -0.021691303
CoType_Participation               0.0516250973    0.113020969 -0.026112578
CoType_Service                     0.0009084163   -0.192251654  0.035487987
lnnum_author                       0.1878182213    0.200258899  0.014997312
international                      0.0663458816    0.146225978 -0.025142831
lnnum_reference                    1.0000000000    0.113220925  0.059453561
num_fac                            0.1132209255    1.000000000 -0.025731499
SDG                                0.0594535609   -0.025731499  1.000000000
lnmean_career_age                  0.0270984086    0.050154564 -0.006445308
lnex_ld_avg_avgimpact              0.3987862107    0.140544301  0.052935917
lnex_ld_avg_insthindex             0.1001251778    0.062378010  0.004308462
ex_ld_bin_gs                      -0.0371980313    0.048152584 -0.005627520
ex_ld_bin_sameC                    0.0272254925   -0.089323033  0.032632160
knowledge_proximity_mean           0.1810163719    0.060987583  0.042655098
lnex_ld_avg_before_year_prod_fac   0.1203983986    0.236533707 -0.045417208
ex_ld_max_before_year_with_ih_bin  0.0845620625    0.147164819 -0.040755125
                                  lnmean_career_age lnex_ld_avg_avgimpact
novel_uzzi_bin                    -0.0117026648     -0.02662202
bin_fac_scientist                  0.0492260820     -0.01821293
CoType_Collaboration               0.0562010588     -0.04205353
CoType_Participation               0.0007095452      0.02864985
CoType_Service                    -0.0492260820      0.01821293
lnnum_author                       0.0409789032      0.31959180
international                      0.0439710013      0.06892244
lnnum_reference                    0.0270984086      0.39878621
num_fac                            0.0501545635      0.14054430
SDG                               -0.0064453075      0.05293592
lnmean_career_age                  1.0000000000      0.11097997
lnex_ld_avg_avgimpact              0.1109799713      1.00000000
lnex_ld_avg_insthindex            -0.0304463927      0.21451201
ex_ld_bin_gs                       0.0711018982      0.04890310
ex_ld_bin_sameC                    0.0557860508      0.07376208
knowledge_proximity_mean           0.0262901314      0.21893988
lnex_ld_avg_before_year_prod_fac   0.2281989175      0.22696526
ex_ld_max_before_year_with_ih_bin  0.1502719425      0.11010051
                                  lnex_ld_avg_insthindex ex_ld_bin_gs
novel_uzzi_bin                    -0.013106378            0.0312148847
bin_fac_scientist                 -0.104061133           -0.0072156230
CoType_Collaboration              -0.078637170            0.0069640190
CoType_Participation              -0.056127092           -0.0207779396
CoType_Service                     0.104061133            0.0072156230
lnnum_author                      -0.010078194           -0.0377622535
international                     -0.112199246           -0.0990872243
lnnum_reference                    0.100125178           -0.0371980313
num_fac                            0.062378010            0.0481525843
SDG                                0.004308462           -0.0056275199
lnmean_career_age                 -0.030446393            0.0711018982
lnex_ld_avg_avgimpact              0.214512013            0.0489030982
lnex_ld_avg_insthindex             1.000000000            0.1926159033
ex_ld_bin_gs                       0.192615903            1.0000000000
ex_ld_bin_sameC                    0.244362569            0.1643600670
knowledge_proximity_mean           0.019085446           -0.0028413932
lnex_ld_avg_before_year_prod_fac   0.061884714            0.0555719361
ex_ld_max_before_year_with_ih_bin -0.029518674            0.0009407081
                                  ex_ld_bin_sameC knowledge_proximity_mean
novel_uzzi_bin                    -0.001855764    -0.013366574
bin_fac_scientist                 -0.222068693     0.005572081
CoType_Collaboration              -0.161267214    -0.017202870
CoType_Participation              -0.128678881     0.032126691
CoType_Service                     0.222068693    -0.005572081
lnnum_author                      -0.080912316     0.107993135
international                     -0.437808260     0.052103814
lnnum_reference                    0.027225492     0.181016372
num_fac                           -0.089323033     0.060987583
SDG                                0.032632160     0.042655098
lnmean_career_age                  0.055786051     0.026290131
lnex_ld_avg_avgimpact              0.073762080     0.218939885
lnex_ld_avg_insthindex             0.244362569     0.019085446
ex_ld_bin_gs                       0.164360067    -0.002841393
ex_ld_bin_sameC                    1.000000000    -0.009390148
knowledge_proximity_mean          -0.009390148     1.000000000
lnex_ld_avg_before_year_prod_fac  -0.008312324     0.206693691
ex_ld_max_before_year_with_ih_bin -0.137434412     0.072154219
                                  lnex_ld_avg_before_year_prod_fac
novel_uzzi_bin                    -0.059692024
bin_fac_scientist                  0.056233408
CoType_Collaboration               0.014551187
CoType_Participation               0.068331904
CoType_Service                    -0.056233408
lnnum_author                       0.168226363
international                      0.126973882
lnnum_reference                    0.120398399
num_fac                            0.236533707
SDG                               -0.045417208
lnmean_career_age                  0.228198918
lnex_ld_avg_avgimpact              0.226965259
lnex_ld_avg_insthindex             0.061884714
ex_ld_bin_gs                       0.055571936
ex_ld_bin_sameC                   -0.008312324
knowledge_proximity_mean           0.206693691
lnex_ld_avg_before_year_prod_fac   1.000000000
ex_ld_max_before_year_with_ih_bin  0.483675896
                                  ex_ld_max_before_year_with_ih_bin
novel_uzzi_bin                    -0.0059397973
bin_fac_scientist                  0.2172964998
CoType_Collaboration               0.1496044423
CoType_Participation               0.1370613249
CoType_Service                    -0.2172964998
lnnum_author                       0.2339379086
international                      0.2071208948
lnnum_reference                    0.0845620625
num_fac                            0.1471648191
SDG                               -0.0407551246
lnmean_career_age                  0.1502719425
lnex_ld_avg_avgimpact              0.1101005147
lnex_ld_avg_insthindex            -0.0295186736
ex_ld_bin_gs                       0.0009407081
ex_ld_bin_sameC                   -0.1374344118
knowledge_proximity_mean           0.0721542186
lnex_ld_avg_before_year_prod_fac   0.4836758962
ex_ld_max_before_year_with_ih_bin  1.0000000000

                                  novel_uzzi_bin bin_fac_scientist
novel_uzzi_bin                              NA   2.575685e-06
bin_fac_scientist                 2.575685e-06             NA
CoType_Collaboration              1.828255e-02   0.000000e+00
CoType_Participation              0.000000e+00   0.000000e+00
CoType_Service                    2.575685e-06   0.000000e+00
lnnum_author                      0.000000e+00   0.000000e+00
international                     0.000000e+00   0.000000e+00
lnnum_reference                   0.000000e+00   6.088727e-01
num_fac                           5.315447e-01   0.000000e+00
SDG                               0.000000e+00   0.000000e+00
lnmean_career_age                 4.339995e-11   0.000000e+00
lnex_ld_avg_avgimpact             0.000000e+00   0.000000e+00
lnex_ld_avg_insthindex            1.549871e-13   0.000000e+00
ex_ld_bin_gs                      0.000000e+00   4.815761e-05
ex_ld_bin_sameC                   2.958861e-01   0.000000e+00
knowledge_proximity_mean          5.107026e-14   1.697527e-03
lnex_ld_avg_before_year_prod_fac  0.000000e+00   0.000000e+00
ex_ld_max_before_year_with_ih_bin 8.206449e-04   0.000000e+00
                                  CoType_Collaboration CoType_Participation
novel_uzzi_bin                    1.828255e-02         0.0000000
bin_fac_scientist                 0.000000e+00         0.0000000
CoType_Collaboration                        NA         0.0000000
CoType_Participation              0.000000e+00                NA
CoType_Service                    0.000000e+00         0.0000000
lnnum_author                      0.000000e+00         0.0000000
international                     0.000000e+00         0.0000000
lnnum_reference                   0.000000e+00         0.0000000
num_fac                           0.000000e+00         0.0000000
SDG                               0.000000e+00         0.0000000
lnmean_career_age                 0.000000e+00         0.6894031
lnex_ld_avg_avgimpact             0.000000e+00         0.0000000
lnex_ld_avg_insthindex            0.000000e+00         0.0000000
ex_ld_bin_gs                      8.757419e-05         0.0000000
ex_ld_bin_sameC                   0.000000e+00         0.0000000
knowledge_proximity_mean          0.000000e+00         0.0000000
lnex_ld_avg_before_year_prod_fac  2.220446e-16         0.0000000
ex_ld_max_before_year_with_ih_bin 0.000000e+00         0.0000000
                                  CoType_Service lnnum_author international
novel_uzzi_bin                    2.575685e-06   0.000000e+00  0
bin_fac_scientist                 0.000000e+00   0.000000e+00  0
CoType_Collaboration              0.000000e+00   0.000000e+00  0
CoType_Participation              0.000000e+00   0.000000e+00  0
CoType_Service                              NA   0.000000e+00  0
lnnum_author                      0.000000e+00             NA  0
international                     0.000000e+00   0.000000e+00 NA
lnnum_reference                   6.088727e-01   0.000000e+00  0
num_fac                           0.000000e+00   0.000000e+00  0
SDG                               0.000000e+00   0.000000e+00  0
lnmean_career_age                 0.000000e+00   0.000000e+00  0
lnex_ld_avg_avgimpact             0.000000e+00   0.000000e+00  0
lnex_ld_avg_insthindex            0.000000e+00   1.371712e-08  0
ex_ld_bin_gs                      4.815761e-05   0.000000e+00  0
ex_ld_bin_sameC                   0.000000e+00   0.000000e+00  0
knowledge_proximity_mean          1.697527e-03   0.000000e+00  0
lnex_ld_avg_before_year_prod_fac  0.000000e+00   0.000000e+00  0
ex_ld_max_before_year_with_ih_bin 0.000000e+00   0.000000e+00  0
                                  lnnum_reference num_fac   SDG
novel_uzzi_bin                    0.0000000       0.5315447 0.0000000000
bin_fac_scientist                 0.6088727       0.0000000 0.0000000000
CoType_Collaboration              0.0000000       0.0000000 0.0000000000
CoType_Participation              0.0000000       0.0000000 0.0000000000
CoType_Service                    0.6088727       0.0000000 0.0000000000
lnnum_author                      0.0000000       0.0000000 0.0000000000
international                     0.0000000       0.0000000 0.0000000000
lnnum_reference                          NA       0.0000000 0.0000000000
num_fac                           0.0000000              NA 0.0000000000
SDG                               0.0000000       0.0000000           NA
lnmean_career_age                 0.0000000       0.0000000 0.0002828917
lnex_ld_avg_avgimpact             0.0000000       0.0000000 0.0000000000
lnex_ld_avg_insthindex            0.0000000       0.0000000 0.0152311207
ex_ld_bin_gs                      0.0000000       0.0000000 0.0015252539
ex_ld_bin_sameC                   0.0000000       0.0000000 0.0000000000
knowledge_proximity_mean          0.0000000       0.0000000 0.0000000000
lnex_ld_avg_before_year_prod_fac  0.0000000       0.0000000 0.0000000000
ex_ld_max_before_year_with_ih_bin 0.0000000       0.0000000 0.0000000000
                                  lnmean_career_age lnex_ld_avg_avgimpact
novel_uzzi_bin                    4.339995e-11       0
bin_fac_scientist                 0.000000e+00       0
CoType_Collaboration              0.000000e+00       0
CoType_Participation              6.894031e-01       0
CoType_Service                    0.000000e+00       0
lnnum_author                      0.000000e+00       0
international                     0.000000e+00       0
lnnum_reference                   0.000000e+00       0
num_fac                           0.000000e+00       0
SDG                               2.828917e-04       0
lnmean_career_age                           NA       0
lnex_ld_avg_avgimpact             0.000000e+00      NA
lnex_ld_avg_insthindex            0.000000e+00       0
ex_ld_bin_gs                      0.000000e+00       0
ex_ld_bin_sameC                   0.000000e+00       0
knowledge_proximity_mean          0.000000e+00       0
lnex_ld_avg_before_year_prod_fac  0.000000e+00       0
ex_ld_max_before_year_with_ih_bin 0.000000e+00       0
                                  lnex_ld_avg_insthindex ex_ld_bin_gs
novel_uzzi_bin                    1.549871e-13           0.000000e+00
bin_fac_scientist                 0.000000e+00           4.815761e-05
CoType_Collaboration              0.000000e+00           8.757419e-05
CoType_Participation              0.000000e+00           0.000000e+00
CoType_Service                    0.000000e+00           4.815761e-05
lnnum_author                      1.371712e-08           0.000000e+00
international                     0.000000e+00           0.000000e+00
lnnum_reference                   0.000000e+00           0.000000e+00
num_fac                           0.000000e+00           0.000000e+00
SDG                               1.523112e-02           1.525254e-03
lnmean_career_age                 0.000000e+00           0.000000e+00
lnex_ld_avg_avgimpact             0.000000e+00           0.000000e+00
lnex_ld_avg_insthindex                      NA           0.000000e+00
ex_ld_bin_gs                      0.000000e+00                     NA
ex_ld_bin_sameC                   0.000000e+00           0.000000e+00
knowledge_proximity_mean          0.000000e+00           1.094936e-01
lnex_ld_avg_before_year_prod_fac  0.000000e+00           0.000000e+00
ex_ld_max_before_year_with_ih_bin 0.000000e+00           5.962005e-01
                                  ex_ld_bin_sameC knowledge_proximity_mean
novel_uzzi_bin                    2.958861e-01    5.107026e-14
bin_fac_scientist                 0.000000e+00    1.697527e-03
CoType_Collaboration              0.000000e+00    0.000000e+00
CoType_Participation              0.000000e+00    0.000000e+00
CoType_Service                    0.000000e+00    1.697527e-03
lnnum_author                      0.000000e+00    0.000000e+00
international                     0.000000e+00    0.000000e+00
lnnum_reference                   0.000000e+00    0.000000e+00
num_fac                           0.000000e+00    0.000000e+00
SDG                               0.000000e+00    0.000000e+00
lnmean_career_age                 0.000000e+00    0.000000e+00
lnex_ld_avg_avgimpact             0.000000e+00    0.000000e+00
lnex_ld_avg_insthindex            0.000000e+00    0.000000e+00
ex_ld_bin_gs                      0.000000e+00    1.094936e-01
ex_ld_bin_sameC                             NA    1.227853e-07
knowledge_proximity_mean          1.227853e-07              NA
lnex_ld_avg_before_year_prod_fac  2.838691e-06    0.000000e+00
ex_ld_max_before_year_with_ih_bin 0.000000e+00    0.000000e+00
                                  lnex_ld_avg_before_year_prod_fac
novel_uzzi_bin                    0.000000e+00
bin_fac_scientist                 0.000000e+00
CoType_Collaboration              2.220446e-16
CoType_Participation              0.000000e+00
CoType_Service                    0.000000e+00
lnnum_author                      0.000000e+00
international                     0.000000e+00
lnnum_reference                   0.000000e+00
num_fac                           0.000000e+00
SDG                               0.000000e+00
lnmean_career_age                 0.000000e+00
lnex_ld_avg_avgimpact             0.000000e+00
lnex_ld_avg_insthindex            0.000000e+00
ex_ld_bin_gs                      0.000000e+00
ex_ld_bin_sameC                   2.838691e-06
knowledge_proximity_mean          0.000000e+00
lnex_ld_avg_before_year_prod_fac            NA
ex_ld_max_before_year_with_ih_bin 0.000000e+00
                                  ex_ld_max_before_year_with_ih_bin
novel_uzzi_bin                    0.0008206449
bin_fac_scientist                 0.0000000000
CoType_Collaboration              0.0000000000
CoType_Participation              0.0000000000
CoType_Service                    0.0000000000
lnnum_author                      0.0000000000
international                     0.0000000000
lnnum_reference                   0.0000000000
num_fac                           0.0000000000
SDG                               0.0000000000
lnmean_career_age                 0.0000000000
lnex_ld_avg_avgimpact             0.0000000000
lnex_ld_avg_insthindex            0.0000000000
ex_ld_bin_gs                      0.5962004733
ex_ld_bin_sameC                   0.0000000000
knowledge_proximity_mean          0.0000000000
lnex_ld_avg_before_year_prod_fac  0.0000000000
ex_ld_max_before_year_with_ih_bin           NA

In [ ]:
# 1. 自定义一个函数来计算这5个指标
# 注意：务必加上 na.rm = TRUE，否则只要数据里有一个缺失值(NA)，结果就会变成 NA
get_desc_stats <- function(x) {
  c(Min    = min(x, na.rm = TRUE),
    Max    = max(x, na.rm = TRUE),
    Mean   = mean(x, na.rm = TRUE),
    Median = median(x, na.rm = TRUE),
    Std    = sd(x, na.rm = TRUE))
}
# 2. 将函数批量应用到 cor_subset 的每一列
# sapply 默认返回的是变量在列、指标在行的矩阵，所以我们用 t() 将它转置，让变量变成行
desc_matrix <- t(sapply(cor_subset, get_desc_stats))
# 3. 转成数据框，并统一保留 3 位小数，保持和相关系数矩阵一样整洁
desc_df <- as.data.frame(desc_matrix)
desc_df <- round(desc_df, 3)
# 4. 查看在屏幕上的结果
print(desc_df)
# 5. 导出为 CSV，方便复制进 Word
write.csv(desc_df, file = "descriptive_statistics.csv", row.names = TRUE, fileEncoding = "UTF-8")

print("成功！描述性统计已保存为 descriptive_statistics.csv")

In [22]:
# 1. 提取相关系数和 P 值
r_mat <- res$r
p_mat <- res$P
# 2. 创建一个和 r_mat 同等大小的字符矩阵，用于存放星号
stars_mat <- matrix("", nrow = nrow(r_mat), ncol = ncol(r_mat))
rownames(stars_mat) <- rownames(r_mat)
colnames(stars_mat) <- colnames(r_mat)
# 3. 按照学术规范根据 P 值打星号 (注意：有些变量如果是完全共线性或者对角线，P值可能为 NA)
p_mat[is.na(p_mat)] <- 1  # 把 NA 的 P 值当做 1 处理，避免报错
stars_mat[p_mat < 0.1]  <- "*"
stars_mat[p_mat < 0.05]  <- "**"
stars_mat[p_mat < 0.01] <- "***"
# 4. 把相关系数保留 3 位小数，并和星号拼接在一起
# sprintf("%.3f", r_mat) 保证 0.5 也会显示为 0.500，极其规整
formatted_mat <- matrix(paste0(sprintf("%.3f", r_mat), stars_mat), nrow = nrow(r_mat))
rownames(formatted_mat) <- rownames(r_mat)
colnames(formatted_mat) <- colnames(r_mat)
# 5. 学术界一般只看“下三角”，我们把上三角全部变为空白
formatted_mat[upper.tri(formatted_mat)] <- ""
# 6. 对角线都是自己和自己的相关，强行修改为 "1" 或者留空，这里设为 "1.000"
diag(formatted_mat) <- "1.000"
# 7. 转为数据框 (Data Frame) 准备导出
final_table <- as.data.frame(formatted_mat)
# 8. 导出为 CSV 文件
# 在 Jupyter 中，这个文件会保存在你当前 Notebook 所在的目录下
write.csv(final_table, file = "correlation_matrix_with_stars.csv", row.names = TRUE, fileEncoding = "UTF-8")
print("成功！带星号的相关性矩阵已经保存为 correlation_matrix_with_stars.csv")

[1] "成功！带星号的相关性矩阵已经保存为 correlation_matrix_with_stars.csv"

# H1:With > Without

In [80]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ text_fac_scientist + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_total_bin <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_total_bin)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
text_fac_scientistStaffPart                   0.064958   0.010007   6.491372
lnnum_author                                 -0.087859   0.007299 -12.037309
internationalinternational                   -0.046539   0.009593  -4.851415
lnnum_reference                               0.052699   0.008659   6.085706
num_fac                                       0.066565   0.006729   9.891698
SDGTrue                                       0.084342   0.008152  10.345615
lnmean_career_age                             0.011241   0.013083   0.859195
lnex_ld_avg_avgimpact                        -0.274514   0.007390 -37.145608
lnex_ld_avg_insthindex                       -0.049651   0.007529  -6.594531
ex_ld_bin_gsGlobalNorth                       0.309478   0.017496  17.688897
ex_ld_bin_sameCSame                          -0.060093   0.009446  -6.362007
knowledge_proximity_mean                     -0.802149   0.159844  -5.018336
lnex_ld_avg_before_year_prod_fac             -0.041687   0.004969  -8.390116
ex_ld_max_before_year_with_ih_binTrue         0.330851   0.011364  29.112770
Agricultural.and.Biological.Sciences          0.757284   0.023982  31.577715
Arts.and.Humanities                           1.771914   0.073062  24.252142
Biochemistry..Genetics.and.Molecular.Biology  0.598316   0.012615  47.430235
Business..Management.and.Accounting          -0.322807   0.087772  -3.677811
Chemical.Engineering                          0.163638   0.020827   7.856859
Chemistry                                     0.458149   0.011151  41.087601
Computer.Science                              0.940944   0.039592  23.766064
Decision.Sciences                             1.224480   0.189161   6.473203
Dentistry                                     1.953513   0.136163  14.346825
Earth.and.Planetary.Sciences                  0.754236   0.015279  49.363251
Economics..Econometrics.and.Finance          -0.074616   0.295394  -0.252599
Energy                                        0.236389   0.017920  13.191493
Engineering                                   0.328106   0.010479  31.309735
Environmental.Science                         0.578364   0.017491  33.066815
Health.Professions                            1.407802   0.128408  10.963473
Immunology.and.Microbiology                   0.235212   0.026916   8.738827
Materials.Science                             0.022472   0.009941   2.260628
Mathematics                                   0.575545   0.125411   4.589272
Medicine                                      0.867923   0.014849  58.450935
Neuroscience                                  0.520662   0.032659  15.942368
Nursing                                       1.051464   0.043247  24.312837
Pharmacology..Toxicology.and.Pharmaceutics    0.904900   0.048290  18.738914
Physics.and.Astronomy                        -0.258385   0.011470 -22.526093
Psychology                                    0.425675   0.157956   2.694900
Social.Sciences                               0.164627   0.156635   1.051028
Veterinary                                    0.601178   0.208368   2.885170
                                               Pr(>|z|)
text_fac_scientistStaffPart                  8.5058e-11 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   1.2258e-06 ***
lnnum_reference                              1.1598e-09 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            3.9023e-01
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                       4.2660e-11 ***
ex_ld_bin_gsGlobalNorth                       < 2.2e-16 ***
ex_ld_bin_sameCSame                          1.9913e-10 ***
knowledge_proximity_mean                     5.2121e-07 ***
lnex_ld_avg_before_year_prod_fac              < 2.2e-16 ***
ex_ld_max_before_year_with_ih_binTrue         < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          2.3524e-04 ***
Chemical.Engineering                         3.9389e-15 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            9.5947e-11 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          8.0058e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                   < 2.2e-16 ***
Materials.Science                            2.3782e-02 *
Mathematics                                  4.4480e-06 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   7.0410e-03 **
Social.Sciences                              2.9325e-01
Veterinary                                   3.9120e-03 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -181,551.0   Adj. Pseudo R2: 0.059007
           BIC:  364,248.1     Squared Cor.: 0.075641

In [15]:
# 每组 reg_class 的平均预测概率
pred_bin <- avg_predictions(model_total_bin, variables = "text_fac_scientist")
pred_bin

  text_fac_scientist estimate  std.error  statistic p.value      s.value
1 NonStaffPart       0.3584868 0.03152955 11.36987  5.907745e-30  97.09524
2 StaffPart          0.3723789 0.03201487 11.63144  2.852572e-31 101.46751
  conf.low  conf.high
1 0.2966901 0.4202836
2 0.3096309 0.4351269

In [16]:
fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_pred.csv")
write.csv(pred_bin, fname, row.names = FALSE)

In [17]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_total_bin,
                           keep = c("text_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\_bin\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   text\_fac\_scientistStaffPart                       & 0.065$^{***}$\\
                                                       & (0.010)\\
   lnnum\_author                                       & -0.088$^{***}$\\
                                                       & (0.007)\\
   internationalinternational                          & -0.046$^{***}$\\
                                                       & (0.010)\\
   lnnum\_reference                                    & 0.053$^{***}$\\
                                                       & (0.009)\\
   num\_fac                                            & 0.067$^{***}$\\
                                                       & (0.007)\\
   SDGTrue                                             & 0.084$^{***}$\\
                                                       & (0.008)\\
   lnmean\_career\_age                                 & 0.011\\
                                                       & (0.013)\\
   lnex\_ld\_avg\_avgimpact                            & -0.275$^{***}$\\
                                                       & (0.007)\\
   lnex\_ld\_avg\_insthindex                           & -0.050$^{***}$\\
                                                       & (0.008)\\
   ex\_ld\_bin\_gsGlobalNorth                          & 0.309$^{***}$\\
                                                       & (0.018)\\
   ex\_ld\_bin\_sameCSame                              & -0.060$^{***}$\\
                                                       & (0.009)\\
   knowledge\_proximity\_mean                          & -0.802$^{***}$\\
                                                       & (0.160)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & -0.042$^{***}$\\
                                                       & (0.005)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & 0.331$^{***}$\\
                                                       & (0.011)\\
   Agricultural.and.Biological.Sciences                & 0.757$^{***}$\\
                                                       & (0.024)\\
   Arts.and.Humanities                                 & 1.77$^{***}$\\
                                                       & (0.073)\\
   Biochemistry..Genetics.and.Molecular.Biology        & 0.598$^{***}$\\
                                                       & (0.013)\\
   Business..Management.and.Accounting                 & -0.323$^{***}$\\
                                                       & (0.088)\\
   Chemical.Engineering                                & 0.164$^{***}$\\
                                                       & (0.021)\\
   Chemistry                                           & 0.458$^{***}$\\
                                                       & (0.011)\\
   Computer.Science                                    & 0.941$^{***}$\\
                                                       & (0.040)\\
   Decision.Sciences                                   & 1.22$^{***}$\\
                                                       & (0.189)\\
   Dentistry                                           & 1.95$^{***}$\\
                                                       & (0.136)\\
   Earth.and.Planetary.Sciences                        & 0.754$^{***}$\\
                                                       & (0.015)\\
   Economics..Econometrics.and.Finance                 & -0.075\\
                                                       & (0.295)\\
   Energy                                              & 0.236$^{***}$\\
                                                       & (0.018)\\
   Engineering                                         & 0.328$^{***}$\\
                                                       & (0.011)\\
   Immunology.and.Microbiology                         & 0.235$^{***}$\\
                                                       & (0.027)\\
   Materials.Science                                   & 0.022$^{**}$\\
                                                       & (0.010)\\
   Mathematics                                         & 0.576$^{***}$\\
                                                       & (0.125)\\
   Medicine                                            & 0.868$^{***}$\\
                                                       & (0.015)\\
   Neuroscience                                        & 0.521$^{***}$\\
                                                       & (0.033)\\
   Nursing                                             & 1.05$^{***}$\\
                                                       & (0.043)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & 0.905$^{***}$\\
                                                       & (0.048)\\
   Physics.and.Astronomy                               & -0.258$^{***}$\\
                                                       & (0.011)\\
   Psychology                                          & 0.426$^{***}$\\
                                                       & (0.158)\\
   Social.Sciences                                     & 0.165\\
                                                       & (0.157)\\
   Veterinary                                          & 0.601$^{***}$\\
                                                       & (0.208)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 294,879\\
   Squared Correlation                                 & 0.07564\\
   Pseudo R$^2$                                        & 0.05947\\
   BIC                                                 & 364,248.1\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [18]:
margins_eff_bin <- avg_comparisons(model_total_bin, variables = "text_fac_scientist", comparison = 'ratio')
margins_eff_bin

  term               contrast                             estimate std.error
1 text_fac_scientist mean(StaffPart) / mean(NonStaffPart) 1.038752 0.006416741
  statistic p.value s.value conf.low conf.high predicted_lo predicted_hi
1 161.8815  0       Inf     1.026175 1.051328  0.284999     0.2984184
  predicted
1 0.284999

In [19]:
fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_comp_ratio.csv")
write.csv(margins_eff_bin, fname, row.names = FALSE)

# H1 different disciplines

In [20]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ text_fac_scientist + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_ps_bin <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Physical.Sciences==1), ], family = binomial("logit"), vcov = "hetero")
summary(model_ps_bin)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 253,575
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
text_fac_scientistStaffPart                   0.058672   0.010578   5.546590
lnnum_author                                 -0.176638   0.008240 -21.437916
internationalinternational                   -0.075425   0.010529  -7.163785
lnnum_reference                               0.077542   0.009242   8.390263
num_fac                                       0.102222   0.007275  14.051730
SDGTrue                                       0.032981   0.008921   3.696875
lnmean_career_age                            -0.050889   0.014203  -3.583109
lnex_ld_avg_avgimpact                        -0.223156   0.008253 -27.037882
lnex_ld_avg_insthindex                       -0.017083   0.008233  -2.075037
ex_ld_bin_gsGlobalNorth                       0.299839   0.018712  16.023652
ex_ld_bin_sameCSame                          -0.054127   0.010396  -5.206483
knowledge_proximity_mean                     -0.265372   0.175050  -1.515974
lnex_ld_avg_before_year_prod_fac             -0.034971   0.005353  -6.532758
ex_ld_max_before_year_with_ih_binTrue         0.343501   0.013054  26.313915
Agricultural.and.Biological.Sciences          1.051566   0.036817  28.561583
Arts.and.Humanities                           1.795034   0.075896  23.651325
Biochemistry..Genetics.and.Molecular.Biology  0.770956   0.014361  53.684789
Business..Management.and.Accounting          -0.283520   0.087253  -3.249419
Chemical.Engineering                          0.179605   0.020984   8.558948
Chemistry                                     0.423581   0.011992  35.321606
Computer.Science                              0.877654   0.040528  21.655498
Decision.Sciences                             1.336985   0.194211   6.884193
Dentistry                                     2.421581   0.205616  11.777186
Earth.and.Planetary.Sciences                  0.773428   0.015588  49.615476
Economics..Econometrics.and.Finance          -0.080795   0.298150  -0.270988
Energy                                        0.237381   0.018333  12.948013
Engineering                                   0.353230   0.011150  31.680948
Environmental.Science                         0.500540   0.018861  26.538824
Health.Professions                            1.641511   0.147726  11.111851
Immunology.and.Microbiology                   0.519050   0.071181   7.291947
Materials.Science                            -0.002942   0.010898  -0.269917
Mathematics                                   0.559849   0.126642   4.420734
Medicine                                      0.974995   0.022659  43.028515
Neuroscience                                  0.709970   0.059065  12.020127
Nursing                                       1.319165   0.067134  19.649698
Pharmacology..Toxicology.and.Pharmaceutics    0.849702   0.066617  12.755071
Physics.and.Astronomy                        -0.244162   0.012115 -20.153327
Psychology                                   -0.519308   0.277229  -1.873207
Social.Sciences                               0.257857   0.182609   1.412070
Veterinary                                    0.739032   0.537004   1.376214
                                               Pr(>|z|)
text_fac_scientistStaffPart                  2.9130e-08 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   7.8480e-13 ***
lnnum_reference                               < 2.2e-16 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                      2.1827e-04 ***
lnmean_career_age                            3.3953e-04 ***
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                       3.7983e-02 *
ex_ld_bin_gsGlobalNorth                       < 2.2e-16 ***
ex_ld_bin_sameCSame                          1.9245e-07 ***
knowledge_proximity_mean                     1.2953e-01
lnex_ld_avg_before_year_prod_fac             6.4569e-11 ***
ex_ld_max_before_year_with_ih_binTrue         < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          1.1564e-03 **
Chemical.Engineering                          < 2.2e-16 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            5.8116e-12 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          7.8640e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                  3.0551e-13 ***
Materials.Science                            7.8722e-01
Mathematics                                  9.8366e-06 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   6.1040e-02 .
Social.Sciences                              1.5793e-01
Veterinary                                   1.6876e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -153,671.4   Adj. Pseudo R2: 0.063687
           BIC:  308,475.1     Squared Cor.: 0.081035

In [21]:
margins_eff_ps_bin <- avg_comparisons(model_ps_bin, variables = "text_fac_scientist", comparison = 'ratio')
margins_eff_ps_bin

  term               contrast                             estimate std.error
1 text_fac_scientist mean(StaffPart) / mean(NonStaffPart) 1.035422 0.006776173
  statistic p.value s.value conf.low conf.high predicted_lo predicted_hi
1 152.8034  0       Inf     1.022141 1.048703  0.2837276    0.295801
  predicted
1 0.2837276

In [22]:
fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_ps_comp_ratio.csv")
write.csv(margins_eff_ps_bin, fname, row.names = FALSE)

In [23]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_ps_bin,
                           keep = c("text_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\_bin\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   text\_fac\_scientistStaffPart                       & 0.059$^{***}$\\
                                                       & (0.011)\\
   lnnum\_author                                       & -0.177$^{***}$\\
                                                       & (0.008)\\
   internationalinternational                          & -0.075$^{***}$\\
                                                       & (0.011)\\
   lnnum\_reference                                    & 0.077$^{***}$\\
                                                       & (0.009)\\
   num\_fac                                            & 0.102$^{***}$\\
                                                       & (0.007)\\
   SDGTrue                                             & 0.033$^{***}$\\
                                                       & (0.009)\\
   lnmean\_career\_age                                 & -0.051$^{***}$\\
                                                       & (0.014)\\
   lnex\_ld\_avg\_avgimpact                            & -0.223$^{***}$\\
                                                       & (0.008)\\
   lnex\_ld\_avg\_insthindex                           & -0.017$^{**}$\\
                                                       & (0.008)\\
   ex\_ld\_bin\_gsGlobalNorth                          & 0.300$^{***}$\\
                                                       & (0.019)\\
   ex\_ld\_bin\_sameCSame                              & -0.054$^{***}$\\
                                                       & (0.010)\\
   knowledge\_proximity\_mean                          & -0.265\\
                                                       & (0.175)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & -0.035$^{***}$\\
                                                       & (0.005)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & 0.344$^{***}$\\
                                                       & (0.013)\\
   Agricultural.and.Biological.Sciences                & 1.05$^{***}$\\
                                                       & (0.037)\\
   Arts.and.Humanities                                 & 1.80$^{***}$\\
                                                       & (0.076)\\
   Biochemistry..Genetics.and.Molecular.Biology        & 0.771$^{***}$\\
                                                       & (0.014)\\
   Business..Management.and.Accounting                 & -0.284$^{***}$\\
                                                       & (0.087)\\
   Chemical.Engineering                                & 0.180$^{***}$\\
                                                       & (0.021)\\
   Chemistry                                           & 0.424$^{***}$\\
                                                       & (0.012)\\
   Computer.Science                                    & 0.878$^{***}$\\
                                                       & (0.041)\\
   Decision.Sciences                                   & 1.34$^{***}$\\
                                                       & (0.194)\\
   Dentistry                                           & 2.42$^{***}$\\
                                                       & (0.206)\\
   Earth.and.Planetary.Sciences                        & 0.773$^{***}$\\
                                                       & (0.016)\\
   Economics..Econometrics.and.Finance                 & -0.081\\
                                                       & (0.298)\\
   Energy                                              & 0.237$^{***}$\\
                                                       & (0.018)\\
   Engineering                                         & 0.353$^{***}$\\
                                                       & (0.011)\\
   Immunology.and.Microbiology                         & 0.519$^{***}$\\
                                                       & (0.071)\\
   Materials.Science                                   & -0.003\\
                                                       & (0.011)\\
   Mathematics                                         & 0.560$^{***}$\\
                                                       & (0.127)\\
   Medicine                                            & 0.975$^{***}$\\
                                                       & (0.023)\\
   Neuroscience                                        & 0.710$^{***}$\\
                                                       & (0.059)\\
   Nursing                                             & 1.32$^{***}$\\
                                                       & (0.067)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & 0.850$^{***}$\\
                                                       & (0.067)\\
   Physics.and.Astronomy                               & -0.244$^{***}$\\
                                                       & (0.012)\\
   Psychology                                          & -0.519$^{*}$\\
                                                       & (0.277)\\
   Social.Sciences                                     & 0.258\\
                                                       & (0.183)\\
   Veterinary                                          & 0.739\\
                                                       & (0.537)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 253,575\\
   Squared Correlation                                 & 0.08103\\
   Pseudo R$^2$                                        & 0.06424\\
   BIC                                                 & 308,475.1\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [24]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ text_fac_scientist + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_ls_bin <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Life.Sciences==1), ], family = binomial("logit"), vcov = "hetero")
summary(model_ls_bin)

NOTE: 1 fixed-effect (1 observation) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 77,590
Fixed-effects: PublishedYear: 48
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
text_fac_scientistStaffPart                   0.131165   0.022359   5.866369
lnnum_author                                  0.232568   0.016875  13.781964
internationalinternational                    0.091356   0.017481   5.225962
lnnum_reference                               0.100861   0.017830   5.656683
num_fac                                      -0.074282   0.012579  -5.904985
SDGTrue                                       0.157392   0.015172  10.373735
lnmean_career_age                             0.149261   0.024350   6.129892
lnex_ld_avg_avgimpact                        -0.386505   0.014080 -27.451053
lnex_ld_avg_insthindex                       -0.136701   0.014241  -9.599456
ex_ld_bin_gsGlobalNorth                       0.056788   0.039531   1.436543
ex_ld_bin_sameCSame                          -0.092207   0.017008  -5.421367
knowledge_proximity_mean                     -2.443432   0.285353  -8.562850
lnex_ld_avg_before_year_prod_fac             -0.035097   0.010247  -3.425207
ex_ld_max_before_year_with_ih_binTrue         0.260074   0.018276  14.230347
Agricultural.and.Biological.Sciences          0.391854   0.028086  13.951869
Arts.and.Humanities                           1.027259   0.304074   3.378319
Biochemistry..Genetics.and.Molecular.Biology -0.103220   0.029771  -3.467152
Business..Management.and.Accounting          -0.230882   0.492183  -0.469097
Chemical.Engineering                          0.293812   0.134716   2.180976
Chemistry                                     0.543994   0.023374  23.273208
Computer.Science                              0.738231   0.067573  10.924934
Decision.Sciences                            -0.319700   0.546091  -0.585433
Dentistry                                     0.626973   0.222953   2.812135
Earth.and.Planetary.Sciences                  0.891483   0.076566  11.643246
Energy                                        0.183032   0.061902   2.956807
Engineering                                   0.499469   0.031436  15.888388
Environmental.Science                        -0.019415   0.031138  -0.623516
Health.Professions                            0.486035   0.349923   1.388979
Immunology.and.Microbiology                   0.083949   0.029658   2.830596
Materials.Science                             0.130027   0.019726   6.591540
Mathematics                                   1.028724   0.532065   1.933457
Medicine                                      0.502928   0.018613  27.019854
Neuroscience                                  0.282962   0.034252   8.261163
Nursing                                       0.640394   0.051444  12.448384
Pharmacology..Toxicology.and.Pharmaceutics    0.611335   0.050707  12.056296
Physics.and.Astronomy                         0.433180   0.031402  13.794851
Psychology                                    0.433378   0.215389   2.012071
Social.Sciences                               0.407445   0.390226   1.044124
Veterinary                                    0.165791   0.235094   0.705214
                                               Pr(>|z|)
text_fac_scientistStaffPart                  4.4544e-09 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   1.7325e-07 ***
lnnum_reference                              1.5433e-08 ***
num_fac                                      3.5268e-09 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            8.7939e-10 ***
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                        < 2.2e-16 ***
ex_ld_bin_gsGlobalNorth                      1.5085e-01
ex_ld_bin_sameCSame                          5.9145e-08 ***
knowledge_proximity_mean                      < 2.2e-16 ***
lnex_ld_avg_before_year_prod_fac             6.1433e-04 ***
ex_ld_max_before_year_with_ih_binTrue         < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                          7.2931e-04 ***
Biochemistry..Genetics.and.Molecular.Biology 5.2600e-04 ***
Business..Management.and.Accounting          6.3900e-01
Chemical.Engineering                         2.9185e-02 *
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            5.5826e-01
Dentistry                                    4.9214e-03 **
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Energy                                       3.1084e-03 **
Engineering                                   < 2.2e-16 ***
Environmental.Science                        5.3295e-01
Health.Professions                           1.6484e-01
Immunology.and.Microbiology                  4.6461e-03 **
Materials.Science                            4.3529e-11 ***
Mathematics                                  5.3180e-02 .
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   4.4212e-02 *
Social.Sciences                              2.9643e-01
Veterinary                                   4.8068e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -50,616.2   Adj. Pseudo R2: 0.054544
           BIC: 102,211.9     Squared Cor.: 0.07536

In [25]:
margins_eff_ls_bin <- avg_comparisons(model_ls_bin, variables = "text_fac_scientist", comparison = 'ratio')
margins_eff_ls_bin

  term               contrast                             estimate std.error
1 text_fac_scientist mean(StaffPart) / mean(NonStaffPart) 1.065502 0.0144741
  statistic p.value s.value conf.low conf.high predicted_lo predicted_hi
1 73.61439  0       Inf     1.037133 1.09387   0.3164041    0.3454315
  predicted
1 0.3164041

In [26]:
fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_ls_comp_ratio.csv")
write.csv(margins_eff_ls_bin, fname, row.names = FALSE)

In [27]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_ls_bin,
                           keep = c("text_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\_bin\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   text\_fac\_scientistStaffPart                       & 0.131$^{***}$\\
                                                       & (0.022)\\
   lnnum\_author                                       & 0.233$^{***}$\\
                                                       & (0.017)\\
   internationalinternational                          & 0.091$^{***}$\\
                                                       & (0.018)\\
   lnnum\_reference                                    & 0.101$^{***}$\\
                                                       & (0.018)\\
   num\_fac                                            & -0.074$^{***}$\\
                                                       & (0.013)\\
   SDGTrue                                             & 0.157$^{***}$\\
                                                       & (0.015)\\
   lnmean\_career\_age                                 & 0.149$^{***}$\\
                                                       & (0.024)\\
   lnex\_ld\_avg\_avgimpact                            & -0.387$^{***}$\\
                                                       & (0.014)\\
   lnex\_ld\_avg\_insthindex                           & -0.137$^{***}$\\
                                                       & (0.014)\\
   ex\_ld\_bin\_gsGlobalNorth                          & 0.057\\
                                                       & (0.040)\\
   ex\_ld\_bin\_sameCSame                              & -0.092$^{***}$\\
                                                       & (0.017)\\
   knowledge\_proximity\_mean                          & -2.44$^{***}$\\
                                                       & (0.285)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & -0.035$^{***}$\\
                                                       & (0.010)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & 0.260$^{***}$\\
                                                       & (0.018)\\
   Agricultural.and.Biological.Sciences                & 0.392$^{***}$\\
                                                       & (0.028)\\
   Arts.and.Humanities                                 & 1.03$^{***}$\\
                                                       & (0.304)\\
   Biochemistry..Genetics.and.Molecular.Biology        & -0.103$^{***}$\\
                                                       & (0.030)\\
   Business..Management.and.Accounting                 & -0.231\\
                                                       & (0.492)\\
   Chemical.Engineering                                & 0.294$^{**}$\\
                                                       & (0.135)\\
   Chemistry                                           & 0.544$^{***}$\\
                                                       & (0.023)\\
   Computer.Science                                    & 0.738$^{***}$\\
                                                       & (0.068)\\
   Decision.Sciences                                   & -0.320\\
                                                       & (0.546)\\
   Dentistry                                           & 0.627$^{***}$\\
                                                       & (0.223)\\
   Earth.and.Planetary.Sciences                        & 0.891$^{***}$\\
                                                       & (0.077)\\
   Energy                                              & 0.183$^{***}$\\
                                                       & (0.062)\\
   Engineering                                         & 0.499$^{***}$\\
                                                       & (0.031)\\
   Immunology.and.Microbiology                         & 0.084$^{***}$\\
                                                       & (0.030)\\
   Materials.Science                                   & 0.130$^{***}$\\
                                                       & (0.020)\\
   Mathematics                                         & 1.03$^{*}$\\
                                                       & (0.532)\\
   Medicine                                            & 0.503$^{***}$\\
                                                       & (0.019)\\
   Neuroscience                                        & 0.283$^{***}$\\
                                                       & (0.034)\\
   Nursing                                             & 0.640$^{***}$\\
                                                       & (0.051)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & 0.611$^{***}$\\
                                                       & (0.051)\\
   Physics.and.Astronomy                               & 0.433$^{***}$\\
                                                       & (0.031)\\
   Psychology                                          & 0.433$^{**}$\\
                                                       & (0.215)\\
   Social.Sciences                                     & 0.407\\
                                                       & (0.390)\\
   Veterinary                                          & 0.166\\
                                                       & (0.235)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 77,590\\
   Squared Correlation                                 & 0.07536\\
   Pseudo R$^2$                                        & 0.05615\\
   BIC                                                 & 102,211.9\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [28]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ text_fac_scientist + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_hs_bin <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Health.Sciences==1), ], family = binomial("logit"), vcov = "hetero")
summary(model_hs_bin)

NOTE: 6 fixed-effects (8 observations) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 33,409
Fixed-effects: PublishedYear: 40
Standard-errors: Heteroskedasticity-robust
                                               Estimate Std. Error    z value
text_fac_scientistStaffPart                    0.388395   0.038336   10.13135
lnnum_author                                   0.319584   0.026505   12.05740
internationalinternational                     0.058681   0.026496    2.21472
lnnum_reference                                0.110130   0.027640    3.98449
num_fac                                       -0.123160   0.020739   -5.93845
SDGTrue                                        0.224109   0.023466    9.55045
lnmean_career_age                              0.184938   0.038681    4.78107
lnex_ld_avg_avgimpact                         -0.334968   0.022019  -15.21267
lnex_ld_avg_insthindex                        -0.120245   0.021503   -5.59208
ex_ld_bin_gsGlobalNorth                        0.232135   0.061719    3.76115
ex_ld_bin_sameCSame                           -0.125016   0.026060   -4.79718
knowledge_proximity_mean                      -1.034300   0.403750   -2.56173
lnex_ld_avg_before_year_prod_fac              -0.067678   0.016063   -4.21320
ex_ld_max_before_year_with_ih_binTrue          0.174603   0.027725    6.29777
Agricultural.and.Biological.Sciences          -0.119140   0.053643   -2.22098
Arts.and.Humanities                            0.837592   0.422883    1.98067
Biochemistry..Genetics.and.Molecular.Biology  -0.230676   0.028629   -8.05734
Business..Management.and.Accounting          -11.719434   0.061636 -190.13831
Chemical.Engineering                          -0.303442   0.275191   -1.10266
Chemistry                                      0.054479   0.038364    1.42006
Computer.Science                               0.602351   0.090014    6.69177
Decision.Sciences                             -1.302208   0.829665   -1.56956
Dentistry                                      0.962250   0.145374    6.61911
Earth.and.Planetary.Sciences                   0.808630   0.194574    4.15591
Economics..Econometrics.and.Finance           10.581434   0.121564   87.04390
Energy                                        -0.158676   0.106370   -1.49173
Engineering                                    0.654440   0.056453   11.59269
Environmental.Science                          0.143987   0.059495    2.42016
Health.Professions                             0.605211   0.142642    4.24288
Immunology.and.Microbiology                   -0.339682   0.038770   -8.76157
Materials.Science                             -0.384766   0.038301  -10.04588
Mathematics                                    0.757252   0.572317    1.32313
Medicine                                       0.208306   0.080889    2.57520
Neuroscience                                   0.230627   0.062468    3.69191
Nursing                                        0.688529   0.068655   10.02888
Pharmacology..Toxicology.and.Pharmaceutics     0.604080   0.084218    7.17284
Physics.and.Astronomy                          0.112172   0.057862    1.93861
Psychology                                     0.865161   0.377476    2.29196
Social.Sciences                                0.783469   0.583936    1.34170
Veterinary                                     0.207268   0.205448    1.00886
                                               Pr(>|z|)
text_fac_scientistStaffPart                   < 2.2e-16 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   2.6779e-02 *
lnnum_reference                              6.7624e-05 ***
num_fac                                      2.8772e-09 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            1.7436e-06 ***
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                       2.2437e-08 ***
ex_ld_bin_gsGlobalNorth                      1.6914e-04 ***
ex_ld_bin_sameCSame                          1.6091e-06 ***
knowledge_proximity_mean                     1.0415e-02 *
lnex_ld_avg_before_year_prod_fac             2.5177e-05 ***
ex_ld_max_before_year_with_ih_binTrue        3.0196e-10 ***
Agricultural.and.Biological.Sciences         2.6352e-02 *
Arts.and.Humanities                          4.7628e-02 *
Biochemistry..Genetics.and.Molecular.Biology 7.7973e-16 ***
Business..Management.and.Accounting           < 2.2e-16 ***
Chemical.Engineering                         2.7018e-01
Chemistry                                    1.5559e-01
Computer.Science                             2.2049e-11 ***
Decision.Sciences                            1.1652e-01
Dentistry                                    3.6137e-11 ***
Earth.and.Planetary.Sciences                 3.2400e-05 ***
Economics..Econometrics.and.Finance           < 2.2e-16 ***
Energy                                       1.3577e-01
Engineering                                   < 2.2e-16 ***
Environmental.Science                        1.5514e-02 *
Health.Professions                           2.2067e-05 ***
Immunology.and.Microbiology                   < 2.2e-16 ***
Materials.Science                             < 2.2e-16 ***
Mathematics                                  1.8579e-01
Medicine                                     1.0018e-02 *
Neuroscience                                 2.2258e-04 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics   7.3459e-13 ***
Physics.and.Astronomy                        5.2549e-02 .
Psychology                                   2.1908e-02 *
Social.Sciences                              1.7969e-01
Veterinary                                   3.1304e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -21,581.4   Adj. Pseudo R2: 0.057238
           BIC:  43,996.1     Squared Cor.: 0.081599

In [29]:
margins_eff_hs_bin <- avg_comparisons(model_hs_bin, variables = "text_fac_scientist", comparison = 'ratio')
margins_eff_hs_bin

  term               contrast                             estimate std.error
1 text_fac_scientist mean(StaffPart) / mean(NonStaffPart) 1.16192  0.04168972
  statistic p.value       s.value  conf.low conf.high predicted_lo predicted_hi
1 27.87066  6.052872e-171 565.4521 1.08021  1.24363   0.7082483    0.7816464
  predicted
1 0.7082483

In [30]:
fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_hs_comp_ratio.csv")
write.csv(margins_eff_hs_bin, fname, row.names = FALSE)

In [31]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_hs_bin,
                           keep = c("text_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\_bin\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   text\_fac\_scientistStaffPart                       & 0.388$^{***}$\\
                                                       & (0.038)\\
   lnnum\_author                                       & 0.320$^{***}$\\
                                                       & (0.026)\\
   internationalinternational                          & 0.059$^{**}$\\
                                                       & (0.026)\\
   lnnum\_reference                                    & 0.110$^{***}$\\
                                                       & (0.028)\\
   num\_fac                                            & -0.123$^{***}$\\
                                                       & (0.021)\\
   SDGTrue                                             & 0.224$^{***}$\\
                                                       & (0.024)\\
   lnmean\_career\_age                                 & 0.185$^{***}$\\
                                                       & (0.039)\\
   lnex\_ld\_avg\_avgimpact                            & -0.335$^{***}$\\
                                                       & (0.022)\\
   lnex\_ld\_avg\_insthindex                           & -0.120$^{***}$\\
                                                       & (0.021)\\
   ex\_ld\_bin\_gsGlobalNorth                          & 0.232$^{***}$\\
                                                       & (0.062)\\
   ex\_ld\_bin\_sameCSame                              & -0.125$^{***}$\\
                                                       & (0.026)\\
   knowledge\_proximity\_mean                          & -1.03$^{**}$\\
                                                       & (0.404)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & -0.068$^{***}$\\
                                                       & (0.016)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & 0.175$^{***}$\\
                                                       & (0.028)\\
   Agricultural.and.Biological.Sciences                & -0.119$^{**}$\\
                                                       & (0.054)\\
   Arts.and.Humanities                                 & 0.838$^{**}$\\
                                                       & (0.423)\\
   Biochemistry..Genetics.and.Molecular.Biology        & -0.231$^{***}$\\
                                                       & (0.029)\\
   Business..Management.and.Accounting                 & -11.7$^{***}$\\
                                                       & (0.062)\\
   Chemical.Engineering                                & -0.303\\
                                                       & (0.275)\\
   Chemistry                                           & 0.054\\
                                                       & (0.038)\\
   Computer.Science                                    & 0.602$^{***}$\\
                                                       & (0.090)\\
   Decision.Sciences                                   & -1.30\\
                                                       & (0.830)\\
   Dentistry                                           & 0.962$^{***}$\\
                                                       & (0.145)\\
   Earth.and.Planetary.Sciences                        & 0.809$^{***}$\\
                                                       & (0.195)\\
   Economics..Econometrics.and.Finance                 & 10.6$^{***}$\\
                                                       & (0.122)\\
   Energy                                              & -0.159\\
                                                       & (0.106)\\
   Engineering                                         & 0.654$^{***}$\\
                                                       & (0.057)\\
   Immunology.and.Microbiology                         & -0.340$^{***}$\\
                                                       & (0.039)\\
   Materials.Science                                   & -0.385$^{***}$\\
                                                       & (0.038)\\
   Mathematics                                         & 0.757\\
                                                       & (0.572)\\
   Medicine                                            & 0.208$^{**}$\\
                                                       & (0.081)\\
   Neuroscience                                        & 0.231$^{***}$\\
                                                       & (0.062)\\
   Nursing                                             & 0.689$^{***}$\\
                                                       & (0.069)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & 0.604$^{***}$\\
                                                       & (0.084)\\
   Physics.and.Astronomy                               & 0.112$^{*}$\\
                                                       & (0.058)\\
   Psychology                                          & 0.865$^{**}$\\
                                                       & (0.377)\\
   Social.Sciences                                     & 0.783\\
                                                       & (0.584)\\
   Veterinary                                          & 0.207\\
                                                       & (0.205)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 33,409\\
   Squared Correlation                                 & 0.08160\\
   Pseudo R$^2$                                        & 0.06068\\
   BIC                                                 & 43,996.1\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [32]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ text_fac_scientist + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_nps_bin <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Physical.Sciences==0), ], family = binomial("logit"), vcov = "hetero")
summary(model_nps_bin)

NOTE: 6 fixed-effects (10 observations) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 41,294
Fixed-effects: PublishedYear: 38
Standard-errors: Heteroskedasticity-robust
                                               Estimate Std. Error     z value
text_fac_scientistStaffPart                    0.317739   0.036403    8.728335
lnnum_author                                   0.344890   0.023766   14.512119
internationalinternational                     0.107954   0.024142    4.471666
lnnum_reference                               -0.088392   0.026780   -3.300651
num_fac                                       -0.131859   0.018676   -7.060333
SDGTrue                                        0.260102   0.021372   12.169968
lnmean_career_age                              0.266285   0.035370    7.528505
lnex_ld_avg_avgimpact                         -0.534767   0.021066  -25.385094
lnex_ld_avg_insthindex                        -0.190767   0.020023   -9.527312
ex_ld_bin_gsGlobalNorth                        0.150297   0.056750    2.648412
ex_ld_bin_sameCSame                           -0.099609   0.023740   -4.195789
knowledge_proximity_mean                      -4.196483   0.435638   -9.632962
lnex_ld_avg_before_year_prod_fac              -0.042454   0.015277   -2.778983
ex_ld_max_before_year_with_ih_binTrue          0.189276   0.024465    7.736626
Agricultural.and.Biological.Sciences           0.113225   0.035314    3.206278
Arts.and.Humanities                            0.935248   0.298090    3.137464
Biochemistry..Genetics.and.Molecular.Biology  -0.284789   0.030631   -9.297487
Business..Management.and.Accounting          -11.769671   0.050497 -233.076238
Decision.Sciences                             -0.623030   0.948209   -0.657059
Dentistry                                      1.046780   0.189736    5.517029
Health.Professions                             0.434179   0.265489    1.635394
Immunology.and.Microbiology                   -0.038182   0.032128   -1.188418
Medicine                                       0.555029   0.022886   24.251678
Neuroscience                                   0.355232   0.040496    8.772114
Nursing                                        0.706464   0.058963   11.981419
Pharmacology..Toxicology.and.Pharmaceutics     0.828626   0.071815   11.538407
Psychology                                     0.574677   0.214031    2.685012
Social.Sciences                               -0.135285   0.342649   -0.394821
Veterinary                                     0.232194   0.227085    1.022496
                                               Pr(>|z|)
text_fac_scientistStaffPart                   < 2.2e-16 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   7.7613e-06 ***
lnnum_reference                              9.6461e-04 ***
num_fac                                      1.6610e-12 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            5.1325e-14 ***
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                        < 2.2e-16 ***
ex_ld_bin_gsGlobalNorth                      8.0871e-03 **
ex_ld_bin_sameCSame                          2.7192e-05 ***
knowledge_proximity_mean                      < 2.2e-16 ***
lnex_ld_avg_before_year_prod_fac             5.4529e-03 **
ex_ld_max_before_year_with_ih_binTrue        1.0209e-14 ***
Agricultural.and.Biological.Sciences         1.3446e-03 **
Arts.and.Humanities                          1.7042e-03 **
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting           < 2.2e-16 ***
Decision.Sciences                            5.1114e-01
Dentistry                                    3.4478e-08 ***
Health.Professions                           1.0197e-01
Immunology.and.Microbiology                  2.3467e-01
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Psychology                                   7.2527e-03 **
Social.Sciences                              6.9298e-01
Veterinary                                   3.0655e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -26,058.1   Adj. Pseudo R2: 0.075881
           BIC:  52,828.4     Squared Cor.: 0.103624

In [33]:
margins_eff_nps_bin <- avg_comparisons(model_nps_bin, variables = "text_fac_scientist", comparison = 'ratio')
margins_eff_nps_bin

  term               contrast                             estimate std.error
1 text_fac_scientist mean(StaffPart) / mean(NonStaffPart) 1.166542 0.03774749
  statistic p.value       s.value  conf.low conf.high predicted_lo predicted_hi
1 30.90384  1.060737e-209 694.1979 1.092559 1.240526  0.6709483    0.7369578
  predicted
1 0.6709483

In [34]:
fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_nps_comp_ratio.csv")
write.csv(margins_eff_nps_bin, fname, row.names = FALSE)

In [35]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_nps_bin,
                           keep = c("text_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\_bin\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   text\_fac\_scientistStaffPart                       & 0.318$^{***}$\\
                                                       & (0.036)\\
   lnnum\_author                                       & 0.345$^{***}$\\
                                                       & (0.024)\\
   internationalinternational                          & 0.108$^{***}$\\
                                                       & (0.024)\\
   lnnum\_reference                                    & -0.088$^{***}$\\
                                                       & (0.027)\\
   num\_fac                                            & -0.132$^{***}$\\
                                                       & (0.019)\\
   SDGTrue                                             & 0.260$^{***}$\\
                                                       & (0.021)\\
   lnmean\_career\_age                                 & 0.266$^{***}$\\
                                                       & (0.035)\\
   lnex\_ld\_avg\_avgimpact                            & -0.535$^{***}$\\
                                                       & (0.021)\\
   lnex\_ld\_avg\_insthindex                           & -0.191$^{***}$\\
                                                       & (0.020)\\
   ex\_ld\_bin\_gsGlobalNorth                          & 0.150$^{***}$\\
                                                       & (0.057)\\
   ex\_ld\_bin\_sameCSame                              & -0.100$^{***}$\\
                                                       & (0.024)\\
   knowledge\_proximity\_mean                          & -4.20$^{***}$\\
                                                       & (0.436)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & -0.043$^{***}$\\
                                                       & (0.015)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & 0.189$^{***}$\\
                                                       & (0.025)\\
   Agricultural.and.Biological.Sciences                & 0.113$^{***}$\\
                                                       & (0.035)\\
   Arts.and.Humanities                                 & 0.935$^{***}$\\
                                                       & (0.298)\\
   Biochemistry..Genetics.and.Molecular.Biology        & -0.285$^{***}$\\
                                                       & (0.031)\\
   Business..Management.and.Accounting                 & -11.8$^{***}$\\
                                                       & (0.051)\\
   Decision.Sciences                                   & -0.623\\
                                                       & (0.948)\\
   Dentistry                                           & 1.05$^{***}$\\
                                                       & (0.190)\\
   Immunology.and.Microbiology                         & -0.038\\
                                                       & (0.032)\\
   Medicine                                            & 0.555$^{***}$\\
                                                       & (0.023)\\
   Neuroscience                                        & 0.355$^{***}$\\
                                                       & (0.041)\\
   Nursing                                             & 0.706$^{***}$\\
                                                       & (0.059)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & 0.829$^{***}$\\
                                                       & (0.072)\\
   Psychology                                          & 0.575$^{***}$\\
                                                       & (0.214)\\
   Social.Sciences                                     & -0.135\\
                                                       & (0.343)\\
   Veterinary                                          & 0.232\\
                                                       & (0.227)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 41,294\\
   Squared Correlation                                 & 0.10362\\
   Pseudo R$^2$                                        & 0.07822\\
   BIC                                                 & 52,828.4\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

# H2: Collaboration > Participation

In [36]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_total <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_total)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
CoTypeCollaboration                           0.093664   0.011280   8.303659
CoTypeParticipation                           0.001874   0.015079   0.124291
lnnum_author                                 -0.082752   0.007391 -11.196746
internationalinternational                   -0.046879   0.009593  -4.886663
lnnum_reference                               0.053317   0.008660   6.156694
num_fac                                       0.066123   0.006732   9.822587
SDGTrue                                       0.083797   0.008154  10.276936
lnmean_career_age                             0.008714   0.013093   0.665580
lnex_ld_avg_avgimpact                        -0.275466   0.007394 -37.255718
lnex_ld_avg_insthindex                       -0.049325   0.007528  -6.551822
ex_ld_bin_gsGlobalNorth                       0.309083   0.017496  17.665624
ex_ld_bin_sameCSame                          -0.060923   0.009449  -6.447760
knowledge_proximity_mean                     -0.806332   0.159827  -5.045036
lnex_ld_avg_before_year_prod_fac             -0.041240   0.004970  -8.298061
ex_ld_max_before_year_with_ih_binTrue         0.329950   0.011365  29.031439
Agricultural.and.Biological.Sciences          0.757736   0.023987  31.589390
Arts.and.Humanities                           1.773738   0.073089  24.268315
Biochemistry..Genetics.and.Molecular.Biology  0.596690   0.012617  47.293727
Business..Management.and.Accounting          -0.326306   0.087868  -3.713584
Chemical.Engineering                          0.163869   0.020824   7.869052
Chemistry                                     0.458109   0.011152  41.080366
Computer.Science                              0.940041   0.039584  23.748065
Decision.Sciences                             1.223643   0.189219   6.466797
Dentistry                                     1.954384   0.136207  14.348587
Earth.and.Planetary.Sciences                  0.753442   0.015282  49.302224
Economics..Econometrics.and.Finance          -0.080021   0.295735  -0.270584
Energy                                        0.236704   0.017921  13.208097
Engineering                                   0.327642   0.010481  31.259865
Environmental.Science                         0.578567   0.017493  33.074461
Health.Professions                            1.410820   0.128459  10.982608
Immunology.and.Microbiology                   0.234569   0.026911   8.716605
Materials.Science                             0.022891   0.009941   2.302568
Mathematics                                   0.574910   0.125458   4.582489
Medicine                                      0.867721   0.014849  58.436220
Neuroscience                                  0.520928   0.032650  15.954927
Nursing                                       1.051941   0.043246  24.324798
Pharmacology..Toxicology.and.Pharmaceutics    0.906084   0.048289  18.763677
Physics.and.Astronomy                        -0.260078   0.011474 -22.665814
Psychology                                    0.428415   0.157763   2.715569
Social.Sciences                               0.166035   0.156640   1.059975
Veterinary                                    0.599875   0.208564   2.876218
                                               Pr(>|z|)
CoTypeCollaboration                           < 2.2e-16 ***
CoTypeParticipation                          9.0108e-01
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   1.0256e-06 ***
lnnum_reference                              7.4279e-10 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            5.0568e-01
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                       5.6839e-11 ***
ex_ld_bin_gsGlobalNorth                       < 2.2e-16 ***
ex_ld_bin_sameCSame                          1.1352e-10 ***
knowledge_proximity_mean                     4.5344e-07 ***
lnex_ld_avg_before_year_prod_fac              < 2.2e-16 ***
ex_ld_max_before_year_with_ih_binTrue         < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          2.0434e-04 ***
Chemical.Engineering                         3.5734e-15 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            1.0010e-10 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          7.8671e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                   < 2.2e-16 ***
Materials.Science                            2.1303e-02 *
Mathematics                                  4.5947e-06 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   6.6162e-03 **
Social.Sciences                              2.8916e-01
Veterinary                                   4.0247e-03 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -181,536.1   Adj. Pseudo R2: 0.059079
           BIC:  364,230.9     Squared Cor.: 0.07571

In [37]:
# 每组 reg_class 的平均预测概率
pred <- avg_predictions(model_total, variables = "CoType")
pred

  CoType        estimate  std.error  statistic p.value      s.value   conf.low
1 Service       0.3585577 0.03153474 11.37024  5.882342e-30  97.10145 0.2967507
2 Collaboration 0.3786608 0.03224739 11.74237  7.728990e-32 103.35142 0.3154571
3 Participation 0.3589555 0.03162498 11.35038  7.384392e-30  96.77336 0.2969716
  conf.high
1 0.4203646
2 0.4418646
3 0.4209393

In [38]:
fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_pred.csv")
write.csv(pred, fname, row.names = FALSE)

In [39]:
# 每组 reg_class 的平均预测概率
margins_eff <- avg_comparisons(model_total, variables = "CoType", comparison = 'ratio')
margins_eff

  term   contrast                            estimate std.error   statistic
1 CoType mean(Collaboration) / mean(Service) 1.056067 0.007531083 140.2277
2 CoType mean(Participation) / mean(Service) 1.001109 0.008929571 112.1117
  p.value s.value conf.low  conf.high predicted_lo predicted_hi predicted
1 0       Inf     1.0413061 1.070827  0.2846939    0.3041460    0.2846939
2 0       Inf     0.9836078 1.018611  0.2846939    0.2850758    0.2846939

In [40]:
fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_comp_ratio.csv")
write.csv(margins_eff, fname, row.names = FALSE)

In [41]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_total,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\_bin\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                                 & 0.094$^{***}$\\
                                                       & (0.011)\\
   CoTypeParticipation                                 & 0.002\\
                                                       & (0.015)\\
   lnnum\_author                                       & -0.083$^{***}$\\
                                                       & (0.007)\\
   internationalinternational                          & -0.047$^{***}$\\
                                                       & (0.010)\\
   lnnum\_reference                                    & 0.053$^{***}$\\
                                                       & (0.009)\\
   num\_fac                                            & 0.066$^{***}$\\
                                                       & (0.007)\\
   SDGTrue                                             & 0.084$^{***}$\\
                                                       & (0.008)\\
   lnmean\_career\_age                                 & 0.009\\
                                                       & (0.013)\\
   lnex\_ld\_avg\_avgimpact                            & -0.275$^{***}$\\
                                                       & (0.007)\\
   lnex\_ld\_avg\_insthindex                           & -0.049$^{***}$\\
                                                       & (0.008)\\
   ex\_ld\_bin\_gsGlobalNorth                          & 0.309$^{***}$\\
                                                       & (0.018)\\
   ex\_ld\_bin\_sameCSame                              & -0.061$^{***}$\\
                                                       & (0.009)\\
   knowledge\_proximity\_mean                          & -0.806$^{***}$\\
                                                       & (0.160)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & -0.041$^{***}$\\
                                                       & (0.005)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & 0.330$^{***}$\\
                                                       & (0.011)\\
   Agricultural.and.Biological.Sciences                & 0.758$^{***}$\\
                                                       & (0.024)\\
   Arts.and.Humanities                                 & 1.77$^{***}$\\
                                                       & (0.073)\\
   Biochemistry..Genetics.and.Molecular.Biology        & 0.597$^{***}$\\
                                                       & (0.013)\\
   Business..Management.and.Accounting                 & -0.326$^{***}$\\
                                                       & (0.088)\\
   Chemical.Engineering                                & 0.164$^{***}$\\
                                                       & (0.021)\\
   Chemistry                                           & 0.458$^{***}$\\
                                                       & (0.011)\\
   Computer.Science                                    & 0.940$^{***}$\\
                                                       & (0.040)\\
   Decision.Sciences                                   & 1.22$^{***}$\\
                                                       & (0.189)\\
   Dentistry                                           & 1.95$^{***}$\\
                                                       & (0.136)\\
   Earth.and.Planetary.Sciences                        & 0.753$^{***}$\\
                                                       & (0.015)\\
   Economics..Econometrics.and.Finance                 & -0.080\\
                                                       & (0.296)\\
   Energy                                              & 0.237$^{***}$\\
                                                       & (0.018)\\
   Engineering                                         & 0.328$^{***}$\\
                                                       & (0.011)\\
   Immunology.and.Microbiology                         & 0.235$^{***}$\\
                                                       & (0.027)\\
   Materials.Science                                   & 0.023$^{**}$\\
                                                       & (0.010)\\
   Mathematics                                         & 0.575$^{***}$\\
                                                       & (0.125)\\
   Medicine                                            & 0.868$^{***}$\\
                                                       & (0.015)\\
   Neuroscience                                        & 0.521$^{***}$\\
                                                       & (0.033)\\
   Nursing                                             & 1.05$^{***}$\\
                                                       & (0.043)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & 0.906$^{***}$\\
                                                       & (0.048)\\
   Physics.and.Astronomy                               & -0.260$^{***}$\\
                                                       & (0.011)\\
   Psychology                                          & 0.428$^{***}$\\
                                                       & (0.158)\\
   Social.Sciences                                     & 0.166\\
                                                       & (0.157)\\
   Veterinary                                          & 0.600$^{***}$\\
                                                       & (0.209)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 294,879\\
   Squared Correlation                                 & 0.07571\\
   Pseudo R$^2$                                        & 0.05955\\
   BIC                                                 & 364,230.9\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

# H2 Discipline

In [42]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_ps <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Physical.Sciences==1), ], family = binomial("logit"), vcov = "hetero")
summary(model_ps)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 253,575
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
CoTypeCollaboration                           0.081750   0.011854   6.896493
CoTypeParticipation                           0.006896   0.015894   0.433865
lnnum_author                                 -0.172038   0.008338 -20.633222
internationalinternational                   -0.075657   0.010529  -7.185651
lnnum_reference                               0.078010   0.009242   8.440694
num_fac                                       0.101840   0.007277  13.994286
SDGTrue                                       0.032604   0.008922   3.654131
lnmean_career_age                            -0.052982   0.014213  -3.727710
lnex_ld_avg_avgimpact                        -0.224111   0.008258 -27.139673
lnex_ld_avg_insthindex                       -0.016826   0.008231  -2.044096
ex_ld_bin_gsGlobalNorth                       0.299818   0.018714  16.021414
ex_ld_bin_sameCSame                          -0.054993   0.010400  -5.287713
knowledge_proximity_mean                     -0.269160   0.175033  -1.537773
lnex_ld_avg_before_year_prod_fac             -0.034663   0.005354  -6.474381
ex_ld_max_before_year_with_ih_binTrue         0.342749   0.013054  26.256043
Agricultural.and.Biological.Sciences          1.052608   0.036817  28.589979
Arts.and.Humanities                           1.796095   0.075906  23.662067
Biochemistry..Genetics.and.Molecular.Biology  0.769335   0.014365  53.557109
Business..Management.and.Accounting          -0.286058   0.087322  -3.275910
Chemical.Engineering                          0.179861   0.020982   8.572209
Chemistry                                     0.423726   0.011993  35.331139
Computer.Science                              0.877018   0.040517  21.645921
Decision.Sciences                             1.335968   0.194233   6.878172
Dentistry                                     2.422376   0.205557  11.784438
Earth.and.Planetary.Sciences                  0.772932   0.015590  49.578754
Economics..Econometrics.and.Finance          -0.085052   0.298427  -0.285000
Energy                                        0.237694   0.018334  12.964556
Engineering                                   0.352935   0.011151  31.650936
Environmental.Science                         0.500923   0.018862  26.556644
Health.Professions                            1.644415   0.147742  11.130280
Immunology.and.Microbiology                   0.518370   0.071150   7.285585
Materials.Science                            -0.002361   0.010899  -0.216591
Mathematics                                   0.559390   0.126671   4.416071
Medicine                                      0.975078   0.022659  43.032842
Neuroscience                                  0.709720   0.059067  12.015514
Nursing                                       1.319969   0.067140  19.659874
Pharmacology..Toxicology.and.Pharmaceutics    0.850318   0.066623  12.763101
Physics.and.Astronomy                        -0.245424   0.012118 -20.252994
Psychology                                   -0.512885   0.276380  -1.855719
Social.Sciences                               0.257902   0.182509   1.413089
Veterinary                                    0.739448   0.538244   1.373815
                                               Pr(>|z|)
CoTypeCollaboration                          5.3302e-12 ***
CoTypeParticipation                          6.6439e-01
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   6.6887e-13 ***
lnnum_reference                               < 2.2e-16 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                      2.5805e-04 ***
lnmean_career_age                            1.9323e-04 ***
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                       4.0944e-02 *
ex_ld_bin_gsGlobalNorth                       < 2.2e-16 ***
ex_ld_bin_sameCSame                          1.2386e-07 ***
knowledge_proximity_mean                     1.2410e-01
lnex_ld_avg_before_year_prod_fac             9.5201e-11 ***
ex_ld_max_before_year_with_ih_binTrue         < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          1.0532e-03 **
Chemical.Engineering                          < 2.2e-16 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            6.0625e-12 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          7.7564e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                  3.2028e-13 ***
Materials.Science                            8.2853e-01
Mathematics                                  1.0051e-05 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   6.3494e-02 .
Social.Sciences                              1.5763e-01
Veterinary                                   1.6950e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -153,662.3   Adj. Pseudo R2: 0.063736
           BIC:  308,469.4     Squared Cor.: 0.081079

In [43]:
# 每组 reg_class 的平均预测概率
margins_eff_ps <- avg_comparisons(model_ps, variables = "CoType", comparison = 'ratio')
margins_eff_ps

  term   contrast                            estimate std.error   statistic
1 CoType mean(Collaboration) / mean(Service) 1.049506 0.007822176 134.1706
2 CoType mean(Participation) / mean(Service) 1.004135 0.009545858 105.1906
  p.value s.value conf.low conf.high predicted_lo predicted_hi predicted
1 0       Inf     1.034175 1.064837  0.2834341    0.3003272    0.2834341
2 0       Inf     0.985425 1.022844  0.2834341    0.2848368    0.2834341

In [44]:
fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_ps_comp_ratio.csv")
write.csv(margins_eff_ps, fname, row.names = FALSE)

In [45]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_ps,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\_bin\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                                 & 0.082$^{***}$\\
                                                       & (0.012)\\
   CoTypeParticipation                                 & 0.007\\
                                                       & (0.016)\\
   lnnum\_author                                       & -0.172$^{***}$\\
                                                       & (0.008)\\
   internationalinternational                          & -0.076$^{***}$\\
                                                       & (0.011)\\
   lnnum\_reference                                    & 0.078$^{***}$\\
                                                       & (0.009)\\
   num\_fac                                            & 0.102$^{***}$\\
                                                       & (0.007)\\
   SDGTrue                                             & 0.033$^{***}$\\
                                                       & (0.009)\\
   lnmean\_career\_age                                 & -0.053$^{***}$\\
                                                       & (0.014)\\
   lnex\_ld\_avg\_avgimpact                            & -0.224$^{***}$\\
                                                       & (0.008)\\
   lnex\_ld\_avg\_insthindex                           & -0.017$^{**}$\\
                                                       & (0.008)\\
   ex\_ld\_bin\_gsGlobalNorth                          & 0.300$^{***}$\\
                                                       & (0.019)\\
   ex\_ld\_bin\_sameCSame                              & -0.055$^{***}$\\
                                                       & (0.010)\\
   knowledge\_proximity\_mean                          & -0.269\\
                                                       & (0.175)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & -0.035$^{***}$\\
                                                       & (0.005)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & 0.343$^{***}$\\
                                                       & (0.013)\\
   Agricultural.and.Biological.Sciences                & 1.05$^{***}$\\
                                                       & (0.037)\\
   Arts.and.Humanities                                 & 1.80$^{***}$\\
                                                       & (0.076)\\
   Biochemistry..Genetics.and.Molecular.Biology        & 0.769$^{***}$\\
                                                       & (0.014)\\
   Business..Management.and.Accounting                 & -0.286$^{***}$\\
                                                       & (0.087)\\
   Chemical.Engineering                                & 0.180$^{***}$\\
                                                       & (0.021)\\
   Chemistry                                           & 0.424$^{***}$\\
                                                       & (0.012)\\
   Computer.Science                                    & 0.877$^{***}$\\
                                                       & (0.041)\\
   Decision.Sciences                                   & 1.34$^{***}$\\
                                                       & (0.194)\\
   Dentistry                                           & 2.42$^{***}$\\
                                                       & (0.206)\\
   Earth.and.Planetary.Sciences                        & 0.773$^{***}$\\
                                                       & (0.016)\\
   Economics..Econometrics.and.Finance                 & -0.085\\
                                                       & (0.298)\\
   Energy                                              & 0.238$^{***}$\\
                                                       & (0.018)\\
   Engineering                                         & 0.353$^{***}$\\
                                                       & (0.011)\\
   Immunology.and.Microbiology                         & 0.518$^{***}$\\
                                                       & (0.071)\\
   Materials.Science                                   & -0.002\\
                                                       & (0.011)\\
   Mathematics                                         & 0.559$^{***}$\\
                                                       & (0.127)\\
   Medicine                                            & 0.975$^{***}$\\
                                                       & (0.023)\\
   Neuroscience                                        & 0.710$^{***}$\\
                                                       & (0.059)\\
   Nursing                                             & 1.32$^{***}$\\
                                                       & (0.067)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & 0.850$^{***}$\\
                                                       & (0.067)\\
   Physics.and.Astronomy                               & -0.245$^{***}$\\
                                                       & (0.012)\\
   Psychology                                          & -0.513$^{*}$\\
                                                       & (0.276)\\
   Social.Sciences                                     & 0.258\\
                                                       & (0.183)\\
   Veterinary                                          & 0.739\\
                                                       & (0.538)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 253,575\\
   Squared Correlation                                 & 0.08108\\
   Pseudo R$^2$                                        & 0.06429\\
   BIC                                                 & 308,469.4\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [46]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_ls <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Life.Sciences==1), ], family = binomial("logit"), vcov = "hetero")
summary(model_ls)

NOTE: 1 fixed-effect (1 observation) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 77,590
Fixed-effects: PublishedYear: 48
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
CoTypeCollaboration                           0.112862   0.025274   4.465483
CoTypeParticipation                           0.177887   0.037424   4.753252
lnnum_author                                  0.232349   0.016872  13.770985
internationalinternational                    0.091095   0.017482   5.210651
lnnum_reference                               0.100646   0.017834   5.643612
num_fac                                      -0.074019   0.012581  -5.883650
SDGTrue                                       0.157520   0.015173  10.381696
lnmean_career_age                             0.150727   0.024366   6.185879
lnex_ld_avg_avgimpact                        -0.386252   0.014079 -27.434283
lnex_ld_avg_insthindex                       -0.136568   0.014240  -9.590414
ex_ld_bin_gsGlobalNorth                       0.057867   0.039549   1.463186
ex_ld_bin_sameCSame                          -0.092429   0.017009  -5.434190
knowledge_proximity_mean                     -2.435012   0.285454  -8.530299
lnex_ld_avg_before_year_prod_fac             -0.034975   0.010247  -3.413148
ex_ld_max_before_year_with_ih_binTrue         0.259702   0.018276  14.209699
Agricultural.and.Biological.Sciences          0.391348   0.028090  13.931849
Arts.and.Humanities                           1.021242   0.303349   3.366557
Biochemistry..Genetics.and.Molecular.Biology -0.102385   0.029778  -3.438253
Business..Management.and.Accounting          -0.223616   0.491384  -0.455075
Chemical.Engineering                          0.293133   0.134946   2.172219
Chemistry                                     0.544489   0.023378  23.290236
Computer.Science                              0.737439   0.067574  10.913108
Decision.Sciences                            -0.315410   0.546453  -0.577195
Dentistry                                     0.628177   0.222952   2.817543
Earth.and.Planetary.Sciences                  0.889794   0.076578  11.619464
Energy                                        0.183354   0.061910   2.961623
Engineering                                   0.499167   0.031443  15.875470
Environmental.Science                        -0.019077   0.031141  -0.612593
Health.Professions                            0.481893   0.349790   1.377662
Immunology.and.Microbiology                   0.084168   0.029657   2.838019
Materials.Science                             0.130502   0.019729   6.614618
Mathematics                                   1.023777   0.530256   1.930721
Medicine                                      0.502860   0.018613  27.016519
Neuroscience                                  0.282591   0.034257   8.249186
Nursing                                       0.640393   0.051447  12.447594
Pharmacology..Toxicology.and.Pharmaceutics    0.610706   0.050708  12.043622
Physics.and.Astronomy                         0.434641   0.031419  13.833883
Psychology                                    0.432178   0.215510   2.005377
Social.Sciences                               0.405807   0.389934   1.040707
Veterinary                                    0.166341   0.234826   0.708358
                                               Pr(>|z|)
CoTypeCollaboration                          7.9888e-06 ***
CoTypeParticipation                          2.0017e-06 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   1.8818e-07 ***
lnnum_reference                              1.6652e-08 ***
num_fac                                      4.0132e-09 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            6.1757e-10 ***
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                        < 2.2e-16 ***
ex_ld_bin_gsGlobalNorth                      1.4342e-01
ex_ld_bin_sameCSame                          5.5046e-08 ***
knowledge_proximity_mean                      < 2.2e-16 ***
lnex_ld_avg_before_year_prod_fac             6.4217e-04 ***
ex_ld_max_before_year_with_ih_binTrue         < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                          7.6113e-04 ***
Biochemistry..Genetics.and.Molecular.Biology 5.8548e-04 ***
Business..Management.and.Accounting          6.4906e-01
Chemical.Engineering                         2.9839e-02 *
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            5.6381e-01
Dentistry                                    4.8393e-03 **
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Energy                                       3.0602e-03 **
Engineering                                   < 2.2e-16 ***
Environmental.Science                        5.4015e-01
Health.Professions                           1.6831e-01
Immunology.and.Microbiology                  4.5394e-03 **
Materials.Science                            3.7251e-11 ***
Mathematics                                  5.3518e-02 .
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   4.4923e-02 *
Social.Sciences                              2.9801e-01
Veterinary                                   4.7872e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -50,614.9   Adj. Pseudo R2: 0.054548
           BIC: 102,220.7     Squared Cor.: 0.07539

In [47]:
# 每组 reg_class 的平均预测概率
margins_eff_ls <- avg_comparisons(model_ls, variables = "CoType", comparison = 'ratio')
margins_eff_ls

  term   contrast                            estimate std.error  statistic
1 CoType mean(Collaboration) / mean(Service) 1.056350 0.01503416 70.26328
2 CoType mean(Participation) / mean(Service) 1.088891 0.02220913 49.02899
  p.value s.value conf.low conf.high predicted_lo predicted_hi predicted
1 0       Inf     1.026883 1.085816  0.316494     0.3413983    0.316494
2 0       Inf     1.045362 1.132420  0.316494     0.3561660    0.316494

In [48]:
fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_ls_comp_ratio.csv")
write.csv(margins_eff_ls, fname, row.names = FALSE)

In [49]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_ls,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\_bin\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                                 & 0.113$^{***}$\\
                                                       & (0.025)\\
   CoTypeParticipation                                 & 0.178$^{***}$\\
                                                       & (0.037)\\
   lnnum\_author                                       & 0.232$^{***}$\\
                                                       & (0.017)\\
   internationalinternational                          & 0.091$^{***}$\\
                                                       & (0.018)\\
   lnnum\_reference                                    & 0.101$^{***}$\\
                                                       & (0.018)\\
   num\_fac                                            & -0.074$^{***}$\\
                                                       & (0.013)\\
   SDGTrue                                             & 0.158$^{***}$\\
                                                       & (0.015)\\
   lnmean\_career\_age                                 & 0.151$^{***}$\\
                                                       & (0.024)\\
   lnex\_ld\_avg\_avgimpact                            & -0.386$^{***}$\\
                                                       & (0.014)\\
   lnex\_ld\_avg\_insthindex                           & -0.137$^{***}$\\
                                                       & (0.014)\\
   ex\_ld\_bin\_gsGlobalNorth                          & 0.058\\
                                                       & (0.040)\\
   ex\_ld\_bin\_sameCSame                              & -0.092$^{***}$\\
                                                       & (0.017)\\
   knowledge\_proximity\_mean                          & -2.44$^{***}$\\
                                                       & (0.285)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & -0.035$^{***}$\\
                                                       & (0.010)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & 0.260$^{***}$\\
                                                       & (0.018)\\
   Agricultural.and.Biological.Sciences                & 0.391$^{***}$\\
                                                       & (0.028)\\
   Arts.and.Humanities                                 & 1.02$^{***}$\\
                                                       & (0.303)\\
   Biochemistry..Genetics.and.Molecular.Biology        & -0.102$^{***}$\\
                                                       & (0.030)\\
   Business..Management.and.Accounting                 & -0.224\\
                                                       & (0.491)\\
   Chemical.Engineering                                & 0.293$^{**}$\\
                                                       & (0.135)\\
   Chemistry                                           & 0.544$^{***}$\\
                                                       & (0.023)\\
   Computer.Science                                    & 0.737$^{***}$\\
                                                       & (0.068)\\
   Decision.Sciences                                   & -0.315\\
                                                       & (0.546)\\
   Dentistry                                           & 0.628$^{***}$\\
                                                       & (0.223)\\
   Earth.and.Planetary.Sciences                        & 0.890$^{***}$\\
                                                       & (0.077)\\
   Energy                                              & 0.183$^{***}$\\
                                                       & (0.062)\\
   Engineering                                         & 0.499$^{***}$\\
                                                       & (0.031)\\
   Immunology.and.Microbiology                         & 0.084$^{***}$\\
                                                       & (0.030)\\
   Materials.Science                                   & 0.131$^{***}$\\
                                                       & (0.020)\\
   Mathematics                                         & 1.02$^{*}$\\
                                                       & (0.530)\\
   Medicine                                            & 0.503$^{***}$\\
                                                       & (0.019)\\
   Neuroscience                                        & 0.283$^{***}$\\
                                                       & (0.034)\\
   Nursing                                             & 0.640$^{***}$\\
                                                       & (0.051)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & 0.611$^{***}$\\
                                                       & (0.051)\\
   Physics.and.Astronomy                               & 0.435$^{***}$\\
                                                       & (0.031)\\
   Psychology                                          & 0.432$^{**}$\\
                                                       & (0.216)\\
   Social.Sciences                                     & 0.406\\
                                                       & (0.390)\\
   Veterinary                                          & 0.166\\
                                                       & (0.235)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 77,590\\
   Squared Correlation                                 & 0.07539\\
   Pseudo R$^2$                                        & 0.05617\\
   BIC                                                 & 102,220.7\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [50]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_hs <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Health.Sciences==1), ], family = binomial("logit"), vcov = "hetero")
summary(model_hs)

NOTE: 6 fixed-effects (8 observations) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 33,409
Fixed-effects: PublishedYear: 40
Standard-errors: Heteroskedasticity-robust
                                               Estimate Std. Error    z value
CoTypeCollaboration                            0.347392   0.044522    7.80271
CoTypeParticipation                            0.478942   0.063318    7.56410
lnnum_author                                   0.318061   0.026497   12.00377
internationalinternational                     0.058039   0.026499    2.19023
lnnum_reference                                0.110106   0.027655    3.98134
num_fac                                       -0.123250   0.020755   -5.93839
SDGTrue                                        0.224452   0.023469    9.56391
lnmean_career_age                              0.187322   0.038706    4.83968
lnex_ld_avg_avgimpact                         -0.334405   0.022013  -15.19152
lnex_ld_avg_insthindex                        -0.120006   0.021494   -5.58330
ex_ld_bin_gsGlobalNorth                        0.233395   0.061762    3.77896
ex_ld_bin_sameCSame                           -0.126106   0.026069   -4.83735
knowledge_proximity_mean                      -1.026069   0.403855   -2.54069
lnex_ld_avg_before_year_prod_fac              -0.067642   0.016059   -4.21200
ex_ld_max_before_year_with_ih_binTrue          0.174274   0.027728    6.28510
Agricultural.and.Biological.Sciences          -0.119245   0.053651   -2.22262
Arts.and.Humanities                            0.831889   0.422804    1.96756
Biochemistry..Genetics.and.Molecular.Biology  -0.230493   0.028628   -8.05124
Business..Management.and.Accounting          -11.694092   0.063735 -183.48040
Chemical.Engineering                          -0.295064   0.274759   -1.07390
Chemistry                                      0.055274   0.038367    1.44069
Computer.Science                               0.602097   0.090070    6.68473
Decision.Sciences                             -1.311993   0.829140   -1.58235
Dentistry                                      0.961801   0.145303    6.61929
Earth.and.Planetary.Sciences                   0.809744   0.194772    4.15740
Economics..Econometrics.and.Finance           10.583516   0.121587   87.04474
Energy                                        -0.158970   0.106392   -1.49419
Engineering                                    0.652641   0.056462   11.55887
Environmental.Science                          0.143890   0.059501    2.41827
Health.Professions                             0.601899   0.142753    4.21637
Immunology.and.Microbiology                   -0.340119   0.038765   -8.77384
Materials.Science                             -0.385385   0.038306  -10.06062
Mathematics                                    0.765286   0.570711    1.34093
Medicine                                       0.208470   0.080869    2.57786
Neuroscience                                   0.229985   0.062491    3.68030
Nursing                                        0.688151   0.068636   10.02614
Pharmacology..Toxicology.and.Pharmaceutics     0.603255   0.084217    7.16311
Physics.and.Astronomy                          0.114218   0.057894    1.97287
Psychology                                     0.863400   0.377324    2.28822
Social.Sciences                                0.779610   0.584488    1.33383
Veterinary                                     0.207589   0.205140    1.01194
                                               Pr(>|z|)
CoTypeCollaboration                          6.0591e-15 ***
CoTypeParticipation                          3.9056e-14 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   2.8507e-02 *
lnnum_reference                              6.8527e-05 ***
num_fac                                      2.8783e-09 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            1.3005e-06 ***
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                       2.3600e-08 ***
ex_ld_bin_gsGlobalNorth                      1.5748e-04 ***
ex_ld_bin_sameCSame                          1.3158e-06 ***
knowledge_proximity_mean                     1.1064e-02 *
lnex_ld_avg_before_year_prod_fac             2.5312e-05 ***
ex_ld_max_before_year_with_ih_binTrue        3.2764e-10 ***
Agricultural.and.Biological.Sciences         2.6242e-02 *
Arts.and.Humanities                          4.9119e-02 *
Biochemistry..Genetics.and.Molecular.Biology 8.1958e-16 ***
Business..Management.and.Accounting           < 2.2e-16 ***
Chemical.Engineering                         2.8287e-01
Chemistry                                    1.4967e-01
Computer.Science                             2.3135e-11 ***
Decision.Sciences                            1.1357e-01
Dentistry                                    3.6094e-11 ***
Earth.and.Planetary.Sciences                 3.2190e-05 ***
Economics..Econometrics.and.Finance           < 2.2e-16 ***
Energy                                       1.3513e-01
Engineering                                   < 2.2e-16 ***
Environmental.Science                        1.5595e-02 *
Health.Professions                           2.4827e-05 ***
Immunology.and.Microbiology                   < 2.2e-16 ***
Materials.Science                             < 2.2e-16 ***
Mathematics                                  1.7994e-01
Medicine                                     9.9416e-03 **
Neuroscience                                 2.3296e-04 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics   7.8865e-13 ***
Physics.and.Astronomy                        4.8510e-02 *
Psychology                                   2.2125e-02 *
Social.Sciences                              1.8226e-01
Veterinary                                   3.1157e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -21,579.7   Adj. Pseudo R2: 0.057266
           BIC:  44,003.2     Squared Cor.: 0.081668

In [51]:
# 每组 reg_class 的平均预测概率
margins_eff_hs <- avg_comparisons(model_hs, variables = "CoType", comparison = 'ratio')
margins_eff_hs

  term   contrast                            estimate std.error  statistic
1 CoType mean(Collaboration) / mean(Service) 1.145328 0.03903589 29.34038
2 CoType mean(Participation) / mean(Service) 1.198086 0.05429612 22.06578
  p.value       s.value  conf.low conf.high predicted_lo predicted_hi predicted
1 3.169837e-189 626.1800 1.068819 1.221837  0.708386     0.7746839    0.708386
2 6.739312e-108 356.0156 1.091668 1.304505  0.708386     0.7968141    0.708386

In [52]:
fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_hs_comp_ratio.csv")
write.csv(margins_eff_hs, fname, row.names = FALSE)

In [53]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_hs,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\_bin\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                                 & 0.347$^{***}$\\
                                                       & (0.044)\\
   CoTypeParticipation                                 & 0.479$^{***}$\\
                                                       & (0.063)\\
   lnnum\_author                                       & 0.318$^{***}$\\
                                                       & (0.026)\\
   internationalinternational                          & 0.058$^{**}$\\
                                                       & (0.026)\\
   lnnum\_reference                                    & 0.110$^{***}$\\
                                                       & (0.028)\\
   num\_fac                                            & -0.123$^{***}$\\
                                                       & (0.021)\\
   SDGTrue                                             & 0.224$^{***}$\\
                                                       & (0.024)\\
   lnmean\_career\_age                                 & 0.187$^{***}$\\
                                                       & (0.039)\\
   lnex\_ld\_avg\_avgimpact                            & -0.334$^{***}$\\
                                                       & (0.022)\\
   lnex\_ld\_avg\_insthindex                           & -0.120$^{***}$\\
                                                       & (0.021)\\
   ex\_ld\_bin\_gsGlobalNorth                          & 0.233$^{***}$\\
                                                       & (0.062)\\
   ex\_ld\_bin\_sameCSame                              & -0.126$^{***}$\\
                                                       & (0.026)\\
   knowledge\_proximity\_mean                          & -1.03$^{**}$\\
                                                       & (0.404)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & -0.068$^{***}$\\
                                                       & (0.016)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & 0.174$^{***}$\\
                                                       & (0.028)\\
   Agricultural.and.Biological.Sciences                & -0.119$^{**}$\\
                                                       & (0.054)\\
   Arts.and.Humanities                                 & 0.832$^{**}$\\
                                                       & (0.423)\\
   Biochemistry..Genetics.and.Molecular.Biology        & -0.230$^{***}$\\
                                                       & (0.029)\\
   Business..Management.and.Accounting                 & -11.7$^{***}$\\
                                                       & (0.064)\\
   Chemical.Engineering                                & -0.295\\
                                                       & (0.275)\\
   Chemistry                                           & 0.055\\
                                                       & (0.038)\\
   Computer.Science                                    & 0.602$^{***}$\\
                                                       & (0.090)\\
   Decision.Sciences                                   & -1.31\\
                                                       & (0.829)\\
   Dentistry                                           & 0.962$^{***}$\\
                                                       & (0.145)\\
   Earth.and.Planetary.Sciences                        & 0.810$^{***}$\\
                                                       & (0.195)\\
   Economics..Econometrics.and.Finance                 & 10.6$^{***}$\\
                                                       & (0.122)\\
   Energy                                              & -0.159\\
                                                       & (0.106)\\
   Engineering                                         & 0.653$^{***}$\\
                                                       & (0.057)\\
   Immunology.and.Microbiology                         & -0.340$^{***}$\\
                                                       & (0.039)\\
   Materials.Science                                   & -0.385$^{***}$\\
                                                       & (0.038)\\
   Mathematics                                         & 0.765\\
                                                       & (0.571)\\
   Medicine                                            & 0.208$^{***}$\\
                                                       & (0.081)\\
   Neuroscience                                        & 0.230$^{***}$\\
                                                       & (0.062)\\
   Nursing                                             & 0.688$^{***}$\\
                                                       & (0.069)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & 0.603$^{***}$\\
                                                       & (0.084)\\
   Physics.and.Astronomy                               & 0.114$^{**}$\\
                                                       & (0.058)\\
   Psychology                                          & 0.863$^{**}$\\
                                                       & (0.377)\\
   Social.Sciences                                     & 0.780\\
                                                       & (0.584)\\
   Veterinary                                          & 0.208\\
                                                       & (0.205)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 33,409\\
   Squared Correlation                                 & 0.08167\\
   Pseudo R$^2$                                        & 0.06075\\
   BIC                                                 & 44,003.2\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [54]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_nps <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Physical.Sciences==0), ], family = binomial("logit"), vcov = "hetero")
summary(model_nps)

NOTE: 6 fixed-effects (10 observations) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 41,294
Fixed-effects: PublishedYear: 38
Standard-errors: Heteroskedasticity-robust
                                               Estimate Std. Error     z value
CoTypeCollaboration                            0.281504   0.042795    6.578026
CoTypeParticipation                            0.395612   0.059091    6.694940
lnnum_author                                   0.344441   0.023759   14.497001
internationalinternational                     0.107923   0.024142    4.470310
lnnum_reference                               -0.088769   0.026784   -3.314210
num_fac                                       -0.131631   0.018687   -7.044027
SDGTrue                                        0.260535   0.021376   12.188100
lnmean_career_age                              0.268377   0.035399    7.581545
lnex_ld_avg_avgimpact                         -0.534705   0.021070  -25.378090
lnex_ld_avg_insthindex                        -0.190322   0.020026   -9.503859
ex_ld_bin_gsGlobalNorth                        0.152237   0.056817    2.679438
ex_ld_bin_sameCSame                           -0.100106   0.023742   -4.216328
knowledge_proximity_mean                      -4.179590   0.435906   -9.588291
lnex_ld_avg_before_year_prod_fac              -0.042799   0.015277   -2.801456
ex_ld_max_before_year_with_ih_binTrue          0.189085   0.024465    7.728865
Agricultural.and.Biological.Sciences           0.113035   0.035315    3.200809
Arts.and.Humanities                            0.920384   0.297824    3.090363
Biochemistry..Genetics.and.Molecular.Biology  -0.284026   0.030631   -9.272387
Business..Management.and.Accounting          -11.755318   0.051718 -227.297108
Decision.Sciences                             -0.622566   0.950582   -0.654932
Dentistry                                      1.046458   0.189620    5.518709
Health.Professions                             0.431887   0.265345    1.627640
Immunology.and.Microbiology                   -0.038241   0.032126   -1.190344
Medicine                                       0.555125   0.022887   24.254997
Neuroscience                                   0.354464   0.040507    8.750633
Nursing                                        0.706599   0.058966   11.983127
Pharmacology..Toxicology.and.Pharmaceutics     0.826830   0.071825   11.511783
Psychology                                     0.573594   0.213898    2.681631
Social.Sciences                               -0.138181   0.342609   -0.403319
Veterinary                                     0.232365   0.226736    1.024823
                                               Pr(>|z|)
CoTypeCollaboration                          4.7673e-11 ***
CoTypeParticipation                          2.1576e-11 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   7.8106e-06 ***
lnnum_reference                              9.1903e-04 ***
num_fac                                      1.8676e-12 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            3.4146e-14 ***
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                        < 2.2e-16 ***
ex_ld_bin_gsGlobalNorth                      7.3746e-03 **
ex_ld_bin_sameCSame                          2.4831e-05 ***
knowledge_proximity_mean                      < 2.2e-16 ***
lnex_ld_avg_before_year_prod_fac             5.0873e-03 **
ex_ld_max_before_year_with_ih_binTrue        1.0851e-14 ***
Agricultural.and.Biological.Sciences         1.3704e-03 **
Arts.and.Humanities                          1.9991e-03 **
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting           < 2.2e-16 ***
Decision.Sciences                            5.1251e-01
Dentistry                                    3.4150e-08 ***
Health.Professions                           1.0360e-01
Immunology.and.Microbiology                  2.3391e-01
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Psychology                                   7.3264e-03 **
Social.Sciences                              6.8671e-01
Veterinary                                   3.0545e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -26,056.8   Adj. Pseudo R2: 0.075893
           BIC:  52,836.3     Squared Cor.: 0.103672

In [55]:
# 每组 reg_class 的平均预测概率
margins_eff_nps <- avg_comparisons(model_nps, variables = "CoType", comparison = 'ratio')
margins_eff_nps

  term   contrast                            estimate std.error  statistic
1 CoType mean(Collaboration) / mean(Service) 1.147427 0.03664651 31.31067
2 CoType mean(Participation) / mean(Service) 1.207672 0.05131421 23.53484
  p.value       s.value  conf.low conf.high predicted_lo predicted_hi predicted
1 3.339641e-215 712.4748 1.075601 1.219253  0.6711659    0.7300680    0.6711659
2 1.794850e-122 404.4314 1.107098 1.308246  0.6711659    0.7519566    0.6711659

In [56]:
fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_nps_comp_ratio.csv")
write.csv(margins_eff_nps, fname, row.names = FALSE)

In [57]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_nps,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\_bin\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                                 & 0.282$^{***}$\\
                                                       & (0.043)\\
   CoTypeParticipation                                 & 0.396$^{***}$\\
                                                       & (0.059)\\
   lnnum\_author                                       & 0.344$^{***}$\\
                                                       & (0.024)\\
   internationalinternational                          & 0.108$^{***}$\\
                                                       & (0.024)\\
   lnnum\_reference                                    & -0.089$^{***}$\\
                                                       & (0.027)\\
   num\_fac                                            & -0.132$^{***}$\\
                                                       & (0.019)\\
   SDGTrue                                             & 0.261$^{***}$\\
                                                       & (0.021)\\
   lnmean\_career\_age                                 & 0.268$^{***}$\\
                                                       & (0.035)\\
   lnex\_ld\_avg\_avgimpact                            & -0.535$^{***}$\\
                                                       & (0.021)\\
   lnex\_ld\_avg\_insthindex                           & -0.190$^{***}$\\
                                                       & (0.020)\\
   ex\_ld\_bin\_gsGlobalNorth                          & 0.152$^{***}$\\
                                                       & (0.057)\\
   ex\_ld\_bin\_sameCSame                              & -0.100$^{***}$\\
                                                       & (0.024)\\
   knowledge\_proximity\_mean                          & -4.18$^{***}$\\
                                                       & (0.436)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & -0.043$^{***}$\\
                                                       & (0.015)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & 0.189$^{***}$\\
                                                       & (0.025)\\
   Agricultural.and.Biological.Sciences                & 0.113$^{***}$\\
                                                       & (0.035)\\
   Arts.and.Humanities                                 & 0.920$^{***}$\\
                                                       & (0.298)\\
   Biochemistry..Genetics.and.Molecular.Biology        & -0.284$^{***}$\\
                                                       & (0.031)\\
   Business..Management.and.Accounting                 & -11.8$^{***}$\\
                                                       & (0.052)\\
   Decision.Sciences                                   & -0.623\\
                                                       & (0.951)\\
   Dentistry                                           & 1.05$^{***}$\\
                                                       & (0.190)\\
   Immunology.and.Microbiology                         & -0.038\\
                                                       & (0.032)\\
   Medicine                                            & 0.555$^{***}$\\
                                                       & (0.023)\\
   Neuroscience                                        & 0.354$^{***}$\\
                                                       & (0.041)\\
   Nursing                                             & 0.707$^{***}$\\
                                                       & (0.059)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & 0.827$^{***}$\\
                                                       & (0.072)\\
   Psychology                                          & 0.574$^{***}$\\
                                                       & (0.214)\\
   Social.Sciences                                     & -0.138\\
                                                       & (0.343)\\
   Veterinary                                          & 0.232\\
                                                       & (0.227)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 41,294\\
   Squared Correlation                                 & 0.10367\\
   Pseudo R$^2$                                        & 0.07826\\
   BIC                                                 & 52,836.3\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

# H3: Too much will suppress

# H3a: Participation too much not good

In [58]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ ratio_fac_scientist + I(ratio_fac_scientist^2) +  ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_h3_pratio <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_h3_pratio)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
ratio_fac_scientist                           0.399062   0.071372   5.591267
I(ratio_fac_scientist^2)                     -0.433564   0.122480  -3.539884
lnnum_author                                 -0.082493   0.007276 -11.337694
internationalinternational                   -0.046839   0.009596  -4.881206
lnnum_reference                               0.053172   0.008663   6.137694
num_fac                                       0.066116   0.006744   9.804320
SDGTrue                                       0.084209   0.008153  10.328778
lnmean_career_age                             0.010584   0.013087   0.808759
lnex_ld_avg_avgimpact                        -0.274666   0.007390 -37.164694
lnex_ld_avg_insthindex                       -0.049450   0.007532  -6.564943
ex_ld_bin_gsGlobalNorth                       0.309141   0.017495  17.669790
ex_ld_bin_sameCSame                          -0.060311   0.009439  -6.389433
knowledge_proximity_mean                     -0.803880   0.159918  -5.026820
lnex_ld_avg_before_year_prod_fac             -0.041385   0.004973  -8.322592
ex_ld_max_before_year_with_ih_binTrue         0.330477   0.011366  29.077166
Agricultural.and.Biological.Sciences          0.756757   0.023985  31.550601
Arts.and.Humanities                           1.771987   0.073079  24.247580
Biochemistry..Genetics.and.Molecular.Biology  0.597798   0.012612  47.397785
Business..Management.and.Accounting          -0.322884   0.087803  -3.677369
Chemical.Engineering                          0.163729   0.020828   7.861096
Chemistry                                     0.458407   0.011150  41.111054
Computer.Science                              0.940507   0.039588  23.757107
Decision.Sciences                             1.225182   0.189175   6.476462
Dentistry                                     1.954087   0.136120  14.355666
Earth.and.Planetary.Sciences                  0.753922   0.015281  49.338461
Economics..Econometrics.and.Finance          -0.077227   0.295639  -0.261221
Energy                                        0.236928   0.017920  13.221191
Engineering                                   0.328003   0.010482  31.291545
Environmental.Science                         0.578857   0.017492  33.092826
Health.Professions                            1.410085   0.128372  10.984406
Immunology.and.Microbiology                   0.234760   0.026909   8.724157
Materials.Science                             0.022590   0.009940   2.272738
Mathematics                                   0.574730   0.125522   4.578707
Medicine                                      0.867400   0.014844  58.434814
Neuroscience                                  0.521131   0.032654  15.959134
Nursing                                       1.051942   0.043252  24.321263
Pharmacology..Toxicology.and.Pharmaceutics    0.905283   0.048277  18.751703
Physics.and.Astronomy                        -0.259072   0.011487 -22.553409
Psychology                                    0.427178   0.157852   2.706190
Social.Sciences                               0.165813   0.156671   1.058351
Veterinary                                    0.600397   0.208551   2.878893
                                               Pr(>|z|)
ratio_fac_scientist                          2.2542e-08 ***
I(ratio_fac_scientist^2)                     4.0030e-04 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   1.0544e-06 ***
lnnum_reference                              8.3728e-10 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            4.1865e-01
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                       5.2053e-11 ***
ex_ld_bin_gsGlobalNorth                       < 2.2e-16 ***
ex_ld_bin_sameCSame                          1.6650e-10 ***
knowledge_proximity_mean                     4.9868e-07 ***
lnex_ld_avg_before_year_prod_fac              < 2.2e-16 ***
ex_ld_max_before_year_with_ih_binTrue         < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          2.3565e-04 ***
Chemical.Engineering                         3.8079e-15 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            9.3898e-11 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          7.9392e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                   < 2.2e-16 ***
Materials.Science                            2.3042e-02 *
Mathematics                                  4.6786e-06 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   6.8060e-03 **
Social.Sciences                              2.8990e-01
Veterinary                                   3.9907e-03 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -181,548.5   Adj. Pseudo R2: 0.059015
           BIC:  364,255.8     Squared Cor.: 0.075651

In [59]:
library(marginaleffects)
# 设置 draw = FALSE，直接拦截绘图数据
plot_data <- plot_predictions(model_h3_pratio, condition = "ratio_fac_scientist", draw = FALSE)
# 选出我们最需要的几列：x轴变量、预测值(estimate)、置信区间下限(conf.low)、上限(conf.high)
export_data <- plot_data[, c("ratio_fac_scientist", "estimate", "conf.low", "conf.high")]
# # 导出为 CSV 文件，给 Python 准备
write.csv(export_data, "R_ex_ld_h3_pred_pratio.csv", row.names = FALSE)
export_data
# print("数据已成功导出！")
# head(export_data)

   ratio_fac_scientist estimate  conf.low  conf.high
1  0.00000000          0.2482029 0.1974836 0.3069658
2  0.02003023          0.2496648 0.1987348 0.3086196
3  0.04006047          0.2510671 0.1999325 0.3102091
4  0.06009070          0.2524089 0.2010766 0.3117325
5  0.08012094          0.2536896 0.2021670 0.3131885
6  0.10015117          0.2549085 0.2032036 0.3145756
7  0.12018141          0.2560650 0.2041863 0.3158927
8  0.14021164          0.2571584 0.2051149 0.3171384
9  0.16024187          0.2581883 0.2059893 0.3183119
10 0.18027211          0.2591540 0.2068094 0.3194122
11 0.20030234          0.2600551 0.2075748 0.3204384
12 0.22033258          0.2608912 0.2082855 0.3213899
13 0.24036281          0.2616618 0.2089410 0.3222660
14 0.26039305          0.2623665 0.2095412 0.3230662
15 0.28042328          0.2630050 0.2100858 0.3237902
16 0.30045351          0.2635770 0.2105744 0.3244377
17 0.32048375          0.2640821 0.2110066 0.3250087
18 0.34051398          0.2645202 0.2113821 0.3255029
19 0.36054422          0.2648910 0.2117003 0.3259206
20 0.38057445          0.2651943 0.2119610 0.3262619
21 0.40060469          0.2654300 0.2121636 0.3265271
22 0.42063492          0.2655980 0.2123075 0.3267166
23 0.44066515          0.2656982 0.2123923 0.3268310
24 0.46069539          0.2657305 0.2124173 0.3268709
25 0.48072562          0.2656949 0.2123820 0.3268371
26 0.50075586          0.2655915 0.2122858 0.3267304
27 0.52078609          0.2654202 0.2121280 0.3265518
28 0.54081633          0.2651812 0.2119079 0.3263023
29 0.56084656          0.2648746 0.2116249 0.3259831
30 0.58087680          0.2645006 0.2112782 0.3255955
31 0.60090703          0.2640593 0.2108671 0.3251409
32 0.62093726          0.2635509 0.2103910 0.3246207
33 0.64096750          0.2629757 0.2098491 0.3240364
34 0.66099773          0.2623340 0.2092407 0.3233898
35 0.68102797          0.2616261 0.2085650 0.3226826
36 0.70105820          0.2608523 0.2078213 0.3219165
37 0.72108844          0.2600131 0.2070090 0.3210935
38 0.74111867          0.2591089 0.2061274 0.3202154
39 0.76114890          0.2581400 0.2051758 0.3192842
40 0.78117914          0.2571071 0.2041537 0.3183021
41 0.80120937          0.2560106 0.2030606 0.3172710
42 0.82123961          0.2548511 0.2018959 0.3161931
43 0.84126984          0.2536292 0.2006592 0.3150706
44 0.86130008          0.2523455 0.1993503 0.3139055
45 0.88133031          0.2510007 0.1979689 0.3127000
46 0.90136054          0.2495956 0.1965148 0.3114564
47 0.92139078          0.2481308 0.1949880 0.3101766
48 0.94142101          0.2466071 0.1933887 0.3088627
49 0.96145125          0.2450253 0.1917171 0.3075170
50 0.98148148          0.2433864 0.1899734 0.3061412

In [60]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_h3_pratio,
                           keep = c("ratio_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\_bin\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   ratio\_fac\_scientist                               & 0.399$^{***}$\\
                                                       & (0.071)\\
   ratio\_fac\_scientist square                        & -0.434$^{***}$\\
                                                       & (0.122)\\
   lnnum\_author                                       & -0.083$^{***}$\\
                                                       & (0.007)\\
   internationalinternational                          & -0.047$^{***}$\\
                                                       & (0.010)\\
   lnnum\_reference                                    & 0.053$^{***}$\\
                                                       & (0.009)\\
   num\_fac                                            & 0.066$^{***}$\\
                                                       & (0.007)\\
   SDGTrue                                             & 0.084$^{***}$\\
                                                       & (0.008)\\
   lnmean\_career\_age                                 & 0.011\\
                                                       & (0.013)\\
   lnex\_ld\_avg\_avgimpact                            & -0.275$^{***}$\\
                                                       & (0.007)\\
   lnex\_ld\_avg\_insthindex                           & -0.049$^{***}$\\
                                                       & (0.008)\\
   ex\_ld\_bin\_gsGlobalNorth                          & 0.309$^{***}$\\
                                                       & (0.018)\\
   ex\_ld\_bin\_sameCSame                              & -0.060$^{***}$\\
                                                       & (0.009)\\
   knowledge\_proximity\_mean                          & -0.804$^{***}$\\
                                                       & (0.160)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & -0.041$^{***}$\\
                                                       & (0.005)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & 0.330$^{***}$\\
                                                       & (0.011)\\
   Agricultural.and.Biological.Sciences                & 0.757$^{***}$\\
                                                       & (0.024)\\
   Arts.and.Humanities                                 & 1.77$^{***}$\\
                                                       & (0.073)\\
   Biochemistry..Genetics.and.Molecular.Biology        & 0.598$^{***}$\\
                                                       & (0.013)\\
   Business..Management.and.Accounting                 & -0.323$^{***}$\\
                                                       & (0.088)\\
   Chemical.Engineering                                & 0.164$^{***}$\\
                                                       & (0.021)\\
   Chemistry                                           & 0.458$^{***}$\\
                                                       & (0.011)\\
   Computer.Science                                    & 0.941$^{***}$\\
                                                       & (0.040)\\
   Decision.Sciences                                   & 1.23$^{***}$\\
                                                       & (0.189)\\
   Dentistry                                           & 1.95$^{***}$\\
                                                       & (0.136)\\
   Earth.and.Planetary.Sciences                        & 0.754$^{***}$\\
                                                       & (0.015)\\
   Economics..Econometrics.and.Finance                 & -0.077\\
                                                       & (0.296)\\
   Energy                                              & 0.237$^{***}$\\
                                                       & (0.018)\\
   Engineering                                         & 0.328$^{***}$\\
                                                       & (0.011)\\
   Immunology.and.Microbiology                         & 0.235$^{***}$\\
                                                       & (0.027)\\
   Materials.Science                                   & 0.023$^{**}$\\
                                                       & (0.010)\\
   Mathematics                                         & 0.575$^{***}$\\
                                                       & (0.126)\\
   Medicine                                            & 0.867$^{***}$\\
                                                       & (0.015)\\
   Neuroscience                                        & 0.521$^{***}$\\
                                                       & (0.033)\\
   Nursing                                             & 1.05$^{***}$\\
                                                       & (0.043)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & 0.905$^{***}$\\
                                                       & (0.048)\\
   Physics.and.Astronomy                               & -0.259$^{***}$\\
                                                       & (0.011)\\
   Psychology                                          & 0.427$^{***}$\\
                                                       & (0.158)\\
   Social.Sciences                                     & 0.166\\
                                                       & (0.157)\\
   Veterinary                                          & 0.600$^{***}$\\
                                                       & (0.209)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 294,879\\
   Squared Correlation                                 & 0.07565\\
   Pseudo R$^2$                                        & 0.05949\\
   BIC                                                 & 364,255.8\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

# H3b: Lead too much not good

In [61]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ fac_scientist_lead_ratio + I(fac_scientist_lead_ratio^2) +  ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_h3_lratio <- feglm(fml, data = data[(data$paper_type =='article')&(data$CoType_Service==0)&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_h3_lratio)

NOTE: 1 fixed-effect (11 observations) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 78,522
Fixed-effects: PublishedYear: 50
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
fac_scientist_lead_ratio                      0.254071   0.107512   2.363190
I(fac_scientist_lead_ratio^2)                -0.397031   0.159333  -2.491822
lnnum_author                                 -0.286696   0.015260 -18.787212
internationalinternational                   -0.095836   0.022500  -4.259467
lnnum_reference                               0.099232   0.017992   5.515410
num_fac                                       0.105508   0.010548  10.002539
SDGTrue                                       0.086080   0.016575   5.193481
lnmean_career_age                            -0.138351   0.030250  -4.573525
lnex_ld_avg_avgimpact                        -0.188596   0.014787 -12.754104
lnex_ld_avg_insthindex                       -0.043868   0.014598  -3.005007
ex_ld_bin_gsGlobalNorth                       0.495898   0.035384  14.014851
ex_ld_bin_sameCSame                          -0.111001   0.021351  -5.198862
knowledge_proximity_mean                     -0.905252   0.321920  -2.812040
lnex_ld_avg_before_year_prod_fac             -0.001122   0.009697  -0.115664
ex_ld_max_before_year_with_ih_binTrue         0.059114   0.033910   1.743293
Agricultural.and.Biological.Sciences          0.563118   0.051554  10.922841
Arts.and.Humanities                           2.094188   0.123781  16.918523
Biochemistry..Genetics.and.Molecular.Biology  0.868583   0.027134  32.011031
Business..Management.and.Accounting          -0.439960   0.144027  -3.054701
Chemical.Engineering                          0.228030   0.045211   5.043674
Chemistry                                     0.429390   0.023171  18.531652
Computer.Science                              0.879612   0.090744   9.693288
Decision.Sciences                             1.253177   0.325741   3.847152
Dentistry                                     1.878980   0.255698   7.348428
Earth.and.Planetary.Sciences                  0.966329   0.027753  34.819046
Economics..Econometrics.and.Finance          -0.120765   0.535716  -0.225426
Energy                                        0.291133   0.037234   7.819038
Engineering                                   0.365673   0.020282  18.029184
Environmental.Science                         0.823668   0.039889  20.649211
Health.Professions                            1.490300   0.236907   6.290667
Immunology.and.Microbiology                   0.069264   0.107023   0.647194
Materials.Science                            -0.119319   0.019731  -6.047294
Mathematics                                   0.138493   0.223339   0.620103
Medicine                                      1.348642   0.041126  32.793158
Neuroscience                                  0.531590   0.083348   6.377974
Nursing                                       1.838744   0.145180  12.665263
Pharmacology..Toxicology.and.Pharmaceutics    1.159520   0.143783   8.064357
Physics.and.Astronomy                        -0.352087   0.020763 -16.957557
Psychology                                   -0.617376   0.357984  -1.724589
Social.Sciences                              -0.041413   0.236883  -0.174822
Veterinary                                    0.382277   0.605066   0.631794
                                               Pr(>|z|)
fac_scientist_lead_ratio                     1.8118e-02 *
I(fac_scientist_lead_ratio^2)                1.2709e-02 *
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   2.0491e-05 ***
lnnum_reference                              3.4797e-08 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                      2.0640e-07 ***
lnmean_career_age                            4.7959e-06 ***
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                       2.6557e-03 **
ex_ld_bin_gsGlobalNorth                       < 2.2e-16 ***
ex_ld_bin_sameCSame                          2.0051e-07 ***
knowledge_proximity_mean                     4.9228e-03 **
lnex_ld_avg_before_year_prod_fac             9.0792e-01
ex_ld_max_before_year_with_ih_binTrue        8.1282e-02 .
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          2.2528e-03 **
Chemical.Engineering                         4.5668e-07 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            1.1950e-04 ***
Dentistry                                    2.0055e-13 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          8.2165e-01
Energy                                       5.3229e-15 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                           3.1610e-10 ***
Immunology.and.Microbiology                  5.1751e-01
Materials.Science                            1.4730e-09 ***
Mathematics                                  5.3519e-01
Medicine                                      < 2.2e-16 ***
Neuroscience                                 1.7945e-10 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics   7.3622e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   8.4601e-02 .
Social.Sciences                              8.6122e-01
Veterinary                                   5.2752e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -45,668.6   Adj. Pseudo R2: 0.101431
           BIC:  92,362.9     Squared Cor.: 0.12821

In [62]:
library(marginaleffects)
# 设置 draw = FALSE，直接拦截绘图数据
plot_data <- plot_predictions(model_h3_lratio, condition = "fac_scientist_lead_ratio", draw = FALSE)
# 选出我们最需要的几列：x轴变量、预测值(estimate)、置信区间下限(conf.low)、上限(conf.high)
export_data <- plot_data[, c("fac_scientist_lead_ratio", "estimate", "conf.low", "conf.high")]
# # 导出为 CSV 文件，给 Python 准备
write.csv(export_data, "R_ex_ld_h3_pred_lratio.csv", row.names = FALSE)
export_data
# print("数据已成功导出！")
# head(export_data)

   fac_scientist_lead_ratio estimate  conf.low  conf.high
1  0.00000000               0.2282580 0.1399389 0.3496565
2  0.01992225               0.2291231 0.1405339 0.3507653
3  0.03984451               0.2299346 0.1410897 0.3518100
4  0.05976676               0.2306922 0.1416063 0.3527891
5  0.07968902               0.2313955 0.1420839 0.3537015
6  0.09961127               0.2320441 0.1425226 0.3545462
7  0.11953353               0.2326377 0.1429224 0.3553220
8  0.13945578               0.2331761 0.1432835 0.3560282
9  0.15937804               0.2336588 0.1436060 0.3566637
10 0.17930029               0.2340858 0.1438900 0.3572280
11 0.19922255               0.2344567 0.1441356 0.3577202
12 0.21914480               0.2347714 0.1443428 0.3581400
13 0.23906706               0.2350297 0.1445117 0.3584867
14 0.25898931               0.2352315 0.1446423 0.3587600
15 0.27891156               0.2353767 0.1447347 0.3589596
16 0.29883382               0.2354652 0.1447889 0.3590853
17 0.31875607               0.2354970 0.1448048 0.3591369
18 0.33867833               0.2354721 0.1447826 0.3591146
19 0.35860058               0.2353905 0.1447221 0.3590182
20 0.37852284               0.2352521 0.1446234 0.3588480
21 0.39844509               0.2350572 0.1444863 0.3586042
22 0.41836735               0.2348057 0.1443109 0.3582872
23 0.43828960               0.2344978 0.1440971 0.3578974
24 0.45821186               0.2341337 0.1438447 0.3574353
25 0.47813411               0.2337136 0.1435538 0.3569015
26 0.49805637               0.2332375 0.1432242 0.3562967
27 0.51797862               0.2327059 0.1428557 0.3556218
28 0.53790087               0.2321190 0.1424484 0.3548775
29 0.55782313               0.2314770 0.1420020 0.3540649
30 0.57774538               0.2307803 0.1415164 0.3531850
31 0.59766764               0.2300293 0.1409915 0.3522389
32 0.61758989               0.2292243 0.1404272 0.3512279
33 0.63751215               0.2283657 0.1398232 0.3501532
34 0.65743440               0.2274540 0.1391796 0.3490163
35 0.67735666               0.2264897 0.1384961 0.3478187
36 0.69727891               0.2254732 0.1377726 0.3465617
37 0.71720117               0.2244051 0.1370090 0.3452472
38 0.73712342               0.2232859 0.1362052 0.3438767
39 0.75704568               0.2221163 0.1353611 0.3424521
40 0.77696793               0.2208968 0.1344766 0.3409752
41 0.79689018               0.2196281 0.1335516 0.3394478
42 0.81681244               0.2183108 0.1325862 0.3378720
43 0.83673469               0.2169457 0.1315803 0.3362497
44 0.85665695               0.2155335 0.1305339 0.3345830
45 0.87657920               0.2140749 0.1294471 0.3328741
46 0.89650146               0.2125708 0.1283200 0.3311249
47 0.91642371               0.2110219 0.1271527 0.3293379
48 0.93634597               0.2094292 0.1259454 0.3275152
49 0.95626822               0.2077934 0.1246984 0.3256589
50 0.97619048               0.2061154 0.1234118 0.3237715

In [63]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_h3_lratio,
                           keep = c("fac_scientist_lead_ratio", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\_bin\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   fac\_scientist\_lead\_ratio                         & 0.254$^{**}$\\
                                                       & (0.108)\\
   fac\_scientist\_lead\_ratio square                  & -0.397$^{**}$\\
                                                       & (0.159)\\
   lnnum\_author                                       & -0.287$^{***}$\\
                                                       & (0.015)\\
   internationalinternational                          & -0.096$^{***}$\\
                                                       & (0.022)\\
   lnnum\_reference                                    & 0.099$^{***}$\\
                                                       & (0.018)\\
   num\_fac                                            & 0.106$^{***}$\\
                                                       & (0.011)\\
   SDGTrue                                             & 0.086$^{***}$\\
                                                       & (0.017)\\
   lnmean\_career\_age                                 & -0.138$^{***}$\\
                                                       & (0.030)\\
   lnex\_ld\_avg\_avgimpact                            & -0.189$^{***}$\\
                                                       & (0.015)\\
   lnex\_ld\_avg\_insthindex                           & -0.044$^{***}$\\
                                                       & (0.015)\\
   ex\_ld\_bin\_gsGlobalNorth                          & 0.496$^{***}$\\
                                                       & (0.035)\\
   ex\_ld\_bin\_sameCSame                              & -0.111$^{***}$\\
                                                       & (0.021)\\
   knowledge\_proximity\_mean                          & -0.905$^{***}$\\
                                                       & (0.322)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & -0.001\\
                                                       & (0.010)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & 0.059$^{*}$\\
                                                       & (0.034)\\
   Agricultural.and.Biological.Sciences                & 0.563$^{***}$\\
                                                       & (0.052)\\
   Arts.and.Humanities                                 & 2.09$^{***}$\\
                                                       & (0.124)\\
   Biochemistry..Genetics.and.Molecular.Biology        & 0.869$^{***}$\\
                                                       & (0.027)\\
   Business..Management.and.Accounting                 & -0.440$^{***}$\\
                                                       & (0.144)\\
   Chemical.Engineering                                & 0.228$^{***}$\\
                                                       & (0.045)\\
   Chemistry                                           & 0.429$^{***}$\\
                                                       & (0.023)\\
   Computer.Science                                    & 0.880$^{***}$\\
                                                       & (0.091)\\
   Decision.Sciences                                   & 1.25$^{***}$\\
                                                       & (0.326)\\
   Dentistry                                           & 1.88$^{***}$\\
                                                       & (0.256)\\
   Earth.and.Planetary.Sciences                        & 0.966$^{***}$\\
                                                       & (0.028)\\
   Economics..Econometrics.and.Finance                 & -0.121\\
                                                       & (0.536)\\
   Energy                                              & 0.291$^{***}$\\
                                                       & (0.037)\\
   Engineering                                         & 0.366$^{***}$\\
                                                       & (0.020)\\
   Immunology.and.Microbiology                         & 0.069\\
                                                       & (0.107)\\
   Materials.Science                                   & -0.119$^{***}$\\
                                                       & (0.020)\\
   Mathematics                                         & 0.138\\
                                                       & (0.223)\\
   Medicine                                            & 1.35$^{***}$\\
                                                       & (0.041)\\
   Neuroscience                                        & 0.532$^{***}$\\
                                                       & (0.083)\\
   Nursing                                             & 1.84$^{***}$\\
                                                       & (0.145)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & 1.16$^{***}$\\
                                                       & (0.144)\\
   Physics.and.Astronomy                               & -0.352$^{***}$\\
                                                       & (0.021)\\
   Psychology                                          & -0.617$^{*}$\\
                                                       & (0.358)\\
   Social.Sciences                                     & -0.041\\
                                                       & (0.237)\\
   Veterinary                                          & 0.382\\
                                                       & (0.605)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 78,522\\
   Squared Correlation                                 & 0.12821\\
   Pseudo R$^2$                                        & 0.10320\\
   BIC                                                 & 92,362.9\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

# Moderating

In [14]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType*lnex_ld_avg_before_year_prod_fac  + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_pre_facpub <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_pre_facpub)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                                      Estimate Std. Error
CoTypeCollaboration                                   0.077524   0.025548
CoTypeParticipation                                   0.183022   0.036288
lnex_ld_avg_before_year_prod_fac                     -0.034970   0.005794
lnnum_author                                         -0.077789   0.007564
internationalinternational                           -0.048093   0.009603
lnnum_reference                                       0.053375   0.008660
num_fac                                               0.067123   0.006768
SDGTrue                                               0.083389   0.008155
lnmean_career_age                                     0.007946   0.013100
lnex_ld_avg_avgimpact                                -0.275959   0.007399
lnex_ld_avg_insthindex                               -0.048949   0.007532
ex_ld_bin_gsGlobalNorth                               0.309820   0.017502
ex_ld_bin_sameCSame                                  -0.062527   0.009460
knowledge_proximity_mean                             -0.795917   0.159912
ex_ld_max_before_year_with_ih_binTrue                 0.324780   0.011481
Agricultural.and.Biological.Sciences                  0.756010   0.023992
Arts.and.Humanities                                   1.771557   0.073080
Biochemistry..Genetics.and.Molecular.Biology          0.595929   0.012617
Business..Management.and.Accounting                  -0.327138   0.087898
Chemical.Engineering                                  0.163207   0.020827
Chemistry                                             0.458024   0.011151
Computer.Science                                      0.939377   0.039568
Decision.Sciences                                     1.219108   0.188958
Dentistry                                             1.953494   0.136284
Earth.and.Planetary.Sciences                          0.753546   0.015283
Economics..Econometrics.and.Finance                  -0.077407   0.295585
Energy                                                0.235921   0.017923
Engineering                                           0.326635   0.010490
Environmental.Science                                 0.578061   0.017493
Health.Professions                                    1.408228   0.128461
Immunology.and.Microbiology                           0.233780   0.026910
Materials.Science                                     0.022847   0.009941
Mathematics                                           0.578513   0.125519
Medicine                                              0.866930   0.014849
Neuroscience                                          0.520340   0.032640
Nursing                                               1.051717   0.043236
Pharmacology..Toxicology.and.Pharmaceutics            0.906872   0.048288
Physics.and.Astronomy                                -0.260102   0.011476
Psychology                                            0.425995   0.157857
Social.Sciences                                       0.159149   0.156407
Veterinary                                            0.601420   0.208498
CoTypeCollaboration:lnex_ld_avg_before_year_prod_fac  0.006766   0.009965
CoTypeParticipation:lnex_ld_avg_before_year_prod_fac -0.075558   0.013736
                                                        z value   Pr(>|z|)
CoTypeCollaboration                                    3.034454 2.4097e-03 **
CoTypeParticipation                                    5.043610 4.5683e-07 ***
lnex_ld_avg_before_year_prod_fac                      -6.035895 1.5808e-09 ***
lnnum_author                                         -10.283987  < 2.2e-16 ***
internationalinternational                            -5.008204 5.4940e-07 ***
lnnum_reference                                        6.163346 7.1224e-10 ***
num_fac                                                9.917676  < 2.2e-16 ***
SDGTrue                                               10.225463  < 2.2e-16 ***
lnmean_career_age                                      0.606535 5.4416e-01
lnex_ld_avg_avgimpact                                -37.295814  < 2.2e-16 ***
lnex_ld_avg_insthindex                                -6.498917 8.0901e-11 ***
ex_ld_bin_gsGlobalNorth                               17.702434  < 2.2e-16 ***
ex_ld_bin_sameCSame                                   -6.609884 3.8462e-11 ***
knowledge_proximity_mean                              -4.977230 6.4501e-07 ***
ex_ld_max_before_year_with_ih_binTrue                 28.287903  < 2.2e-16 ***
Agricultural.and.Biological.Sciences                  31.510602  < 2.2e-16 ***
Arts.and.Humanities                                   24.241180  < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology          47.232186  < 2.2e-16 ***
Business..Management.and.Accounting                   -3.721778 1.9783e-04 ***
Chemical.Engineering                                   7.836291 4.6405e-15 ***
Chemistry                                             41.074274  < 2.2e-16 ***
Computer.Science                                      23.741092  < 2.2e-16 ***
Decision.Sciences                                      6.451751 1.1057e-10 ***
Dentistry                                             14.334027  < 2.2e-16 ***
Earth.and.Planetary.Sciences                          49.306430  < 2.2e-16 ***
Economics..Econometrics.and.Finance                   -0.261876 7.9342e-01
Energy                                                13.163339  < 2.2e-16 ***
Engineering                                           31.138265  < 2.2e-16 ***
Environmental.Science                                 33.045266  < 2.2e-16 ***
Health.Professions                                    10.962298  < 2.2e-16 ***
Immunology.and.Microbiology                            8.687630  < 2.2e-16 ***
Materials.Science                                      2.298232 2.1549e-02 *
Mathematics                                            4.608959 4.0469e-06 ***
Medicine                                              58.381515  < 2.2e-16 ***
Neuroscience                                          15.941557  < 2.2e-16 ***
Nursing                                               24.325165  < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics            18.780338  < 2.2e-16 ***
Physics.and.Astronomy                                -22.664034  < 2.2e-16 ***
Psychology                                             2.698612 6.9629e-03 **
Social.Sciences                                        1.017530 3.0890e-01
Veterinary                                             2.884542 3.9198e-03 **
CoTypeCollaboration:lnex_ld_avg_before_year_prod_fac   0.679017 4.9713e-01
CoTypeParticipation:lnex_ld_avg_before_year_prod_fac  -5.500806 3.7806e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -181,520.3   Adj. Pseudo R2: 0.059151
           BIC:  364,224.5     Squared Cor.: 0.07576

In [15]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType*lnex_ld_avg_before_year_with_ih  + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_pre_facpub <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_pre_facpub)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                                     Estimate Std. Error
CoTypeCollaboration                                  0.189021   0.019932
CoTypeParticipation                                  0.294749   0.027377
lnex_ld_avg_before_year_with_ih                      0.143061   0.008074
lnnum_author                                        -0.070425   0.007635
internationalinternational                          -0.052485   0.009604
lnnum_reference                                      0.055130   0.008667
num_fac                                              0.068463   0.006746
SDGTrue                                              0.085719   0.008162
lnmean_career_age                                    0.004793   0.013110
lnex_ld_avg_avgimpact                               -0.276463   0.007407
lnex_ld_avg_insthindex                              -0.041626   0.007556
ex_ld_bin_gsGlobalNorth                              0.304096   0.017521
ex_ld_bin_sameCSame                                 -0.051193   0.009509
knowledge_proximity_mean                            -0.765522   0.160022
lnex_ld_avg_before_year_prod_fac                    -0.073390   0.006241
ex_ld_max_before_year_with_ih_binTrue                0.239077   0.012347
Agricultural.and.Biological.Sciences                 0.750681   0.023999
Arts.and.Humanities                                  1.759150   0.073194
Biochemistry..Genetics.and.Molecular.Biology         0.610546   0.012649
Business..Management.and.Accounting                 -0.348761   0.088025
Chemical.Engineering                                 0.169375   0.020857
Chemistry                                            0.458412   0.011160
Computer.Science                                     0.936131   0.039511
Decision.Sciences                                    1.212182   0.189796
Dentistry                                            1.937950   0.136518
Earth.and.Planetary.Sciences                         0.752127   0.015307
Economics..Econometrics.and.Finance                 -0.080285   0.296923
Energy                                               0.234488   0.017942
Engineering                                          0.323450   0.010500
Environmental.Science                                0.578856   0.017492
Health.Professions                                   1.401205   0.128604
Immunology.and.Microbiology                          0.245883   0.026940
Materials.Science                                    0.016004   0.009958
Mathematics                                          0.574349   0.126424
Medicine                                             0.877011   0.014859
Neuroscience                                         0.517026   0.032669
Nursing                                              1.051445   0.043085
Pharmacology..Toxicology.and.Pharmaceutics           0.913673   0.048259
Physics.and.Astronomy                               -0.278544   0.011556
Psychology                                           0.434192   0.158760
Social.Sciences                                      0.138230   0.156895
Veterinary                                           0.618644   0.208757
CoTypeCollaboration:lnex_ld_avg_before_year_with_ih -0.114406   0.011234
CoTypeParticipation:lnex_ld_avg_before_year_with_ih -0.232556   0.014820
                                                       z value   Pr(>|z|)
CoTypeCollaboration                                   9.483346  < 2.2e-16 ***
CoTypeParticipation                                  10.766142  < 2.2e-16 ***
lnex_ld_avg_before_year_with_ih                      17.719484  < 2.2e-16 ***
lnnum_author                                         -9.223833  < 2.2e-16 ***
internationalinternational                           -5.464776 4.6349e-08 ***
lnnum_reference                                       6.361200 2.0018e-10 ***
num_fac                                              10.148137  < 2.2e-16 ***
SDGTrue                                              10.501942  < 2.2e-16 ***
lnmean_career_age                                     0.365576 7.1468e-01
lnex_ld_avg_avgimpact                               -37.323742  < 2.2e-16 ***
lnex_ld_avg_insthindex                               -5.509080 3.6071e-08 ***
ex_ld_bin_gsGlobalNorth                              17.356049  < 2.2e-16 ***
ex_ld_bin_sameCSame                                  -5.383534 7.3038e-08 ***
knowledge_proximity_mean                             -4.783852 1.7197e-06 ***
lnex_ld_avg_before_year_prod_fac                    -11.758629  < 2.2e-16 ***
ex_ld_max_before_year_with_ih_binTrue                19.363129  < 2.2e-16 ***
Agricultural.and.Biological.Sciences                 31.279803  < 2.2e-16 ***
Arts.and.Humanities                                  24.033917  < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology         48.268739  < 2.2e-16 ***
Business..Management.and.Accounting                  -3.962084 7.4298e-05 ***
Chemical.Engineering                                  8.120809 4.6309e-16 ***
Chemistry                                            41.075928  < 2.2e-16 ***
Computer.Science                                     23.692864  < 2.2e-16 ***
Decision.Sciences                                     6.386760 1.6944e-10 ***
Dentistry                                            14.195601  < 2.2e-16 ***
Earth.and.Planetary.Sciences                         49.137721  < 2.2e-16 ***
Economics..Econometrics.and.Finance                  -0.270392 7.8686e-01
Energy                                               13.069335  < 2.2e-16 ***
Engineering                                          30.803986  < 2.2e-16 ***
Environmental.Science                                33.093156  < 2.2e-16 ***
Health.Professions                                   10.895538  < 2.2e-16 ***
Immunology.and.Microbiology                           9.126908  < 2.2e-16 ***
Materials.Science                                     1.607190 1.0801e-01
Mathematics                                           4.543052 5.5446e-06 ***
Medicine                                             59.023551  < 2.2e-16 ***
Neuroscience                                         15.826336  < 2.2e-16 ***
Nursing                                              24.404090  < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics           18.932527  < 2.2e-16 ***
Physics.and.Astronomy                               -24.104132  < 2.2e-16 ***
Psychology                                            2.734897 6.2400e-03 **
Social.Sciences                                       0.881039 3.7830e-01
Veterinary                                            2.963462 3.0420e-03 **
CoTypeCollaboration:lnex_ld_avg_before_year_with_ih -10.183787  < 2.2e-16 ***
CoTypeParticipation:lnex_ld_avg_before_year_with_ih -15.692359  < 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -181,327.7   Adj. Pseudo R2: 0.060143
           BIC:  363,851.9     Squared Cor.: 0.077082

In [41]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType*lnex_ld_avg_before_year_participation  + ", paper_level, "+", ex_controls, "+ lnex_ld_avg_before_year_prod_fac ",  "+",disciplines, " | PublishedYear")
)
model_pre_facpub <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_pre_facpub)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                                           Estimate Std. Error
CoTypeCollaboration                                        0.177073   0.014540
CoTypeParticipation                                        0.319217   0.021682
lnex_ld_avg_before_year_participation                      0.120695   0.011073
lnnum_author                                              -0.046444   0.007749
internationalinternational                                -0.044135   0.009611
lnnum_reference                                            0.057652   0.008641
num_fac                                                    0.061298   0.006750
SDGTrue                                                    0.083007   0.008152
lnmean_career_age                                          0.019726   0.013073
lnex_ld_avg_avgimpact                                     -0.272777   0.007387
lnex_ld_avg_insthindex                                    -0.045304   0.007527
ex_ld_bin_gsGlobalNorth                                    0.314382   0.017491
ex_ld_bin_sameCSame                                       -0.079964   0.009486
knowledge_proximity_mean                                  -0.780839   0.159844
lnex_ld_avg_before_year_prod_fac                           0.008948   0.005276
Agricultural.and.Biological.Sciences                       0.771837   0.023931
Arts.and.Humanities                                        1.781377   0.072570
Biochemistry..Genetics.and.Molecular.Biology               0.583196   0.012621
Business..Management.and.Accounting                       -0.337853   0.088242
Chemical.Engineering                                       0.156933   0.020809
Chemistry                                                  0.470181   0.011128
Computer.Science                                           0.930564   0.039455
Decision.Sciences                                          1.229211   0.187570
Dentistry                                                  1.974605   0.135831
Earth.and.Planetary.Sciences                               0.751488   0.015319
Economics..Econometrics.and.Finance                       -0.094900   0.293478
Energy                                                     0.246638   0.017916
Engineering                                                0.340477   0.010463
Environmental.Science                                      0.572317   0.017539
Health.Professions                                         1.411369   0.128232
Immunology.and.Microbiology                                0.218346   0.026792
Materials.Science                                          0.036470   0.009920
Mathematics                                                0.608451   0.124497
Medicine                                                   0.855449   0.014799
Neuroscience                                               0.514858   0.032461
Nursing                                                    1.059462   0.043166
Pharmacology..Toxicology.and.Pharmaceutics                 0.908597   0.048038
Physics.and.Astronomy                                     -0.256522   0.011515
Psychology                                                 0.410068   0.156166
Social.Sciences                                            0.177706   0.156190
Veterinary                                                 0.606931   0.206958
CoTypeCollaboration:lnex_ld_avg_before_year_participation -0.115179   0.016149
CoTypeParticipation:lnex_ld_avg_before_year_participation -0.363091   0.018423
                                                             z value   Pr(>|z|)
CoTypeCollaboration                                        12.178343  < 2.2e-16
CoTypeParticipation                                        14.722986  < 2.2e-16
lnex_ld_avg_before_year_participation                      10.899505  < 2.2e-16
lnnum_author                                               -5.993754 2.0505e-09
internationalinternational                                 -4.592136 4.3873e-06
lnnum_reference                                             6.672028 2.5229e-11
num_fac                                                     9.081301  < 2.2e-16
SDGTrue                                                    10.182477  < 2.2e-16
lnmean_career_age                                           1.508852 1.3134e-01
lnex_ld_avg_avgimpact                                     -36.927654  < 2.2e-16
lnex_ld_avg_insthindex                                     -6.018487 1.7606e-09
ex_ld_bin_gsGlobalNorth                                    17.973994  < 2.2e-16
ex_ld_bin_sameCSame                                        -8.429938  < 2.2e-16
knowledge_proximity_mean                                   -4.885001 1.0343e-06
lnex_ld_avg_before_year_prod_fac                            1.696092 8.9868e-02
Agricultural.and.Biological.Sciences                       32.252636  < 2.2e-16
Arts.and.Humanities                                        24.547179  < 2.2e-16
Biochemistry..Genetics.and.Molecular.Biology               46.206593  < 2.2e-16
Business..Management.and.Accounting                        -3.828698 1.2882e-04
Chemical.Engineering                                        7.541627 4.6414e-14
Chemistry                                                  42.252108  < 2.2e-16
Computer.Science                                           23.585342  < 2.2e-16
Decision.Sciences                                           6.553357 5.6258e-11
Dentistry                                                  14.537235  < 2.2e-16
Earth.and.Planetary.Sciences                               49.054956  < 2.2e-16
Economics..Econometrics.and.Finance                        -0.323363 7.4642e-01
Energy                                                     13.766257  < 2.2e-16
Engineering                                                32.540306  < 2.2e-16
Environmental.Science                                      32.631374  < 2.2e-16
Health.Professions                                         11.006392  < 2.2e-16
Immunology.and.Microbiology                                 8.149768 3.6462e-16
Materials.Science                                           3.676610 2.3635e-04
Mathematics                                                 4.887276 1.0224e-06
Medicine                                                   57.804655  < 2.2e-16
Neuroscience                                               15.860875  < 2.2e-16
Nursing                                                    24.544054  < 2.2e-16
Pharmacology..Toxicology.and.Pharmaceutics                 18.914126  < 2.2e-16
Physics.and.Astronomy                                     -22.276665  < 2.2e-16
Psychology                                                  2.625850 8.6433e-03
Social.Sciences                                             1.137757 2.5522e-01
Veterinary                                                  2.932629 3.3610e-03
CoTypeCollaboration:lnex_ld_avg_before_year_participation  -7.132422 9.8618e-13
CoTypeParticipation:lnex_ld_avg_before_year_participation -19.708283  < 2.2e-16

CoTypeCollaboration                                       ***
CoTypeParticipation                                       ***
lnex_ld_avg_before_year_participation                     ***
lnnum_author                                              ***
internationalinternational                                ***
lnnum_reference                                           ***
num_fac                                                   ***
SDGTrue                                                   ***
lnmean_career_age
lnex_ld_avg_avgimpact                                     ***
lnex_ld_avg_insthindex                                    ***
ex_ld_bin_gsGlobalNorth                                   ***
ex_ld_bin_sameCSame                                       ***
knowledge_proximity_mean                                  ***
lnex_ld_avg_before_year_prod_fac                          .
Agricultural.and.Biological.Sciences                      ***
Arts.and.Humanities                                       ***
Biochemistry..Genetics.and.Molecular.Biology              ***
Business..Management.and.Accounting                       ***
Chemical.Engineering                                      ***
Chemistry                                                 ***
Computer.Science                                          ***
Decision.Sciences                                         ***
Dentistry                                                 ***
Earth.and.Planetary.Sciences                              ***
Economics..Econometrics.and.Finance
Energy                                                    ***
Engineering                                               ***
Environmental.Science                                     ***
Health.Professions                                        ***
Immunology.and.Microbiology                               ***
Materials.Science                                         ***
Mathematics                                               ***
Medicine                                                  ***
Neuroscience                                              ***
Nursing                                                   ***
Pharmacology..Toxicology.and.Pharmaceutics                ***
Physics.and.Astronomy                                     ***
Psychology                                                **
Social.Sciences
Veterinary                                                **
CoTypeCollaboration:lnex_ld_avg_before_year_participation ***
CoTypeParticipation:lnex_ld_avg_before_year_participation ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -181,791.3   Adj. Pseudo R2: 0.057747
           BIC:  364,766.5     Squared Cor.: 0.073804

In [42]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_pre_facpub,
                           keep = c("CoType", "lnex_ld_avg_before_year_participation"),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                                           & novel\_uzzi\_bin\\
   Model:                                                                        & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                                                           & 0.177$^{***}$\\
                                                                                 & (0.015)\\
   CoTypeParticipation                                                           & 0.319$^{***}$\\
                                                                                 & (0.022)\\
   lnex\_ld\_avg\_before\_year\_participation                                    & 0.121$^{***}$\\
                                                                                 & (0.011)\\
   CoTypeCollaboration $\times$ lnex\_ld\_avg\_before\_year\_participation       & -0.115$^{***}$\\
                                                                                 & (0.016)\\
   CoTypeParticipation $\times$ lnex\_ld\_avg\_before\_year\_participation       & -0.363$^{***}$\\
                                                                                 & (0.018)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                                                 & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                                                  & 294,879\\
   Squared Correlation                                                           & 0.07380\\
   Pseudo R$^2$                                                                  & 0.05823\\
   BIC                                                                           & 364,766.5\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [36]:
# 1. 找到你这个连续变量的实际最小值和最大值（假设是 0 和 10，你需要改成你的实际极值）
min_val <- min(data$lnex_ld_avg_before_year_participation, na.rm=TRUE)
max_val <- max(data$lnex_ld_avg_before_year_participation, na.rm=TRUE)
# 2. 运行估计
res_pre_facpub <- avg_comparisons(
    model_pre_facpub,
    variables = "CoType",
    comparison = "ratio",
    newdata = datagrid(
    model = model_pre_facpub,
    lnex_ld_avg_before_year_participation = seq(min_val, max_val, length.out = 50) # 这里的 10 可以改成任意你想要的数字
  ),
    by = "lnex_ld_avg_before_year_participation"
)
res_pre_facpub

    rowid term   contrast
1    1    CoType mean(Collaboration) / mean(Service)
2    2    CoType mean(Collaboration) / mean(Service)
3    3    CoType mean(Collaboration) / mean(Service)
4    4    CoType mean(Collaboration) / mean(Service)
5    5    CoType mean(Collaboration) / mean(Service)
6    6    CoType mean(Collaboration) / mean(Service)
7    7    CoType mean(Collaboration) / mean(Service)
8    8    CoType mean(Collaboration) / mean(Service)
9    9    CoType mean(Collaboration) / mean(Service)
10  10    CoType mean(Collaboration) / mean(Service)
11  11    CoType mean(Collaboration) / mean(Service)
12  12    CoType mean(Collaboration) / mean(Service)
13  13    CoType mean(Collaboration) / mean(Service)
14  14    CoType mean(Collaboration) / mean(Service)
15  15    CoType mean(Collaboration) / mean(Service)
16  16    CoType mean(Collaboration) / mean(Service)
17  17    CoType mean(Collaboration) / mean(Service)
18  18    CoType mean(Collaboration) / mean(Service)
19  19    CoType mean(Collaboration) / mean(Service)
20  20    CoType mean(Collaboration) / mean(Service)
21  21    CoType mean(Collaboration) / mean(Service)
22  22    CoType mean(Collaboration) / mean(Service)
23  23    CoType mean(Collaboration) / mean(Service)
24  24    CoType mean(Collaboration) / mean(Service)
25  25    CoType mean(Collaboration) / mean(Service)
26  26    CoType mean(Collaboration) / mean(Service)
27  27    CoType mean(Collaboration) / mean(Service)
28  28    CoType mean(Collaboration) / mean(Service)
29  29    CoType mean(Collaboration) / mean(Service)
30  30    CoType mean(Collaboration) / mean(Service)
⋮   ⋮     ⋮      ⋮
71   71   CoType mean(Participation) / mean(Service)
72   72   CoType mean(Participation) / mean(Service)
73   73   CoType mean(Participation) / mean(Service)
74   74   CoType mean(Participation) / mean(Service)
75   75   CoType mean(Participation) / mean(Service)
76   76   CoType mean(Participation) / mean(Service)
77   77   CoType mean(Participation) / mean(Service)
78   78   CoType mean(Participation) / mean(Service)
79   79   CoType mean(Participation) / mean(Service)
80   80   CoType mean(Participation) / mean(Service)
81   81   CoType mean(Participation) / mean(Service)
82   82   CoType mean(Participation) / mean(Service)
83   83   CoType mean(Participation) / mean(Service)
84   84   CoType mean(Participation) / mean(Service)
85   85   CoType mean(Participation) / mean(Service)
86   86   CoType mean(Participation) / mean(Service)
87   87   CoType mean(Participation) / mean(Service)
88   88   CoType mean(Participation) / mean(Service)
89   89   CoType mean(Participation) / mean(Service)
90   90   CoType mean(Participation) / mean(Service)
91   91   CoType mean(Participation) / mean(Service)
92   92   CoType mean(Participation) / mean(Service)
93   93   CoType mean(Participation) / mean(Service)
94   94   CoType mean(Participation) / mean(Service)
95   95   CoType mean(Participation) / mean(Service)
96   96   CoType mean(Participation) / mean(Service)
97   97   CoType mean(Participation) / mean(Service)
98   98   CoType mean(Participation) / mean(Service)
99   99   CoType mean(Participation) / mean(Service)
100 100   CoType mean(Participation) / mean(Service)
    lnex_ld_avg_before_year_participation estimate  std.error   statistic
1   0.0000000                             1.1432238 0.013665503  83.65765
2   0.1318028                             1.1299023 0.012373630  91.31535
3   0.2636056                             1.1167860 0.011300257  98.82838
4   0.3954085                             1.1038719 0.010485475 105.27629
5   0.5272113                             1.0911569 0.009965852 109.48958
6   0.6590141                             1.0786380 0.009762539 110.48744
7   0.7908169                             1.0663121 0.009870804 108.02688
8   0.9226198                             1.0541763 0.010258757 102.75868
9   1.0544226                             1.0422278 0.010876922  95.82010
10  1.1862254                             1.0304636 0.011671568  88.28836
11  1.3180282                             1.0188810 0.012594271  80.90035
12  1.4498310                             1.0074772 0.013605855  74.04732
13  1.5816339                             0.9962494 0.014676450  67.88082
14  1.7134367                             0.9851951 0.015783990  62.41737
15  1.8452395                             0.9743115 0.016912366  57.60941
16  1.9770423                             0.9635960 0.018049867  53.38521
17  2.1088452                             0.9530461 0.019187973  49.66893
18  2.2406480                             0.9426593 0.020320463  46.38966
19  2.3724508                             0.9324331 0.021442783  43.48470
20  2.5042536                             0.9223649 0.022551594  40.90021
21  2.6360564                             0.9124526 0.023644455  38.59055
22  2.7678593                             0.9026935 0.024719593  36.51733
23  2.8996621                             0.8930855 0.025775734  34.64830
24  3.0314649                             0.8836261 0.026811990  32.95638
25  3.1632677                             0.8743133 0.027827760  31.41874
26  3.2950706                             0.8651446 0.028822665  30.01612
27  3.4268734                             0.8561179 0.029796506  28.73216
28  3.5586762                             0.8472311 0.030749217  27.55293
29  3.6904790                             0.8384820 0.031680835  26.46654
30  3.8222818                             0.8298686 0.032591490  25.46274
⋮   ⋮                                     ⋮         ⋮           ⋮
71  2.636056                              0.6116937 0.02008924  30.44882
72  2.767859                              0.5890812 0.02059209  28.60716
73  2.899662                              0.5672518 0.02104018  26.96041
74  3.031465                              0.5461823 0.02143468  25.48125
75  3.163268                              0.5258501 0.02177718  24.14684
76  3.295071                              0.5062327 0.02206958  22.93803
77  3.426873                              0.4873083 0.02231394  21.83874
78  3.558676                              0.4690554 0.02251248  20.83535
79  3.690479                              0.4514533 0.02266747  19.91635
80  3.822282                              0.4344812 0.02278120  19.07192
81  3.954085                              0.4181192 0.02285598  18.29365
82  4.085887                              0.4023477 0.02289409  17.57431
83  4.217690                              0.3871476 0.02289777  16.90766
84  4.349493                              0.3725003 0.02286921  16.28829
85  4.481296                              0.3583875 0.02281055  15.71148
86  4.613099                              0.3447916 0.02272384  15.17312
87  4.744902                              0.3316952 0.02261109  14.66958
88  4.876704                              0.3190816 0.02247419  14.19769
89  5.008507                              0.3069344 0.02231500  13.75462
90  5.140310                              0.2952377 0.02213527  13.33789
91  5.272113                              0.2839760 0.02193670  12.94525
92  5.403916                              0.2731343 0.02172088  12.57474
93  5.535719                              0.2626980 0.02148934  12.22457
94  5.667521                              0.2526529 0.02124354  11.89316
95  5.799324                              0.2429852 0.02098486  11.57907
96  5.931127                              0.2336817 0.02071460  11.28101
97  6.062930                              0.2247293 0.02043401  10.99781
98  6.194733                              0.2161155 0.02014424  10.72840
99  6.326535                              0.2078282 0.01984640  10.47183
100 6.458338                              0.1998555 0.01954153  10.22722
    p.value       s.value   conf.low  conf.high predicted_lo predicted_hi
1    0.000000e+00      Inf  1.1164399 1.1700077 0.2280035    0.2606591
2    0.000000e+00      Inf  1.1056504 1.1541541 0.2308157    0.2607992
3    0.000000e+00      Inf  1.0946379 1.1389341 0.2336521    0.2609394
4    0.000000e+00      Inf  1.0833208 1.1244231 0.2365126    0.2610796
5    0.000000e+00      Inf  1.0716242 1.1106896 0.2393972    0.2612199
6    0.000000e+00      Inf  1.0595038 1.0977722 0.2423058    0.2613603
7    0.000000e+00      Inf  1.0469657 1.0856585 0.2452384    0.2615007
8    0.000000e+00      Inf  1.0340695 1.0742831 0.2481948    0.2616411
9    0.000000e+00      Inf  1.0209094 1.0635461 0.2511750    0.2617816
10   0.000000e+00      Inf  1.0075877 1.0533395 0.2541789    0.2619221
11   0.000000e+00      Inf  0.9941967 1.0435653 0.2572064    0.2620627
12   0.000000e+00      Inf  0.9808102 1.0341442 0.2602573    0.2622033
13   0.000000e+00      Inf  0.9674841 1.0250147 0.2633316    0.2623440
14   0.000000e+00      Inf  0.9542590 1.0161311 0.2664292    0.2624847
15   0.000000e+00      Inf  0.9411638 1.0074591 0.2695498    0.2626255
16   0.000000e+00      Inf  0.9282189 0.9989731 0.2726935    0.2627663
17   0.000000e+00      Inf  0.9154384 0.9906539 0.2758599    0.2629072
18   0.000000e+00      Inf  0.9028319 0.9824867 0.2790490    0.2630481
19   0.000000e+00      Inf  0.8904060 0.9744601 0.2822606    0.2631891
20   0.000000e+00      Inf  0.8781646 0.9665653 0.2854945    0.2633301
21   0.000000e+00      Inf  0.8661103 0.9587948 0.2887505    0.2634712
22  5.887864e-292 967.4453  0.8542440 0.9511430 0.2920286    0.2636123
23  4.737630e-263 871.4229  0.8425660 0.9436050 0.2953283    0.2637535
24  3.427638e-238 788.8417  0.8310756 0.9361767 0.2986497    0.2638947
25  1.122378e-216 717.3699  0.8197718 0.9288547 0.3019924    0.2640359
26  6.046428e-198 655.1457  0.8086532 0.9216360 0.3053562    0.2641772
27  1.513516e-181 600.6711  0.7977178 0.9145180 0.3087409    0.2643186
28  4.081389e-167 552.7329  0.7869638 0.9074985 0.3121462    0.2644600
29  2.354190e-154 510.3417  0.7763887 0.9005753 0.3155720    0.2646015
30  5.101990e-143 472.6847  0.7659904 0.8937467 0.3190180    0.2647430
⋮   ⋮             ⋮         ⋮         ⋮         ⋮            ⋮
71  1.241604e-203 674.03920 0.5723195 0.6510679 0.2887505    0.17662688
72  5.472813e-180 595.49477 0.5487214 0.6294409 0.2920286    0.17202853
73  4.307063e-160 529.40179 0.5260138 0.6084898 0.2953283    0.16752553
74  3.181600e-143 473.36596 0.5041711 0.5881935 0.2986497    0.16311718
75  8.059939e-129 425.51796 0.4831676 0.5685325 0.3019924    0.15880270
76  1.940084e-116 384.38754 0.4629771 0.5494882 0.3053562    0.15458127
77  9.947116e-106 348.81010 0.4435737 0.5310428 0.3087409    0.15045198
78   2.069891e-96 317.85554 0.4249318 0.5131791 0.3121462    0.14641389
79   2.936129e-88 290.77576 0.4070258 0.4958807 0.3155720    0.14246601
80   4.321353e-81 266.96469 0.3898309 0.4791315 0.3190180    0.13860730
81   9.297953e-75 245.92769 0.3733223 0.4629161 0.3224838    0.13483666
82   3.875964e-69 227.25848 0.3574761 0.4472193 0.3259692    0.13115298
83   3.951025e-64 210.62117 0.3422688 0.4320264 0.3294741    0.12755510
84   1.195312e-59 195.73637 0.3276775 0.4173231 0.3329979    0.12404183
85   1.261976e-55 182.37036 0.3136797 0.4030954 0.3365406    0.12061195
86   5.328200e-52 170.32661 0.3002537 0.3893295 0.3401017    0.11726421
87   1.009624e-48 159.43873 0.2873783 0.3760121 0.3436810    0.11399735
88   9.467974e-46 149.56564 0.2750330 0.3631302 0.3472781    0.11081007
89   4.777601e-43 140.58662 0.2631978 0.3506710 0.3508928    0.10770108
90   1.393565e-40 132.39834 0.2518534 0.3386220 0.3545246    0.10466904
91   2.499465e-38 124.91165 0.2409809 0.3269712 0.3581733    0.10171264
92   2.907622e-36 118.04957 0.2305622 0.3157065 0.3618385    0.09883052
93   2.297856e-34 111.74527 0.2205797 0.3048163 0.3655199    0.09602134
94   1.284474e-32 105.94052 0.2110163 0.2942895 0.3692170    0.09328374
95   5.261103e-31 100.58441 0.2018557 0.2841148 0.3729295    0.09061637
96   1.628616e-29  95.63227 0.1930818 0.2742816 0.3766571    0.08801787
97   3.915292e-28  91.04487 0.1846794 0.2647792 0.3803993    0.08548687
98   7.487923e-27  86.78749 0.1766335 0.2555975 0.3841558    0.08302203
99   1.163691e-25  82.82949 0.1689299 0.2467264 0.3879262    0.08062200
100  1.497591e-24  79.14363 0.1615548 0.2381562 0.3917101    0.07828542
    predicted
1   0.2280035
2   0.2308157
3   0.2336521
4   0.2365126
5   0.2393972
6   0.2423058
7   0.2452384
8   0.2481948
9   0.2511750
10  0.2541789
11  0.2572064
12  0.2602573
13  0.2633316
14  0.2664292
15  0.2695498
16  0.2726935
17  0.2758599
18  0.2790490
19  0.2822606
20  0.2854945
21  0.2887505
22  0.2920286
23  0.2953283
24  0.2986497
25  0.3019924
26  0.3053562
27  0.3087409
28  0.3121462
29  0.3155720
30  0.3190180
⋮   ⋮
71  0.2887505
72  0.2920286
73  0.2953283
74  0.2986497
75  0.3019924
76  0.3053562
77  0.3087409
78  0.3121462
79  0.3155720
80  0.3190180
81  0.3224838
82  0.3259692
83  0.3294741
84  0.3329979
85  0.3365406
86  0.3401017
87  0.3436810
88  0.3472781
89  0.3508928
90  0.3545246
91  0.3581733
92  0.3618385
93  0.3655199
94  0.3692170
95  0.3729295
96  0.3766571
97  0.3803993
98  0.3841558
99  0.3879262
100 0.3917101

In [37]:
fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h4c_comp_pre_participation.csv")
write.csv(res_pre_facpub, fname, row.names = FALSE)

In [43]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType*lnex_ld_avg_before_year_co_lead  + ", paper_level, "+", ex_controls, "+ lnex_ld_avg_before_year_prod_fac ", "+",disciplines, " | PublishedYear")
)
model_pre_facpub <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_pre_facpub)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                                     Estimate Std. Error
CoTypeCollaboration                                  0.241026   0.018547
CoTypeParticipation                                  0.194909   0.024565
lnex_ld_avg_before_year_co_lead                      0.236184   0.007843
lnnum_author                                        -0.055695   0.007407
internationalinternational                          -0.043925   0.009593
lnnum_reference                                      0.057563   0.008659
num_fac                                              0.063569   0.006738
SDGTrue                                              0.085222   0.008156
lnmean_career_age                                    0.014247   0.013083
lnex_ld_avg_avgimpact                               -0.276988   0.007398
lnex_ld_avg_insthindex                              -0.036970   0.007544
ex_ld_bin_gsGlobalNorth                              0.303224   0.017530
ex_ld_bin_sameCSame                                 -0.061321   0.009453
knowledge_proximity_mean                            -0.803636   0.159843
lnex_ld_avg_before_year_prod_fac                    -0.067656   0.005864
Agricultural.and.Biological.Sciences                 0.760201   0.023967
Arts.and.Humanities                                  1.771775   0.072895
Biochemistry..Genetics.and.Molecular.Biology         0.602105   0.012611
Business..Management.and.Accounting                 -0.348715   0.088227
Chemical.Engineering                                 0.171009   0.020848
Chemistry                                            0.467311   0.011146
Computer.Science                                     0.927127   0.039399
Decision.Sciences                                    1.220703   0.190507
Dentistry                                            1.953098   0.136107
Earth.and.Planetary.Sciences                         0.744428   0.015341
Economics..Econometrics.and.Finance                 -0.108456   0.295885
Energy                                               0.248122   0.017934
Engineering                                          0.334003   0.010479
Environmental.Science                                0.576251   0.017526
Health.Professions                                   1.403398   0.128386
Immunology.and.Microbiology                          0.236889   0.026847
Materials.Science                                    0.026884   0.009940
Mathematics                                          0.586446   0.125997
Medicine                                             0.870715   0.014806
Neuroscience                                         0.512789   0.032532
Nursing                                              1.053033   0.043019
Pharmacology..Toxicology.and.Pharmaceutics           0.917201   0.048050
Physics.and.Astronomy                               -0.280286   0.011563
Psychology                                           0.429534   0.157153
Social.Sciences                                      0.160041   0.156747
Veterinary                                           0.625745   0.208470
CoTypeCollaboration:lnex_ld_avg_before_year_co_lead -0.183441   0.011643
CoTypeParticipation:lnex_ld_avg_before_year_co_lead -0.210838   0.016387
                                                       z value   Pr(>|z|)
CoTypeCollaboration                                  12.995557  < 2.2e-16 ***
CoTypeParticipation                                   7.934300 2.1169e-15 ***
lnex_ld_avg_before_year_co_lead                      30.114211  < 2.2e-16 ***
lnnum_author                                         -7.519611 5.4939e-14 ***
internationalinternational                           -4.578646 4.6800e-06 ***
lnnum_reference                                       6.647518 2.9808e-11 ***
num_fac                                               9.435007  < 2.2e-16 ***
SDGTrue                                              10.449605  < 2.2e-16 ***
lnmean_career_age                                     1.088967 2.7617e-01
lnex_ld_avg_avgimpact                               -37.439281  < 2.2e-16 ***
lnex_ld_avg_insthindex                               -4.900295 9.5693e-07 ***
ex_ld_bin_gsGlobalNorth                              17.297661  < 2.2e-16 ***
ex_ld_bin_sameCSame                                  -6.486553 8.7823e-11 ***
knowledge_proximity_mean                             -5.027663 4.9649e-07 ***
lnex_ld_avg_before_year_prod_fac                    -11.536565  < 2.2e-16 ***
Agricultural.and.Biological.Sciences                 31.718269  < 2.2e-16 ***
Arts.and.Humanities                                  24.305734  < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology         47.745367  < 2.2e-16 ***
Business..Management.and.Accounting                  -3.952489 7.7342e-05 ***
Chemical.Engineering                                  8.202642 2.3516e-16 ***
Chemistry                                            41.927399  < 2.2e-16 ***
Computer.Science                                     23.531949  < 2.2e-16 ***
Decision.Sciences                                     6.407665 1.4777e-10 ***
Dentistry                                            14.349765  < 2.2e-16 ***
Earth.and.Planetary.Sciences                         48.525966  < 2.2e-16 ***
Economics..Econometrics.and.Finance                  -0.366549 7.1396e-01
Energy                                               13.835017  < 2.2e-16 ***
Engineering                                          31.874608  < 2.2e-16 ***
Environmental.Science                                32.879298  < 2.2e-16 ***
Health.Professions                                   10.931105  < 2.2e-16 ***
Immunology.and.Microbiology                           8.823541  < 2.2e-16 ***
Materials.Science                                     2.704749 6.8356e-03 **
Mathematics                                           4.654435 3.2487e-06 ***
Medicine                                             58.810223  < 2.2e-16 ***
Neuroscience                                         15.762752  < 2.2e-16 ***
Nursing                                              24.478214  < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics           19.088381  < 2.2e-16 ***
Physics.and.Astronomy                               -24.240781  < 2.2e-16 ***
Psychology                                            2.733219 6.2719e-03 **
Social.Sciences                                       1.021009 3.0725e-01
Veterinary                                            3.001602 2.6856e-03 **
CoTypeCollaboration:lnex_ld_avg_before_year_co_lead -15.755765  < 2.2e-16 ***
CoTypeParticipation:lnex_ld_avg_before_year_co_lead -12.866470  < 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -181,515.9   Adj. Pseudo R2: 0.059173
           BIC:  364,215.7     Squared Cor.: 0.075851

In [44]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_pre_facpub,
                           keep = c("CoType", "lnex_ld_avg_before_year_co_lead"),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                                       & novel\_uzzi\_bin\\
   Model:                                                                    & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                                                       & 0.241$^{***}$\\
                                                                             & (0.018)\\
   CoTypeParticipation                                                       & 0.195$^{***}$\\
                                                                             & (0.025)\\
   lnex\_ld\_avg\_before\_year\_co\_lead                                     & 0.236$^{***}$\\
                                                                             & (0.008)\\
   CoTypeCollaboration $\times$ lnex\_ld\_avg\_before\_year\_co\_lead        & -0.183$^{***}$\\
                                                                             & (0.012)\\
   CoTypeParticipation $\times$ lnex\_ld\_avg\_before\_year\_co\_lead        & -0.211$^{***}$\\
                                                                             & (0.016)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                                             & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                                              & 294,879\\
   Squared Correlation                                                       & 0.07585\\
   Pseudo R$^2$                                                              & 0.05965\\
   BIC                                                                       & 364,215.7\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [39]:
# 1. 找到你这个连续变量的实际最小值和最大值（假设是 0 和 10，你需要改成你的实际极值）
min_val <- min(data$lnex_ld_avg_before_year_co_lead, na.rm=TRUE)
max_val <- max(data$lnex_ld_avg_before_year_co_lead, na.rm=TRUE)
# 2. 运行估计
res_pre_facpub <- avg_comparisons(
    model_pre_facpub,
    variables = "CoType",
    comparison = "ratio",
    newdata = datagrid(
    model = model_pre_facpub,
    lnex_ld_avg_before_year_co_lead = seq(min_val, max_val, length.out = 50) # 这里的 10 可以改成任意你想要的数字
  ),
    by = "lnex_ld_avg_before_year_co_lead"
)
res_pre_facpub

    rowid term   contrast
1    1    CoType mean(Collaboration) / mean(Service)
2    2    CoType mean(Collaboration) / mean(Service)
3    3    CoType mean(Collaboration) / mean(Service)
4    4    CoType mean(Collaboration) / mean(Service)
5    5    CoType mean(Collaboration) / mean(Service)
6    6    CoType mean(Collaboration) / mean(Service)
7    7    CoType mean(Collaboration) / mean(Service)
8    8    CoType mean(Collaboration) / mean(Service)
9    9    CoType mean(Collaboration) / mean(Service)
10  10    CoType mean(Collaboration) / mean(Service)
11  11    CoType mean(Collaboration) / mean(Service)
12  12    CoType mean(Collaboration) / mean(Service)
13  13    CoType mean(Collaboration) / mean(Service)
14  14    CoType mean(Collaboration) / mean(Service)
15  15    CoType mean(Collaboration) / mean(Service)
16  16    CoType mean(Collaboration) / mean(Service)
17  17    CoType mean(Collaboration) / mean(Service)
18  18    CoType mean(Collaboration) / mean(Service)
19  19    CoType mean(Collaboration) / mean(Service)
20  20    CoType mean(Collaboration) / mean(Service)
21  21    CoType mean(Collaboration) / mean(Service)
22  22    CoType mean(Collaboration) / mean(Service)
23  23    CoType mean(Collaboration) / mean(Service)
24  24    CoType mean(Collaboration) / mean(Service)
25  25    CoType mean(Collaboration) / mean(Service)
26  26    CoType mean(Collaboration) / mean(Service)
27  27    CoType mean(Collaboration) / mean(Service)
28  28    CoType mean(Collaboration) / mean(Service)
29  29    CoType mean(Collaboration) / mean(Service)
30  30    CoType mean(Collaboration) / mean(Service)
⋮   ⋮     ⋮      ⋮
71   71   CoType mean(Participation) / mean(Service)
72   72   CoType mean(Participation) / mean(Service)
73   73   CoType mean(Participation) / mean(Service)
74   74   CoType mean(Participation) / mean(Service)
75   75   CoType mean(Participation) / mean(Service)
76   76   CoType mean(Participation) / mean(Service)
77   77   CoType mean(Participation) / mean(Service)
78   78   CoType mean(Participation) / mean(Service)
79   79   CoType mean(Participation) / mean(Service)
80   80   CoType mean(Participation) / mean(Service)
81   81   CoType mean(Participation) / mean(Service)
82   82   CoType mean(Participation) / mean(Service)
83   83   CoType mean(Participation) / mean(Service)
84   84   CoType mean(Participation) / mean(Service)
85   85   CoType mean(Participation) / mean(Service)
86   86   CoType mean(Participation) / mean(Service)
87   87   CoType mean(Participation) / mean(Service)
88   88   CoType mean(Participation) / mean(Service)
89   89   CoType mean(Participation) / mean(Service)
90   90   CoType mean(Participation) / mean(Service)
91   91   CoType mean(Participation) / mean(Service)
92   92   CoType mean(Participation) / mean(Service)
93   93   CoType mean(Participation) / mean(Service)
94   94   CoType mean(Participation) / mean(Service)
95   95   CoType mean(Participation) / mean(Service)
96   96   CoType mean(Participation) / mean(Service)
97   97   CoType mean(Participation) / mean(Service)
98   98   CoType mean(Participation) / mean(Service)
99   99   CoType mean(Participation) / mean(Service)
100 100   CoType mean(Participation) / mean(Service)
    lnex_ld_avg_before_year_co_lead estimate  std.error   statistic
1   0.0000000                       1.2047486 0.018588781  64.81053
2   0.1185947                       1.1838889 0.017149565  69.03317
3   0.2371894                       1.1635337 0.015798618  73.64782
4   0.3557841                       1.1436721 0.014540888  78.65215
5   0.4743789                       1.1242928 0.013382941  84.00939
6   0.5929736                       1.1053851 0.012333043  89.62793
7   0.7115683                       1.0869385 0.011401212  95.33535
8   0.8301630                       1.0689428 0.010598889 100.85423
9   0.9487577                       1.0513878 0.009938015 105.79454
10  1.0673524                       1.0342636 0.009429439 109.68454
11  1.1859471                       1.0175608 0.009080652 112.05811
12  1.3045419                       1.0012698 0.008893399 112.58572
13  1.4231366                       0.9853815 0.008862159 111.18978
14  1.5417313                       0.9698868 0.008974234 108.07460
15  1.6603260                       0.9547770 0.009211556 103.64992
16  1.7789207                       0.9400435 0.009553413  98.39871
17  1.8975154                       0.9256778 0.009979065  92.76198
18  2.0161101                       0.9116718 0.010469533  87.07856
19  2.1347049                       0.8980174 0.011008506  81.57486
20  2.2532996                       0.8847067 0.011582559  76.38266
21  2.3718943                       0.8717320 0.012180933  71.56529
22  2.4904890                       0.8590859 0.012795158  67.14149
23  2.6090837                       0.8467610 0.013418658  63.10326
24  2.7276784                       0.8347501 0.014046356  59.42823
25  2.8462731                       0.8230462 0.014674362  56.08736
26  2.9648679                       0.8116424 0.015299716  53.04951
27  3.0834626                       0.8005320 0.015920168  50.28414
28  3.2020573                       0.7897085 0.016534036  47.76260
29  3.3206520                       0.7791653 0.017140074  45.45869
30  3.4392467                       0.7688964 0.017737381  43.34892
⋮   ⋮                               ⋮         ⋮           ⋮
71  2.371894                        0.8031136 0.01639790  48.97662
72  2.490489                        0.7896486 0.01719680  45.91835
73  2.609084                        0.7765405 0.01799444  43.15448
74  2.727678                        0.7637801 0.01878620  40.65645
75  2.846273                        0.7513588 0.01956868  38.39599
76  2.964868                        0.7392679 0.02033939  36.34661
77  3.083463                        0.7274990 0.02109654  34.48429
78  3.202057                        0.7160442 0.02183887  32.78761
79  3.320652                        0.7048954 0.02256555  31.23768
80  3.439247                        0.6940448 0.02327606  29.81798
81  3.557841                        0.6834851 0.02397012  28.51405
82  3.676436                        0.6732088 0.02464766  27.31329
83  3.795031                        0.6632087 0.02530875  26.20472
84  3.913626                        0.6534780 0.02595358  25.17873
85  4.032220                        0.6440098 0.02658241  24.22692
86  4.150815                        0.6347974 0.02719557  23.34194
87  4.269410                        0.6258345 0.02779348  22.51731
88  4.388004                        0.6171146 0.02837654  21.74735
89  4.506599                        0.6086318 0.02894521  21.02703
90  4.625194                        0.6003799 0.02949997  20.35188
91  4.743789                        0.5923532 0.03004130  19.71797
92  4.862383                        0.5845460 0.03056969  19.12175
93  4.980978                        0.5769528 0.03108563  18.56011
94  5.099573                        0.5695680 0.03158962  18.03023
95  5.218167                        0.5623866 0.03208214  17.52959
96  5.336762                        0.5554032 0.03256368  17.05591
97  5.455357                        0.5486131 0.03303471  16.60717
98  5.573952                        0.5420112 0.03349570  16.18151
99  5.692546                        0.5355928 0.03394711  15.77727
100 5.811141                        0.5293533 0.03438938  15.39293
    p.value       s.value  conf.low  conf.high predicted_lo predicted_hi
1   0             Inf      1.1683153 1.2411820 0.2064969    0.2487768
2   0             Inf      1.1502763 1.2175014 0.2111243    0.2499477
3   0             Inf      1.1325690 1.1944985 0.2158271    0.2511221
4   0             Inf      1.1151724 1.1721717 0.2206055    0.2523003
5   0             Inf      1.0980627 1.1505228 0.2254592    0.2534821
6   0             Inf      1.0812128 1.1295574 0.2303881    0.2546675
7   0             Inf      1.0645926 1.1092845 0.2353920    0.2558566
8   0             Inf      1.0481693 1.0897162 0.2404707    0.2570494
9   0             Inf      1.0319096 1.0708659 0.2456237    0.2582457
10  0             Inf      1.0157823 1.0527450 0.2508507    0.2594457
11  0             Inf      0.9997630 1.0353585 0.2561511    0.2606493
12  0             Inf      0.9838391 1.0187005 0.2615245    0.2618565
13  0             Inf      0.9680120 1.0027510 0.2669701    0.2630674
14  0             Inf      0.9522976 0.9874760 0.2724872    0.2642818
15  0             Inf      0.9367227 0.9728313 0.2780752    0.2654998
16  0             Inf      0.9213191 0.9587678 0.2837330    0.2667213
17  0             Inf      0.9061192 0.9452364 0.2894598    0.2679465
18  0             Inf      0.8911519 0.9321917 0.2952545    0.2691752
19  0             Inf      0.8764411 0.9195936 0.3011161    0.2704075
20  0             Inf      0.8620053 0.9074081 0.3070433    0.2716433
21  0             Inf      0.8478578 0.8956062 0.3130350    0.2728826
22  0             Inf      0.8340079 0.8841640 0.3190897    0.2741255
23  0             Inf      0.8204609 0.8730611 0.3252061    0.2753719
24  0             Inf      0.8072198 0.8622805 0.3313827    0.2766217
25  0             Inf      0.7942850 0.8518074 0.3376179    0.2778751
26  0             Inf      0.7816555 0.8416293 0.3439101    0.2791320
27  0             Inf      0.7693291 0.8317350 0.3502575    0.2803924
28  0             Inf      0.7573024 0.8221146 0.3566584    0.2816562
29  0             Inf      0.7455714 0.8127593 0.3631109    0.2829235
30  0             Inf      0.7341317 0.8036610 0.3696131    0.2841942
⋮   ⋮             ⋮        ⋮         ⋮         ⋮            ⋮
71   0.000000e+00      Inf 0.7709743 0.8352528 0.3130350    0.2514026
72   0.000000e+00      Inf 0.7559435 0.8233537 0.3190897    0.2519687
73   0.000000e+00      Inf 0.7412721 0.8118089 0.3252061    0.2525357
74   0.000000e+00      Inf 0.7269599 0.8006004 0.3313827    0.2531035
75   0.000000e+00      Inf 0.7130049 0.7897127 0.3376179    0.2536722
76  2.972477e-289 958.4656 0.6994034 0.7791323 0.3439101    0.2542417
77  1.379697e-260 863.2370 0.6861506 0.7688475 0.3502575    0.2548120
78  8.843432e-236 780.8304 0.6732408 0.7588476 0.3566584    0.2553832
79  3.281782e-214 709.1781 0.6606677 0.7491230 0.3631109    0.2559552
80  2.284710e-195 646.5840 0.6484246 0.7396651 0.3696131    0.2565281
81  7.844499e-179 591.6534 0.6365045 0.7304657 0.3761630    0.2571018
82  2.948917e-164 543.2360 0.6249003 0.7215173 0.3827584    0.2576763
83  2.347884e-151 500.3798 0.6136045 0.7128130 0.3893973    0.2582517
84  6.851034e-140 462.2936 0.6026099 0.7043461 0.3960774    0.2588279
85  1.158071e-129 428.3170 0.5919092 0.6961103 0.4027966    0.2594050
86  1.664135e-120 397.8966 0.5814951 0.6880998 0.4095524    0.2599828
87  2.808954e-112 370.5659 0.5713603 0.6803087 0.4163426    0.2605616
88  7.318081e-105 345.9310 0.5614976 0.6727316 0.4231647    0.2611411
89   3.711894e-98 323.6568 0.5519002 0.6653634 0.4300161    0.2617215
90   4.467787e-92 303.4578 0.5425611 0.6581988 0.4368945    0.2623027
91   1.511902e-86 285.0895 0.5334734 0.6512331 0.4437973    0.2628848
92   1.664132e-81 268.3414 0.5246306 0.6444615 0.4507218    0.2634676
93   6.756285e-77 253.0322 0.5160260 0.6378795 0.4576655    0.2640513
94   1.128224e-72 239.0048 0.5076535 0.6314825 0.4646256    0.2646359
95   8.518745e-69 226.1224 0.4995067 0.6252664 0.4715995    0.2652212
96   3.159065e-65 214.2658 0.4915796 0.6192269 0.4785846    0.2658074
97   6.184243e-62 203.3309 0.4838662 0.6133599 0.4855780    0.2663945
98   6.809947e-59 193.2261 0.4763608 0.6076615 0.4925771    0.2669823
99   4.460538e-56 183.8708 0.4690577 0.6021279 0.4995791    0.2675710
100  1.825745e-53 175.1937 0.4619513 0.5967552 0.5065813    0.2681605
    predicted
1   0.2064969
2   0.2111243
3   0.2158271
4   0.2206055
5   0.2254592
6   0.2303881
7   0.2353920
8   0.2404707
9   0.2456237
10  0.2508507
11  0.2561511
12  0.2615245
13  0.2669701
14  0.2724872
15  0.2780752
16  0.2837330
17  0.2894598
18  0.2952545
19  0.3011161
20  0.3070433
21  0.3130350
22  0.3190897
23  0.3252061
24  0.3313827
25  0.3376179
26  0.3439101
27  0.3502575
28  0.3566584
29  0.3631109
30  0.3696131
⋮   ⋮
71  0.3130350
72  0.3190897
73  0.3252061
74  0.3313827
75  0.3376179
76  0.3439101
77  0.3502575
78  0.3566584
79  0.3631109
80  0.3696131
81  0.3761630
82  0.3827584
83  0.3893973
84  0.3960774
85  0.4027966
86  0.4095524
87  0.4163426
88  0.4231647
89  0.4300161
90  0.4368945
91  0.4437973
92  0.4507218
93  0.4576655
94  0.4646256
95  0.4715995
96  0.4785846
97  0.4855780
98  0.4925771
99  0.4995791
100 0.5065813

In [40]:
fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h4c_comp_pre_co_lead.csv")
write.csv(res_pre_facpub, fname, row.names = FALSE)

In [ ]:
 [46] "lnex_ld_avg_before_year_prod_fac"            
 [47] "lnex_ld_avg_before_year_with_ih"             
 [48] "ex_ld_ratio_before_year_with_ih_bin"         
 [49] "ex_ld_max_before_year_with_ih_bin"           
[50] "lnex_ld_avg_before_year_participation"       
 [51] "ex_ld_ratio_before_year_participation_bin"   
 [52] "ex_ld_max_before_year_participation_bin"     
 [53] "lnex_ld_avg_before_year_co_lead"             
 [54] "ex_ld_ratio_before_year_co_lead_bin"         
 [55] "ex_ld_max_before_year_co_lead_bin"  

moderating <- "lnex_ld_avg_before_year_prod_fac + ex_ld_max_before_year_with_ih_bin"
moderating2 <- "lnex_ld_avg_before_year_prod_fac + ex_ld_max_before_year_participation_bin"
moderating3 <- "lnex_ld_avg_before_year_prod_fac + ex_ld_max_before_year_co_lead_bin"

In [25]:
# 生成新变量名为 binary_ex_ld
data <- data %>%
  mutate(before_year_fac= if_else(ex_ld_avg_before_year_prod_fac == 0, "False", "True"))
data$before_year_fac <- factor(data$before_year_fac)
data <- within(data, before_year_fac <- relevel(before_year_fac, ref = 'False'))

In [31]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+", disciplines, " | PublishedYear")
)
model_pre_facpub <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$before_year_fac=='False'), ], family = binomial("logit"), vcov = "hetero")
summary(model_pre_facpub)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 7,969
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                               Estimate Std. Error    z value
CoTypeCollaboration                            0.126156   0.059444   2.122262
CoTypeParticipation                            0.133038   0.104896   1.268285
lnnum_author                                   0.030602   0.047929   0.638490
internationalinternational                    -0.136724   0.060002  -2.278676
lnnum_reference                                0.128095   0.044759   2.861877
num_fac                                        0.161398   0.075014   2.151575
SDGTrue                                        0.052675   0.049469   1.064826
lnmean_career_age                             -0.033195   0.062703  -0.529410
lnex_ld_avg_avgimpact                         -0.138302   0.033108  -4.177278
lnex_ld_avg_insthindex                        -0.025546   0.036483  -0.700198
ex_ld_bin_gsGlobalNorth                        0.309741   0.083793   3.696502
ex_ld_bin_sameCSame                           -0.009906   0.058130  -0.170419
knowledge_proximity_mean                      -4.234101   0.882960  -4.795347
Agricultural.and.Biological.Sciences           0.878003   0.130925   6.706160
Arts.and.Humanities                            1.893332   0.288288   6.567511
Biochemistry..Genetics.and.Molecular.Biology   0.380290   0.076461   4.973636
Business..Management.and.Accounting            0.620689   0.813938   0.762575
Chemical.Engineering                           0.257795   0.143174   1.800573
Chemistry                                      0.176216   0.072032   2.446343
Computer.Science                               0.555800   0.182630   3.043317
Decision.Sciences                             13.836332   0.121464 113.913457
Dentistry                                      0.773560   0.437215   1.769288
Earth.and.Planetary.Sciences                   0.275305   0.096439   2.854716
Economics..Econometrics.and.Finance          -12.567821   0.239725 -52.425900
Energy                                         0.070253   0.134372   0.522824
Engineering                                    0.350183   0.062089   5.639986
Environmental.Science                          0.207026   0.097085   2.132413
Health.Professions                             1.110307   0.647029   1.716009
Immunology.and.Microbiology                    0.540802   0.178905   3.022850
Materials.Science                              0.114368   0.058686   1.948802
Mathematics                                   -0.409663   0.589477  -0.694960
Medicine                                       0.991048   0.085489  11.592700
Neuroscience                                   0.589204   0.202379   2.911389
Nursing                                        0.950222   0.250090   3.799518
Pharmacology..Toxicology.and.Pharmaceutics     1.122255   0.297957   3.766496
Physics.and.Astronomy                         -0.384181   0.068720  -5.590549
Psychology                                    -0.395532   0.723644  -0.546583
Social.Sciences                               -0.296480   0.543390  -0.545611
Veterinary                                     0.838824   1.351430   0.620693
                                               Pr(>|z|)
CoTypeCollaboration                          3.3816e-02 *
CoTypeParticipation                          2.0470e-01
lnnum_author                                 5.2315e-01
internationalinternational                   2.2686e-02 *
lnnum_reference                              4.2114e-03 **
num_fac                                      3.1431e-02 *
SDGTrue                                      2.8695e-01
lnmean_career_age                            5.9652e-01
lnex_ld_avg_avgimpact                        2.9502e-05 ***
lnex_ld_avg_insthindex                       4.8380e-01
ex_ld_bin_gsGlobalNorth                      2.1859e-04 ***
ex_ld_bin_sameCSame                          8.6468e-01
knowledge_proximity_mean                     1.6239e-06 ***
Agricultural.and.Biological.Sciences         1.9981e-11 ***
Arts.and.Humanities                          5.1163e-11 ***
Biochemistry..Genetics.and.Molecular.Biology 6.5709e-07 ***
Business..Management.and.Accounting          4.4572e-01
Chemical.Engineering                         7.1770e-02 .
Chemistry                                    1.4431e-02 *
Computer.Science                             2.3399e-03 **
Decision.Sciences                             < 2.2e-16 ***
Dentistry                                    7.6846e-02 .
Earth.and.Planetary.Sciences                 4.3075e-03 **
Economics..Econometrics.and.Finance           < 2.2e-16 ***
Energy                                       6.0110e-01
Engineering                                  1.7006e-08 ***
Environmental.Science                        3.2973e-02 *
Health.Professions                           8.6160e-02 .
Immunology.and.Microbiology                  2.5041e-03 **
Materials.Science                            5.1319e-02 .
Mathematics                                  4.8708e-01
Medicine                                      < 2.2e-16 ***
Neuroscience                                 3.5983e-03 **
Nursing                                      1.4498e-04 ***
Pharmacology..Toxicology.and.Pharmaceutics   1.6555e-04 ***
Physics.and.Astronomy                        2.2635e-08 ***
Psychology                                   5.8467e-01
Social.Sciences                              5.8533e-01
Veterinary                                   5.3480e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -5,016.3   Adj. Pseudo R2: 0.047687
           BIC: 10,841.1     Squared Cor.: 0.082426

In [65]:
# 1. 找到你这个连续变量的实际最小值和最大值（假设是 0 和 10，你需要改成你的实际极值）
min_val <- min(data$lnex_ld_avg_before_year_prod_fac, na.rm=TRUE)
max_val <- max(data$lnex_ld_avg_before_year_prod_fac, na.rm=TRUE)
# 2. 运行估计
res_pre_facpub <- avg_comparisons(
    model_pre_facpub,
    variables = "CoType",
    comparison = "ratio",
    newdata = datagrid(
    model = model_pre_facpub,
    lnex_ld_avg_before_year_prod_fac = seq(min_val, max_val, length.out = 50) # 这里的 10 可以改成任意你想要的数字
  ),
    by = "lnex_ld_avg_before_year_prod_fac"
)
res_pre_facpub

    rowid term   contrast
1    1    CoType mean(Collaboration) / mean(Service)
2    2    CoType mean(Collaboration) / mean(Service)
3    3    CoType mean(Collaboration) / mean(Service)
4    4    CoType mean(Collaboration) / mean(Service)
5    5    CoType mean(Collaboration) / mean(Service)
6    6    CoType mean(Collaboration) / mean(Service)
7    7    CoType mean(Collaboration) / mean(Service)
8    8    CoType mean(Collaboration) / mean(Service)
9    9    CoType mean(Collaboration) / mean(Service)
10  10    CoType mean(Collaboration) / mean(Service)
11  11    CoType mean(Collaboration) / mean(Service)
12  12    CoType mean(Collaboration) / mean(Service)
13  13    CoType mean(Collaboration) / mean(Service)
14  14    CoType mean(Collaboration) / mean(Service)
15  15    CoType mean(Collaboration) / mean(Service)
16  16    CoType mean(Collaboration) / mean(Service)
17  17    CoType mean(Collaboration) / mean(Service)
18  18    CoType mean(Collaboration) / mean(Service)
19  19    CoType mean(Collaboration) / mean(Service)
20  20    CoType mean(Collaboration) / mean(Service)
21  21    CoType mean(Collaboration) / mean(Service)
22  22    CoType mean(Collaboration) / mean(Service)
23  23    CoType mean(Collaboration) / mean(Service)
24  24    CoType mean(Collaboration) / mean(Service)
25  25    CoType mean(Collaboration) / mean(Service)
26  26    CoType mean(Collaboration) / mean(Service)
27  27    CoType mean(Collaboration) / mean(Service)
28  28    CoType mean(Collaboration) / mean(Service)
29  29    CoType mean(Collaboration) / mean(Service)
30  30    CoType mean(Collaboration) / mean(Service)
⋮   ⋮     ⋮      ⋮
71   71   CoType mean(Participation) / mean(Service)
72   72   CoType mean(Participation) / mean(Service)
73   73   CoType mean(Participation) / mean(Service)
74   74   CoType mean(Participation) / mean(Service)
75   75   CoType mean(Participation) / mean(Service)
76   76   CoType mean(Participation) / mean(Service)
77   77   CoType mean(Participation) / mean(Service)
78   78   CoType mean(Participation) / mean(Service)
79   79   CoType mean(Participation) / mean(Service)
80   80   CoType mean(Participation) / mean(Service)
81   81   CoType mean(Participation) / mean(Service)
82   82   CoType mean(Participation) / mean(Service)
83   83   CoType mean(Participation) / mean(Service)
84   84   CoType mean(Participation) / mean(Service)
85   85   CoType mean(Participation) / mean(Service)
86   86   CoType mean(Participation) / mean(Service)
87   87   CoType mean(Participation) / mean(Service)
88   88   CoType mean(Participation) / mean(Service)
89   89   CoType mean(Participation) / mean(Service)
90   90   CoType mean(Participation) / mean(Service)
91   91   CoType mean(Participation) / mean(Service)
92   92   CoType mean(Participation) / mean(Service)
93   93   CoType mean(Participation) / mean(Service)
94   94   CoType mean(Participation) / mean(Service)
95   95   CoType mean(Participation) / mean(Service)
96   96   CoType mean(Participation) / mean(Service)
97   97   CoType mean(Participation) / mean(Service)
98   98   CoType mean(Participation) / mean(Service)
99   99   CoType mean(Participation) / mean(Service)
100 100   CoType mean(Participation) / mean(Service)
    lnex_ld_avg_before_year_prod_fac estimate  std.error   statistic
1   0.0000000                        1.058109  0.019753175  53.56652
2   0.1359301                        1.058889  0.018873402  56.10480
3   0.2718602                        1.059670  0.018003832  58.85804
4   0.4077903                        1.060454  0.017146734  61.84584
5   0.5437204                        1.061240  0.016304778  65.08768
6   0.6796505                        1.062028  0.015481208  68.60112
7   0.8155806                        1.062818  0.014679872  72.39969
8   0.9515107                        1.063610  0.013905532  76.48830
9   1.0874408                        1.064405  0.013163790  80.85853
10  1.2233709                        1.065201  0.012461433  85.47982
11  1.3593011                        1.066000  0.011806538  90.28892
12  1.4952312                        1.066800  0.011208498  95.17778
13  1.6311613                        1.067603  0.010678012  99.98140
14  1.7670914                        1.068407  0.010226793 104.47138
15  1.9030215                        1.069214  0.009866958 108.36307
16  2.0389516                        1.070023  0.009610049 111.34415
17  2.1748817                        1.070834  0.009465796 113.12662
18  2.3108118                        1.071646  0.009440663 113.51389
19  2.4467419                        1.072461  0.009536907 112.45380
20  2.5826720                        1.073278  0.009752227 110.05470
21  2.7186021                        1.074097  0.010080249 106.55466
22  2.8545322                        1.074919  0.010511632 102.25992
23  2.9904623                        1.075742  0.011035433  97.48071
24  3.1263924                        1.076567  0.011640282  92.48634
25  3.2623225                        1.077394  0.012315313  87.48413
26  3.3982526                        1.078224  0.013050581  82.61883
27  3.5341827                        1.079055  0.013837475  77.98064
28  3.6701128                        1.079889  0.014668575  73.61919
29  3.8060429                        1.080724  0.015537619  69.55532
30  3.9419730                        1.081562  0.016439388  65.79087
⋮   ⋮                                ⋮         ⋮           ⋮
71  2.718602                         0.9832074 0.01172241  83.87420
72  2.854532                         0.9755417 0.01212884  80.43155
73  2.990462                         0.9679001 0.01266723  76.40974
74  3.126392                         0.9602832 0.01331725  72.10822
75  3.262323                         0.9526918 0.01405929  67.76242
76  3.398253                         0.9451264 0.01487569  63.53497
77  3.534183                         0.9375877 0.01575117  59.52496
78  3.670113                         0.9300763 0.01667294  55.78359
79  3.806043                         0.9225928 0.01763041  52.32962
80  3.941973                         0.9151378 0.01861496  49.16141
81  4.077903                         0.9077118 0.01961954  46.26570
82  4.213833                         0.9003155 0.02063841  43.62329
83  4.349763                         0.8929493 0.02166691  41.21259
84  4.485693                         0.8856138 0.02270118  39.01180
85  4.621624                         0.8783096 0.02373807  37.00005
86  4.757554                         0.8710370 0.02477496  35.15795
87  4.893484                         0.8637966 0.02580970  33.46791
88  5.029414                         0.8565889 0.02684043  31.91412
89  5.165344                         0.8494143 0.02786565  30.48248
90  5.301274                         0.8422732 0.02888404  29.16050
91  5.437204                         0.8351661 0.02989452  27.93710
92  5.573134                         0.8280934 0.03089614  26.80249
93  5.709064                         0.8210556 0.03188808  25.74804
94  5.844995                         0.8140529 0.03286966  24.76609
95  5.980925                         0.8070857 0.03384028  23.84985
96  6.116855                         0.8001545 0.03479943  22.99333
97  6.252785                         0.7932596 0.03574665  22.19116
98  6.388715                         0.7864012 0.03668156  21.43860
99  6.524645                         0.7795798 0.03760382  20.73140
100 6.660575                         0.7727956 0.03851314  20.06576
    p.value       s.value  conf.low  conf.high predicted_lo predicted_hi
1   0             Inf      1.019393  1.096824  0.2637936    0.2791224
2   0             Inf      1.021897  1.095880  0.2628715    0.2783516
3   0             Inf      1.024383  1.094957  0.2619515    0.2775822
4   0             Inf      1.026847  1.094061  0.2610335    0.2768141
5   0             Inf      1.029283  1.093197  0.2601176    0.2760473
6   0             Inf      1.031686  1.092371  0.2592038    0.2752818
7   0             Inf      1.034046  1.091590  0.2582921    0.2745176
8   0             Inf      1.036356  1.090865  0.2573825    0.2737547
9   0             Inf      1.038604  1.090205  0.2564750    0.2729932
10  0             Inf      1.040777  1.089625  0.2555696    0.2722330
11  0             Inf      1.042859  1.089140  0.2546662    0.2714741
12  0             Inf      1.044832  1.088768  0.2537650    0.2707165
13  0             Inf      1.046674  1.088531  0.2528659    0.2699603
14  0             Inf      1.048363  1.088451  0.2519689    0.2692054
15  0             Inf      1.049875  1.088553  0.2510740    0.2684519
16  0             Inf      1.051187  1.088858  0.2501813    0.2676996
17  0             Inf      1.052281  1.089386  0.2492906    0.2669488
18  0             Inf      1.053143  1.090150  0.2484021    0.2661992
19  0             Inf      1.053769  1.091153  0.2475157    0.2654510
20  0             Inf      1.054164  1.092392  0.2466314    0.2647042
21  0             Inf      1.054341  1.093854  0.2457492    0.2639586
22  0             Inf      1.054316  1.095521  0.2448692    0.2632145
23  0             Inf      1.054113  1.097371  0.2439913    0.2624717
24  0             Inf      1.053753  1.099382  0.2431156    0.2617302
25  0             Inf      1.053257  1.101532  0.2422419    0.2609901
26  0             Inf      1.052645  1.103802  0.2413705    0.2602514
27  0             Inf      1.051934  1.106176  0.2405011    0.2595140
28  0             Inf      1.051139  1.108638  0.2396339    0.2587779
29  0             Inf      1.050271  1.111177  0.2387688    0.2580432
30  0             Inf      1.049341  1.113782  0.2379059    0.2573099
⋮   ⋮             ⋮        ⋮         ⋮         ⋮            ⋮
71   0.000000e+00      Inf 0.9602320 1.0061829 0.2457492    0.2416225
72   0.000000e+00      Inf 0.9517696 0.9993138 0.2448692    0.2388801
73   0.000000e+00      Inf 0.9430728 0.9927274 0.2439913    0.2361592
74   0.000000e+00      Inf 0.9341819 0.9863846 0.2431156    0.2334598
75   0.000000e+00      Inf 0.9251361 0.9802475 0.2422419    0.2307819
76   0.000000e+00      Inf 0.9159706 0.9742822 0.2413705    0.2281256
77   0.000000e+00      Inf 0.9067159 0.9684594 0.2405011    0.2254909
78   0.000000e+00      Inf 0.8973979 0.9627546 0.2396339    0.2228778
79   0.000000e+00      Inf 0.8880378 0.9571477 0.2387688    0.2202864
80   0.000000e+00      Inf 0.8786531 0.9516224 0.2379059    0.2177167
81   0.000000e+00      Inf 0.8692582 0.9461654 0.2370452    0.2151687
82   0.000000e+00      Inf 0.8598649 0.9407660 0.2361865    0.2126424
83   0.000000e+00      Inf 0.8504830 0.9354157 0.2353301    0.2101378
84   0.000000e+00      Inf 0.8411204 0.9301073 0.2344758    0.2076550
85  1.143133e-299 993.0635 0.8317838 0.9248353 0.2336236    0.2051938
86  8.787555e-271 897.1071 0.8224790 0.9195950 0.2327736    0.2027544
87  1.413030e-245 813.3736 0.8132105 0.9143827 0.2319257    0.2003367
88  1.700793e-223 740.0238 0.8039826 0.9091952 0.2310801    0.1979406
89  4.447771e-204 675.5202 0.7947986 0.9040299 0.2302365    0.1955662
90  6.148689e-187 618.5803 0.7856615 0.8988849 0.2293952    0.1932134
91  9.458491e-172 568.1300 0.7765739 0.8937583 0.2285559    0.1908822
92  3.022162e-158 523.2691 0.7675381 0.8886488 0.2277189    0.1885725
93  3.390391e-146 483.2401 0.7585561 0.8835550 0.2268840    0.1862844
94  2.080368e-135 447.4035 0.7496295 0.8784762 0.2260513    0.1840177
95  1.016199e-125 415.2178 0.7407600 0.8734115 0.2252208    0.1817725
96  5.436193e-117 386.2230 0.7319489 0.8683601 0.2243924    0.1795486
97  4.180775e-109 360.0264 0.7231974 0.8633217 0.2235662    0.1773460
98  5.834537e-102 336.2920 0.7145067 0.8582958 0.2227421    0.1751647
99   1.804651e-95 314.7314 0.7058777 0.8532819 0.2219202    0.1730045
100  1.470120e-89 295.0957 0.6973112 0.8482800 0.2211005    0.1708655
    predicted
1   0.2637936
2   0.2628715
3   0.2619515
4   0.2610335
5   0.2601176
6   0.2592038
7   0.2582921
8   0.2573825
9   0.2564750
10  0.2555696
11  0.2546662
12  0.2537650
13  0.2528659
14  0.2519689
15  0.2510740
16  0.2501813
17  0.2492906
18  0.2484021
19  0.2475157
20  0.2466314
21  0.2457492
22  0.2448692
23  0.2439913
24  0.2431156
25  0.2422419
26  0.2413705
27  0.2405011
28  0.2396339
29  0.2387688
30  0.2379059
⋮   ⋮
71  0.2457492
72  0.2448692
73  0.2439913
74  0.2431156
75  0.2422419
76  0.2413705
77  0.2405011
78  0.2396339
79  0.2387688
80  0.2379059
81  0.2370452
82  0.2361865
83  0.2353301
84  0.2344758
85  0.2336236
86  0.2327736
87  0.2319257
88  0.2310801
89  0.2302365
90  0.2293952
91  0.2285559
92  0.2277189
93  0.2268840
94  0.2260513
95  0.2252208
96  0.2243924
97  0.2235662
98  0.2227421
99  0.2219202
100 0.2211005

In [66]:
fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h4_comp_pre_facpub.csv")
write.csv(res_pre_facpub, fname, row.names = FALSE)

In [67]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_pre_facpub,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                                        & novel\_uzzi\_bin\\
   Model:                                                                     & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                                                        & 0.077$^{***}$\\
                                                                              & (0.025)\\
   CoTypeParticipation                                                        & 0.183$^{***}$\\
                                                                              & (0.036)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac                                     & -0.035$^{***}$\\
                                                                              & (0.006)\\
   lnnum\_author                                                              & -0.078$^{***}$\\
                                                                              & (0.008)\\
   internationalinternational                                                 & -0.048$^{***}$\\
                                                                              & (0.010)\\
   lnnum\_reference                                                           & 0.053$^{***}$\\
                                                                              & (0.009)\\
   num\_fac                                                                   & 0.067$^{***}$\\
                                                                              & (0.007)\\
   SDGTrue                                                                    & 0.083$^{***}$\\
                                                                              & (0.008)\\
   lnmean\_career\_age                                                        & 0.008\\
                                                                              & (0.013)\\
   lnex\_ld\_avg\_avgimpact                                                   & -0.276$^{***}$\\
                                                                              & (0.007)\\
   lnex\_ld\_avg\_insthindex                                                  & -0.049$^{***}$\\
                                                                              & (0.008)\\
   ex\_ld\_bin\_gsGlobalNorth                                                 & 0.310$^{***}$\\
                                                                              & (0.018)\\
   ex\_ld\_bin\_sameCSame                                                     & -0.062$^{***}$\\
                                                                              & (0.009)\\
   knowledge\_proximity\_mean                                                 & -0.796$^{***}$\\
                                                                              & (0.160)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue                               & 0.325$^{***}$\\
                                                                              & (0.011)\\
   Agricultural.and.Biological.Sciences                                       & 0.756$^{***}$\\
                                                                              & (0.024)\\
   Arts.and.Humanities                                                        & 1.77$^{***}$\\
                                                                              & (0.073)\\
   Biochemistry..Genetics.and.Molecular.Biology                               & 0.596$^{***}$\\
                                                                              & (0.013)\\
   Business..Management.and.Accounting                                        & -0.327$^{***}$\\
                                                                              & (0.088)\\
   Chemical.Engineering                                                       & 0.163$^{***}$\\
                                                                              & (0.021)\\
   Chemistry                                                                  & 0.458$^{***}$\\
                                                                              & (0.011)\\
   Computer.Science                                                           & 0.939$^{***}$\\
                                                                              & (0.040)\\
   Decision.Sciences                                                          & 1.22$^{***}$\\
                                                                              & (0.189)\\
   Dentistry                                                                  & 1.95$^{***}$\\
                                                                              & (0.136)\\
   Earth.and.Planetary.Sciences                                               & 0.754$^{***}$\\
                                                                              & (0.015)\\
   Economics..Econometrics.and.Finance                                        & -0.077\\
                                                                              & (0.296)\\
   Energy                                                                     & 0.236$^{***}$\\
                                                                              & (0.018)\\
   Engineering                                                                & 0.327$^{***}$\\
                                                                              & (0.011)\\
   Immunology.and.Microbiology                                                & 0.234$^{***}$\\
                                                                              & (0.027)\\
   Materials.Science                                                          & 0.023$^{**}$\\
                                                                              & (0.010)\\
   Mathematics                                                                & 0.579$^{***}$\\
                                                                              & (0.126)\\
   Medicine                                                                   & 0.867$^{***}$\\
                                                                              & (0.015)\\
   Neuroscience                                                               & 0.520$^{***}$\\
                                                                              & (0.033)\\
   Nursing                                                                    & 1.05$^{***}$\\
                                                                              & (0.043)\\
   Pharmacology..Toxicology.and.Pharmaceutics                                 & 0.907$^{***}$\\
                                                                              & (0.048)\\
   Physics.and.Astronomy                                                      & -0.260$^{***}$\\
                                                                              & (0.011)\\
   Psychology                                                                 & 0.426$^{***}$\\
                                                                              & (0.158)\\
   Social.Sciences                                                            & 0.159\\
                                                                              & (0.156)\\
   Veterinary                                                                 & 0.601$^{***}$\\
                                                                              & (0.208)\\
   CoTypeCollaboration $\times$ lnex\_ld\_avg\_before\_year\_prod\_fac        & 0.007\\
                                                                              & (0.010)\\
   CoTypeParticipation $\times$ lnex\_ld\_avg\_before\_year\_prod\_fac        & -0.076$^{***}$\\
                                                                              & (0.014)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                                              & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                                               & 294,879\\
   Squared Correlation                                                        & 0.07576\\
   Pseudo R$^2$                                                               & 0.05963\\
   BIC                                                                        & 364,224.5\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [68]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType*ex_ld_max_before_year_with_ih_bin  + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_pre_withih <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_pre_withih)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                                           Estimate Std. Error
CoTypeCollaboration                                        0.299043   0.031937
CoTypeParticipation                                        0.355810   0.055328
ex_ld_max_before_year_with_ih_binTrue                      0.357776   0.011822
lnnum_author                                              -0.081817   0.007394
internationalinternational                                -0.048462   0.009594
lnnum_reference                                            0.054297   0.008662
num_fac                                                    0.067452   0.006735
SDGTrue                                                    0.083733   0.008156
lnmean_career_age                                          0.006806   0.013098
lnex_ld_avg_avgimpact                                     -0.274479   0.007394
lnex_ld_avg_insthindex                                    -0.049962   0.007530
ex_ld_bin_gsGlobalNorth                                    0.309955   0.017499
ex_ld_bin_sameCSame                                       -0.061083   0.009450
knowledge_proximity_mean                                  -0.787580   0.159890
lnex_ld_avg_before_year_prod_fac                          -0.036275   0.005002
Agricultural.and.Biological.Sciences                       0.757105   0.024002
Arts.and.Humanities                                        1.768181   0.073097
Biochemistry..Genetics.and.Molecular.Biology               0.598073   0.012622
Business..Management.and.Accounting                       -0.326513   0.087770
Chemical.Engineering                                       0.163598   0.020825
Chemistry                                                  0.457038   0.011155
Computer.Science                                           0.939486   0.039592
Decision.Sciences                                          1.219672   0.188741
Dentistry                                                  1.950601   0.136308
Earth.and.Planetary.Sciences                               0.754425   0.015278
Economics..Econometrics.and.Finance                       -0.080879   0.295010
Energy                                                     0.234980   0.017924
Engineering                                                0.325489   0.010486
Environmental.Science                                      0.580215   0.017490
Health.Professions                                         1.411391   0.128648
Immunology.and.Microbiology                                0.235226   0.026942
Materials.Science                                          0.022017   0.009944
Mathematics                                                0.575953   0.125651
Medicine                                                   0.869438   0.014866
Neuroscience                                               0.520731   0.032674
Nursing                                                    1.050663   0.043266
Pharmacology..Toxicology.and.Pharmaceutics                 0.908135   0.048323
Physics.and.Astronomy                                     -0.260904   0.011473
Psychology                                                 0.433750   0.157429
Social.Sciences                                            0.159043   0.156470
Veterinary                                                 0.595545   0.208786
CoTypeCollaboration:ex_ld_max_before_year_with_ih_binTrue -0.233723   0.033608
CoTypeParticipation:ex_ld_max_before_year_with_ih_binTrue -0.384353   0.057088
                                                             z value   Pr(>|z|)
CoTypeCollaboration                                         9.363448  < 2.2e-16
CoTypeParticipation                                         6.430902 1.2685e-10
ex_ld_max_before_year_with_ih_binTrue                      30.263452  < 2.2e-16
lnnum_author                                              -11.065423  < 2.2e-16
internationalinternational                                 -5.051476 4.3841e-07
lnnum_reference                                             6.268710 3.6405e-10
num_fac                                                    10.015120  < 2.2e-16
SDGTrue                                                    10.266691  < 2.2e-16
lnmean_career_age                                           0.519640 6.0331e-01
lnex_ld_avg_avgimpact                                     -37.120666  < 2.2e-16
lnex_ld_avg_insthindex                                     -6.634983 3.2454e-11
ex_ld_bin_gsGlobalNorth                                    17.712926  < 2.2e-16
ex_ld_bin_sameCSame                                        -6.464048 1.0194e-10
knowledge_proximity_mean                                   -4.925760 8.4033e-07
lnex_ld_avg_before_year_prod_fac                           -7.252341 4.0963e-13
Agricultural.and.Biological.Sciences                       31.543245  < 2.2e-16
Arts.and.Humanities                                        24.189417  < 2.2e-16
Biochemistry..Genetics.and.Molecular.Biology               47.384282  < 2.2e-16
Business..Management.and.Accounting                        -3.720080 1.9916e-04
Chemical.Engineering                                        7.855728 3.9746e-15
Chemistry                                                  40.971216  < 2.2e-16
Computer.Science                                           23.728985  < 2.2e-16
Decision.Sciences                                           6.462137 1.0323e-10
Dentistry                                                  14.310292  < 2.2e-16
Earth.and.Planetary.Sciences                               49.380147  < 2.2e-16
Economics..Econometrics.and.Finance                        -0.274157 7.8396e-01
Energy                                                     13.109533  < 2.2e-16
Engineering                                                31.041510  < 2.2e-16
Environmental.Science                                      33.174149  < 2.2e-16
Health.Professions                                         10.970922  < 2.2e-16
Immunology.and.Microbiology                                 8.730745  < 2.2e-16
Materials.Science                                           2.214068 2.6824e-02
Mathematics                                                 4.583746 4.5672e-06
Medicine                                                   58.484748  < 2.2e-16
Neuroscience                                               15.937073  < 2.2e-16
Nursing                                                    24.284064  < 2.2e-16
Pharmacology..Toxicology.and.Pharmaceutics                 18.792865  < 2.2e-16
Physics.and.Astronomy                                     -22.740876  < 2.2e-16
Psychology                                                  2.755209 5.8655e-03
Social.Sciences                                             1.016447 3.0942e-01
Veterinary                                                  2.852414 4.3389e-03
CoTypeCollaboration:ex_ld_max_before_year_with_ih_binTrue  -6.954385 3.5410e-12
CoTypeParticipation:ex_ld_max_before_year_with_ih_binTrue  -6.732687 1.6656e-11

CoTypeCollaboration                                       ***
CoTypeParticipation                                       ***
ex_ld_max_before_year_with_ih_binTrue                     ***
lnnum_author                                              ***
internationalinternational                                ***
lnnum_reference                                           ***
num_fac                                                   ***
SDGTrue                                                   ***
lnmean_career_age
lnex_ld_avg_avgimpact                                     ***
lnex_ld_avg_insthindex                                    ***
ex_ld_bin_gsGlobalNorth                                   ***
ex_ld_bin_sameCSame                                       ***
knowledge_proximity_mean                                  ***
lnex_ld_avg_before_year_prod_fac                          ***
Agricultural.and.Biological.Sciences                      ***
Arts.and.Humanities                                       ***
Biochemistry..Genetics.and.Molecular.Biology              ***
Business..Management.and.Accounting                       ***
Chemical.Engineering                                      ***
Chemistry                                                 ***
Computer.Science                                          ***
Decision.Sciences                                         ***
Dentistry                                                 ***
Earth.and.Planetary.Sciences                              ***
Economics..Econometrics.and.Finance
Energy                                                    ***
Engineering                                               ***
Environmental.Science                                     ***
Health.Professions                                        ***
Immunology.and.Microbiology                               ***
Materials.Science                                         *
Mathematics                                               ***
Medicine                                                  ***
Neuroscience                                              ***
Nursing                                                   ***
Pharmacology..Toxicology.and.Pharmaceutics                ***
Physics.and.Astronomy                                     ***
Psychology                                                **
Social.Sciences
Veterinary                                                **
CoTypeCollaboration:ex_ld_max_before_year_with_ih_binTrue ***
CoTypeParticipation:ex_ld_max_before_year_with_ih_binTrue ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -181,492.3   Adj. Pseudo R2: 0.059296
           BIC:  364,168.5     Squared Cor.: 0.075998

In [69]:
# 每组 reg_class 的平均预测概率
res_pre_withih <- avg_comparisons(model_pre_withih, variables = "CoType", comparison = 'ratio', by = 'ex_ld_max_before_year_with_ih_bin')
res_pre_withih

  term   contrast                            ex_ld_max_before_year_with_ih_bin
1 CoType mean(Collaboration) / mean(Service) False
2 CoType mean(Collaboration) / mean(Service) True
3 CoType mean(Participation) / mean(Service) False
4 CoType mean(Participation) / mean(Service) True
  estimate  std.error   statistic p.value       s.value  conf.low  conf.high
1 1.1830643 0.022747259  52.00909  0.000000e+00      Inf 1.1384805 1.227648
2 1.0389235 0.007496342 138.59072  0.000000e+00      Inf 1.0242309 1.053616
3 1.2188867 0.037326152  32.65503 6.797902e-234 774.5661 1.1457288 1.292045
4 0.9831902 0.009145438 107.50609  0.000000e+00      Inf 0.9652655 1.001115
  predicted_lo predicted_hi predicted
1 0.2463877    0.3059910    0.2463877
2 0.2858751    0.2993944    0.2858751
3 0.2463877    0.3181772    0.2463877
4 0.2858751    0.2800838    0.2858751

In [70]:
fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h4_comp_pre_withih.csv")
write.csv(res_pre_withih, fname, row.names = FALSE)

In [71]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_pre_withih,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                                               & novel\_uzzi\_bin\\
   Model:                                                                            & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                                                               & 0.299$^{***}$\\
                                                                                     & (0.032)\\
   CoTypeParticipation                                                               & 0.356$^{***}$\\
                                                                                     & (0.055)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue                                      & 0.358$^{***}$\\
                                                                                     & (0.012)\\
   lnnum\_author                                                                     & -0.082$^{***}$\\
                                                                                     & (0.007)\\
   internationalinternational                                                        & -0.049$^{***}$\\
                                                                                     & (0.010)\\
   lnnum\_reference                                                                  & 0.054$^{***}$\\
                                                                                     & (0.009)\\
   num\_fac                                                                          & 0.068$^{***}$\\
                                                                                     & (0.007)\\
   SDGTrue                                                                           & 0.084$^{***}$\\
                                                                                     & (0.008)\\
   lnmean\_career\_age                                                               & 0.007\\
                                                                                     & (0.013)\\
   lnex\_ld\_avg\_avgimpact                                                          & -0.274$^{***}$\\
                                                                                     & (0.007)\\
   lnex\_ld\_avg\_insthindex                                                         & -0.050$^{***}$\\
                                                                                     & (0.008)\\
   ex\_ld\_bin\_gsGlobalNorth                                                        & 0.310$^{***}$\\
                                                                                     & (0.018)\\
   ex\_ld\_bin\_sameCSame                                                            & -0.061$^{***}$\\
                                                                                     & (0.009)\\
   knowledge\_proximity\_mean                                                        & -0.788$^{***}$\\
                                                                                     & (0.160)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac                                            & -0.036$^{***}$\\
                                                                                     & (0.005)\\
   Agricultural.and.Biological.Sciences                                              & 0.757$^{***}$\\
                                                                                     & (0.024)\\
   Arts.and.Humanities                                                               & 1.77$^{***}$\\
                                                                                     & (0.073)\\
   Biochemistry..Genetics.and.Molecular.Biology                                      & 0.598$^{***}$\\
                                                                                     & (0.013)\\
   Business..Management.and.Accounting                                               & -0.327$^{***}$\\
                                                                                     & (0.088)\\
   Chemical.Engineering                                                              & 0.164$^{***}$\\
                                                                                     & (0.021)\\
   Chemistry                                                                         & 0.457$^{***}$\\
                                                                                     & (0.011)\\
   Computer.Science                                                                  & 0.939$^{***}$\\
                                                                                     & (0.040)\\
   Decision.Sciences                                                                 & 1.22$^{***}$\\
                                                                                     & (0.189)\\
   Dentistry                                                                         & 1.95$^{***}$\\
                                                                                     & (0.136)\\
   Earth.and.Planetary.Sciences                                                      & 0.754$^{***}$\\
                                                                                     & (0.015)\\
   Economics..Econometrics.and.Finance                                               & -0.081\\
                                                                                     & (0.295)\\
   Energy                                                                            & 0.235$^{***}$\\
                                                                                     & (0.018)\\
   Engineering                                                                       & 0.325$^{***}$\\
                                                                                     & (0.011)\\
   Immunology.and.Microbiology                                                       & 0.235$^{***}$\\
                                                                                     & (0.027)\\
   Materials.Science                                                                 & 0.022$^{**}$\\
                                                                                     & (0.010)\\
   Mathematics                                                                       & 0.576$^{***}$\\
                                                                                     & (0.126)\\
   Medicine                                                                          & 0.869$^{***}$\\
                                                                                     & (0.015)\\
   Neuroscience                                                                      & 0.521$^{***}$\\
                                                                                     & (0.033)\\
   Nursing                                                                           & 1.05$^{***}$\\
                                                                                     & (0.043)\\
   Pharmacology..Toxicology.and.Pharmaceutics                                        & 0.908$^{***}$\\
                                                                                     & (0.048)\\
   Physics.and.Astronomy                                                             & -0.261$^{***}$\\
                                                                                     & (0.011)\\
   Psychology                                                                        & 0.434$^{***}$\\
                                                                                     & (0.157)\\
   Social.Sciences                                                                   & 0.159\\
                                                                                     & (0.156)\\
   Veterinary                                                                        & 0.596$^{***}$\\
                                                                                     & (0.209)\\
   CoTypeCollaboration $\times$ ex\_ld\_max\_before\_year\_with\_ih\_binTrue         & -0.234$^{***}$\\
                                                                                     & (0.034)\\
   CoTypeParticipation $\times$ ex\_ld\_max\_before\_year\_with\_ih\_binTrue         & -0.384$^{***}$\\
                                                                                     & (0.057)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                                                     & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                                                      & 294,879\\
   Squared Correlation                                                               & 0.07600\\
   Pseudo R$^2$                                                                      & 0.05978\\
   BIC                                                                               & 364,168.5\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [72]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType*ex_ld_max_before_year_participation_bin  + ", paper_level, "+", ex_controls, "+", moderating2, "+",disciplines, " | PublishedYear")
)
model_pre_partic <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_pre_partic)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                                                 Estimate
CoTypeCollaboration                                              0.188863
CoTypeParticipation                                              0.239312
ex_ld_max_before_year_participation_binTrue                      0.216772
lnnum_author                                                    -0.078782
internationalinternational                                      -0.045550
lnnum_reference                                                  0.057236
num_fac                                                          0.063163
SDGTrue                                                          0.085091
lnmean_career_age                                                0.018301
lnex_ld_avg_avgimpact                                           -0.272872
lnex_ld_avg_insthindex                                          -0.046700
ex_ld_bin_gsGlobalNorth                                          0.312195
ex_ld_bin_sameCSame                                             -0.068788
knowledge_proximity_mean                                        -0.840388
lnex_ld_avg_before_year_prod_fac                                -0.015743
Agricultural.and.Biological.Sciences                             0.770850
Arts.and.Humanities                                              1.774070
Biochemistry..Genetics.and.Molecular.Biology                     0.593589
Business..Management.and.Accounting                             -0.340562
Chemical.Engineering                                             0.161706
Chemistry                                                        0.467652
Computer.Science                                                 0.936480
Decision.Sciences                                                1.235738
Dentistry                                                        1.970469
Earth.and.Planetary.Sciences                                     0.754486
Economics..Econometrics.and.Finance                             -0.085632
Energy                                                           0.241933
Engineering                                                      0.337511
Environmental.Science                                            0.574971
Health.Professions                                               1.412784
Immunology.and.Microbiology                                      0.231042
Materials.Science                                                0.029860
Mathematics                                                      0.595351
Medicine                                                         0.862732
Neuroscience                                                     0.518442
Nursing                                                          1.062559
Pharmacology..Toxicology.and.Pharmaceutics                       0.906601
Physics.and.Astronomy                                           -0.256912
Psychology                                                       0.405062
Social.Sciences                                                  0.178997
Veterinary                                                       0.615619
CoTypeCollaboration:ex_ld_max_before_year_participation_binTrue -0.113071
CoTypeParticipation:ex_ld_max_before_year_participation_binTrue -0.294047
                                                                Std. Error
CoTypeCollaboration                                               0.017904
CoTypeParticipation                                               0.034927
ex_ld_max_before_year_participation_binTrue                       0.010989
lnnum_author                                                      0.007344
internationalinternational                                        0.009600
lnnum_reference                                                   0.008651
num_fac                                                           0.006728
SDGTrue                                                           0.008150
lnmean_career_age                                                 0.013081
lnex_ld_avg_avgimpact                                             0.007378
lnex_ld_avg_insthindex                                            0.007523
ex_ld_bin_gsGlobalNorth                                           0.017485
ex_ld_bin_sameCSame                                               0.009447
knowledge_proximity_mean                                          0.159711
lnex_ld_avg_before_year_prod_fac                                  0.004961
Agricultural.and.Biological.Sciences                              0.023926
Arts.and.Humanities                                               0.072681
Biochemistry..Genetics.and.Molecular.Biology                      0.012620
Business..Management.and.Accounting                               0.087905
Chemical.Engineering                                              0.020815
Chemistry                                                         0.011133
Computer.Science                                                  0.039478
Decision.Sciences                                                 0.188365
Dentistry                                                         0.135515
Earth.and.Planetary.Sciences                                      0.015303
Economics..Econometrics.and.Finance                               0.294670
Energy                                                            0.017921
Engineering                                                       0.010464
Environmental.Science                                             0.017527
Health.Professions                                                0.128157
Immunology.and.Microbiology                                       0.026881
Materials.Science                                                 0.009936
Mathematics                                                       0.124549
Medicine                                                          0.014811
Neuroscience                                                      0.032498
Nursing                                                           0.043195
Pharmacology..Toxicology.and.Pharmaceutics                        0.048081
Physics.and.Astronomy                                             0.011478
Psychology                                                        0.157365
Social.Sciences                                                   0.156466
Veterinary                                                        0.207067
CoTypeCollaboration:ex_ld_max_before_year_participation_binTrue   0.022072
CoTypeParticipation:ex_ld_max_before_year_participation_binTrue   0.038178
                                                                   z value
CoTypeCollaboration                                              10.548625
CoTypeParticipation                                               6.851805
ex_ld_max_before_year_participation_binTrue                      19.725440
lnnum_author                                                    -10.727151
internationalinternational                                       -4.744851
lnnum_reference                                                   6.615858
num_fac                                                           9.387780
SDGTrue                                                          10.440931
lnmean_career_age                                                 1.399106
lnex_ld_avg_avgimpact                                           -36.984533
lnex_ld_avg_insthindex                                           -6.207203
ex_ld_bin_gsGlobalNorth                                          17.855157
ex_ld_bin_sameCSame                                              -7.281442
knowledge_proximity_mean                                         -5.261921
lnex_ld_avg_before_year_prod_fac                                 -3.173385
Agricultural.and.Biological.Sciences                             32.218737
Arts.and.Humanities                                              24.409134
Biochemistry..Genetics.and.Molecular.Biology                     47.036768
Business..Management.and.Accounting                              -3.874220
Chemical.Engineering                                              7.768889
Chemistry                                                        42.007521
Computer.Science                                                 23.721668
Decision.Sciences                                                 6.560342
Dentistry                                                        14.540648
Earth.and.Planetary.Sciences                                     49.303314
Economics..Econometrics.and.Finance                              -0.290602
Energy                                                           13.500005
Engineering                                                      32.254633
Environmental.Science                                            32.804224
Health.Professions                                               11.023890
Immunology.and.Microbiology                                       8.594901
Materials.Science                                                 3.005192
Mathematics                                                       4.780041
Medicine                                                         58.248695
Neuroscience                                                     15.953036
Nursing                                                          24.599019
Pharmacology..Toxicology.and.Pharmaceutics                       18.855719
Physics.and.Astronomy                                           -22.383901
Psychology                                                        2.574021
Social.Sciences                                                   1.144003
Veterinary                                                        2.973046
CoTypeCollaboration:ex_ld_max_before_year_participation_binTrue  -5.122841
CoTypeParticipation:ex_ld_max_before_year_participation_binTrue  -7.701905
                                                                  Pr(>|z|)
CoTypeCollaboration                                              < 2.2e-16 ***
CoTypeParticipation                                             7.2924e-12 ***
ex_ld_max_before_year_participation_binTrue                      < 2.2e-16 ***
lnnum_author                                                     < 2.2e-16 ***
internationalinternational                                      2.0866e-06 ***
lnnum_reference                                                 3.6940e-11 ***
num_fac                                                          < 2.2e-16 ***
SDGTrue                                                          < 2.2e-16 ***
lnmean_career_age                                               1.6178e-01
lnex_ld_avg_avgimpact                                            < 2.2e-16 ***
lnex_ld_avg_insthindex                                          5.3936e-10 ***
ex_ld_bin_gsGlobalNorth                                          < 2.2e-16 ***
ex_ld_bin_sameCSame                                             3.3027e-13 ***
knowledge_proximity_mean                                        1.4256e-07 ***
lnex_ld_avg_before_year_prod_fac                                1.5067e-03 **
Agricultural.and.Biological.Sciences                             < 2.2e-16 ***
Arts.and.Humanities                                              < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology                     < 2.2e-16 ***
Business..Management.and.Accounting                             1.0697e-04 ***
Chemical.Engineering                                            7.9178e-15 ***
Chemistry                                                        < 2.2e-16 ***
Computer.Science                                                 < 2.2e-16 ***
Decision.Sciences                                               5.3684e-11 ***
Dentistry                                                        < 2.2e-16 ***
Earth.and.Planetary.Sciences                                     < 2.2e-16 ***
Economics..Econometrics.and.Finance                             7.7136e-01
Energy                                                           < 2.2e-16 ***
Engineering                                                      < 2.2e-16 ***
Environmental.Science                                            < 2.2e-16 ***
Health.Professions                                               < 2.2e-16 ***
Immunology.and.Microbiology                                      < 2.2e-16 ***
Materials.Science                                               2.6541e-03 **
Mathematics                                                     1.7526e-06 ***
Medicine                                                         < 2.2e-16 ***
Neuroscience                                                     < 2.2e-16 ***
Nursing                                                          < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics                       < 2.2e-16 ***
Physics.and.Astronomy                                            < 2.2e-16 ***
Psychology                                                      1.0052e-02 *
Social.Sciences                                                 2.5262e-01
Veterinary                                                      2.9486e-03 **
CoTypeCollaboration:ex_ld_max_before_year_participation_binTrue 3.0097e-07 ***
CoTypeParticipation:ex_ld_max_before_year_participation_binTrue 1.3405e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -181,765.0   Adj. Pseudo R2: 0.057883
           BIC:  364,713.9     Squared Cor.: 0.074192

In [73]:
# 每组 reg_class 的平均预测概率
res_pre_partic <- avg_comparisons(model_pre_partic, variables = "CoType", comparison = 'ratio', by = 'ex_ld_max_before_year_participation_bin')
res_pre_partic

  term   contrast
1 CoType mean(Collaboration) / mean(Service)
2 CoType mean(Collaboration) / mean(Service)
3 CoType mean(Participation) / mean(Service)
4 CoType mean(Participation) / mean(Service)
  ex_ld_max_before_year_participation_bin estimate  std.error   statistic
1 False                                   1.1123545 0.012681821  87.71252
2 True                                    1.0461863 0.008918249 117.30849
3 False                                   1.1430292 0.022816679  50.09621
4 True                                    0.9672328 0.009912748  97.57464
  p.value s.value conf.low  conf.high predicted_lo predicted_hi predicted
1 0       Inf     1.0874986 1.1372104 0.2642670    0.3025795    0.2642670
2 0       Inf     1.0287068 1.0636657 0.2875882    0.3033630    0.2875882
3 0       Inf     1.0983093 1.1877490 0.2642670    0.3133303    0.2642670
4 0       Inf     0.9478042 0.9866614 0.2875882    0.2765056    0.2875882

In [74]:
fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h4_comp_pre_partic.csv")
write.csv(res_pre_partic, fname, row.names = FALSE)

In [75]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_pre_partic,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                                                   & novel\_uzzi\_bin\\
   Model:                                                                                & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                                                                   & 0.189$^{***}$\\
                                                                                         & (0.018)\\
   CoTypeParticipation                                                                   & 0.239$^{***}$\\
                                                                                         & (0.035)\\
   lnnum\_author                                                                         & -0.079$^{***}$\\
                                                                                         & (0.007)\\
   internationalinternational                                                            & -0.046$^{***}$\\
                                                                                         & (0.010)\\
   lnnum\_reference                                                                      & 0.057$^{***}$\\
                                                                                         & (0.009)\\
   num\_fac                                                                              & 0.063$^{***}$\\
                                                                                         & (0.007)\\
   SDGTrue                                                                               & 0.085$^{***}$\\
                                                                                         & (0.008)\\
   lnmean\_career\_age                                                                   & 0.018\\
                                                                                         & (0.013)\\
   lnex\_ld\_avg\_avgimpact                                                              & -0.273$^{***}$\\
                                                                                         & (0.007)\\
   lnex\_ld\_avg\_insthindex                                                             & -0.047$^{***}$\\
                                                                                         & (0.008)\\
   ex\_ld\_bin\_gsGlobalNorth                                                            & 0.312$^{***}$\\
                                                                                         & (0.018)\\
   ex\_ld\_bin\_sameCSame                                                                & -0.069$^{***}$\\
                                                                                         & (0.009)\\
   knowledge\_proximity\_mean                                                            & -0.840$^{***}$\\
                                                                                         & (0.160)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac                                                & -0.016$^{***}$\\
                                                                                         & (0.005)\\
   Agricultural.and.Biological.Sciences                                                  & 0.771$^{***}$\\
                                                                                         & (0.024)\\
   Arts.and.Humanities                                                                   & 1.77$^{***}$\\
                                                                                         & (0.073)\\
   Biochemistry..Genetics.and.Molecular.Biology                                          & 0.594$^{***}$\\
                                                                                         & (0.013)\\
   Business..Management.and.Accounting                                                   & -0.341$^{***}$\\
                                                                                         & (0.088)\\
   Chemical.Engineering                                                                  & 0.162$^{***}$\\
                                                                                         & (0.021)\\
   Chemistry                                                                             & 0.468$^{***}$\\
                                                                                         & (0.011)\\
   Computer.Science                                                                      & 0.936$^{***}$\\
                                                                                         & (0.040)\\
   Decision.Sciences                                                                     & 1.24$^{***}$\\
                                                                                         & (0.188)\\
   Dentistry                                                                             & 1.97$^{***}$\\
                                                                                         & (0.136)\\
   Earth.and.Planetary.Sciences                                                          & 0.754$^{***}$\\
                                                                                         & (0.015)\\
   Economics..Econometrics.and.Finance                                                   & -0.086\\
                                                                                         & (0.295)\\
   Energy                                                                                & 0.242$^{***}$\\
                                                                                         & (0.018)\\
   Engineering                                                                           & 0.338$^{***}$\\
                                                                                         & (0.011)\\
   Immunology.and.Microbiology                                                           & 0.231$^{***}$\\
                                                                                         & (0.027)\\
   Materials.Science                                                                     & 0.030$^{***}$\\
                                                                                         & (0.010)\\
   Mathematics                                                                           & 0.595$^{***}$\\
                                                                                         & (0.125)\\
   Medicine                                                                              & 0.863$^{***}$\\
                                                                                         & (0.015)\\
   Neuroscience                                                                          & 0.518$^{***}$\\
                                                                                         & (0.033)\\
   Nursing                                                                               & 1.06$^{***}$\\
                                                                                         & (0.043)\\
   Pharmacology..Toxicology.and.Pharmaceutics                                            & 0.907$^{***}$\\
                                                                                         & (0.048)\\
   Physics.and.Astronomy                                                                 & -0.257$^{***}$\\
                                                                                         & (0.011)\\
   Psychology                                                                            & 0.405$^{**}$\\
                                                                                         & (0.157)\\
   Social.Sciences                                                                       & 0.179\\
                                                                                         & (0.156)\\
   Veterinary                                                                            & 0.616$^{***}$\\
                                                                                         & (0.207)\\
   CoTypeCollaboration $\times$ ex\_ld\_max\_before\_year\_participation\_binTrue        & -0.113$^{***}$\\
                                                                                         & (0.022)\\
   CoTypeParticipation $\times$ ex\_ld\_max\_before\_year\_participation\_binTrue        & -0.294$^{***}$\\
                                                                                         & (0.038)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                                                         & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                                                          & 294,879\\
   Squared Correlation                                                                   & 0.07419\\
   Pseudo R$^2$                                                                          & 0.05837\\
   BIC                                                                                   & 364,713.9\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [76]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType*ex_ld_max_before_year_co_lead_bin  + ", paper_level, "+", ex_controls, "+", moderating3, "+",disciplines, " | PublishedYear")
)
model_pre_co_lead <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_pre_co_lead)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                                           Estimate Std. Error
CoTypeCollaboration                                        0.267458   0.028977
CoTypeParticipation                                        0.269529   0.040795
ex_ld_max_before_year_co_lead_binTrue                      0.348245   0.011349
lnnum_author                                              -0.080558   0.007430
internationalinternational                                -0.047824   0.009599
lnnum_reference                                            0.053119   0.008662
num_fac                                                    0.066011   0.006742
SDGTrue                                                    0.083444   0.008156
lnmean_career_age                                          0.005323   0.013099
lnex_ld_avg_avgimpact                                     -0.275856   0.007399
lnex_ld_avg_insthindex                                    -0.049932   0.007528
ex_ld_bin_gsGlobalNorth                                    0.310351   0.017500
ex_ld_bin_sameCSame                                       -0.063571   0.009445
knowledge_proximity_mean                                  -0.774874   0.159927
lnex_ld_avg_before_year_prod_fac                          -0.040814   0.005034
Agricultural.and.Biological.Sciences                       0.756626   0.024018
Arts.and.Humanities                                        1.766472   0.073005
Biochemistry..Genetics.and.Molecular.Biology               0.597787   0.012619
Business..Management.and.Accounting                       -0.329882   0.087839
Chemical.Engineering                                       0.164930   0.020826
Chemistry                                                  0.458575   0.011151
Computer.Science                                           0.936592   0.039610
Decision.Sciences                                          1.209673   0.188519
Dentistry                                                  1.954205   0.136199
Earth.and.Planetary.Sciences                               0.749407   0.015283
Economics..Econometrics.and.Finance                       -0.088131   0.295097
Energy                                                     0.237449   0.017926
Engineering                                                0.324226   0.010491
Environmental.Science                                      0.577379   0.017483
Health.Professions                                         1.404243   0.128447
Immunology.and.Microbiology                                0.234468   0.026919
Materials.Science                                          0.021427   0.009947
Mathematics                                                0.579279   0.126243
Medicine                                                   0.871224   0.014863
Neuroscience                                               0.519095   0.032679
Nursing                                                    1.049772   0.043207
Pharmacology..Toxicology.and.Pharmaceutics                 0.906494   0.048369
Physics.and.Astronomy                                     -0.262363   0.011473
Psychology                                                 0.431698   0.156946
Social.Sciences                                            0.164849   0.156214
Veterinary                                                 0.589223   0.208413
CoTypeCollaboration:ex_ld_max_before_year_co_lead_binTrue -0.211693   0.030888
CoTypeParticipation:ex_ld_max_before_year_co_lead_binTrue -0.307487   0.043061
                                                             z value   Pr(>|z|)
CoTypeCollaboration                                         9.230090  < 2.2e-16
CoTypeParticipation                                         6.606852 3.9258e-11
ex_ld_max_before_year_co_lead_binTrue                      30.685782  < 2.2e-16
lnnum_author                                              -10.842825  < 2.2e-16
internationalinternational                                 -4.982005 6.2929e-07
lnnum_reference                                             6.132585 8.6462e-10
num_fac                                                     9.791031  < 2.2e-16
SDGTrue                                                    10.231044  < 2.2e-16
lnmean_career_age                                           0.406363 6.8448e-01
lnex_ld_avg_avgimpact                                     -37.281401  < 2.2e-16
lnex_ld_avg_insthindex                                     -6.632427 3.3021e-11
ex_ld_bin_gsGlobalNorth                                    17.734391  < 2.2e-16
ex_ld_bin_sameCSame                                        -6.730987 1.6852e-11
knowledge_proximity_mean                                   -4.845164 1.2651e-06
lnex_ld_avg_before_year_prod_fac                           -8.107346 5.1737e-16
Agricultural.and.Biological.Sciences                       31.501901  < 2.2e-16
Arts.and.Humanities                                        24.196583  < 2.2e-16
Biochemistry..Genetics.and.Molecular.Biology               47.372918  < 2.2e-16
Business..Management.and.Accounting                        -3.755519 1.7298e-04
Chemical.Engineering                                        7.919504 2.3846e-15
Chemistry                                                  41.124534  < 2.2e-16
Computer.Science                                           23.645395  < 2.2e-16
Decision.Sciences                                           6.416713 1.3925e-10
Dentistry                                                  14.348106  < 2.2e-16
Earth.and.Planetary.Sciences                               49.034790  < 2.2e-16
Economics..Econometrics.and.Finance                        -0.298650 7.6521e-01
Energy                                                     13.246219  < 2.2e-16
Engineering                                                30.905252  < 2.2e-16
Environmental.Science                                      33.024430  < 2.2e-16
Health.Professions                                         10.932491  < 2.2e-16
Immunology.and.Microbiology                                 8.710287  < 2.2e-16
Materials.Science                                           2.154181 3.1226e-02
Mathematics                                                 4.588594 4.4624e-06
Medicine                                                   58.617962  < 2.2e-16
Neuroscience                                               15.884581  < 2.2e-16
Nursing                                                    24.296418  < 2.2e-16
Pharmacology..Toxicology.and.Pharmaceutics                 18.741133  < 2.2e-16
Physics.and.Astronomy                                     -22.868071  < 2.2e-16
Psychology                                                  2.750612 5.9484e-03
Social.Sciences                                             1.055276 2.9130e-01
Veterinary                                                  2.827183 4.6960e-03
CoTypeCollaboration:ex_ld_max_before_year_co_lead_binTrue  -6.853539 7.2045e-12
CoTypeParticipation:ex_ld_max_before_year_co_lead_binTrue  -7.140751 9.2822e-13

CoTypeCollaboration                                       ***
CoTypeParticipation                                       ***
ex_ld_max_before_year_co_lead_binTrue                     ***
lnnum_author                                              ***
internationalinternational                                ***
lnnum_reference                                           ***
num_fac                                                   ***
SDGTrue                                                   ***
lnmean_career_age
lnex_ld_avg_avgimpact                                     ***
lnex_ld_avg_insthindex                                    ***
ex_ld_bin_gsGlobalNorth                                   ***
ex_ld_bin_sameCSame                                       ***
knowledge_proximity_mean                                  ***
lnex_ld_avg_before_year_prod_fac                          ***
Agricultural.and.Biological.Sciences                      ***
Arts.and.Humanities                                       ***
Biochemistry..Genetics.and.Molecular.Biology              ***
Business..Management.and.Accounting                       ***
Chemical.Engineering                                      ***
Chemistry                                                 ***
Computer.Science                                          ***
Decision.Sciences                                         ***
Dentistry                                                 ***
Earth.and.Planetary.Sciences                              ***
Economics..Econometrics.and.Finance
Energy                                                    ***
Engineering                                               ***
Environmental.Science                                     ***
Health.Professions                                        ***
Immunology.and.Microbiology                               ***
Materials.Science                                         *
Mathematics                                               ***
Medicine                                                  ***
Neuroscience                                              ***
Nursing                                                   ***
Pharmacology..Toxicology.and.Pharmaceutics                ***
Physics.and.Astronomy                                     ***
Psychology                                                **
Social.Sciences
Veterinary                                                **
CoTypeCollaboration:ex_ld_max_before_year_co_lead_binTrue ***
CoTypeParticipation:ex_ld_max_before_year_co_lead_binTrue ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -181,485.2   Adj. Pseudo R2: 0.059333
           BIC:  364,154.2     Squared Cor.: 0.076036

In [77]:
# 每组 reg_class 的平均预测概率
res_pre_co_lead <- avg_comparisons(model_pre_co_lead, variables = "CoType", comparison = 'ratio', by = 'ex_ld_max_before_year_co_lead_bin')
res_pre_co_lead

  term   contrast                            ex_ld_max_before_year_co_lead_bin
1 CoType mean(Collaboration) / mean(Service) False
2 CoType mean(Collaboration) / mean(Service) True
3 CoType mean(Participation) / mean(Service) False
4 CoType mean(Participation) / mean(Service) True
  estimate std.error   statistic p.value s.value conf.low  conf.high
1 1.163111 0.020427971  56.93719 0       Inf     1.1230732 1.2031494
2 1.033176 0.007494015 137.86681 0       Inf     1.0184879 1.0478639
3 1.164406 0.027393115  42.50726 0       Inf     1.1107168 1.2180958
4 0.977683 0.009356526 104.49209 0       Inf     0.9593446 0.9960215
  predicted_lo predicted_hi predicted
1 0.2510753    0.3046128    0.2510753
2 0.2896318    0.3012384    0.2896318
3 0.2510753    0.3050516    0.2510753
4 0.2896318    0.2818850    0.2896318

In [78]:
fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h4_comp_pre_co_lead.csv")
write.csv(res_pre_co_lead, fname, row.names = FALSE)

In [79]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_pre_co_lead,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                                               & novel\_uzzi\_bin\\
   Model:                                                                            & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                                                               & 0.267$^{***}$\\
                                                                                     & (0.029)\\
   CoTypeParticipation                                                               & 0.270$^{***}$\\
                                                                                     & (0.041)\\
   lnnum\_author                                                                     & -0.081$^{***}$\\
                                                                                     & (0.007)\\
   internationalinternational                                                        & -0.048$^{***}$\\
                                                                                     & (0.010)\\
   lnnum\_reference                                                                  & 0.053$^{***}$\\
                                                                                     & (0.009)\\
   num\_fac                                                                          & 0.066$^{***}$\\
                                                                                     & (0.007)\\
   SDGTrue                                                                           & 0.083$^{***}$\\
                                                                                     & (0.008)\\
   lnmean\_career\_age                                                               & 0.005\\
                                                                                     & (0.013)\\
   lnex\_ld\_avg\_avgimpact                                                          & -0.276$^{***}$\\
                                                                                     & (0.007)\\
   lnex\_ld\_avg\_insthindex                                                         & -0.050$^{***}$\\
                                                                                     & (0.008)\\
   ex\_ld\_bin\_gsGlobalNorth                                                        & 0.310$^{***}$\\
                                                                                     & (0.018)\\
   ex\_ld\_bin\_sameCSame                                                            & -0.064$^{***}$\\
                                                                                     & (0.009)\\
   knowledge\_proximity\_mean                                                        & -0.775$^{***}$\\
                                                                                     & (0.160)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac                                            & -0.041$^{***}$\\
                                                                                     & (0.005)\\
   Agricultural.and.Biological.Sciences                                              & 0.757$^{***}$\\
                                                                                     & (0.024)\\
   Arts.and.Humanities                                                               & 1.77$^{***}$\\
                                                                                     & (0.073)\\
   Biochemistry..Genetics.and.Molecular.Biology                                      & 0.598$^{***}$\\
                                                                                     & (0.013)\\
   Business..Management.and.Accounting                                               & -0.330$^{***}$\\
                                                                                     & (0.088)\\
   Chemical.Engineering                                                              & 0.165$^{***}$\\
                                                                                     & (0.021)\\
   Chemistry                                                                         & 0.459$^{***}$\\
                                                                                     & (0.011)\\
   Computer.Science                                                                  & 0.937$^{***}$\\
                                                                                     & (0.040)\\
   Decision.Sciences                                                                 & 1.21$^{***}$\\
                                                                                     & (0.189)\\
   Dentistry                                                                         & 1.95$^{***}$\\
                                                                                     & (0.136)\\
   Earth.and.Planetary.Sciences                                                      & 0.749$^{***}$\\
                                                                                     & (0.015)\\
   Economics..Econometrics.and.Finance                                               & -0.088\\
                                                                                     & (0.295)\\
   Energy                                                                            & 0.237$^{***}$\\
                                                                                     & (0.018)\\
   Engineering                                                                       & 0.324$^{***}$\\
                                                                                     & (0.011)\\
   Immunology.and.Microbiology                                                       & 0.234$^{***}$\\
                                                                                     & (0.027)\\
   Materials.Science                                                                 & 0.021$^{**}$\\
                                                                                     & (0.010)\\
   Mathematics                                                                       & 0.579$^{***}$\\
                                                                                     & (0.126)\\
   Medicine                                                                          & 0.871$^{***}$\\
                                                                                     & (0.015)\\
   Neuroscience                                                                      & 0.519$^{***}$\\
                                                                                     & (0.033)\\
   Nursing                                                                           & 1.05$^{***}$\\
                                                                                     & (0.043)\\
   Pharmacology..Toxicology.and.Pharmaceutics                                        & 0.906$^{***}$\\
                                                                                     & (0.048)\\
   Physics.and.Astronomy                                                             & -0.262$^{***}$\\
                                                                                     & (0.011)\\
   Psychology                                                                        & 0.432$^{***}$\\
                                                                                     & (0.157)\\
   Social.Sciences                                                                   & 0.165\\
                                                                                     & (0.156)\\
   Veterinary                                                                        & 0.589$^{***}$\\
                                                                                     & (0.208)\\
   CoTypeCollaboration $\times$ ex\_ld\_max\_before\_year\_co\_lead\_binTrue         & -0.212$^{***}$\\
                                                                                     & (0.031)\\
   CoTypeParticipation $\times$ ex\_ld\_max\_before\_year\_co\_lead\_binTrue         & -0.307$^{***}$\\
                                                                                     & (0.043)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                                                     & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                                                      & 294,879\\
   Squared Correlation                                                               & 0.07604\\
   Pseudo R$^2$                                                                      & 0.05981\\
   BIC                                                                               & 364,154.2\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

# 补充一个更deep的point，曾经开展过“Co-lead”,后续合作/参与的收益受损更严重

# Step-wised

In [81]:
fml1 <- as.formula(
  paste0("novel_uzzi_bin ~ text_fac_scientist + ", disciplines, " | PublishedYear")
)
fml2 <- as.formula(
  paste0("novel_uzzi_bin ~ text_fac_scientist + ", paper_level, "+",disciplines, " | PublishedYear")
)
fml3 <- as.formula(
  paste0("novel_uzzi_bin ~ text_fac_scientist + ", paper_level, "+", ex_controls, "+",disciplines, " | PublishedYear")
)
fml4 <- as.formula(
  paste0("novel_uzzi_bin ~ text_fac_scientist + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_1 <- feglm(fml1, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
model_2 <- feglm(fml2, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
model_3 <- feglm(fml3, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
model_4 <- feglm(fml4, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")

In [82]:
model_1
model_2
model_3
model_4

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error  z value
text_fac_scientistStaffPart                   0.119764   0.009233 12.97138
Agricultural.and.Biological.Sciences          0.765513   0.023779 32.19238
Arts.and.Humanities                           1.861914   0.072157 25.80357
Biochemistry..Genetics.and.Molecular.Biology  0.513419   0.012218 42.02188
Business..Management.and.Accounting          -0.392942   0.087433 -4.49420
Chemical.Engineering                          0.160682   0.020746  7.74520
Chemistry                                     0.495371   0.010969 45.16053
Computer.Science                              0.941051   0.039255 23.97277
                                               Pr(>|z|)
text_fac_scientistStaffPart                   < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          6.9831e-06 ***
Chemical.Engineering                         9.5434e-15 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
... 19 coefficients remaining (display them with summary() or use argument n)
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -183,221.1   Adj. Pseudo R2: 0.050423
           BIC:  367,424.6     Squared Cor.: 0.065044

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                      Estimate Std. Error    z value  Pr(>|z|)
text_fac_scientistStaffPart           0.140662   0.009737  14.446215 < 2.2e-16
lnnum_author                         -0.132290   0.007077 -18.692584 < 2.2e-16
internationalinternational           -0.011325   0.008701  -1.301585   0.19306
lnnum_reference                      -0.013291   0.008424  -1.577673   0.11464
num_fac                               0.055900   0.006562   8.519151 < 2.2e-16
SDGTrue                               0.077598   0.008111   9.567509 < 2.2e-16
lnmean_career_age                    -0.005025   0.012682  -0.396260   0.69191
Agricultural.and.Biological.Sciences  0.756770   0.023770  31.837440 < 2.2e-16

text_fac_scientistStaffPart          ***
lnnum_author                         ***
internationalinternational
lnnum_reference
num_fac                              ***
SDGTrue                              ***
lnmean_career_age
Agricultural.and.Biological.Sciences ***
... 25 coefficients remaining (display them with summary() or use argument n)
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -182,989.4   Adj. Pseudo R2: 0.051592
           BIC:  367,036.8     Squared Cor.: 0.06597

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                             Estimate Std. Error   z value   Pr(>|z|)
text_fac_scientistStaffPart  0.104018   0.009877  10.53152  < 2.2e-16 ***
lnnum_author                -0.069970   0.007090  -9.86959  < 2.2e-16 ***
internationalinternational  -0.032494   0.009576  -3.39316 6.9092e-04 ***
lnnum_reference              0.054540   0.008631   6.31915 2.6300e-10 ***
num_fac                      0.064876   0.006621   9.79849  < 2.2e-16 ***
SDGTrue                      0.082338   0.008139  10.11637  < 2.2e-16 ***
lnmean_career_age            0.034551   0.012865   2.68557 7.2405e-03 **
lnex_ld_avg_avgimpact       -0.268328   0.007289 -36.81067  < 2.2e-16 ***
... 30 coefficients remaining (display them with summary() or use argument n)
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -181,994.4   Adj. Pseudo R2: 0.05672
           BIC:  365,109.8     Squared Cor.: 0.072644

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                             Estimate Std. Error    z value   Pr(>|z|)
text_fac_scientistStaffPart  0.064958   0.010007   6.491372 8.5058e-11 ***
lnnum_author                -0.087859   0.007299 -12.037309  < 2.2e-16 ***
internationalinternational  -0.046539   0.009593  -4.851415 1.2258e-06 ***
lnnum_reference              0.052699   0.008659   6.085706 1.1598e-09 ***
num_fac                      0.066565   0.006729   9.891698  < 2.2e-16 ***
SDGTrue                      0.084342   0.008152  10.345615  < 2.2e-16 ***
lnmean_career_age            0.011241   0.013083   0.859195 3.9023e-01
lnex_ld_avg_avgimpact       -0.274514   0.007390 -37.145608  < 2.2e-16 ***
... 32 coefficients remaining (display them with summary() or use argument n)
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -181,551.0   Adj. Pseudo R2: 0.059007
           BIC:  364,248.1     Squared Cor.: 0.075641

In [87]:
# 直接把 4 个模型并排放在一起
tab_latex <- etable(model_1, model_2, model_3, model_4,
                    keep = c("text_fac_scientist", paper_vars, ex_vars, moderating_var),
                    se = "hetero",
                    tex = TRUE,
                    digits = 3,
                    fitstat = ~ n + pr2 + ar2) # 可选：指定要在底部报告的统计量（如样本量、R方、调整R方）

# 打印出可以直接复制到 LaTeX 的代码
cat(tab_latex)

\begingroup \centering \begin{tabular}{lcccc}    \tabularnewline \midrule \midrule    Dependent Variable: & \multicolumn{4}{c}{novel\_uzzi\_bin}\\    Model:                                              & (1)           & (2)            & (3)            & (4)\\      \midrule    \emph{Variables}\\    text\_fac\_scientistStaffPart                       & 0.120$^{***}$ & 0.141$^{***}$  & 0.104$^{***}$  & 0.065$^{***}$\\                                                           & (0.009)       & (0.010)        & (0.010)        & (0.010)\\       lnnum\_author                                       &               & -0.132$^{***}$ & -0.070$^{***}$ & -0.088$^{***}$\\                                                           &               & (0.007)        & (0.007)        & (0.007)\\       internationalinternational                          &               & -0.011         & -0.033$^{***}$ & -0.046$^{***}$\\                                                           &               & (0.009)        & (0.010)        & (0.010)\\       lnnum\_reference                                    &               & -0.013         & 0.054$^{***}$  & 0.053$^{***}$\\                                                           &               & (0.008)        & (0.009)        & (0.009)\\       num\_fac                                            &               & 0.056$^{***}$  & 0.065$^{***}$  & 0.067$^{***}$\\                                                           &               & (0.007)        & (0.007)        & (0.007)\\       SDGTrue                                             &               & 0.078$^{***}$  & 0.082$^{***}$  & 0.084$^{***}$\\                                                           &               & (0.008)        & (0.008)        & (0.008)\\       lnmean\_career\_age                                 &               & -0.005         & 0.035$^{***}$  & 0.011\\                                                           &               & (0.013)        & (0.013)        & (0.013)\\       lnex\_ld\_avg\_avgimpact                            &               &                & -0.268$^{***}$ & -0.275$^{***}$\\                                                           &               &                & (0.007)        & (0.007)\\       lnex\_ld\_avg\_insthindex                           &               &                & -0.047$^{***}$ & -0.050$^{***}$\\                                                           &               &                & (0.007)        & (0.008)\\       ex\_ld\_bin\_gsGlobalNorth                          &               &                & 0.321$^{***}$  & 0.309$^{***}$\\                                                           &               &                & (0.017)        & (0.018)\\       ex\_ld\_bin\_sameCSame                              &               &                & -0.084$^{***}$ & -0.060$^{***}$\\                                                           &               &                & (0.009)        & (0.009)\\       knowledge\_proximity\_mean                          &               &                & -0.789$^{***}$ & -0.802$^{***}$\\                                                           &               &                & (0.157)        & (0.160)\\       lnex\_ld\_avg\_before\_year\_prod\_fac              &               &                &                & -0.042$^{***}$\\                                                           &               &                &                & (0.005)\\       ex\_ld\_max\_before\_year\_with\_ih\_binTrue        &               &                &                & 0.331$^{***}$\\                                                           &               &                &                & (0.011)\\       \midrule    \emph{Fixed-effects}\\    PublishedYear                                       & Yes           & Yes            & Yes            & Yes\\      \midrule    \emph{Fit statistics}\\    Observations                                        & 294,879       & 294,879        & 294,879        & 294,879\\      Pseudo R$^2$                                        & 0.05082       & 0.05202        & 0.05718        & 0.05947\\      \midrule \midrule    \multicolumn{5}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\    \multicolumn{5}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\ \end{tabular} \par\endgroup

In [91]:
fmlrd <- as.formula(
  paste0("novel_uzzi_bin ~ text_fac_scientist + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_ps_bin <- feglm(fmlrd, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Physical.Sciences==1), ], family = binomial("logit"), vcov = "hetero")
model_nps_bin <- feglm(fmlrd, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Physical.Sciences==0), ], family = binomial("logit"), vcov = "hetero")
model_hs_bin <- feglm(fmlrd, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Health.Sciences==1), ], family = binomial("logit"), vcov = "hetero")
model_ls_bin <- feglm(fmlrd, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Life.Sciences==1), ], family = binomial("logit"), vcov = "hetero")

NOTE: 6 fixed-effects (10 observations) removed because of only 0 (or only 1) outcomes.

NOTE: 6 fixed-effects (8 observations) removed because of only 0 (or only 1) outcomes.

NOTE: 1 fixed-effect (1 observation) removed because of only 0 (or only 1) outcomes.

In [93]:
# 直接把 4 个模型并排放在一起
tab_latex <- etable(model_ps_bin, model_nps_bin, model_hs_bin, model_ls_bin,
                    keep = c("text_fac_scientist", paper_vars, ex_vars, moderating_var),
                    se = "hetero",
                    tex = TRUE,
                    digits = 3,
                    fitstat = ~ n + pr2 + ar2) # 可选：指定要在底部报告的统计量（如样本量、R方、调整R方）

# 打印出可以直接复制到 LaTeX 的代码
cat(tab_latex)

\begingroup \centering \begin{tabular}{lcccc}    \tabularnewline \midrule \midrule    Dependent Variable: & \multicolumn{4}{c}{novel\_uzzi\_bin}\\    Model:                                              & (1)            & (2)            & (3)            & (4)\\      \midrule    \emph{Variables}\\    text\_fac\_scientistStaffPart                       & 0.059$^{***}$  & 0.318$^{***}$  & 0.388$^{***}$  & 0.131$^{***}$\\                                                           & (0.011)        & (0.036)        & (0.038)        & (0.022)\\       lnnum\_author                                       & -0.177$^{***}$ & 0.345$^{***}$  & 0.320$^{***}$  & 0.233$^{***}$\\                                                           & (0.008)        & (0.024)        & (0.026)        & (0.017)\\       internationalinternational                          & -0.075$^{***}$ & 0.108$^{***}$  & 0.059$^{**}$   & 0.091$^{***}$\\                                                           & (0.011)        & (0.024)        & (0.026)        & (0.018)\\       lnnum\_reference                                    & 0.077$^{***}$  & -0.088$^{***}$ & 0.110$^{***}$  & 0.101$^{***}$\\                                                           & (0.009)        & (0.027)        & (0.028)        & (0.018)\\       num\_fac                                            & 0.102$^{***}$  & -0.132$^{***}$ & -0.123$^{***}$ & -0.074$^{***}$\\                                                           & (0.007)        & (0.019)        & (0.021)        & (0.013)\\       SDGTrue                                             & 0.033$^{***}$  & 0.260$^{***}$  & 0.224$^{***}$  & 0.157$^{***}$\\                                                           & (0.009)        & (0.021)        & (0.024)        & (0.015)\\       lnmean\_career\_age                                 & -0.051$^{***}$ & 0.266$^{***}$  & 0.185$^{***}$  & 0.149$^{***}$\\                                                           & (0.014)        & (0.035)        & (0.039)        & (0.024)\\       lnex\_ld\_avg\_avgimpact                            & -0.223$^{***}$ & -0.535$^{***}$ & -0.335$^{***}$ & -0.387$^{***}$\\                                                           & (0.008)        & (0.021)        & (0.022)        & (0.014)\\       lnex\_ld\_avg\_insthindex                           & -0.017$^{**}$  & -0.191$^{***}$ & -0.120$^{***}$ & -0.137$^{***}$\\                                                           & (0.008)        & (0.020)        & (0.021)        & (0.014)\\       ex\_ld\_bin\_gsGlobalNorth                          & 0.300$^{***}$  & 0.150$^{***}$  & 0.232$^{***}$  & 0.057\\                                                           & (0.019)        & (0.057)        & (0.062)        & (0.040)\\       ex\_ld\_bin\_sameCSame                              & -0.054$^{***}$ & -0.100$^{***}$ & -0.125$^{***}$ & -0.092$^{***}$\\                                                           & (0.010)        & (0.024)        & (0.026)        & (0.017)\\       knowledge\_proximity\_mean                          & -0.265         & -4.20$^{***}$  & -1.03$^{**}$   & -2.44$^{***}$\\                                                           & (0.175)        & (0.436)        & (0.404)        & (0.285)\\       lnex\_ld\_avg\_before\_year\_prod\_fac              & -0.035$^{***}$ & -0.043$^{***}$ & -0.068$^{***}$ & -0.035$^{***}$\\                                                           & (0.005)        & (0.015)        & (0.016)        & (0.010)\\       ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & 0.344$^{***}$  & 0.189$^{***}$  & 0.175$^{***}$  & 0.260$^{***}$\\                                                           & (0.013)        & (0.025)        & (0.028)        & (0.018)\\       \midrule    \emph{Fixed-effects}\\    PublishedYear                                       & Yes            & Yes            & Yes            & Yes\\      \midrule    \emph{Fit statistics}\\    Observations                                        & 253,575        & 41,294         & 33,409         & 77,590\\      Pseudo R$^2$                                        & 0.06424        & 0.07822        & 0.06068        & 0.05615\\      \midrule \midrule    \multicolumn{5}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\    \multicolumn{5}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\ \end{tabular} \par\endgroup

In [92]:
model_ps_bin
model_nps_bin
model_hs_bin
model_ls_bin

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 253,575
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                             Estimate Std. Error   z value   Pr(>|z|)
text_fac_scientistStaffPart  0.058672   0.010578   5.54659 2.9130e-08 ***
lnnum_author                -0.176638   0.008240 -21.43792  < 2.2e-16 ***
internationalinternational  -0.075425   0.010529  -7.16378 7.8480e-13 ***
lnnum_reference              0.077542   0.009242   8.39026  < 2.2e-16 ***
num_fac                      0.102222   0.007275  14.05173  < 2.2e-16 ***
SDGTrue                      0.032981   0.008921   3.69687 2.1827e-04 ***
lnmean_career_age           -0.050889   0.014203  -3.58311 3.3953e-04 ***
lnex_ld_avg_avgimpact       -0.223156   0.008253 -27.03788  < 2.2e-16 ***
... 32 coefficients remaining (display them with summary() or use argument n)
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -153,671.4   Adj. Pseudo R2: 0.063687
           BIC:  308,475.1     Squared Cor.: 0.081035

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 41,294
Fixed-effects: PublishedYear: 38
Standard-errors: Heteroskedasticity-robust
                             Estimate Std. Error   z value   Pr(>|z|)
text_fac_scientistStaffPart  0.317739   0.036403   8.72833  < 2.2e-16 ***
lnnum_author                 0.344890   0.023766  14.51212  < 2.2e-16 ***
internationalinternational   0.107954   0.024142   4.47167 7.7613e-06 ***
lnnum_reference             -0.088392   0.026780  -3.30065 9.6461e-04 ***
num_fac                     -0.131859   0.018676  -7.06033 1.6610e-12 ***
SDGTrue                      0.260102   0.021372  12.16997  < 2.2e-16 ***
lnmean_career_age            0.266285   0.035370   7.52850 5.1325e-14 ***
lnex_ld_avg_avgimpact       -0.534767   0.021066 -25.38509  < 2.2e-16 ***
... 21 coefficients remaining (display them with summary() or use argument n)
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -26,058.1   Adj. Pseudo R2: 0.075881
           BIC:  52,828.4     Squared Cor.: 0.103624

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 33,409
Fixed-effects: PublishedYear: 40
Standard-errors: Heteroskedasticity-robust
                             Estimate Std. Error   z value   Pr(>|z|)
text_fac_scientistStaffPart  0.388395   0.038336  10.13135  < 2.2e-16 ***
lnnum_author                 0.319584   0.026505  12.05740  < 2.2e-16 ***
internationalinternational   0.058681   0.026496   2.21472 2.6779e-02 *
lnnum_reference              0.110130   0.027640   3.98449 6.7624e-05 ***
num_fac                     -0.123160   0.020739  -5.93845 2.8772e-09 ***
SDGTrue                      0.224109   0.023466   9.55045  < 2.2e-16 ***
lnmean_career_age            0.184938   0.038681   4.78107 1.7436e-06 ***
lnex_ld_avg_avgimpact       -0.334968   0.022019 -15.21267  < 2.2e-16 ***
... 32 coefficients remaining (display them with summary() or use argument n)
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -21,581.4   Adj. Pseudo R2: 0.057238
           BIC:  43,996.1     Squared Cor.: 0.081599

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 77,590
Fixed-effects: PublishedYear: 48
Standard-errors: Heteroskedasticity-robust
                             Estimate Std. Error   z value   Pr(>|z|)
text_fac_scientistStaffPart  0.131165   0.022359   5.86637 4.4544e-09 ***
lnnum_author                 0.232568   0.016875  13.78196  < 2.2e-16 ***
internationalinternational   0.091356   0.017481   5.22596 1.7325e-07 ***
lnnum_reference              0.100861   0.017830   5.65668 1.5433e-08 ***
num_fac                     -0.074282   0.012579  -5.90498 3.5268e-09 ***
SDGTrue                      0.157392   0.015172  10.37373  < 2.2e-16 ***
lnmean_career_age            0.149261   0.024350   6.12989 8.7939e-10 ***
lnex_ld_avg_avgimpact       -0.386505   0.014080 -27.45105  < 2.2e-16 ***
... 31 coefficients remaining (display them with summary() or use argument n)
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -50,616.2   Adj. Pseudo R2: 0.054544
           BIC: 102,211.9     Squared Cor.: 0.07536

In [88]:
fmlt1 <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", disciplines, " | PublishedYear")
)
fmlt2 <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+",disciplines, " | PublishedYear")
)
fmlt3 <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+",disciplines, " | PublishedYear")
)
fmlt4 <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_t1 <- feglm(fmlt1, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
model_t2 <- feglm(fmlt2, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
model_t3 <- feglm(fmlt3, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
model_t4 <- feglm(fmlt4, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")

In [89]:
model_t1
model_t2
model_t3
model_t4

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error  z value
CoTypeCollaboration                           0.159156   0.010644 14.95214
CoTypeParticipation                           0.037926   0.014258  2.65998
Agricultural.and.Biological.Sciences          0.765525   0.023788 32.18123
Arts.and.Humanities                           1.862658   0.072192 25.80129
Biochemistry..Genetics.and.Molecular.Biology  0.510660   0.012224 41.77467
Business..Management.and.Accounting          -0.395923   0.087547 -4.52242
Chemical.Engineering                          0.160474   0.020743  7.73635
Chemistry                                     0.494542   0.010971 45.07566
                                               Pr(>|z|)
CoTypeCollaboration                           < 2.2e-16 ***
CoTypeParticipation                          7.8145e-03 **
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          6.1137e-06 ***
Chemical.Engineering                         1.0231e-14 ***
Chemistry                                     < 2.2e-16 ***
... 20 coefficients remaining (display them with summary() or use argument n)
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -183,194.3   Adj. Pseudo R2: 0.050556
           BIC:  367,383.5     Squared Cor.: 0.065163

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                            Estimate Std. Error    z value   Pr(>|z|)
CoTypeCollaboration         0.166329   0.011004  15.115250  < 2.2e-16 ***
CoTypeParticipation         0.083954   0.014865   5.647811 1.6250e-08 ***
lnnum_author               -0.127904   0.007167 -17.846845  < 2.2e-16 ***
internationalinternational -0.011376   0.008700  -1.307567 1.9102e-01
lnnum_reference            -0.012900   0.008424  -1.531293 1.2570e-01
num_fac                     0.055591   0.006563   8.470389  < 2.2e-16 ***
SDGTrue                     0.077079   0.008112   9.501670  < 2.2e-16 ***
lnmean_career_age          -0.007455   0.012693  -0.587354 5.5697e-01
... 26 coefficients remaining (display them with summary() or use argument n)
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -182,977.3   Adj. Pseudo R2: 0.051649
           BIC:  367,025.1     Squared Cor.: 0.066024

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                            Estimate Std. Error  z value   Pr(>|z|)
CoTypeCollaboration         0.134576   0.011132 12.08924  < 2.2e-16 ***
CoTypeParticipation         0.036306   0.015001  2.42016 1.5514e-02 *
lnnum_author               -0.064427   0.007187 -8.96456  < 2.2e-16 ***
internationalinternational -0.032915   0.009577 -3.43686 5.8849e-04 ***
lnnum_reference             0.055179   0.008632  6.39273 1.6295e-10 ***
num_fac                     0.064480   0.006623  9.73558  < 2.2e-16 ***
SDGTrue                     0.081746   0.008141 10.04169  < 2.2e-16 ***
lnmean_career_age           0.031941   0.012874  2.48095 1.3103e-02 *
... 31 coefficients remaining (display them with summary() or use argument n)
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -181,977.3   Adj. Pseudo R2: 0.056804
           BIC:  365,088.1     Squared Cor.: 0.072729

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                            Estimate Std. Error    z value   Pr(>|z|)
CoTypeCollaboration         0.093664   0.011280   8.303659  < 2.2e-16 ***
CoTypeParticipation         0.001874   0.015079   0.124291 9.0108e-01
lnnum_author               -0.082752   0.007391 -11.196746  < 2.2e-16 ***
internationalinternational -0.046879   0.009593  -4.886663 1.0256e-06 ***
lnnum_reference             0.053317   0.008660   6.156694 7.4279e-10 ***
num_fac                     0.066123   0.006732   9.822587  < 2.2e-16 ***
SDGTrue                     0.083797   0.008154  10.276936  < 2.2e-16 ***
lnmean_career_age           0.008714   0.013093   0.665580 5.0568e-01
... 33 coefficients remaining (display them with summary() or use argument n)
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -181,536.1   Adj. Pseudo R2: 0.059079
           BIC:  364,230.9     Squared Cor.: 0.07571

In [90]:
# 直接把 4 个模型并排放在一起
tab_latex <- etable(model_t1, model_t2, model_t3, model_t4,
                    keep = c("CoType", paper_vars, ex_vars, moderating_var),
                    se = "hetero",
                    tex = TRUE,
                    digits = 3,
                    fitstat = ~ n + pr2 + ar2) # 可选：指定要在底部报告的统计量（如样本量、R方、调整R方）

# 打印出可以直接复制到 LaTeX 的代码
cat(tab_latex)

\begingroup \centering \begin{tabular}{lcccc}    \tabularnewline \midrule \midrule    Dependent Variable: & \multicolumn{4}{c}{novel\_uzzi\_bin}\\    Model:                                              & (1)           & (2)            & (3)            & (4)\\      \midrule    \emph{Variables}\\    CoTypeCollaboration                                 & 0.159$^{***}$ & 0.166$^{***}$  & 0.135$^{***}$  & 0.094$^{***}$\\                                                           & (0.011)       & (0.011)        & (0.011)        & (0.011)\\       CoTypeParticipation                                 & 0.038$^{***}$ & 0.084$^{***}$  & 0.036$^{**}$   & 0.002\\                                                           & (0.014)       & (0.015)        & (0.015)        & (0.015)\\       lnnum\_author                                       &               & -0.128$^{***}$ & -0.064$^{***}$ & -0.083$^{***}$\\                                                           &               & (0.007)        & (0.007)        & (0.007)\\       internationalinternational                          &               & -0.011         & -0.033$^{***}$ & -0.047$^{***}$\\                                                           &               & (0.009)        & (0.010)        & (0.010)\\       lnnum\_reference                                    &               & -0.013         & 0.055$^{***}$  & 0.053$^{***}$\\                                                           &               & (0.008)        & (0.009)        & (0.009)\\       num\_fac                                            &               & 0.056$^{***}$  & 0.065$^{***}$  & 0.066$^{***}$\\                                                           &               & (0.007)        & (0.007)        & (0.007)\\       SDGTrue                                             &               & 0.077$^{***}$  & 0.082$^{***}$  & 0.084$^{***}$\\                                                           &               & (0.008)        & (0.008)        & (0.008)\\       lnmean\_career\_age                                 &               & -0.007         & 0.032$^{**}$   & 0.009\\                                                           &               & (0.013)        & (0.013)        & (0.013)\\       lnex\_ld\_avg\_avgimpact                            &               &                & -0.269$^{***}$ & -0.275$^{***}$\\                                                           &               &                & (0.007)        & (0.007)\\       lnex\_ld\_avg\_insthindex                           &               &                & -0.047$^{***}$ & -0.049$^{***}$\\                                                           &               &                & (0.007)        & (0.008)\\       ex\_ld\_bin\_gsGlobalNorth                          &               &                & 0.320$^{***}$  & 0.309$^{***}$\\                                                           &               &                & (0.017)        & (0.018)\\       ex\_ld\_bin\_sameCSame                              &               &                & -0.085$^{***}$ & -0.061$^{***}$\\                                                           &               &                & (0.009)        & (0.009)\\       knowledge\_proximity\_mean                          &               &                & -0.791$^{***}$ & -0.806$^{***}$\\                                                           &               &                & (0.157)        & (0.160)\\       lnex\_ld\_avg\_before\_year\_prod\_fac              &               &                &                & -0.041$^{***}$\\                                                           &               &                &                & (0.005)\\       ex\_ld\_max\_before\_year\_with\_ih\_binTrue        &               &                &                & 0.330$^{***}$\\                                                           &               &                &                & (0.011)\\       \midrule    \emph{Fixed-effects}\\    PublishedYear                                       & Yes           & Yes            & Yes            & Yes\\      \midrule    \emph{Fit statistics}\\    Observations                                        & 294,879       & 294,879        & 294,879        & 294,879\\      Pseudo R$^2$                                        & 0.05096       & 0.05208        & 0.05727        & 0.05955\\      \midrule \midrule    \multicolumn{5}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\    \multicolumn{5}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\ \end{tabular} \par\endgroup

In [94]:
fmltrd <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
tmodel_ps_bin <- feglm(fmltrd, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Physical.Sciences==1), ], family = binomial("logit"), vcov = "hetero")
tmodel_nps_bin <- feglm(fmltrd, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Physical.Sciences==0), ], family = binomial("logit"), vcov = "hetero")
tmodel_hs_bin <- feglm(fmltrd, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Health.Sciences==1), ], family = binomial("logit"), vcov = "hetero")
tmodel_ls_bin <- feglm(fmltrd, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Life.Sciences==1), ], family = binomial("logit"), vcov = "hetero")

NOTE: 6 fixed-effects (10 observations) removed because of only 0 (or only 1) outcomes.

NOTE: 6 fixed-effects (8 observations) removed because of only 0 (or only 1) outcomes.

NOTE: 1 fixed-effect (1 observation) removed because of only 0 (or only 1) outcomes.

In [95]:
tmodel_ps_bin
tmodel_nps_bin
tmodel_hs_bin
tmodel_ls_bin

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 253,575
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                            Estimate Std. Error    z value   Pr(>|z|)
CoTypeCollaboration         0.081750   0.011854   6.896493 5.3302e-12 ***
CoTypeParticipation         0.006896   0.015894   0.433865 6.6439e-01
lnnum_author               -0.172038   0.008338 -20.633222  < 2.2e-16 ***
internationalinternational -0.075657   0.010529  -7.185651 6.6887e-13 ***
lnnum_reference             0.078010   0.009242   8.440694  < 2.2e-16 ***
num_fac                     0.101840   0.007277  13.994286  < 2.2e-16 ***
SDGTrue                     0.032604   0.008922   3.654131 2.5805e-04 ***
lnmean_career_age          -0.052982   0.014213  -3.727710 1.9323e-04 ***
... 33 coefficients remaining (display them with summary() or use argument n)
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -153,662.3   Adj. Pseudo R2: 0.063736
           BIC:  308,469.4     Squared Cor.: 0.081079

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 41,294
Fixed-effects: PublishedYear: 38
Standard-errors: Heteroskedasticity-robust
                            Estimate Std. Error  z value   Pr(>|z|)
CoTypeCollaboration         0.281504   0.042795  6.57803 4.7673e-11 ***
CoTypeParticipation         0.395612   0.059091  6.69494 2.1576e-11 ***
lnnum_author                0.344441   0.023759 14.49700  < 2.2e-16 ***
internationalinternational  0.107923   0.024142  4.47031 7.8106e-06 ***
lnnum_reference            -0.088769   0.026784 -3.31421 9.1903e-04 ***
num_fac                    -0.131631   0.018687 -7.04403 1.8676e-12 ***
SDGTrue                     0.260535   0.021376 12.18810  < 2.2e-16 ***
lnmean_career_age           0.268377   0.035399  7.58155 3.4146e-14 ***
... 22 coefficients remaining (display them with summary() or use argument n)
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -26,056.8   Adj. Pseudo R2: 0.075893
           BIC:  52,836.3     Squared Cor.: 0.103672

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 33,409
Fixed-effects: PublishedYear: 40
Standard-errors: Heteroskedasticity-robust
                            Estimate Std. Error  z value   Pr(>|z|)
CoTypeCollaboration         0.347392   0.044522  7.80271 6.0591e-15 ***
CoTypeParticipation         0.478942   0.063318  7.56410 3.9056e-14 ***
lnnum_author                0.318061   0.026497 12.00377  < 2.2e-16 ***
internationalinternational  0.058039   0.026499  2.19023 2.8507e-02 *
lnnum_reference             0.110106   0.027655  3.98134 6.8527e-05 ***
num_fac                    -0.123250   0.020755 -5.93839 2.8783e-09 ***
SDGTrue                     0.224452   0.023469  9.56391  < 2.2e-16 ***
lnmean_career_age           0.187322   0.038706  4.83968 1.3005e-06 ***
... 33 coefficients remaining (display them with summary() or use argument n)
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -21,579.7   Adj. Pseudo R2: 0.057266
           BIC:  44,003.2     Squared Cor.: 0.081668

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 77,590
Fixed-effects: PublishedYear: 48
Standard-errors: Heteroskedasticity-robust
                            Estimate Std. Error  z value   Pr(>|z|)
CoTypeCollaboration         0.112862   0.025274  4.46548 7.9888e-06 ***
CoTypeParticipation         0.177887   0.037424  4.75325 2.0017e-06 ***
lnnum_author                0.232349   0.016872 13.77098  < 2.2e-16 ***
internationalinternational  0.091095   0.017482  5.21065 1.8818e-07 ***
lnnum_reference             0.100646   0.017834  5.64361 1.6652e-08 ***
num_fac                    -0.074019   0.012581 -5.88365 4.0132e-09 ***
SDGTrue                     0.157520   0.015173 10.38170  < 2.2e-16 ***
lnmean_career_age           0.150727   0.024366  6.18588 6.1757e-10 ***
... 32 coefficients remaining (display them with summary() or use argument n)
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -50,614.9   Adj. Pseudo R2: 0.054548
           BIC: 102,220.7     Squared Cor.: 0.07539

In [96]:
# 直接把 4 个模型并排放在一起
tab_latex <- etable(tmodel_ps_bin, tmodel_nps_bin, tmodel_hs_bin, tmodel_ls_bin,
                    keep = c("CoType", paper_vars, ex_vars, moderating_var),
                    se = "hetero",
                    tex = TRUE,
                    digits = 3,
                    fitstat = ~ n + pr2 + ar2) # 可选：指定要在底部报告的统计量（如样本量、R方、调整R方）

# 打印出可以直接复制到 LaTeX 的代码
cat(tab_latex)

\begingroup \centering \begin{tabular}{lcccc}    \tabularnewline \midrule \midrule    Dependent Variable: & \multicolumn{4}{c}{novel\_uzzi\_bin}\\    Model:                                              & (1)            & (2)            & (3)            & (4)\\      \midrule    \emph{Variables}\\    CoTypeCollaboration                                 & 0.082$^{***}$  & 0.282$^{***}$  & 0.347$^{***}$  & 0.113$^{***}$\\                                                           & (0.012)        & (0.043)        & (0.044)        & (0.025)\\       CoTypeParticipation                                 & 0.007          & 0.396$^{***}$  & 0.479$^{***}$  & 0.178$^{***}$\\                                                           & (0.016)        & (0.059)        & (0.063)        & (0.037)\\       lnnum\_author                                       & -0.172$^{***}$ & 0.344$^{***}$  & 0.318$^{***}$  & 0.232$^{***}$\\                                                           & (0.008)        & (0.024)        & (0.026)        & (0.017)\\       internationalinternational                          & -0.076$^{***}$ & 0.108$^{***}$  & 0.058$^{**}$   & 0.091$^{***}$\\                                                           & (0.011)        & (0.024)        & (0.026)        & (0.018)\\       lnnum\_reference                                    & 0.078$^{***}$  & -0.089$^{***}$ & 0.110$^{***}$  & 0.101$^{***}$\\                                                           & (0.009)        & (0.027)        & (0.028)        & (0.018)\\       num\_fac                                            & 0.102$^{***}$  & -0.132$^{***}$ & -0.123$^{***}$ & -0.074$^{***}$\\                                                           & (0.007)        & (0.019)        & (0.021)        & (0.013)\\       SDGTrue                                             & 0.033$^{***}$  & 0.261$^{***}$  & 0.224$^{***}$  & 0.158$^{***}$\\                                                           & (0.009)        & (0.021)        & (0.024)        & (0.015)\\       lnmean\_career\_age                                 & -0.053$^{***}$ & 0.268$^{***}$  & 0.187$^{***}$  & 0.151$^{***}$\\                                                           & (0.014)        & (0.035)        & (0.039)        & (0.024)\\       lnex\_ld\_avg\_avgimpact                            & -0.224$^{***}$ & -0.535$^{***}$ & -0.334$^{***}$ & -0.386$^{***}$\\                                                           & (0.008)        & (0.021)        & (0.022)        & (0.014)\\       lnex\_ld\_avg\_insthindex                           & -0.017$^{**}$  & -0.190$^{***}$ & -0.120$^{***}$ & -0.137$^{***}$\\                                                           & (0.008)        & (0.020)        & (0.021)        & (0.014)\\       ex\_ld\_bin\_gsGlobalNorth                          & 0.300$^{***}$  & 0.152$^{***}$  & 0.233$^{***}$  & 0.058\\                                                           & (0.019)        & (0.057)        & (0.062)        & (0.040)\\       ex\_ld\_bin\_sameCSame                              & -0.055$^{***}$ & -0.100$^{***}$ & -0.126$^{***}$ & -0.092$^{***}$\\                                                           & (0.010)        & (0.024)        & (0.026)        & (0.017)\\       knowledge\_proximity\_mean                          & -0.269         & -4.18$^{***}$  & -1.03$^{**}$   & -2.44$^{***}$\\                                                           & (0.175)        & (0.436)        & (0.404)        & (0.285)\\       lnex\_ld\_avg\_before\_year\_prod\_fac              & -0.035$^{***}$ & -0.043$^{***}$ & -0.068$^{***}$ & -0.035$^{***}$\\                                                           & (0.005)        & (0.015)        & (0.016)        & (0.010)\\       ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & 0.343$^{***}$  & 0.189$^{***}$  & 0.174$^{***}$  & 0.260$^{***}$\\                                                           & (0.013)        & (0.025)        & (0.028)        & (0.018)\\       \midrule    \emph{Fixed-effects}\\    PublishedYear                                       & Yes            & Yes            & Yes            & Yes\\      \midrule    \emph{Fit statistics}\\    Observations                                        & 253,575        & 41,294         & 33,409         & 77,590\\      Pseudo R$^2$                                        & 0.06429        & 0.07826        & 0.06075        & 0.05617\\      \midrule \midrule    \multicolumn{5}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\    \multicolumn{5}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\ \end{tabular} \par\endgroup

In [90]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+",disciplines, " | PublishedYear")
)
model3 <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model3)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
CoTypeCollaboration                           0.143687   0.011097  12.948869
CoTypeParticipation                           0.047011   0.014969   3.140640
lnnum_author                                 -0.068658   0.007116  -9.648419
internationalinternational                   -0.031089   0.009559  -3.252299
lnnum_reference                               0.061520   0.008603   7.150632
num_fac                                       0.059498   0.006605   9.007958
SDGTrue                                       0.092371   0.008114  11.384687
lnmean_career_age                             0.033050   0.012852   2.571617
lnex_ld_avg_avgimpact                        -0.264828   0.007259 -36.483771
lnex_ld_avg_insthindex                       -0.049529   0.007468  -6.632131
ex_ld_bin_gsGlobalNorth                       0.319559   0.017431  18.332975
ex_ld_bin_sameCSame                          -0.088044   0.009395  -9.371276
knowledge_proximity_mean                     -0.536984   0.156999  -3.420305
Arts.and.Humanities                           1.761999   0.072602  24.269151
Biochemistry..Genetics.and.Molecular.Biology  0.560437   0.012537  44.703274
Business..Management.and.Accounting          -0.344905   0.088174  -3.911635
Chemical.Engineering                          0.127998   0.020763   6.164848
Chemistry                                     0.436398   0.011069  39.426244
Computer.Science                              0.885328   0.039395  22.473379
Decision.Sciences                             1.205541   0.188256   6.403744
Dentistry                                     1.932497   0.135449  14.267307
Earth.and.Planetary.Sciences                  0.707815   0.015281  46.318485
Economics..Econometrics.and.Finance          -0.146465   0.292554  -0.500642
Energy                                        0.215856   0.017843  12.097741
Engineering                                   0.301371   0.010388  29.012331
Environmental.Science                         0.556121   0.017498  31.781864
Health.Professions                            1.376601   0.128348  10.725554
Immunology.and.Microbiology                   0.170265   0.026632   6.393299
Materials.Science                             0.001639   0.009727   0.168540
Mathematics                                   0.566115   0.123863   4.570476
Medicine                                      0.805057   0.014620  55.064785
Neuroscience                                  0.513867   0.032067  16.024855
Nursing                                       1.142418   0.043670  26.160014
Pharmacology..Toxicology.and.Pharmaceutics    0.891611   0.047942  18.597867
Physics.and.Astronomy                        -0.293480   0.011296 -25.979886
Psychology                                    0.370676   0.153231   2.419069
Social.Sciences                               0.155397   0.156885   0.990516
Veterinary                                    0.592872   0.205209   2.889114
                                               Pr(>|z|)
CoTypeCollaboration                           < 2.2e-16 ***
CoTypeParticipation                          1.6858e-03 **
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   1.1448e-03 **
lnnum_reference                              8.6379e-13 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            1.0122e-02 *
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                       3.3087e-11 ***
ex_ld_bin_gsGlobalNorth                       < 2.2e-16 ***
ex_ld_bin_sameCSame                           < 2.2e-16 ***
knowledge_proximity_mean                     6.2551e-04 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          9.1674e-05 ***
Chemical.Engineering                         7.0551e-10 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            1.5161e-10 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          6.1662e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                  1.6234e-10 ***
Materials.Science                            8.6616e-01
Mathematics                                  4.8662e-06 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   1.5560e-02 *
Social.Sciences                              3.2192e-01
Veterinary                                   3.8633e-03 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -182,548.0   Adj. Pseudo R2: 0.053853
           BIC:  366,216.9     Squared Cor.: 0.068979

In [91]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model4 <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model4)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
CoTypeCollaboration                           0.099926   0.011245   8.886446
CoTypeParticipation                           0.010299   0.015044   0.684582
lnnum_author                                 -0.087020   0.007328 -11.874570
internationalinternational                   -0.045118   0.009576  -4.711696
lnnum_reference                               0.059057   0.008633   6.841129
num_fac                                       0.062924   0.006715   9.369983
SDGTrue                                       0.093974   0.008128  11.561174
lnmean_career_age                             0.012005   0.013072   0.918354
lnex_ld_avg_avgimpact                        -0.269872   0.007355 -36.690437
lnex_ld_avg_insthindex                       -0.051397   0.007510  -6.844259
ex_ld_bin_gsGlobalNorth                       0.309880   0.017490  17.717256
ex_ld_bin_sameCSame                          -0.063400   0.009432  -6.721559
knowledge_proximity_mean                     -0.519050   0.159415  -3.255960
lnex_ld_avg_before_year_prod_fac             -0.049429   0.004953  -9.979480
ex_ld_max_before_year_with_ih_binTrue         0.341342   0.011341  30.097556
Arts.and.Humanities                           1.739659   0.073159  23.779227
Biochemistry..Genetics.and.Molecular.Biology  0.581832   0.012607  46.150420
Business..Management.and.Accounting          -0.356803   0.087998  -4.054647
Chemical.Engineering                          0.134750   0.020810   6.475235
Chemistry                                     0.423471   0.011105  38.132697
Computer.Science                              0.895903   0.039528  22.665211
Decision.Sciences                             1.190685   0.189362   6.287886
Dentistry                                     1.903426   0.136163  13.979002
Earth.and.Planetary.Sciences                  0.710429   0.015254  46.572210
Economics..Econometrics.and.Finance          -0.112709   0.295110  -0.381923
Energy                                        0.199571   0.017872  11.166486
Engineering                                   0.283702   0.010425  27.213022
Environmental.Science                         0.563181   0.017461  32.253949
Health.Professions                            1.369455   0.128704  10.640324
Immunology.and.Microbiology                   0.192720   0.026784   7.195428
Materials.Science                            -0.021025   0.009864  -2.131434
Mathematics                                   0.545550   0.125475   4.347874
Medicine                                      0.823541   0.014724  55.930203
Neuroscience                                  0.518029   0.032283  16.046508
Nursing                                       1.134037   0.043674  25.965997
Pharmacology..Toxicology.and.Pharmaceutics    0.892005   0.048193  18.509024
Physics.and.Astronomy                        -0.309036   0.011406 -27.095196
Psychology                                    0.395773   0.155025   2.552955
Social.Sciences                               0.123036   0.157185   0.782746
Veterinary                                    0.590046   0.206852   2.852509
                                               Pr(>|z|)
CoTypeCollaboration                           < 2.2e-16 ***
CoTypeParticipation                          4.9361e-01
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   2.4566e-06 ***
lnnum_reference                              7.8571e-12 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            3.5843e-01
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                       7.6873e-12 ***
ex_ld_bin_gsGlobalNorth                       < 2.2e-16 ***
ex_ld_bin_sameCSame                          1.7979e-11 ***
knowledge_proximity_mean                     1.1301e-03 **
lnex_ld_avg_before_year_prod_fac              < 2.2e-16 ***
ex_ld_max_before_year_with_ih_binTrue         < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          5.0210e-05 ***
Chemical.Engineering                         9.4665e-11 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            3.2182e-10 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          7.0252e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                  6.2265e-13 ***
Materials.Science                            3.3053e-02 *
Mathematics                                  1.3746e-05 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   1.0681e-02 *
Social.Sciences                              4.3378e-01
Veterinary                                   4.3376e-03 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -182,077.2   Adj. Pseudo R2: 0.056282
           BIC:  365,300.4     Squared Cor.: 0.072158

In [92]:
# 直接把 4 个模型并排放在一起
tab_latex <- etable(model1, model2, model3, model4,
                    keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                    se = "hetero",
                    tex = TRUE,
                    digits = 3,
                    fitstat = ~ n + r2 + ar2) # 可选：指定要在底部报告的统计量（如样本量、R方、调整R方）

# 打印出可以直接复制到 LaTeX 的代码
cat(tab_latex)

\begingroup \centering \begin{tabular}{lcccc}    \tabularnewline \midrule \midrule    Dependent Variable: & \multicolumn{4}{c}{novel\_uzzi\_bin}\\    Model:                                              & (1)            & (2)            & (3)            & (4)\\      \midrule    \emph{Variables}\\    CoTypeCollaboration                                 & 0.168$^{***}$  & 0.176$^{***}$  & 0.144$^{***}$  & 0.100$^{***}$\\                                                           & (0.011)        & (0.011)        & (0.011)        & (0.011)\\       CoTypeParticipation                                 & 0.047$^{***}$  & 0.095$^{***}$  & 0.047$^{***}$  & 0.010\\                                                           & (0.014)        & (0.015)        & (0.015)        & (0.015)\\       Arts.and.Humanities                                 & 1.84$^{***}$   & 1.81$^{***}$   & 1.76$^{***}$   & 1.74$^{***}$\\                                                           & (0.072)        & (0.072)        & (0.073)        & (0.073)\\       Biochemistry..Genetics.and.Molecular.Biology        & 0.498$^{***}$  & 0.488$^{***}$  & 0.560$^{***}$  & 0.582$^{***}$\\                                                           & (0.012)        & (0.012)        & (0.013)        & (0.013)\\       Business..Management.and.Accounting                 & -0.428$^{***}$ & -0.391$^{***}$ & -0.345$^{***}$ & -0.357$^{***}$\\                                                           & (0.088)        & (0.088)        & (0.088)        & (0.088)\\       Chemical.Engineering                                & 0.131$^{***}$  & 0.118$^{***}$  & 0.128$^{***}$  & 0.135$^{***}$\\                                                           & (0.021)        & (0.021)        & (0.021)        & (0.021)\\       Chemistry                                           & 0.459$^{***}$  & 0.444$^{***}$  & 0.436$^{***}$  & 0.423$^{***}$\\                                                           & (0.011)        & (0.011)        & (0.011)        & (0.011)\\       Computer.Science                                    & 0.897$^{***}$  & 0.886$^{***}$  & 0.885$^{***}$  & 0.896$^{***}$\\                                                           & (0.039)        & (0.039)        & (0.039)        & (0.040)\\       Decision.Sciences                                   & 1.23$^{***}$   & 1.24$^{***}$   & 1.21$^{***}$   & 1.19$^{***}$\\                                                           & (0.187)        & (0.186)        & (0.188)        & (0.189)\\       Dentistry                                           & 1.99$^{***}$   & 1.99$^{***}$   & 1.93$^{***}$   & 1.90$^{***}$\\                                                           & (0.135)        & (0.135)        & (0.135)        & (0.136)\\       Earth.and.Planetary.Sciences                        & 0.737$^{***}$  & 0.718$^{***}$  & 0.708$^{***}$  & 0.710$^{***}$\\                                                           & (0.015)        & (0.015)        & (0.015)        & (0.015)\\       Economics..Econometrics.and.Finance                 & -0.125         & -0.175         & -0.146         & -0.113\\                                                           & (0.298)        & (0.297)        & (0.293)        & (0.295)\\       Energy                                              & 0.173$^{***}$  & 0.167$^{***}$  & 0.216$^{***}$  & 0.200$^{***}$\\                                                           & (0.018)        & (0.018)        & (0.018)        & (0.018)\\       Engineering                                         & 0.340$^{***}$  & 0.328$^{***}$  & 0.301$^{***}$  & 0.284$^{***}$\\                                                           & (0.010)        & (0.010)        & (0.010)        & (0.010)\\       Immunology.and.Microbiology                         & 0.100$^{***}$  & 0.104$^{***}$  & 0.170$^{***}$  & 0.193$^{***}$\\                                                           & (0.026)        & (0.026)        & (0.027)        & (0.027)\\       Materials.Science                                   & 0.025$^{***}$  & 0.017$^{*}$    & 0.002          & -0.021$^{**}$\\                                                           & (0.009)        & (0.010)        & (0.010)        & (0.010)\\       Mathematics                                         & 0.563$^{***}$  & 0.544$^{***}$  & 0.566$^{***}$  & 0.546$^{***}$\\                                                           & (0.124)        & (0.123)        & (0.124)        & (0.125)\\       Medicine                                            & 0.769$^{***}$  & 0.771$^{***}$  & 0.805$^{***}$  & 0.824$^{***}$\\                                                           & (0.015)        & (0.015)        & (0.015)        & (0.015)\\       Neuroscience                                        & 0.460$^{***}$  & 0.460$^{***}$  & 0.514$^{***}$  & 0.518$^{***}$\\                                                           & (0.032)        & (0.032)        & (0.032)        & (0.032)\\       Nursing                                             & 1.15$^{***}$   & 1.14$^{***}$   & 1.14$^{***}$   & 1.13$^{***}$\\                                                           & (0.043)        & (0.043)        & (0.044)        & (0.044)\\       Pharmacology..Toxicology.and.Pharmaceutics          & 0.918$^{***}$  & 0.898$^{***}$  & 0.892$^{***}$  & 0.892$^{***}$\\                                                           & (0.048)        & (0.048)        & (0.048)        & (0.048)\\       Physics.and.Astronomy                               & -0.258$^{***}$ & -0.245$^{***}$ & -0.293$^{***}$ & -0.309$^{***}$\\                                                           & (0.011)        & (0.011)        & (0.011)        & (0.011)\\       Psychology                                          & 0.350$^{**}$   & 0.334$^{**}$   & 0.371$^{**}$   & 0.396$^{**}$\\                                                           & (0.151)        & (0.152)        & (0.153)        & (0.155)\\       Social.Sciences                                     & 0.191          & 0.200          & 0.155          & 0.123\\                                                           & (0.161)        & (0.159)        & (0.157)        & (0.157)\\       Veterinary                                          & 0.572$^{***}$  & 0.583$^{***}$  & 0.593$^{***}$  & 0.590$^{***}$\\                                                           & (0.204)        & (0.206)        & (0.205)        & (0.207)\\       lnnum\_author                                       &                & -0.131$^{***}$ & -0.069$^{***}$ & -0.087$^{***}$\\                                                           &                & (0.007)        & (0.007)        & (0.007)\\       internationalinternational                          &                & -0.008         & -0.031$^{***}$ & -0.045$^{***}$\\                                                           &                & (0.009)        & (0.010)        & (0.010)\\       lnnum\_reference                                    &                & -0.006         & 0.061$^{***}$  & 0.059$^{***}$\\                                                           &                & (0.008)        & (0.009)        & (0.009)\\       num\_fac                                            &                & 0.051$^{***}$  & 0.059$^{***}$  & 0.063$^{***}$\\                                                           &                & (0.007)        & (0.007)        & (0.007)\\       SDGTrue                                             &                & 0.088$^{***}$  & 0.092$^{***}$  & 0.094$^{***}$\\                                                           &                & (0.008)        & (0.008)        & (0.008)\\       lnmean\_career\_age                                 &                & -0.007         & 0.033$^{**}$   & 0.012\\                                                           &                & (0.013)        & (0.013)        & (0.013)\\       lnex\_ld\_avg\_avgimpact                            &                &                & -0.265$^{***}$ & -0.270$^{***}$\\                                                           &                &                & (0.007)        & (0.007)\\       lnex\_ld\_avg\_insthindex                           &                &                & -0.050$^{***}$ & -0.051$^{***}$\\                                                           &                &                & (0.007)        & (0.008)\\       ex\_ld\_bin\_gsGlobalNorth                          &                &                & 0.320$^{***}$  & 0.310$^{***}$\\                                                           &                &                & (0.017)        & (0.018)\\       ex\_ld\_bin\_sameCSame                              &                &                & -0.088$^{***}$ & -0.063$^{***}$\\                                                           &                &                & (0.009)        & (0.009)\\       knowledge\_proximity\_mean                          &                &                & -0.537$^{***}$ & -0.519$^{***}$\\                                                           &                &                & (0.157)        & (0.159)\\       lnex\_ld\_avg\_before\_year\_prod\_fac              &                &                &                & -0.049$^{***}$\\                                                           &                &                &                & (0.005)\\       ex\_ld\_max\_before\_year\_with\_ih\_binTrue        &                &                &                & 0.341$^{***}$\\                                                           &                &                &                & (0.011)\\       \midrule    \emph{Fixed-effects}\\    PublishedYear                                       & Yes            & Yes            & Yes            & Yes\\      \midrule    \emph{Fit statistics}\\    Observations                                        & 294,879        & 294,879        & 294,879        & 294,879\\      \midrule \midrule    \multicolumn{5}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\    \multicolumn{5}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\ \end{tabular} \par\endgroup