In [2]:
library("lme4")
library("margins")
library("stargazer")
library("emmeans")
library("ggeffects")
library("broom")
library("broom.mixed")
library("MASS")
library("pscl")
library("fixest")
library("marginaleffects")
library("modelsummary")
library("glmmTMB")
library("dplyr")

In [3]:
packageVersion("marginaleffects")

[1] ‘0.25.1’

In [4]:
main_path <- "/home/20250114zmz_kd/"
data <- read.csv(paste0(main_path, "GraduationPaper/RevisetoJournal/99931-LastAuthorMergeSimilarity.csv"))
dim(data)

[1] 317960     92

In [5]:
print(names(data))

 [1] "X"
 [2] "work_id"
 [3] "PublishedYear"
 [4] "Facility"
 [5] "num_fac"
 [6] "paper_type"
 [7] "paper_language"
 [8] "novel_uzzi"
 [9] "novel_uzzi_bin"
[10] "num_fac_scientist"
[11] "ratio_fac_scientist"
[12] "bin_fac_scientist"
[13] "text_fac_scientist"
[14] "fac_scientist_team"
[15] "num_leader"
[16] "ratio_leader"
[17] "bin_leader"
[18] "fac_scientist_lead_num"
[19] "fac_scientist_lead_ratio"
[20] "fac_scientist_lead_bin"
[21] "fac_scientist_lead_text"
[22] "CoType"
[23] "CoType_Collaboration"
[24] "CoType_Participation"
[25] "CoType_Service"
[26] "lnnum_author"
[27] "lnnum_inst"
[28] "international"
[29] "lnnum_country"
[30] "lnnum_reference"
[31] "open_access"
[32] "RaoStirling"
[33] "SDG"
[34] "lntimescited5"
[35] "lntimescited10"
[36] "lntimescitedall"
[37] "lnab_length"
[38] "lnmean_career_age"
[39] "last_author"
[40] "lnlast_avgimpact"
[41] "last_SameCountry"
[42] "last_GlobalSouth"
[43] "lnlast_insthindex"
[44] "lnlast_before_year_prod_fac"
[45] "last_before_year_with_ih_bin"
[46] "last_before_year_co_lead_bin"
[47] "last_before_year_participation_bin"
[48] "Agricultural.and.Biological.Sciences"
[49] "Arts.and.Humanities"
[50] "Biochemistry..Genetics.and.Molecular.Biology"
[51] "Business..Management.and.Accounting"
[52] "Chemical.Engineering"
[53] "Chemistry"
[54] "Computer.Science"
[55] "Decision.Sciences"
[56] "Dentistry"
[57] "Earth.and.Planetary.Sciences"
[58] "Economics..Econometrics.and.Finance"
[59] "Energy"
[60] "Engineering"
[61] "Environmental.Science"
[62] "Health.Professions"
[63] "Immunology.and.Microbiology"
[64] "Materials.Science"
[65] "Mathematics"
[66] "Medicine"
[67] "Neuroscience"
[68] "Nursing"
[69] "Pharmacology..Toxicology.and.Pharmaceutics"
[70] "Physics.and.Astronomy"
[71] "Psychology"
[72] "Social.Sciences"
[73] "Veterinary"
[74] "domain_Health.Sciences"
[75] "domain_Life.Sciences"
[76] "domain_Physical.Sciences"
[77] "domain_Social.Sciences"
[78] "sum"
[79] "num_author"
[80] "num_inst"
[81] "num_country"
[82] "num_reference"
[83] "timescited5"
[84] "timescited10"
[85] "timescitedall"
[86] "ab_length"
[87] "mean_career_age"
[88] "last_avgimpact"
[89] "last_insthindex"
[90] "last_before_year_prod_fac"
[91] "knowledge_proximity_mean"
[92] "knowledge_proximity_max"

In [6]:
colSums(is.na(data))

                                           X
                                           0
                                     work_id
                                           0
                               PublishedYear
                                           0
                                    Facility
                                           0
                                     num_fac
                                           0
                                  paper_type
                                           0
                              paper_language
                                           0
                                  novel_uzzi
                                        2598
                              novel_uzzi_bin
                                           0
                           num_fac_scientist
                                           0
                         ratio_fac_scientist
                                           0
                           bin_fac_scientist
                                           0
                          text_fac_scientist
                                           0
                          fac_scientist_team
                                           0
                                  num_leader
                                           0
                                ratio_leader
                                           0
                                  bin_leader
                                           0
                      fac_scientist_lead_num
                                           0
                    fac_scientist_lead_ratio
                                           0
                      fac_scientist_lead_bin
                                           0
                     fac_scientist_lead_text
                                           0
                                      CoType
                                           0
                        CoType_Collaboration
                                           0
                        CoType_Participation
                                           0
                              CoType_Service
                                           0
                                lnnum_author
                                           0
                                  lnnum_inst
                                           0
                               international
                                           0
                               lnnum_country
                                           0
                             lnnum_reference
                                           0
                                 open_access
                                           0
                                 RaoStirling
                                           0
                                         SDG
                                           0
                               lntimescited5
                                       14707
                              lntimescited10
                                       12903
                             lntimescitedall
                                           0
                                 lnab_length
                                           0
                           lnmean_career_age
                                           0
                                 last_author
                                           0
                            lnlast_avgimpact
                                           0
                            last_SameCountry
                                           0
                            last_GlobalSouth
                                           0
                           lnlast_insthindex
                                           0
                 lnlast_before_year_prod_fac
                                           0
                last_before_year_with_ih_bin
                                           0
                last_before_year_co_lead_bin
                                           0
          last_before_year_participation_bin
                                           0
        Agricultural.and.Biological.Sciences
                                           0
                         Arts.and.Humanities
                                           0
Biochemistry..Genetics.and.Molecular.Biology
                                           0
         Business..Management.and.Accounting
                                           0
                        Chemical.Engineering
                                           0
                                   Chemistry
                                           0
                            Computer.Science
                                           0
                           Decision.Sciences
                                           0
                                   Dentistry
                                           0
                Earth.and.Planetary.Sciences
                                           0
         Economics..Econometrics.and.Finance
                                           0
                                      Energy
                                           0
                                 Engineering
                                           0
                       Environmental.Science
                                           0
                          Health.Professions
                                           0
                 Immunology.and.Microbiology
                                           0
                           Materials.Science
                                           0
                                 Mathematics
                                           0
                                    Medicine
                                           0
                                Neuroscience
                                           0
                                     Nursing
                                           0
  Pharmacology..Toxicology.and.Pharmaceutics
                                           0
                       Physics.and.Astronomy
                                           0
                                  Psychology
                                           0
                             Social.Sciences
                                           0
                                  Veterinary
                                           0
                      domain_Health.Sciences
                                           0
                        domain_Life.Sciences
                                           0
                    domain_Physical.Sciences
                                           0
                      domain_Social.Sciences
                                           0
                                         sum
                                           0
                                  num_author
                                           0
                                    num_inst
                                           0
                                 num_country
                                           0
                               num_reference
                                           0
                                 timescited5
                                       14707
                                timescited10
                                       12903
                               timescitedall
                                           0
                                   ab_length
                                           0
                             mean_career_age
                                           0
                              last_avgimpact
                                         211
                             last_insthindex
                                           0
                   last_before_year_prod_fac
                                           0
                    knowledge_proximity_mean
                                       42737
                     knowledge_proximity_max
                                       42737

In [7]:
# 把所有无限值替换成 NA
data[sapply(data, is.infinite)] <- NA

In [8]:
# data <- data %>% filter(!is.na(mean_career_age))
# data <- data %>% filter(!is.na(frac_hype_words))
# data <- data %>% filter(!is.na(source_hindex))
# data <- data %>% filter(!is.na(open_access))
# dim(data)

In [9]:
# 找出所有包含无限值的行和列
inf_mask <- sapply(data, function(col) is.infinite(col))
rows_with_inf <- apply(inf_mask, 1, any)  # 哪些行至少有一个Inf
cols_with_inf <- colnames(data)[apply(inf_mask, 2, any)]  # 哪些列有Inf

# 打印包含无限值的行数和列名
cat("包含无限值的行数:", sum(rows_with_inf), "\n")
cat("包含无限值的列名:", paste(cols_with_inf, collapse = ", "), "\n")

# 查看这些行具体内容
data_filt_with_inf <- data[rows_with_inf, c(cols_with_inf), drop=FALSE]
print(data_filt_with_inf)

包含无限值的行数: 0
包含无限值的列名:
data frame with 0 columns and 0 rows

In [10]:
data$Facility <- as.factor(data$Facility)

In [11]:
data$CoType <- factor(data$CoType)
data <- within(data, CoType <- relevel(CoType, ref = 'Service'))
data$paper_type <- factor(data$paper_type)
data <- within(data, paper_type <- relevel(paper_type, ref = 'review'))
data$text_fac_scientist <- factor(data$text_fac_scientist)
data <- within(data, text_fac_scientist <- relevel(text_fac_scientist, ref = 'NonStaffPart'))
data$fac_scientist_lead_text <- factor(data$fac_scientist_lead_text)
data <- within(data, fac_scientist_lead_text <- relevel(fac_scientist_lead_text, ref = 'NonStaffLead'))
data$open_access <- factor(data$open_access)
data <- within(data, open_access <- relevel(open_access, ref = 'False'))
data$SDG <- factor(data$SDG)
data <- within(data, SDG <- relevel(SDG, ref = 'False'))
data$last_SameCountry <- factor(data$last_SameCountry)
data <- within(data, last_SameCountry <- relevel(last_SameCountry, ref = 'NonSame'))
data$last_GlobalSouth <- factor(data$last_GlobalSouth)
data <- within(data, last_GlobalSouth <- relevel(last_GlobalSouth, ref = 'GlobalSouth'))
data$last_before_year_with_ih_bin <- factor(data$last_before_year_with_ih_bin)
data <- within(data, last_before_year_with_ih_bin <- relevel(last_before_year_with_ih_bin, ref = 'False'))
data$last_before_year_participation_bin <- factor(data$last_before_year_participation_bin)
data <- within(data, last_before_year_participation_bin <- relevel(last_before_year_participation_bin, ref = 'False'))
data$last_before_year_co_lead_bin <- factor(data$last_before_year_co_lead_bin)
data <- within(data, last_before_year_co_lead_bin <- relevel(last_before_year_co_lead_bin, ref = 'False'))
data$international <- factor(data$international)
data <- within(data, international <- relevel(international, ref = 'domestic'))

In [12]:
paper_level <- "lnnum_author + international + lnnum_reference + num_fac + SDG + lnmean_career_age"
ex_controls <- "lnlast_avgimpact + lnlast_insthindex + last_GlobalSouth + last_SameCountry + knowledge_proximity_mean"
moderating <- "lnlast_before_year_prod_fac + last_before_year_with_ih_bin"
moderating2 <- "lnlast_before_year_prod_fac + last_before_year_participation_bin"
moderating3 <- "lnlast_before_year_prod_fac + last_before_year_co_lead_bin"
disciplines <- "Agricultural.and.Biological.Sciences + Arts.and.Humanities + Biochemistry..Genetics.and.Molecular.Biology + Business..Management.and.Accounting + Chemical.Engineering + 
 Chemistry + Computer.Science + Decision.Sciences + Dentistry + Earth.and.Planetary.Sciences + 
Economics..Econometrics.and.Finance + Energy + Engineering + Environmental.Science + Health.Professions + 
Immunology.and.Microbiology + Materials.Science + Mathematics + Medicine + Neuroscience + Nursing +
Pharmacology..Toxicology.and.Pharmaceutics + Physics.and.Astronomy + Psychology + Social.Sciences + Veterinary "

In [13]:
paper_vars <- c("lnnum_author", "international", "lnnum_reference", "num_fac", "SDG", "lnmean_career_age")
ex_vars <- c("lnlast_avgimpact", "lnlast_insthindex", "last_GlobalSouth", "last_SameCountry", "knowledge_proximity_mean")
moderating_var <- c("lnlast_before_year_prod_fac", "last_before_year_with_ih_bin")
moderating2_var <- c("lnlast_before_year_prod_fac", "last_before_year_participation_bin")
moderating3_var <- c("lnlast_before_year_prod_fac", "last_before_year_co_lead_bin")
disciplines_vars <- c("Agricultural.and.Biological.Sciences", "Arts.and.Humanities", "Biochemistry..Genetics.and.Molecular.Biology", "Business..Management.and.Accounting",
                 "Chemical.Engineering", "Chemistry", "Computer.Science", "Decision.Sciences", "Dentistry",
                 "Earth.and.Planetary.Sciences", "Economics..Econometrics.and.Finance", "Energy", "Engineering",
                 "Environmental.Science + Health.Professions", "Immunology.and.Microbiology", "Materials.Science", "Mathematics",
                 "Medicine", "Neuroscience", "Nursing", "Pharmacology..Toxicology.and.Pharmaceutics", "Physics.and.Astronomy",
                 "Psychology", "Social.Sciences", "Veterinary")

# H1:With > Without

In [14]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ text_fac_scientist + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_total_bin <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_total_bin)

NOTE: 42,366 observations removed because of NA values (LHS: 42,366, RHS: 42,366, Fixed-effects: 42,366).

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 273,125
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
text_fac_scientistStaffPart                   0.081315   0.010400   7.819061
lnnum_author                                 -0.125868   0.007499 -16.785508
internationalinternational                   -0.046838   0.009772  -4.792872
lnnum_reference                               0.056831   0.009042   6.284937
num_fac                                       0.076664   0.006908  11.097094
SDGTrue                                       0.075029   0.008520   8.806287
lnmean_career_age                            -0.017545   0.013446  -1.304821
lnlast_avgimpact                             -0.244643   0.006355 -38.496044
lnlast_insthindex                            -0.026812   0.005933  -4.518741
last_GlobalSouthGlobalNorth                   0.305341   0.017870  17.086586
last_SameCountrySame                         -0.078511   0.009586  -8.189982
knowledge_proximity_mean                     -0.682773   0.153167  -4.457704
lnlast_before_year_prod_fac                  -0.043015   0.004055 -10.607076
last_before_year_with_ih_binTrue              0.212098   0.011332  18.716368
Agricultural.and.Biological.Sciences          0.790008   0.025549  30.921244
Arts.and.Humanities                           1.809415   0.079931  22.637337
Biochemistry..Genetics.and.Molecular.Biology  0.631548   0.013171  47.951620
Business..Management.and.Accounting          -0.254675   0.088242  -2.886104
Chemical.Engineering                          0.195513   0.021683   9.016768
Chemistry                                     0.477131   0.011620  41.061524
Computer.Science                              0.928567   0.042707  21.742915
Decision.Sciences                             1.196520   0.201185   5.947375
Dentistry                                     1.957274   0.142649  13.720915
Earth.and.Planetary.Sciences                  0.759502   0.016267  46.690521
Economics..Econometrics.and.Finance          -0.506834   0.394378  -1.285148
Energy                                        0.267466   0.018636  14.352394
Engineering                                   0.333250   0.010938  30.468187
Environmental.Science                         0.537385   0.018747  28.664381
Health.Professions                            1.584502   0.138246  11.461441
Immunology.and.Microbiology                   0.249833   0.028967   8.624800
Materials.Science                             0.055493   0.010340   5.367019
Mathematics                                   0.604665   0.129641   4.664162
Medicine                                      0.850256   0.015715  54.105362
Neuroscience                                  0.503185   0.034493  14.588099
Nursing                                       1.070016   0.046613  22.955253
Pharmacology..Toxicology.and.Pharmaceutics    0.878511   0.050978  17.233215
Physics.and.Astronomy                        -0.250367   0.011928 -20.989284
Psychology                                    0.422374   0.166609   2.535117
Social.Sciences                              -0.044215   0.174581  -0.253266
Veterinary                                    0.551850   0.231115   2.387770
                                               Pr(>|z|)
text_fac_scientistStaffPart                  5.3219e-15 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   1.6441e-06 ***
lnnum_reference                              3.2799e-10 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            1.9195e-01
lnlast_avgimpact                              < 2.2e-16 ***
lnlast_insthindex                            6.2208e-06 ***
last_GlobalSouthGlobalNorth                   < 2.2e-16 ***
last_SameCountrySame                         2.6127e-16 ***
knowledge_proximity_mean                     8.2842e-06 ***
lnlast_before_year_prod_fac                   < 2.2e-16 ***
last_before_year_with_ih_binTrue              < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          3.9004e-03 **
Chemical.Engineering                          < 2.2e-16 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            2.7248e-09 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          1.9874e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                   < 2.2e-16 ***
Materials.Science                            8.0049e-08 ***
Mathematics                                  3.0988e-06 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   1.1241e-02 *
Social.Sciences                              8.0006e-01
Veterinary                                   1.6951e-02 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -166,724.1   Adj. Pseudo R2: 0.057939
           BIC:  334,587.3     Squared Cor.: 0.073806

In [15]:
# 每组 reg_class 的平均预测概率
pred_bin <- avg_predictions(model_total_bin, variables = "text_fac_scientist")
pred_bin

  text_fac_scientist estimate  std.error  statistic p.value      s.value
1 NonStaffPart       0.3465627 0.02960296 11.70703  1.173205e-31 102.7493
2 StaffPart          0.3637671 0.03025959 12.02155  2.737939e-33 108.1705
  conf.low  conf.high
1 0.2885419 0.4045834
2 0.3044594 0.4230748

In [16]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_pred.csv")
# write.csv(pred_bin, fname, row.names = FALSE)

In [17]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_total_bin,
                           keep = c("text_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   text\_fac\_scientistStaffPart                & 0.081$^{***}$\\
                                                & (0.010)\\
   lnnum\_author                                & -0.126$^{***}$\\
                                                & (0.007)\\
   internationalinternational                   & -0.047$^{***}$\\
                                                & (0.010)\\
   lnnum\_reference                             & 0.057$^{***}$\\
                                                & (0.009)\\
   num\_fac                                     & 0.077$^{***}$\\
                                                & (0.007)\\
   SDGTrue                                      & 0.075$^{***}$\\
                                                & (0.009)\\
   lnmean\_career\_age                          & -0.018\\
                                                & (0.013)\\
   lnlast\_avgimpact                            & -0.245$^{***}$\\
                                                & (0.006)\\
   lnlast\_insthindex                           & -0.027$^{***}$\\
                                                & (0.006)\\
   last\_GlobalSouthGlobalNorth                 & 0.305$^{***}$\\
                                                & (0.018)\\
   last\_SameCountrySame                        & -0.079$^{***}$\\
                                                & (0.010)\\
   knowledge\_proximity\_mean                   & -0.683$^{***}$\\
                                                & (0.153)\\
   lnlast\_before\_year\_prod\_fac              & -0.043$^{***}$\\
                                                & (0.004)\\
   last\_before\_year\_with\_ih\_binTrue        & 0.212$^{***}$\\
                                                & (0.011)\\
   Agricultural.and.Biological.Sciences         & 0.790$^{***}$\\
                                                & (0.025)\\
   Arts.and.Humanities                          & 1.81$^{***}$\\
                                                & (0.080)\\
   Biochemistry..Genetics.and.Molecular.Biology & 0.632$^{***}$\\
                                                & (0.013)\\
   Business..Management.and.Accounting          & -0.255$^{***}$\\
                                                & (0.088)\\
   Chemical.Engineering                         & 0.196$^{***}$\\
                                                & (0.022)\\
   Chemistry                                    & 0.477$^{***}$\\
                                                & (0.012)\\
   Computer.Science                             & 0.929$^{***}$\\
                                                & (0.043)\\
   Decision.Sciences                            & 1.20$^{***}$\\
                                                & (0.201)\\
   Dentistry                                    & 1.96$^{***}$\\
                                                & (0.143)\\
   Earth.and.Planetary.Sciences                 & 0.760$^{***}$\\
                                                & (0.016)\\
   Economics..Econometrics.and.Finance          & -0.507\\
                                                & (0.394)\\
   Energy                                       & 0.267$^{***}$\\
                                                & (0.019)\\
   Engineering                                  & 0.333$^{***}$\\
                                                & (0.011)\\
   Immunology.and.Microbiology                  & 0.250$^{***}$\\
                                                & (0.029)\\
   Materials.Science                            & 0.056$^{***}$\\
                                                & (0.010)\\
   Mathematics                                  & 0.605$^{***}$\\
                                                & (0.130)\\
   Medicine                                     & 0.850$^{***}$\\
                                                & (0.016)\\
   Neuroscience                                 & 0.503$^{***}$\\
                                                & (0.035)\\
   Nursing                                      & 1.07$^{***}$\\
                                                & (0.047)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 0.879$^{***}$\\
                                                & (0.051)\\
   Physics.and.Astronomy                        & -0.250$^{***}$\\
                                                & (0.012)\\
   Psychology                                   & 0.422$^{**}$\\
                                                & (0.167)\\
   Social.Sciences                              & -0.044\\
                                                & (0.175)\\
   Veterinary                                   & 0.552$^{**}$\\
                                                & (0.231)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 273,125\\
   Squared Correlation                          & 0.07381\\
   Pseudo R$^2$                                 & 0.05845\\
   BIC                                          & 334,587.3\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [18]:
margins_eff_bin <- avg_comparisons(model_total_bin, variables = "text_fac_scientist", comparison = 'ratio')
margins_eff_bin

  term               contrast                             estimate std.error
1 text_fac_scientist mean(StaffPart) / mean(NonStaffPart) 1.049643 0.006907395
  statistic p.value s.value conf.low conf.high predicted_lo predicted_hi
1 151.9593  0       Inf     1.036105 1.063181  0.261085     0.277074
  predicted
1 0.261085

In [19]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_comp_ratio.csv")
# write.csv(margins_eff_bin, fname, row.names = FALSE)

# H1 different disciplines

In [20]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ text_fac_scientist + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_ps_bin <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Physical.Sciences==1), ], family = binomial("logit"), vcov = "hetero")
summary(model_ps_bin)

NOTE: 34,712 observations removed because of NA values (LHS: 34,712, RHS: 34,712, Fixed-effects: 34,712).

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 236,379
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
text_fac_scientistStaffPart                   0.070454   0.010947   6.435783
lnnum_author                                 -0.202150   0.008420 -24.009627
internationalinternational                   -0.080801   0.010669  -7.573755
lnnum_reference                               0.074842   0.009614   7.784900
num_fac                                       0.112658   0.007418  15.186707
SDGTrue                                       0.025031   0.009293   2.693466
lnmean_career_age                            -0.065049   0.014561  -4.467446
lnlast_avgimpact                             -0.185837   0.007005 -26.530700
lnlast_insthindex                            -0.012331   0.006467  -1.906658
last_GlobalSouthGlobalNorth                   0.292991   0.019176  15.279362
last_SameCountrySame                         -0.081066   0.010499  -7.721695
knowledge_proximity_mean                     -0.181849   0.167775  -1.083887
lnlast_before_year_prod_fac                  -0.031128   0.004408  -7.062396
last_before_year_with_ih_binTrue              0.188664   0.012483  15.113885
Agricultural.and.Biological.Sciences          1.070947   0.039121  27.375533
Arts.and.Humanities                           1.828456   0.082810  22.080217
Biochemistry..Genetics.and.Molecular.Biology  0.790971   0.014840  53.299852
Business..Management.and.Accounting          -0.227355   0.087798  -2.589516
Chemical.Engineering                          0.203686   0.021822   9.334023
Chemistry                                     0.434827   0.012511  34.756184
Computer.Science                              0.861209   0.043620  19.743255
Decision.Sciences                             1.282788   0.205160   6.252612
Dentistry                                     2.451430   0.216091  11.344451
Earth.and.Planetary.Sciences                  0.779075   0.016543  47.094410
Economics..Econometrics.and.Finance          -0.530154   0.396062  -1.338562
Energy                                        0.261243   0.019042  13.719377
Engineering                                   0.352369   0.011618  30.329945
Environmental.Science                         0.449910   0.020195  22.278523
Health.Professions                            1.824467   0.158683  11.497557
Immunology.and.Microbiology                   0.561207   0.076056   7.378844
Materials.Science                             0.023253   0.011337   2.051149
Mathematics                                   0.588906   0.130540   4.511321
Medicine                                      0.952775   0.023893  39.877459
Neuroscience                                  0.706192   0.061949  11.399622
Nursing                                       1.367775   0.072630  18.832038
Pharmacology..Toxicology.and.Pharmaceutics    0.799105   0.070515  11.332373
Physics.and.Astronomy                        -0.238735   0.012589 -18.964201
Psychology                                   -0.506941   0.295376  -1.716257
Social.Sciences                               0.092699   0.209629   0.442204
Veterinary                                    0.064158   0.560156   0.114536
                                               Pr(>|z|)
text_fac_scientistStaffPart                  1.2284e-10 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   3.6259e-14 ***
lnnum_reference                              6.9769e-15 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                      7.0713e-03 **
lnmean_career_age                            7.9159e-06 ***
lnlast_avgimpact                              < 2.2e-16 ***
lnlast_insthindex                            5.6565e-02 .
last_GlobalSouthGlobalNorth                   < 2.2e-16 ***
last_SameCountrySame                         1.1479e-14 ***
knowledge_proximity_mean                     2.7841e-01
lnlast_before_year_prod_fac                  1.6366e-12 ***
last_before_year_with_ih_binTrue              < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          9.6111e-03 **
Chemical.Engineering                          < 2.2e-16 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            4.0364e-10 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          1.8071e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                  1.5967e-13 ***
Materials.Science                            4.0252e-02 *
Mathematics                                  6.4425e-06 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   8.6115e-02 .
Social.Sciences                              6.5834e-01
Veterinary                                   9.0881e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -142,057.7   Adj. Pseudo R2: 0.061991
           BIC:  285,241.4     Squared Cor.: 0.078277

In [21]:
margins_eff_ps_bin <- avg_comparisons(model_ps_bin, variables = "text_fac_scientist", comparison = 'ratio')
margins_eff_ps_bin

  term               contrast                             estimate std.error
1 text_fac_scientist mean(StaffPart) / mean(NonStaffPart) 1.043481 0.007211544
  statistic p.value s.value conf.low conf.high predicted_lo predicted_hi
1 144.6959  0       Inf     1.029347 1.057615  0.2640665    0.2779838
  predicted
1 0.2640665

In [22]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_ps_comp_ratio.csv")
# write.csv(margins_eff_ps_bin, fname, row.names = FALSE)

In [23]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_ps_bin,
                           keep = c("text_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   text\_fac\_scientistStaffPart                & 0.070$^{***}$\\
                                                & (0.011)\\
   lnnum\_author                                & -0.202$^{***}$\\
                                                & (0.008)\\
   internationalinternational                   & -0.081$^{***}$\\
                                                & (0.011)\\
   lnnum\_reference                             & 0.075$^{***}$\\
                                                & (0.010)\\
   num\_fac                                     & 0.113$^{***}$\\
                                                & (0.007)\\
   SDGTrue                                      & 0.025$^{***}$\\
                                                & (0.009)\\
   lnmean\_career\_age                          & -0.065$^{***}$\\
                                                & (0.015)\\
   lnlast\_avgimpact                            & -0.186$^{***}$\\
                                                & (0.007)\\
   lnlast\_insthindex                           & -0.012$^{*}$\\
                                                & (0.006)\\
   last\_GlobalSouthGlobalNorth                 & 0.293$^{***}$\\
                                                & (0.019)\\
   last\_SameCountrySame                        & -0.081$^{***}$\\
                                                & (0.011)\\
   knowledge\_proximity\_mean                   & -0.182\\
                                                & (0.168)\\
   lnlast\_before\_year\_prod\_fac              & -0.031$^{***}$\\
                                                & (0.004)\\
   last\_before\_year\_with\_ih\_binTrue        & 0.189$^{***}$\\
                                                & (0.013)\\
   Agricultural.and.Biological.Sciences         & 1.07$^{***}$\\
                                                & (0.039)\\
   Arts.and.Humanities                          & 1.83$^{***}$\\
                                                & (0.083)\\
   Biochemistry..Genetics.and.Molecular.Biology & 0.791$^{***}$\\
                                                & (0.015)\\
   Business..Management.and.Accounting          & -0.227$^{***}$\\
                                                & (0.088)\\
   Chemical.Engineering                         & 0.204$^{***}$\\
                                                & (0.022)\\
   Chemistry                                    & 0.435$^{***}$\\
                                                & (0.013)\\
   Computer.Science                             & 0.861$^{***}$\\
                                                & (0.044)\\
   Decision.Sciences                            & 1.28$^{***}$\\
                                                & (0.205)\\
   Dentistry                                    & 2.45$^{***}$\\
                                                & (0.216)\\
   Earth.and.Planetary.Sciences                 & 0.779$^{***}$\\
                                                & (0.017)\\
   Economics..Econometrics.and.Finance          & -0.530\\
                                                & (0.396)\\
   Energy                                       & 0.261$^{***}$\\
                                                & (0.019)\\
   Engineering                                  & 0.352$^{***}$\\
                                                & (0.012)\\
   Immunology.and.Microbiology                  & 0.561$^{***}$\\
                                                & (0.076)\\
   Materials.Science                            & 0.023$^{**}$\\
                                                & (0.011)\\
   Mathematics                                  & 0.589$^{***}$\\
                                                & (0.131)\\
   Medicine                                     & 0.953$^{***}$\\
                                                & (0.024)\\
   Neuroscience                                 & 0.706$^{***}$\\
                                                & (0.062)\\
   Nursing                                      & 1.37$^{***}$\\
                                                & (0.073)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 0.799$^{***}$\\
                                                & (0.070)\\
   Physics.and.Astronomy                        & -0.239$^{***}$\\
                                                & (0.013)\\
   Psychology                                   & -0.507$^{*}$\\
                                                & (0.295)\\
   Social.Sciences                              & 0.093\\
                                                & (0.210)\\
   Veterinary                                   & 0.064\\
                                                & (0.560)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 236,379\\
   Squared Correlation                          & 0.07828\\
   Pseudo R$^2$                                 & 0.06259\\
   BIC                                          & 285,241.4\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [24]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ text_fac_scientist + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_ls_bin <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Life.Sciences==1), ], family = binomial("logit"), vcov = "hetero")
summary(model_ls_bin)

NOTES: 13,892 observations removed because of NA values (LHS: 13,892, RHS: 13,892, Fixed-effects: 13,892).
       2 fixed-effects (4 observations) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 70,337
Fixed-effects: PublishedYear: 46
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
text_fac_scientistStaffPart                   0.113046   0.023331   4.845399
lnnum_author                                  0.180385   0.017241  10.462383
internationalinternational                    0.111894   0.018150   6.165011
lnnum_reference                               0.145338   0.018785   7.736957
num_fac                                      -0.060284   0.013161  -4.580447
SDGTrue                                       0.137956   0.015996   8.624487
lnmean_career_age                             0.098343   0.025046   3.926456
lnlast_avgimpact                             -0.438829   0.012450 -35.248358
lnlast_insthindex                            -0.021464   0.011375  -1.886897
last_GlobalSouthGlobalNorth                   0.115078   0.038683   2.974901
last_SameCountrySame                         -0.102851   0.017592  -5.846445
knowledge_proximity_mean                     -2.681323   0.274393  -9.771848
lnlast_before_year_prod_fac                  -0.076010   0.007758  -9.797353
last_before_year_with_ih_binTrue              0.284785   0.020238  14.071620
Agricultural.and.Biological.Sciences          0.424557   0.029950  14.175320
Arts.and.Humanities                           0.999703   0.313542   3.188416
Biochemistry..Genetics.and.Molecular.Biology -0.068237   0.031993  -2.132876
Business..Management.and.Accounting           0.188172   0.486831   0.386524
Chemical.Engineering                          0.345128   0.142328   2.424885
Chemistry                                     0.548503   0.024338  22.537054
Computer.Science                              0.664209   0.073446   9.043460
Decision.Sciences                            -0.079893   0.823527  -0.097013
Dentistry                                     0.649653   0.233723   2.779589
Earth.and.Planetary.Sciences                  0.845951   0.083219  10.165409
Energy                                        0.216525   0.065783   3.291510
Engineering                                   0.470741   0.032788  14.357074
Environmental.Science                        -0.041668   0.033178  -1.255894
Health.Professions                            0.831507   0.417426   1.991983
Immunology.and.Microbiology                   0.121423   0.031894   3.807067
Materials.Science                             0.135921   0.020625   6.590178
Mathematics                                   0.915496   0.583832   1.568082
Medicine                                      0.505469   0.019825  25.496337
Neuroscience                                  0.261426   0.036406   7.180815
Nursing                                       0.638328   0.056108  11.376837
Pharmacology..Toxicology.and.Pharmaceutics    0.590239   0.054228  10.884361
Physics.and.Astronomy                         0.382561   0.032095  11.919677
Psychology                                    0.438806   0.247041   1.776246
Social.Sciences                               0.175752   0.446056   0.394014
Veterinary                                    0.222532   0.264795   0.840390
                                               Pr(>|z|)
text_fac_scientistStaffPart                  1.2636e-06 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   7.0478e-10 ***
lnnum_reference                              1.0182e-14 ***
num_fac                                      4.6398e-06 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            8.6207e-05 ***
lnlast_avgimpact                              < 2.2e-16 ***
lnlast_insthindex                            5.9174e-02 .
last_GlobalSouthGlobalNorth                  2.9308e-03 **
last_SameCountrySame                         5.0219e-09 ***
knowledge_proximity_mean                      < 2.2e-16 ***
lnlast_before_year_prod_fac                   < 2.2e-16 ***
last_before_year_with_ih_binTrue              < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                          1.4305e-03 **
Biochemistry..Genetics.and.Molecular.Biology 3.2935e-02 *
Business..Management.and.Accounting          6.9911e-01
Chemical.Engineering                         1.5313e-02 *
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            9.2272e-01
Dentistry                                    5.4428e-03 **
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Energy                                       9.9651e-04 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                        2.0915e-01
Health.Professions                           4.6373e-02 *
Immunology.and.Microbiology                  1.4062e-04 ***
Materials.Science                            4.3930e-11 ***
Mathematics                                  1.1686e-01
Medicine                                      < 2.2e-16 ***
Neuroscience                                 6.9297e-13 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   7.5692e-02 .
Social.Sciences                              6.9357e-01
Veterinary                                   4.0069e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -45,596.2   Adj. Pseudo R2: 0.058894
           BIC:  92,141.1     Squared Cor.: 0.080757

In [25]:
margins_eff_ls_bin <- avg_comparisons(model_ls_bin, variables = "text_fac_scientist", comparison = 'ratio')
margins_eff_ls_bin

  term               contrast                             estimate std.error
1 text_fac_scientist mean(StaffPart) / mean(NonStaffPart) 1.056879 0.01393498
  statistic p.value s.value conf.low conf.high predicted_lo predicted_hi
1 75.84356  0       Inf     1.029567 1.084191  0.3070609    0.3316239
  predicted
1 0.3070609

In [26]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_ls_comp_ratio.csv")
# write.csv(margins_eff_ls_bin, fname, row.names = FALSE)

In [27]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_ls_bin,
                           keep = c("text_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   text\_fac\_scientistStaffPart                & 0.113$^{***}$\\
                                                & (0.023)\\
   lnnum\_author                                & 0.180$^{***}$\\
                                                & (0.017)\\
   internationalinternational                   & 0.112$^{***}$\\
                                                & (0.018)\\
   lnnum\_reference                             & 0.145$^{***}$\\
                                                & (0.019)\\
   num\_fac                                     & -0.060$^{***}$\\
                                                & (0.013)\\
   SDGTrue                                      & 0.138$^{***}$\\
                                                & (0.016)\\
   lnmean\_career\_age                          & 0.098$^{***}$\\
                                                & (0.025)\\
   lnlast\_avgimpact                            & -0.439$^{***}$\\
                                                & (0.012)\\
   lnlast\_insthindex                           & -0.021$^{*}$\\
                                                & (0.011)\\
   last\_GlobalSouthGlobalNorth                 & 0.115$^{***}$\\
                                                & (0.039)\\
   last\_SameCountrySame                        & -0.103$^{***}$\\
                                                & (0.018)\\
   knowledge\_proximity\_mean                   & -2.68$^{***}$\\
                                                & (0.274)\\
   lnlast\_before\_year\_prod\_fac              & -0.076$^{***}$\\
                                                & (0.008)\\
   last\_before\_year\_with\_ih\_binTrue        & 0.285$^{***}$\\
                                                & (0.020)\\
   Agricultural.and.Biological.Sciences         & 0.425$^{***}$\\
                                                & (0.030)\\
   Arts.and.Humanities                          & 1.00$^{***}$\\
                                                & (0.314)\\
   Biochemistry..Genetics.and.Molecular.Biology & -0.068$^{**}$\\
                                                & (0.032)\\
   Business..Management.and.Accounting          & 0.188\\
                                                & (0.487)\\
   Chemical.Engineering                         & 0.345$^{**}$\\
                                                & (0.142)\\
   Chemistry                                    & 0.549$^{***}$\\
                                                & (0.024)\\
   Computer.Science                             & 0.664$^{***}$\\
                                                & (0.073)\\
   Decision.Sciences                            & -0.080\\
                                                & (0.824)\\
   Dentistry                                    & 0.650$^{***}$\\
                                                & (0.234)\\
   Earth.and.Planetary.Sciences                 & 0.846$^{***}$\\
                                                & (0.083)\\
   Energy                                       & 0.217$^{***}$\\
                                                & (0.066)\\
   Engineering                                  & 0.471$^{***}$\\
                                                & (0.033)\\
   Immunology.and.Microbiology                  & 0.121$^{***}$\\
                                                & (0.032)\\
   Materials.Science                            & 0.136$^{***}$\\
                                                & (0.021)\\
   Mathematics                                  & 0.915\\
                                                & (0.584)\\
   Medicine                                     & 0.505$^{***}$\\
                                                & (0.020)\\
   Neuroscience                                 & 0.261$^{***}$\\
                                                & (0.036)\\
   Nursing                                      & 0.638$^{***}$\\
                                                & (0.056)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 0.590$^{***}$\\
                                                & (0.054)\\
   Physics.and.Astronomy                        & 0.383$^{***}$\\
                                                & (0.032)\\
   Psychology                                   & 0.439$^{*}$\\
                                                & (0.247)\\
   Social.Sciences                              & 0.176\\
                                                & (0.446)\\
   Veterinary                                   & 0.223\\
                                                & (0.265)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 70,337\\
   Squared Correlation                          & 0.08076\\
   Pseudo R$^2$                                 & 0.06062\\
   BIC                                          & 92,141.1\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [28]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ text_fac_scientist + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_hs_bin <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Health.Sciences==1), ], family = binomial("logit"), vcov = "hetero")
summary(model_hs_bin)

NOTES: 8,210 observations removed because of NA values (LHS: 8,210, RHS: 8,210, Fixed-effects: 8,210).
       7 fixed-effects (10 observations) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 28,986
Fixed-effects: PublishedYear: 38
Standard-errors: Heteroskedasticity-robust
                                               Estimate Std. Error     z value
text_fac_scientistStaffPart                    0.349758   0.040071    8.728414
lnnum_author                                   0.238587   0.027792    8.584726
internationalinternational                     0.073157   0.028046    2.608475
lnnum_reference                                0.145033   0.029727    4.878896
num_fac                                       -0.099153   0.022155   -4.475346
SDGTrue                                        0.210391   0.025213    8.344474
lnmean_career_age                              0.166853   0.040361    4.134024
lnlast_avgimpact                              -0.357707   0.019423  -18.416711
lnlast_insthindex                             -0.022833   0.017396   -1.312529
last_GlobalSouthGlobalNorth                    0.290200   0.061406    4.725904
last_SameCountrySame                          -0.116892   0.027605   -4.234440
knowledge_proximity_mean                      -0.731681   0.393248   -1.860610
lnlast_before_year_prod_fac                   -0.091502   0.012195   -7.503137
last_before_year_with_ih_binTrue               0.238105   0.032043    7.430892
Agricultural.and.Biological.Sciences          -0.094707   0.058881   -1.608442
Arts.and.Humanities                            0.916659   0.500739    1.830611
Biochemistry..Genetics.and.Molecular.Biology  -0.203990   0.031029   -6.574124
Business..Management.and.Accounting          -11.677409   0.064734 -180.389565
Chemical.Engineering                          -0.320192   0.293725   -1.090106
Chemistry                                      0.059099   0.040780    1.449224
Computer.Science                               0.548621   0.100947    5.434757
Decision.Sciences                             -0.157437   0.956831   -0.164540
Dentistry                                      0.895503   0.153526    5.832896
Earth.and.Planetary.Sciences                   0.865583   0.213757    4.049379
Energy                                        -0.014448   0.109679   -0.131731
Engineering                                    0.618056   0.059657   10.360246
Environmental.Science                          0.154192   0.064414    2.393781
Health.Professions                             0.695556   0.156128    4.455050
Immunology.and.Microbiology                   -0.331637   0.042447   -7.813011
Materials.Science                             -0.397229   0.040897   -9.713030
Mathematics                                    0.834182   0.629884    1.324343
Medicine                                       0.154840   0.087630    1.766983
Neuroscience                                   0.171485   0.067020    2.558722
Nursing                                        0.659391   0.074470    8.854475
Pharmacology..Toxicology.and.Pharmaceutics     0.617107   0.088976    6.935676
Physics.and.Astronomy                          0.039009   0.060882    0.640733
Psychology                                     0.775320   0.397511    1.950438
Social.Sciences                                0.653347   0.613688    1.064625
Veterinary                                     0.203844   0.234392    0.869673
                                               Pr(>|z|)
text_fac_scientistStaffPart                   < 2.2e-16 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   9.0947e-03 **
lnnum_reference                              1.0668e-06 ***
num_fac                                      7.6288e-06 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            3.5647e-05 ***
lnlast_avgimpact                              < 2.2e-16 ***
lnlast_insthindex                            1.8934e-01
last_GlobalSouthGlobalNorth                  2.2909e-06 ***
last_SameCountrySame                         2.2912e-05 ***
knowledge_proximity_mean                     6.2799e-02 .
lnlast_before_year_prod_fac                  6.2309e-14 ***
last_before_year_with_ih_binTrue             1.0787e-13 ***
Agricultural.and.Biological.Sciences         1.0774e-01
Arts.and.Humanities                          6.7159e-02 .
Biochemistry..Genetics.and.Molecular.Biology 4.8940e-11 ***
Business..Management.and.Accounting           < 2.2e-16 ***
Chemical.Engineering                         2.7567e-01
Chemistry                                    1.4728e-01
Computer.Science                             5.4871e-08 ***
Decision.Sciences                            8.6931e-01
Dentistry                                    5.4474e-09 ***
Earth.and.Planetary.Sciences                 5.1354e-05 ***
Energy                                       8.9520e-01
Engineering                                   < 2.2e-16 ***
Environmental.Science                        1.6676e-02 *
Health.Professions                           8.3874e-06 ***
Immunology.and.Microbiology                  5.5838e-15 ***
Materials.Science                             < 2.2e-16 ***
Mathematics                                  1.8539e-01
Medicine                                     7.7231e-02 .
Neuroscience                                 1.0506e-02 *
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics   4.0428e-12 ***
Physics.and.Astronomy                        5.2170e-01
Psychology                                   5.1124e-02 .
Social.Sciences                              2.8705e-01
Veterinary                                   3.8448e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -18,716.4   Adj. Pseudo R2: 0.05937
           BIC:  38,224.0     Squared Cor.: 0.084633

In [29]:
margins_eff_hs_bin <- avg_comparisons(model_hs_bin, variables = "text_fac_scientist", comparison = 'ratio')
margins_eff_hs_bin

  term               contrast                             estimate std.error
1 text_fac_scientist mean(StaffPart) / mean(NonStaffPart) 1.148676 0.03742427
  statistic p.value       s.value  conf.low conf.high predicted_lo predicted_hi
1 30.69336  6.980536e-207 684.8358 1.075326 1.222027  0.6688488    0.7413009
  predicted
1 0.6688488

In [30]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_hs_comp_ratio.csv")
# write.csv(margins_eff_hs_bin, fname, row.names = FALSE)

In [31]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_hs_bin,
                           keep = c("text_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   text\_fac\_scientistStaffPart                & 0.350$^{***}$\\
                                                & (0.040)\\
   lnnum\_author                                & 0.239$^{***}$\\
                                                & (0.028)\\
   internationalinternational                   & 0.073$^{***}$\\
                                                & (0.028)\\
   lnnum\_reference                             & 0.145$^{***}$\\
                                                & (0.030)\\
   num\_fac                                     & -0.099$^{***}$\\
                                                & (0.022)\\
   SDGTrue                                      & 0.210$^{***}$\\
                                                & (0.025)\\
   lnmean\_career\_age                          & 0.167$^{***}$\\
                                                & (0.040)\\
   lnlast\_avgimpact                            & -0.358$^{***}$\\
                                                & (0.019)\\
   lnlast\_insthindex                           & -0.023\\
                                                & (0.017)\\
   last\_GlobalSouthGlobalNorth                 & 0.290$^{***}$\\
                                                & (0.061)\\
   last\_SameCountrySame                        & -0.117$^{***}$\\
                                                & (0.028)\\
   knowledge\_proximity\_mean                   & -0.732$^{*}$\\
                                                & (0.393)\\
   lnlast\_before\_year\_prod\_fac              & -0.091$^{***}$\\
                                                & (0.012)\\
   last\_before\_year\_with\_ih\_binTrue        & 0.238$^{***}$\\
                                                & (0.032)\\
   Agricultural.and.Biological.Sciences         & -0.095\\
                                                & (0.059)\\
   Arts.and.Humanities                          & 0.917$^{*}$\\
                                                & (0.501)\\
   Biochemistry..Genetics.and.Molecular.Biology & -0.204$^{***}$\\
                                                & (0.031)\\
   Business..Management.and.Accounting          & -11.7$^{***}$\\
                                                & (0.065)\\
   Chemical.Engineering                         & -0.320\\
                                                & (0.294)\\
   Chemistry                                    & 0.059\\
                                                & (0.041)\\
   Computer.Science                             & 0.549$^{***}$\\
                                                & (0.101)\\
   Decision.Sciences                            & -0.157\\
                                                & (0.957)\\
   Dentistry                                    & 0.896$^{***}$\\
                                                & (0.154)\\
   Earth.and.Planetary.Sciences                 & 0.866$^{***}$\\
                                                & (0.214)\\
   Energy                                       & -0.014\\
                                                & (0.110)\\
   Engineering                                  & 0.618$^{***}$\\
                                                & (0.060)\\
   Immunology.and.Microbiology                  & -0.332$^{***}$\\
                                                & (0.042)\\
   Materials.Science                            & -0.397$^{***}$\\
                                                & (0.041)\\
   Mathematics                                  & 0.834\\
                                                & (0.630)\\
   Medicine                                     & 0.155$^{*}$\\
                                                & (0.088)\\
   Neuroscience                                 & 0.171$^{**}$\\
                                                & (0.067)\\
   Nursing                                      & 0.659$^{***}$\\
                                                & (0.074)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 0.617$^{***}$\\
                                                & (0.089)\\
   Physics.and.Astronomy                        & 0.039\\
                                                & (0.061)\\
   Psychology                                   & 0.775$^{*}$\\
                                                & (0.398)\\
   Social.Sciences                              & 0.653\\
                                                & (0.614)\\
   Veterinary                                   & 0.204\\
                                                & (0.234)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 28,986\\
   Squared Correlation                          & 0.08463\\
   Pseudo R$^2$                                 & 0.06317\\
   BIC                                          & 38,224.0\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [32]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ text_fac_scientist + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_nps_bin <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Physical.Sciences==0), ], family = binomial("logit"), vcov = "hetero")
summary(model_nps_bin)

NOTES: 7,654 observations removed because of NA values (LHS: 7,654, RHS: 7,654, Fixed-effects: 7,654).
       6 fixed-effects (11 observations) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 36,735
Fixed-effects: PublishedYear: 38
Standard-errors: Heteroskedasticity-robust
                                               Estimate Std. Error     z value
text_fac_scientistStaffPart                    0.299875   0.038622    7.764310
lnnum_author                                   0.260322   0.024324   10.702261
internationalinternational                     0.132678   0.025455    5.212175
lnnum_reference                               -0.048035   0.028696   -1.673936
num_fac                                       -0.117326   0.019919   -5.890094
SDGTrue                                        0.251293   0.022779   11.031759
lnmean_career_age                              0.148785   0.036698    4.054309
lnlast_avgimpact                              -0.559184   0.017659  -31.666369
lnlast_insthindex                             -0.057632   0.016065   -3.587425
last_GlobalSouthGlobalNorth                    0.243610   0.055419    4.395753
last_SameCountrySame                          -0.090625   0.024875   -3.643194
knowledge_proximity_mean                      -4.136717   0.421688   -9.809899
lnlast_before_year_prod_fac                   -0.068607   0.011190   -6.131101
last_before_year_with_ih_binTrue               0.260836   0.028753    9.071489
Agricultural.and.Biological.Sciences           0.150702   0.037946    3.971548
Arts.and.Humanities                            0.953792   0.344512    2.768528
Biochemistry..Genetics.and.Molecular.Biology  -0.265404   0.033584   -7.902591
Business..Management.and.Accounting          -10.277553   0.039854 -257.879245
Decision.Sciences                             -0.013606   1.116411   -0.012187
Dentistry                                      1.018004   0.201143    5.061090
Health.Professions                             0.646910   0.303944    2.128383
Immunology.and.Microbiology                   -0.008761   0.034847   -0.251411
Medicine                                       0.558339   0.024431   22.853585
Neuroscience                                   0.329880   0.043667    7.554451
Nursing                                        0.700769   0.064028   10.944708
Pharmacology..Toxicology.and.Pharmaceutics     0.844111   0.076669   11.009801
Psychology                                     0.518967   0.239244    2.169194
Social.Sciences                               -0.552068   0.381729   -1.446230
Veterinary                                     0.420994   0.260594    1.615516
                                               Pr(>|z|)
text_fac_scientistStaffPart                  8.2091e-15 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   1.8664e-07 ***
lnnum_reference                              9.4143e-02 .
num_fac                                      3.8598e-09 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            5.0283e-05 ***
lnlast_avgimpact                              < 2.2e-16 ***
lnlast_insthindex                            3.3396e-04 ***
last_GlobalSouthGlobalNorth                  1.1039e-05 ***
last_SameCountrySame                         2.6928e-04 ***
knowledge_proximity_mean                      < 2.2e-16 ***
lnlast_before_year_prod_fac                  8.7273e-10 ***
last_before_year_with_ih_binTrue              < 2.2e-16 ***
Agricultural.and.Biological.Sciences         7.1407e-05 ***
Arts.and.Humanities                          5.6310e-03 **
Biochemistry..Genetics.and.Molecular.Biology 2.7316e-15 ***
Business..Management.and.Accounting           < 2.2e-16 ***
Decision.Sciences                            9.9028e-01
Dentistry                                    4.1687e-07 ***
Health.Professions                           3.3305e-02 *
Immunology.and.Microbiology                  8.0150e-01
Medicine                                      < 2.2e-16 ***
Neuroscience                                 4.2063e-14 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Psychology                                   3.0068e-02 *
Social.Sciences                              1.4811e-01
Veterinary                                   1.0620e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -22,953.0   Adj. Pseudo R2: 0.080766
           BIC:  46,610.2     Squared Cor.: 0.109024

In [33]:
margins_eff_nps_bin <- avg_comparisons(model_nps_bin, variables = "text_fac_scientist", comparison = 'ratio')
margins_eff_nps_bin

  term               contrast                             estimate std.error
1 text_fac_scientist mean(StaffPart) / mean(NonStaffPart) 1.15914  0.03564953
  statistic p.value       s.value  conf.low conf.high predicted_lo predicted_hi
1 32.51488  6.571103e-232 767.9712 1.089268 1.229012  0.6504019    0.715181
  predicted
1 0.6504019

In [34]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_nps_comp_ratio.csv")
# write.csv(margins_eff_nps_bin, fname, row.names = FALSE)

In [35]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_nps_bin,
                           keep = c("text_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   text\_fac\_scientistStaffPart                & 0.300$^{***}$\\
                                                & (0.039)\\
   lnnum\_author                                & 0.260$^{***}$\\
                                                & (0.024)\\
   internationalinternational                   & 0.133$^{***}$\\
                                                & (0.025)\\
   lnnum\_reference                             & -0.048$^{*}$\\
                                                & (0.029)\\
   num\_fac                                     & -0.117$^{***}$\\
                                                & (0.020)\\
   SDGTrue                                      & 0.251$^{***}$\\
                                                & (0.023)\\
   lnmean\_career\_age                          & 0.149$^{***}$\\
                                                & (0.037)\\
   lnlast\_avgimpact                            & -0.559$^{***}$\\
                                                & (0.018)\\
   lnlast\_insthindex                           & -0.058$^{***}$\\
                                                & (0.016)\\
   last\_GlobalSouthGlobalNorth                 & 0.244$^{***}$\\
                                                & (0.055)\\
   last\_SameCountrySame                        & -0.091$^{***}$\\
                                                & (0.025)\\
   knowledge\_proximity\_mean                   & -4.14$^{***}$\\
                                                & (0.422)\\
   lnlast\_before\_year\_prod\_fac              & -0.069$^{***}$\\
                                                & (0.011)\\
   last\_before\_year\_with\_ih\_binTrue        & 0.261$^{***}$\\
                                                & (0.029)\\
   Agricultural.and.Biological.Sciences         & 0.151$^{***}$\\
                                                & (0.038)\\
   Arts.and.Humanities                          & 0.954$^{***}$\\
                                                & (0.345)\\
   Biochemistry..Genetics.and.Molecular.Biology & -0.265$^{***}$\\
                                                & (0.034)\\
   Business..Management.and.Accounting          & -10.3$^{***}$\\
                                                & (0.040)\\
   Decision.Sciences                            & -0.014\\
                                                & (1.12)\\
   Dentistry                                    & 1.02$^{***}$\\
                                                & (0.201)\\
   Immunology.and.Microbiology                  & -0.009\\
                                                & (0.035)\\
   Medicine                                     & 0.558$^{***}$\\
                                                & (0.024)\\
   Neuroscience                                 & 0.330$^{***}$\\
                                                & (0.044)\\
   Nursing                                      & 0.701$^{***}$\\
                                                & (0.064)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 0.844$^{***}$\\
                                                & (0.077)\\
   Psychology                                   & 0.519$^{**}$\\
                                                & (0.239)\\
   Social.Sciences                              & -0.552\\
                                                & (0.382)\\
   Veterinary                                   & 0.421\\
                                                & (0.261)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 36,735\\
   Squared Correlation                          & 0.10902\\
   Pseudo R$^2$                                 & 0.08340\\
   BIC                                          & 46,610.2\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

# H2: Collaboration > Participation

In [36]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_total <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_total)

NOTE: 42,366 observations removed because of NA values (LHS: 42,366, RHS: 42,366, Fixed-effects: 42,366).

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 273,125
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
CoTypeCollaboration                           0.112047   0.011528   9.719655
CoTypeParticipation                           0.005402   0.015999   0.337646
lnnum_author                                 -0.119416   0.007609 -15.694138
internationalinternational                   -0.046719   0.009770  -4.781675
lnnum_reference                               0.057373   0.009042   6.344928
num_fac                                       0.076336   0.006911  11.045608
SDGTrue                                       0.074198   0.008522   8.706704
lnmean_career_age                            -0.019820   0.013453  -1.473350
lnlast_avgimpact                             -0.244736   0.006356 -38.501853
lnlast_insthindex                            -0.024371   0.005949  -4.096479
last_GlobalSouthGlobalNorth                   0.303824   0.017872  16.999583
last_SameCountrySame                         -0.080810   0.009595  -8.422046
knowledge_proximity_mean                     -0.693983   0.153141  -4.531656
lnlast_before_year_prod_fac                  -0.044060   0.004059 -10.854819
last_before_year_with_ih_binTrue              0.211191   0.011334  18.632982
Agricultural.and.Biological.Sciences          0.790411   0.025553  30.932574
Arts.and.Humanities                           1.811657   0.079926  22.666810
Biochemistry..Genetics.and.Molecular.Biology  0.629003   0.013176  47.740145
Business..Management.and.Accounting          -0.257261   0.088335  -2.912331
Chemical.Engineering                          0.195850   0.021679   9.034041
Chemistry                                     0.477035   0.011621  41.050923
Computer.Science                              0.927115   0.042693  21.715936
Decision.Sciences                             1.196626   0.201065   5.951434
Dentistry                                     1.958623   0.142711  13.724408
Earth.and.Planetary.Sciences                  0.759169   0.016272  46.656180
Economics..Econometrics.and.Finance          -0.512487   0.394911  -1.297728
Energy                                        0.267930   0.018636  14.377269
Engineering                                   0.332440   0.010941  30.385132
Environmental.Science                         0.537509   0.018750  28.667714
Health.Professions                            1.586973   0.138366  11.469382
Immunology.and.Microbiology                   0.248915   0.028956   8.596370
Materials.Science                             0.056564   0.010342   5.469294
Mathematics                                   0.604364   0.129691   4.660032
Medicine                                      0.849578   0.015714  54.064795
Neuroscience                                  0.502887   0.034482  14.584021
Nursing                                       1.070784   0.046605  22.975679
Pharmacology..Toxicology.and.Pharmaceutics    0.879618   0.050973  17.256663
Physics.and.Astronomy                        -0.252191   0.011933 -21.134446
Psychology                                    0.425719   0.166439   2.557804
Social.Sciences                              -0.041891   0.174781  -0.239678
Veterinary                                    0.551633   0.231313   2.384790
                                               Pr(>|z|)
CoTypeCollaboration                           < 2.2e-16 ***
CoTypeParticipation                          7.3563e-01
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   1.7384e-06 ***
lnnum_reference                              2.2253e-10 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            1.4066e-01
lnlast_avgimpact                              < 2.2e-16 ***
lnlast_insthindex                            4.1948e-05 ***
last_GlobalSouthGlobalNorth                   < 2.2e-16 ***
last_SameCountrySame                          < 2.2e-16 ***
knowledge_proximity_mean                     5.8523e-06 ***
lnlast_before_year_prod_fac                   < 2.2e-16 ***
last_before_year_with_ih_binTrue              < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          3.5874e-03 **
Chemical.Engineering                          < 2.2e-16 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            2.6580e-09 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          1.9438e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                   < 2.2e-16 ***
Materials.Science                            4.5183e-08 ***
Mathematics                                  3.1616e-06 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   1.0534e-02 *
Social.Sciences                              8.1058e-01
Veterinary                                   1.7089e-02 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -166,705.4   Adj. Pseudo R2: 0.058039
           BIC:  334,562.4     Squared Cor.: 0.0739

In [37]:
# 每组 reg_class 的平均预测概率
pred <- avg_predictions(model_total, variables = "CoType")
pred

  CoType        estimate  std.error  statistic p.value      s.value  conf.low
1 Service       0.3466111 0.02960925 11.70618  1.185056e-31 102.7348 0.2885780
2 Collaboration 0.3704161 0.03052186 12.13609  6.799831e-34 110.1801 0.3105943
3 Participation 0.3477429 0.02975156 11.68822  1.464214e-31 102.4296 0.2894309
  conf.high
1 0.4046441
2 0.4302378
3 0.4060548

In [38]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_pred.csv")
# write.csv(pred, fname, row.names = FALSE)

In [39]:
# 每组 reg_class 的平均预测概率
margins_eff <- avg_comparisons(model_total, variables = "CoType", comparison = 'ratio')
margins_eff

  term   contrast                            estimate std.error   statistic
1 CoType mean(Collaboration) / mean(Service) 1.068679 0.007978700 133.9415
2 CoType mean(Participation) / mean(Service) 1.003265 0.009682836 103.6128
  p.value s.value conf.low  conf.high predicted_lo predicted_hi predicted
1 0       Inf     1.0530413 1.084317  0.2606975    0.2828639    0.2606975
2 0       Inf     0.9842873 1.022243  0.2606975    0.2617400    0.2606975

In [40]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_comp_ratio.csv")
# write.csv(margins_eff, fname, row.names = FALSE)

In [41]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_total,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                          & 0.112$^{***}$\\
                                                & (0.011)\\
   CoTypeParticipation                          & 0.005\\
                                                & (0.016)\\
   lnnum\_author                                & -0.119$^{***}$\\
                                                & (0.008)\\
   internationalinternational                   & -0.047$^{***}$\\
                                                & (0.010)\\
   lnnum\_reference                             & 0.057$^{***}$\\
                                                & (0.009)\\
   num\_fac                                     & 0.076$^{***}$\\
                                                & (0.007)\\
   SDGTrue                                      & 0.074$^{***}$\\
                                                & (0.009)\\
   lnmean\_career\_age                          & -0.020\\
                                                & (0.013)\\
   lnlast\_avgimpact                            & -0.245$^{***}$\\
                                                & (0.006)\\
   lnlast\_insthindex                           & -0.024$^{***}$\\
                                                & (0.006)\\
   last\_GlobalSouthGlobalNorth                 & 0.304$^{***}$\\
                                                & (0.018)\\
   last\_SameCountrySame                        & -0.081$^{***}$\\
                                                & (0.010)\\
   knowledge\_proximity\_mean                   & -0.694$^{***}$\\
                                                & (0.153)\\
   lnlast\_before\_year\_prod\_fac              & -0.044$^{***}$\\
                                                & (0.004)\\
   last\_before\_year\_with\_ih\_binTrue        & 0.211$^{***}$\\
                                                & (0.011)\\
   Agricultural.and.Biological.Sciences         & 0.790$^{***}$\\
                                                & (0.026)\\
   Arts.and.Humanities                          & 1.81$^{***}$\\
                                                & (0.080)\\
   Biochemistry..Genetics.and.Molecular.Biology & 0.629$^{***}$\\
                                                & (0.013)\\
   Business..Management.and.Accounting          & -0.257$^{***}$\\
                                                & (0.088)\\
   Chemical.Engineering                         & 0.196$^{***}$\\
                                                & (0.022)\\
   Chemistry                                    & 0.477$^{***}$\\
                                                & (0.012)\\
   Computer.Science                             & 0.927$^{***}$\\
                                                & (0.043)\\
   Decision.Sciences                            & 1.20$^{***}$\\
                                                & (0.201)\\
   Dentistry                                    & 1.96$^{***}$\\
                                                & (0.143)\\
   Earth.and.Planetary.Sciences                 & 0.759$^{***}$\\
                                                & (0.016)\\
   Economics..Econometrics.and.Finance          & -0.512\\
                                                & (0.395)\\
   Energy                                       & 0.268$^{***}$\\
                                                & (0.019)\\
   Engineering                                  & 0.332$^{***}$\\
                                                & (0.011)\\
   Immunology.and.Microbiology                  & 0.249$^{***}$\\
                                                & (0.029)\\
   Materials.Science                            & 0.057$^{***}$\\
                                                & (0.010)\\
   Mathematics                                  & 0.604$^{***}$\\
                                                & (0.130)\\
   Medicine                                     & 0.850$^{***}$\\
                                                & (0.016)\\
   Neuroscience                                 & 0.503$^{***}$\\
                                                & (0.035)\\
   Nursing                                      & 1.07$^{***}$\\
                                                & (0.047)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 0.880$^{***}$\\
                                                & (0.051)\\
   Physics.and.Astronomy                        & -0.252$^{***}$\\
                                                & (0.012)\\
   Psychology                                   & 0.426$^{**}$\\
                                                & (0.166)\\
   Social.Sciences                              & -0.042\\
                                                & (0.175)\\
   Veterinary                                   & 0.552$^{**}$\\
                                                & (0.231)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 273,125\\
   Squared Correlation                          & 0.07390\\
   Pseudo R$^2$                                 & 0.05855\\
   BIC                                          & 334,562.4\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

# H2 Discipline

In [42]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_ps <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Physical.Sciences==1), ], family = binomial("logit"), vcov = "hetero")
summary(model_ps)

NOTE: 34,712 observations removed because of NA values (LHS: 34,712, RHS: 34,712, Fixed-effects: 34,712).

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 236,379
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
CoTypeCollaboration                           0.095254   0.012083   7.883175
CoTypeParticipation                           0.008066   0.016803   0.480042
lnnum_author                                 -0.196343   0.008538 -22.995645
internationalinternational                   -0.080574   0.010666  -7.554057
lnnum_reference                               0.075198   0.009613   7.822398
num_fac                                       0.112361   0.007421  15.141508
SDGTrue                                       0.024395   0.009295   2.624462
lnmean_career_age                            -0.066916   0.014567  -4.593528
lnlast_avgimpact                             -0.185953   0.007005 -26.544320
lnlast_insthindex                            -0.010205   0.006484  -1.573922
last_GlobalSouthGlobalNorth                   0.292060   0.019177  15.229392
last_SameCountrySame                         -0.083265   0.010510  -7.922269
knowledge_proximity_mean                     -0.192900   0.167754  -1.149900
lnlast_before_year_prod_fac                  -0.032078   0.004412  -7.270302
last_before_year_with_ih_binTrue              0.187820   0.012485  15.044173
Agricultural.and.Biological.Sciences          1.071988   0.039119  27.402981
Arts.and.Humanities                           1.829861   0.082796  22.100750
Biochemistry..Genetics.and.Molecular.Biology  0.788522   0.014848  53.106249
Business..Management.and.Accounting          -0.229177   0.087863  -2.608334
Chemical.Engineering                          0.203995   0.021818   9.349725
Chemistry                                     0.434900   0.012511  34.760665
Computer.Science                              0.860134   0.043605  19.725592
Decision.Sciences                             1.282396   0.204997   6.255688
Dentistry                                     2.453534   0.216076  11.354972
Earth.and.Planetary.Sciences                  0.778935   0.016545  47.078536
Economics..Econometrics.and.Finance          -0.534681   0.396442  -1.348699
Energy                                        0.261627   0.019042  13.739684
Engineering                                   0.351757   0.011620  30.271631
Environmental.Science                         0.450205   0.020196  22.292021
Health.Professions                            1.826808   0.158760  11.506724
Immunology.and.Microbiology                   0.560116   0.076004   7.369556
Materials.Science                             0.024325   0.011340   2.145078
Mathematics                                   0.588619   0.130579   4.507769
Medicine                                      0.952207   0.023891  39.855640
Neuroscience                                  0.705075   0.061953  11.380846
Nursing                                       1.368424   0.072617  18.844365
Pharmacology..Toxicology.and.Pharmaceutics    0.799868   0.070526  11.341414
Physics.and.Astronomy                        -0.240100   0.012591 -19.068577
Psychology                                   -0.499387   0.294759  -1.694222
Social.Sciences                               0.094881   0.209707   0.452444
Veterinary                                    0.069512   0.563489   0.123360
                                               Pr(>|z|)
CoTypeCollaboration                          3.1917e-15 ***
CoTypeParticipation                          6.3120e-01
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   4.2191e-14 ***
lnnum_reference                              5.1827e-15 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                      8.6786e-03 **
lnmean_career_age                            4.3581e-06 ***
lnlast_avgimpact                              < 2.2e-16 ***
lnlast_insthindex                            1.1551e-01
last_GlobalSouthGlobalNorth                   < 2.2e-16 ***
last_SameCountrySame                         2.3322e-15 ***
knowledge_proximity_mean                     2.5019e-01
lnlast_before_year_prod_fac                  3.5868e-13 ***
last_before_year_with_ih_binTrue              < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          9.0984e-03 **
Chemical.Engineering                          < 2.2e-16 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            3.9577e-10 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          1.7743e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                  1.7120e-13 ***
Materials.Science                            3.1947e-02 *
Mathematics                                  6.5513e-06 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   9.0223e-02 .
Social.Sciences                              6.5095e-01
Veterinary                                   9.0182e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -142,046.2   Adj. Pseudo R2: 0.062061
           BIC:  285,230.8     Squared Cor.: 0.078335

In [43]:
# 每组 reg_class 的平均预测概率
margins_eff_ps <- avg_comparisons(model_ps, variables = "CoType", comparison = 'ratio')
margins_eff_ps

  term   contrast                            estimate std.error   statistic
1 CoType mean(Collaboration) / mean(Service) 1.059000 0.008204009 129.08323
2 CoType mean(Participation) / mean(Service) 1.004934 0.010299339  97.57271
  p.value s.value conf.low  conf.high predicted_lo predicted_hi predicted
1 0       Inf     1.0429204 1.075080  0.2636921    0.2825977    0.2636921
2 0       Inf     0.9847481 1.025121  0.2636921    0.2652612    0.2636921

In [44]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_ps_comp_ratio.csv")
# write.csv(margins_eff_ps, fname, row.names = FALSE)

In [45]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_ps,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                          & 0.095$^{***}$\\
                                                & (0.012)\\
   CoTypeParticipation                          & 0.008\\
                                                & (0.017)\\
   lnnum\_author                                & -0.196$^{***}$\\
                                                & (0.009)\\
   internationalinternational                   & -0.081$^{***}$\\
                                                & (0.011)\\
   lnnum\_reference                             & 0.075$^{***}$\\
                                                & (0.010)\\
   num\_fac                                     & 0.112$^{***}$\\
                                                & (0.007)\\
   SDGTrue                                      & 0.024$^{***}$\\
                                                & (0.009)\\
   lnmean\_career\_age                          & -0.067$^{***}$\\
                                                & (0.015)\\
   lnlast\_avgimpact                            & -0.186$^{***}$\\
                                                & (0.007)\\
   lnlast\_insthindex                           & -0.010\\
                                                & (0.006)\\
   last\_GlobalSouthGlobalNorth                 & 0.292$^{***}$\\
                                                & (0.019)\\
   last\_SameCountrySame                        & -0.083$^{***}$\\
                                                & (0.011)\\
   knowledge\_proximity\_mean                   & -0.193\\
                                                & (0.168)\\
   lnlast\_before\_year\_prod\_fac              & -0.032$^{***}$\\
                                                & (0.004)\\
   last\_before\_year\_with\_ih\_binTrue        & 0.188$^{***}$\\
                                                & (0.013)\\
   Agricultural.and.Biological.Sciences         & 1.07$^{***}$\\
                                                & (0.039)\\
   Arts.and.Humanities                          & 1.83$^{***}$\\
                                                & (0.083)\\
   Biochemistry..Genetics.and.Molecular.Biology & 0.789$^{***}$\\
                                                & (0.015)\\
   Business..Management.and.Accounting          & -0.229$^{***}$\\
                                                & (0.088)\\
   Chemical.Engineering                         & 0.204$^{***}$\\
                                                & (0.022)\\
   Chemistry                                    & 0.435$^{***}$\\
                                                & (0.013)\\
   Computer.Science                             & 0.860$^{***}$\\
                                                & (0.044)\\
   Decision.Sciences                            & 1.28$^{***}$\\
                                                & (0.205)\\
   Dentistry                                    & 2.45$^{***}$\\
                                                & (0.216)\\
   Earth.and.Planetary.Sciences                 & 0.779$^{***}$\\
                                                & (0.017)\\
   Economics..Econometrics.and.Finance          & -0.535\\
                                                & (0.396)\\
   Energy                                       & 0.262$^{***}$\\
                                                & (0.019)\\
   Engineering                                  & 0.352$^{***}$\\
                                                & (0.012)\\
   Immunology.and.Microbiology                  & 0.560$^{***}$\\
                                                & (0.076)\\
   Materials.Science                            & 0.024$^{**}$\\
                                                & (0.011)\\
   Mathematics                                  & 0.589$^{***}$\\
                                                & (0.131)\\
   Medicine                                     & 0.952$^{***}$\\
                                                & (0.024)\\
   Neuroscience                                 & 0.705$^{***}$\\
                                                & (0.062)\\
   Nursing                                      & 1.37$^{***}$\\
                                                & (0.073)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 0.800$^{***}$\\
                                                & (0.070)\\
   Physics.and.Astronomy                        & -0.240$^{***}$\\
                                                & (0.013)\\
   Psychology                                   & -0.499$^{*}$\\
                                                & (0.295)\\
   Social.Sciences                              & 0.095\\
                                                & (0.210)\\
   Veterinary                                   & 0.070\\
                                                & (0.563)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 236,379\\
   Squared Correlation                          & 0.07834\\
   Pseudo R$^2$                                 & 0.06266\\
   BIC                                          & 285,230.8\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [46]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_ls <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Life.Sciences==1), ], family = binomial("logit"), vcov = "hetero")
summary(model_ls)

NOTES: 13,892 observations removed because of NA values (LHS: 13,892, RHS: 13,892, Fixed-effects: 13,892).
       2 fixed-effects (4 observations) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 70,337
Fixed-effects: PublishedYear: 46
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
CoTypeCollaboration                           0.096800   0.025855   3.744029
CoTypeParticipation                           0.160543   0.040047   4.008877
lnnum_author                                  0.179939   0.017242  10.435870
internationalinternational                    0.111468   0.018152   6.140731
lnnum_reference                               0.145096   0.018789   7.722562
num_fac                                      -0.060130   0.013164  -4.567918
SDGTrue                                       0.138025   0.015997   8.628436
lnmean_career_age                             0.099609   0.025060   3.974727
lnlast_avgimpact                             -0.438806   0.012450 -35.246619
lnlast_insthindex                            -0.022122   0.011386  -1.942888
last_GlobalSouthGlobalNorth                   0.116229   0.038698   3.003470
last_SameCountrySame                         -0.102580   0.017592  -5.831083
knowledge_proximity_mean                     -2.671326   0.274500  -9.731609
lnlast_before_year_prod_fac                  -0.075451   0.007769  -9.711879
last_before_year_with_ih_binTrue              0.284922   0.020239  14.077919
Agricultural.and.Biological.Sciences          0.423836   0.029959  14.147249
Arts.and.Humanities                           0.992276   0.312772   3.172522
Biochemistry..Genetics.and.Molecular.Biology -0.067377   0.032001  -2.105448
Business..Management.and.Accounting           0.191467   0.486489   0.393568
Chemical.Engineering                          0.345366   0.142625   2.421495
Chemistry                                     0.548871   0.024341  22.548943
Computer.Science                              0.663935   0.073469   9.036987
Decision.Sciences                            -0.077349   0.821447  -0.094162
Dentistry                                     0.650550   0.233816   2.782314
Earth.and.Planetary.Sciences                  0.843490   0.083229  10.134555
Energy                                        0.216636   0.065791   3.292776
Engineering                                   0.470221   0.032796  14.337732
Environmental.Science                        -0.041413   0.033181  -1.248098
Health.Professions                            0.828394   0.417360   1.984841
Immunology.and.Microbiology                   0.121590   0.031893   3.812409
Materials.Science                             0.136105   0.020625   6.598947
Mathematics                                   0.908055   0.580447   1.564405
Medicine                                      0.505369   0.019825  25.490964
Neuroscience                                  0.261195   0.036408   7.174093
Nursing                                       0.638113   0.056111  11.372342
Pharmacology..Toxicology.and.Pharmaceutics    0.589685   0.054228  10.874129
Physics.and.Astronomy                         0.384077   0.032114  11.959982
Psychology                                    0.437258   0.247171   1.769053
Social.Sciences                               0.175613   0.445552   0.394147
Veterinary                                    0.222535   0.264715   0.840658
                                               Pr(>|z|)
CoTypeCollaboration                          1.8109e-04 ***
CoTypeParticipation                          6.1008e-05 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   8.2143e-10 ***
lnnum_reference                              1.1401e-14 ***
num_fac                                      4.9259e-06 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            7.0460e-05 ***
lnlast_avgimpact                              < 2.2e-16 ***
lnlast_insthindex                            5.2030e-02 .
last_GlobalSouthGlobalNorth                  2.6692e-03 **
last_SameCountrySame                         5.5069e-09 ***
knowledge_proximity_mean                      < 2.2e-16 ***
lnlast_before_year_prod_fac                   < 2.2e-16 ***
last_before_year_with_ih_binTrue              < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                          1.5112e-03 **
Biochemistry..Genetics.and.Molecular.Biology 3.5252e-02 *
Business..Management.and.Accounting          6.9390e-01
Chemical.Engineering                         1.5457e-02 *
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            9.2498e-01
Dentistry                                    5.3973e-03 **
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Energy                                       9.9204e-04 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                        2.1200e-01
Health.Professions                           4.7162e-02 *
Immunology.and.Microbiology                  1.3762e-04 ***
Materials.Science                            4.1409e-11 ***
Mathematics                                  1.1772e-01
Medicine                                      < 2.2e-16 ***
Neuroscience                                 7.2788e-13 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   7.6885e-02 .
Social.Sciences                              6.9347e-01
Veterinary                                   4.0054e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -45,595.1   Adj. Pseudo R2: 0.058896
           BIC:  92,150.1     Squared Cor.: 0.080778

In [47]:
# 每组 reg_class 的平均预测概率
margins_eff_ls <- avg_comparisons(model_ls, variables = "CoType", comparison = 'ratio')
margins_eff_ls

  term   contrast                            estimate std.error  statistic
1 CoType mean(Collaboration) / mean(Service) 1.048688 0.01459297 71.86255
2 CoType mean(Participation) / mean(Service) 1.080859 0.02263597 47.74961
  p.value s.value conf.low conf.high predicted_lo predicted_hi predicted
1 0       Inf     1.020086 1.077289  0.3072144    0.3281919    0.3072144
2 0       Inf     1.036493 1.125225  0.3072144    0.3423967    0.3072144

In [48]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_ls_comp_ratio.csv")
# write.csv(margins_eff_ls, fname, row.names = FALSE)

In [49]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_ls,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                          & 0.097$^{***}$\\
                                                & (0.026)\\
   CoTypeParticipation                          & 0.161$^{***}$\\
                                                & (0.040)\\
   lnnum\_author                                & 0.180$^{***}$\\
                                                & (0.017)\\
   internationalinternational                   & 0.111$^{***}$\\
                                                & (0.018)\\
   lnnum\_reference                             & 0.145$^{***}$\\
                                                & (0.019)\\
   num\_fac                                     & -0.060$^{***}$\\
                                                & (0.013)\\
   SDGTrue                                      & 0.138$^{***}$\\
                                                & (0.016)\\
   lnmean\_career\_age                          & 0.100$^{***}$\\
                                                & (0.025)\\
   lnlast\_avgimpact                            & -0.439$^{***}$\\
                                                & (0.012)\\
   lnlast\_insthindex                           & -0.022$^{*}$\\
                                                & (0.011)\\
   last\_GlobalSouthGlobalNorth                 & 0.116$^{***}$\\
                                                & (0.039)\\
   last\_SameCountrySame                        & -0.103$^{***}$\\
                                                & (0.018)\\
   knowledge\_proximity\_mean                   & -2.67$^{***}$\\
                                                & (0.274)\\
   lnlast\_before\_year\_prod\_fac              & -0.075$^{***}$\\
                                                & (0.008)\\
   last\_before\_year\_with\_ih\_binTrue        & 0.285$^{***}$\\
                                                & (0.020)\\
   Agricultural.and.Biological.Sciences         & 0.424$^{***}$\\
                                                & (0.030)\\
   Arts.and.Humanities                          & 0.992$^{***}$\\
                                                & (0.313)\\
   Biochemistry..Genetics.and.Molecular.Biology & -0.067$^{**}$\\
                                                & (0.032)\\
   Business..Management.and.Accounting          & 0.191\\
                                                & (0.486)\\
   Chemical.Engineering                         & 0.345$^{**}$\\
                                                & (0.143)\\
   Chemistry                                    & 0.549$^{***}$\\
                                                & (0.024)\\
   Computer.Science                             & 0.664$^{***}$\\
                                                & (0.073)\\
   Decision.Sciences                            & -0.077\\
                                                & (0.821)\\
   Dentistry                                    & 0.651$^{***}$\\
                                                & (0.234)\\
   Earth.and.Planetary.Sciences                 & 0.843$^{***}$\\
                                                & (0.083)\\
   Energy                                       & 0.217$^{***}$\\
                                                & (0.066)\\
   Engineering                                  & 0.470$^{***}$\\
                                                & (0.033)\\
   Immunology.and.Microbiology                  & 0.122$^{***}$\\
                                                & (0.032)\\
   Materials.Science                            & 0.136$^{***}$\\
                                                & (0.021)\\
   Mathematics                                  & 0.908\\
                                                & (0.580)\\
   Medicine                                     & 0.505$^{***}$\\
                                                & (0.020)\\
   Neuroscience                                 & 0.261$^{***}$\\
                                                & (0.036)\\
   Nursing                                      & 0.638$^{***}$\\
                                                & (0.056)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 0.590$^{***}$\\
                                                & (0.054)\\
   Physics.and.Astronomy                        & 0.384$^{***}$\\
                                                & (0.032)\\
   Psychology                                   & 0.437$^{*}$\\
                                                & (0.247)\\
   Social.Sciences                              & 0.176\\
                                                & (0.446)\\
   Veterinary                                   & 0.223\\
                                                & (0.265)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 70,337\\
   Squared Correlation                          & 0.08078\\
   Pseudo R$^2$                                 & 0.06065\\
   BIC                                          & 92,150.1\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [50]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_hs <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Health.Sciences==1), ], family = binomial("logit"), vcov = "hetero")
summary(model_hs)

NOTES: 8,210 observations removed because of NA values (LHS: 8,210, RHS: 8,210, Fixed-effects: 8,210).
       7 fixed-effects (10 observations) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 28,986
Fixed-effects: PublishedYear: 38
Standard-errors: Heteroskedasticity-robust
                                               Estimate Std. Error     z value
CoTypeCollaboration                            0.318117   0.045487    6.993570
CoTypeParticipation                            0.431170   0.067770    6.362257
lnnum_author                                   0.237376   0.027779    8.545202
internationalinternational                     0.072265   0.028051    2.576176
lnnum_reference                                0.145028   0.029733    4.877623
num_fac                                       -0.099467   0.022166   -4.487425
SDGTrue                                        0.210641   0.025216    8.353553
lnmean_career_age                              0.168547   0.040380    4.173998
lnlast_avgimpact                              -0.357615   0.019422  -18.413213
lnlast_insthindex                             -0.023564   0.017404   -1.353960
last_GlobalSouthGlobalNorth                    0.291604   0.061435    4.746553
last_SameCountrySame                          -0.117332   0.027606   -4.250190
knowledge_proximity_mean                      -0.726265   0.393376   -1.846235
lnlast_before_year_prod_fac                   -0.090652   0.012211   -7.423853
last_before_year_with_ih_binTrue               0.238191   0.032050    7.431977
Agricultural.and.Biological.Sciences          -0.095505   0.058904   -1.621362
Arts.and.Humanities                            0.905932   0.500807    1.808944
Biochemistry..Genetics.and.Molecular.Biology  -0.203977   0.031028   -6.573940
Business..Management.and.Accounting          -11.659094   0.066129 -176.309258
Chemical.Engineering                          -0.314185   0.293557   -1.070267
Chemistry                                      0.059862   0.040786    1.467708
Computer.Science                               0.548604   0.101044    5.429368
Decision.Sciences                             -0.154655   0.960010   -0.161097
Dentistry                                      0.894575   0.153479    5.828649
Earth.and.Planetary.Sciences                   0.864444   0.214019    4.039092
Energy                                        -0.013834   0.109697   -0.126106
Engineering                                    0.616148   0.059663   10.327070
Environmental.Science                          0.154640   0.064411    2.400838
Health.Professions                             0.692869   0.156191    4.436027
Immunology.and.Microbiology                   -0.332122   0.042442   -7.825269
Materials.Science                             -0.397931   0.040900   -9.729311
Mathematics                                    0.842543   0.628184    1.341235
Medicine                                       0.154199   0.087611    1.760038
Neuroscience                                   0.170979   0.067032    2.550692
Nursing                                        0.658308   0.074455    8.841743
Pharmacology..Toxicology.and.Pharmaceutics     0.616150   0.088964    6.925860
Physics.and.Astronomy                          0.041515   0.060908    0.681603
Psychology                                     0.773544   0.397365    1.946686
Social.Sciences                                0.653120   0.613930    1.063835
Veterinary                                     0.202555   0.234212    0.864833
                                               Pr(>|z|)
CoTypeCollaboration                          2.6798e-12 ***
CoTypeParticipation                          1.9881e-10 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   9.9900e-03 **
lnnum_reference                              1.0737e-06 ***
num_fac                                      7.2089e-06 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            2.9930e-05 ***
lnlast_avgimpact                              < 2.2e-16 ***
lnlast_insthindex                            1.7575e-01
last_GlobalSouthGlobalNorth                  2.0691e-06 ***
last_SameCountrySame                         2.1359e-05 ***
knowledge_proximity_mean                     6.4858e-02 .
lnlast_before_year_prod_fac                  1.1376e-13 ***
last_before_year_with_ih_binTrue             1.0699e-13 ***
Agricultural.and.Biological.Sciences         1.0494e-01
Arts.and.Humanities                          7.0460e-02 .
Biochemistry..Genetics.and.Molecular.Biology 4.9001e-11 ***
Business..Management.and.Accounting           < 2.2e-16 ***
Chemical.Engineering                         2.8450e-01
Chemistry                                    1.4218e-01
Computer.Science                             5.6554e-08 ***
Decision.Sciences                            8.7202e-01
Dentistry                                    5.5878e-09 ***
Earth.and.Planetary.Sciences                 5.3659e-05 ***
Energy                                       8.9965e-01
Engineering                                   < 2.2e-16 ***
Environmental.Science                        1.6358e-02 *
Health.Professions                           9.1634e-06 ***
Immunology.and.Microbiology                  5.0657e-15 ***
Materials.Science                             < 2.2e-16 ***
Mathematics                                  1.7984e-01
Medicine                                     7.8401e-02 .
Neuroscience                                 1.0751e-02 *
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics   4.3334e-12 ***
Physics.and.Astronomy                        4.9549e-01
Psychology                                   5.1572e-02 .
Social.Sciences                              2.8740e-01
Veterinary                                   3.8713e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -18,715.3   Adj. Pseudo R2: 0.059376
           BIC:  38,232.0     Squared Cor.: 0.084668

In [51]:
# 每组 reg_class 的平均预测概率
margins_eff_hs <- avg_comparisons(model_hs, variables = "CoType", comparison = 'ratio')
margins_eff_hs

  term   contrast                            estimate std.error  statistic
1 CoType mean(Collaboration) / mean(Service) 1.135532 0.03583460 31.68815
2 CoType mean(Participation) / mean(Service) 1.182161 0.05014371 23.57546
  p.value       s.value  conf.low conf.high predicted_lo predicted_hi predicted
1 2.262774e-220 729.6461 1.065298 1.205767  0.6688044    0.7351478    0.6688044
2 6.883519e-123 405.8140 1.083881 1.280441  0.6688044    0.7565675    0.6688044

In [52]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_hs_comp_ratio.csv")
# write.csv(margins_eff_hs, fname, row.names = FALSE)

In [53]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_hs,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                          & 0.318$^{***}$\\
                                                & (0.045)\\
   CoTypeParticipation                          & 0.431$^{***}$\\
                                                & (0.068)\\
   lnnum\_author                                & 0.237$^{***}$\\
                                                & (0.028)\\
   internationalinternational                   & 0.072$^{***}$\\
                                                & (0.028)\\
   lnnum\_reference                             & 0.145$^{***}$\\
                                                & (0.030)\\
   num\_fac                                     & -0.100$^{***}$\\
                                                & (0.022)\\
   SDGTrue                                      & 0.211$^{***}$\\
                                                & (0.025)\\
   lnmean\_career\_age                          & 0.169$^{***}$\\
                                                & (0.040)\\
   lnlast\_avgimpact                            & -0.358$^{***}$\\
                                                & (0.019)\\
   lnlast\_insthindex                           & -0.024\\
                                                & (0.017)\\
   last\_GlobalSouthGlobalNorth                 & 0.292$^{***}$\\
                                                & (0.061)\\
   last\_SameCountrySame                        & -0.117$^{***}$\\
                                                & (0.028)\\
   knowledge\_proximity\_mean                   & -0.726$^{*}$\\
                                                & (0.393)\\
   lnlast\_before\_year\_prod\_fac              & -0.091$^{***}$\\
                                                & (0.012)\\
   last\_before\_year\_with\_ih\_binTrue        & 0.238$^{***}$\\
                                                & (0.032)\\
   Agricultural.and.Biological.Sciences         & -0.096\\
                                                & (0.059)\\
   Arts.and.Humanities                          & 0.906$^{*}$\\
                                                & (0.501)\\
   Biochemistry..Genetics.and.Molecular.Biology & -0.204$^{***}$\\
                                                & (0.031)\\
   Business..Management.and.Accounting          & -11.7$^{***}$\\
                                                & (0.066)\\
   Chemical.Engineering                         & -0.314\\
                                                & (0.294)\\
   Chemistry                                    & 0.060\\
                                                & (0.041)\\
   Computer.Science                             & 0.549$^{***}$\\
                                                & (0.101)\\
   Decision.Sciences                            & -0.155\\
                                                & (0.960)\\
   Dentistry                                    & 0.895$^{***}$\\
                                                & (0.153)\\
   Earth.and.Planetary.Sciences                 & 0.864$^{***}$\\
                                                & (0.214)\\
   Energy                                       & -0.014\\
                                                & (0.110)\\
   Engineering                                  & 0.616$^{***}$\\
                                                & (0.060)\\
   Immunology.and.Microbiology                  & -0.332$^{***}$\\
                                                & (0.042)\\
   Materials.Science                            & -0.398$^{***}$\\
                                                & (0.041)\\
   Mathematics                                  & 0.843\\
                                                & (0.628)\\
   Medicine                                     & 0.154$^{*}$\\
                                                & (0.088)\\
   Neuroscience                                 & 0.171$^{**}$\\
                                                & (0.067)\\
   Nursing                                      & 0.658$^{***}$\\
                                                & (0.074)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 0.616$^{***}$\\
                                                & (0.089)\\
   Physics.and.Astronomy                        & 0.042\\
                                                & (0.061)\\
   Psychology                                   & 0.774$^{*}$\\
                                                & (0.397)\\
   Social.Sciences                              & 0.653\\
                                                & (0.614)\\
   Veterinary                                   & 0.203\\
                                                & (0.234)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 28,986\\
   Squared Correlation                          & 0.08467\\
   Pseudo R$^2$                                 & 0.06323\\
   BIC                                          & 38,232.0\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [54]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_nps <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Physical.Sciences==0), ], family = binomial("logit"), vcov = "hetero")
summary(model_nps)

NOTES: 7,654 observations removed because of NA values (LHS: 7,654, RHS: 7,654, Fixed-effects: 7,654).
       6 fixed-effects (11 observations) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 36,735
Fixed-effects: PublishedYear: 38
Standard-errors: Heteroskedasticity-robust
                                               Estimate Std. Error     z value
CoTypeCollaboration                            0.259465   0.044678    5.807505
CoTypeParticipation                            0.395495   0.063833    6.195790
lnnum_author                                   0.259847   0.024321   10.683913
internationalinternational                     0.132649   0.025455    5.211022
lnnum_reference                               -0.048749   0.028703   -1.698391
num_fac                                       -0.117200   0.019928   -5.881031
SDGTrue                                        0.251700   0.022783   11.047773
lnmean_career_age                              0.150690   0.036712    4.104594
lnlast_avgimpact                              -0.559250   0.017657  -31.672244
lnlast_insthindex                             -0.058098   0.016071   -3.615035
last_GlobalSouthGlobalNorth                    0.245800   0.055471    4.431143
last_SameCountrySame                          -0.090672   0.024876   -3.644942
knowledge_proximity_mean                      -4.120010   0.421972   -9.763703
lnlast_before_year_prod_fac                   -0.068009   0.011198   -6.073287
last_before_year_with_ih_binTrue               0.261561   0.028756    9.095922
Agricultural.and.Biological.Sciences           0.150025   0.037959    3.952253
Arts.and.Humanities                            0.931947   0.343893    2.709989
Biochemistry..Genetics.and.Molecular.Biology  -0.264360   0.033592   -7.869746
Business..Management.and.Accounting          -10.260959   0.040893 -250.923980
Decision.Sciences                             -0.017733   1.116333   -0.015885
Dentistry                                      1.019073   0.200981    5.070504
Health.Professions                             0.644794   0.303639    2.123555
Immunology.and.Microbiology                   -0.009008   0.034845   -0.258503
Medicine                                       0.558237   0.024432   22.848721
Neuroscience                                   0.329175   0.043674    7.537153
Nursing                                        0.700265   0.064040   10.934792
Pharmacology..Toxicology.and.Pharmaceutics     0.842766   0.076653   10.994605
Psychology                                     0.517051   0.239028    2.163137
Social.Sciences                               -0.545246   0.380920   -1.431392
Veterinary                                     0.421071   0.260564    1.615998
                                               Pr(>|z|)
CoTypeCollaboration                          6.3411e-09 ***
CoTypeParticipation                          5.7993e-10 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   1.8780e-07 ***
lnnum_reference                              8.9434e-02 .
num_fac                                      4.0772e-09 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            4.0503e-05 ***
lnlast_avgimpact                              < 2.2e-16 ***
lnlast_insthindex                            3.0031e-04 ***
last_GlobalSouthGlobalNorth                  9.3735e-06 ***
last_SameCountrySame                         2.6745e-04 ***
knowledge_proximity_mean                      < 2.2e-16 ***
lnlast_before_year_prod_fac                  1.2532e-09 ***
last_before_year_with_ih_binTrue              < 2.2e-16 ***
Agricultural.and.Biological.Sciences         7.7419e-05 ***
Arts.and.Humanities                          6.7285e-03 **
Biochemistry..Genetics.and.Molecular.Biology 3.5536e-15 ***
Business..Management.and.Accounting           < 2.2e-16 ***
Decision.Sciences                            9.8733e-01
Dentistry                                    3.9676e-07 ***
Health.Professions                           3.3707e-02 *
Immunology.and.Microbiology                  7.9602e-01
Medicine                                      < 2.2e-16 ***
Neuroscience                                 4.8034e-14 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Psychology                                   3.0531e-02 *
Social.Sciences                              1.5232e-01
Veterinary                                   1.0609e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -22,951.3   Adj. Pseudo R2: 0.080793
           BIC:  46,617.3     Squared Cor.: 0.109077

In [55]:
# 每组 reg_class 的平均预测概率
margins_eff_nps <- avg_comparisons(model_nps, variables = "CoType", comparison = 'ratio')
margins_eff_nps

  term   contrast                            estimate std.error  statistic
1 CoType mean(Collaboration) / mean(Service) 1.137504 0.03461788 32.85887
2 CoType mean(Participation) / mean(Service) 1.210474 0.05194766 23.30180
  p.value       s.value  conf.low conf.high predicted_lo predicted_hi predicted
1 8.509612e-237 784.2079 1.069654 1.205354  0.6506765    0.7071286    0.6506765
2 4.250477e-120 396.5437 1.108659 1.312290  0.6506765    0.7344871    0.6506765

In [56]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_nps_comp_ratio.csv")
# write.csv(margins_eff_nps, fname, row.names = FALSE)

In [57]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_nps,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                          & 0.259$^{***}$\\
                                                & (0.045)\\
   CoTypeParticipation                          & 0.395$^{***}$\\
                                                & (0.064)\\
   lnnum\_author                                & 0.260$^{***}$\\
                                                & (0.024)\\
   internationalinternational                   & 0.133$^{***}$\\
                                                & (0.025)\\
   lnnum\_reference                             & -0.049$^{*}$\\
                                                & (0.029)\\
   num\_fac                                     & -0.117$^{***}$\\
                                                & (0.020)\\
   SDGTrue                                      & 0.252$^{***}$\\
                                                & (0.023)\\
   lnmean\_career\_age                          & 0.151$^{***}$\\
                                                & (0.037)\\
   lnlast\_avgimpact                            & -0.559$^{***}$\\
                                                & (0.018)\\
   lnlast\_insthindex                           & -0.058$^{***}$\\
                                                & (0.016)\\
   last\_GlobalSouthGlobalNorth                 & 0.246$^{***}$\\
                                                & (0.056)\\
   last\_SameCountrySame                        & -0.091$^{***}$\\
                                                & (0.025)\\
   knowledge\_proximity\_mean                   & -4.12$^{***}$\\
                                                & (0.422)\\
   lnlast\_before\_year\_prod\_fac              & -0.068$^{***}$\\
                                                & (0.011)\\
   last\_before\_year\_with\_ih\_binTrue        & 0.262$^{***}$\\
                                                & (0.029)\\
   Agricultural.and.Biological.Sciences         & 0.150$^{***}$\\
                                                & (0.038)\\
   Arts.and.Humanities                          & 0.932$^{***}$\\
                                                & (0.344)\\
   Biochemistry..Genetics.and.Molecular.Biology & -0.264$^{***}$\\
                                                & (0.034)\\
   Business..Management.and.Accounting          & -10.3$^{***}$\\
                                                & (0.041)\\
   Decision.Sciences                            & -0.018\\
                                                & (1.12)\\
   Dentistry                                    & 1.02$^{***}$\\
                                                & (0.201)\\
   Immunology.and.Microbiology                  & -0.009\\
                                                & (0.035)\\
   Medicine                                     & 0.558$^{***}$\\
                                                & (0.024)\\
   Neuroscience                                 & 0.329$^{***}$\\
                                                & (0.044)\\
   Nursing                                      & 0.700$^{***}$\\
                                                & (0.064)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 0.843$^{***}$\\
                                                & (0.077)\\
   Psychology                                   & 0.517$^{**}$\\
                                                & (0.239)\\
   Social.Sciences                              & -0.545\\
                                                & (0.381)\\
   Veterinary                                   & 0.421\\
                                                & (0.261)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 36,735\\
   Squared Correlation                          & 0.10908\\
   Pseudo R$^2$                                 & 0.08347\\
   BIC                                          & 46,617.3\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

# H3: Too much will suppress

# H3a: Participation too much not good

In [58]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ ratio_fac_scientist + I(ratio_fac_scientist^2) +  ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_h3_pratio <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_h3_pratio)

NOTE: 42,366 observations removed because of NA values (LHS: 42,366, RHS: 42,366, Fixed-effects: 42,366).

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 273,125
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
ratio_fac_scientist                           0.296426   0.059327   4.996507
I(ratio_fac_scientist^2)                     -0.146006   0.071108  -2.053317
lnnum_author                                 -0.117575   0.007488 -15.700843
internationalinternational                   -0.043629   0.009817  -4.444134
lnnum_reference                               0.058428   0.009049   6.457116
num_fac                                       0.076445   0.006922  11.044099
SDGTrue                                       0.074110   0.008522   8.696590
lnmean_career_age                            -0.017258   0.013449  -1.283257
lnlast_avgimpact                             -0.244609   0.006356 -38.484626
lnlast_insthindex                            -0.024399   0.005970  -4.087007
last_GlobalSouthGlobalNorth                   0.303777   0.017876  16.993260
last_SameCountrySame                         -0.079582   0.009576  -8.310889
knowledge_proximity_mean                     -0.699595   0.153233  -4.565571
lnlast_before_year_prod_fac                  -0.044545   0.004062 -10.965190
last_before_year_with_ih_binTrue              0.213609   0.011277  18.942841
Agricultural.and.Biological.Sciences          0.789832   0.025558  30.903968
Arts.and.Humanities                           1.813615   0.079956  22.682769
Biochemistry..Genetics.and.Molecular.Biology  0.629299   0.013170  47.781010
Business..Management.and.Accounting          -0.253227   0.088282  -2.868372
Chemical.Engineering                          0.195310   0.021678   9.009565
Chemistry                                     0.477279   0.011621  41.072072
Computer.Science                              0.927290   0.042698  21.717591
Decision.Sciences                             1.197490   0.201165   5.952789
Dentistry                                     1.960595   0.142634  13.745642
Earth.and.Planetary.Sciences                  0.760390   0.016270  46.737093
Economics..Econometrics.and.Finance          -0.510521   0.394895  -1.292804
Energy                                        0.268183   0.018632  14.394005
Engineering                                   0.332188   0.010945  30.352053
Environmental.Science                         0.537661   0.018755  28.667773
Health.Professions                            1.586607   0.138300  11.472236
Immunology.and.Microbiology                   0.248990   0.028952   8.600069
Materials.Science                             0.056886   0.010343   5.499901
Mathematics                                   0.602069   0.129871   4.635881
Medicine                                      0.849262   0.015711  54.054321
Neuroscience                                  0.503519   0.034481  14.602937
Nursing                                       1.071113   0.046614  22.978439
Pharmacology..Toxicology.and.Pharmaceutics    0.879725   0.050960  17.263052
Physics.and.Astronomy                        -0.252876   0.011948 -21.164588
Psychology                                    0.423952   0.166430   2.547331
Social.Sciences                              -0.039225   0.174907  -0.224260
Veterinary                                    0.549516   0.231276   2.376016
                                               Pr(>|z|)
ratio_fac_scientist                          5.8378e-07 ***
I(ratio_fac_scientist^2)                     4.0042e-02 *
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   8.8247e-06 ***
lnnum_reference                              1.0672e-10 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            1.9940e-01
lnlast_avgimpact                              < 2.2e-16 ***
lnlast_insthindex                            4.3697e-05 ***
last_GlobalSouthGlobalNorth                   < 2.2e-16 ***
last_SameCountrySame                          < 2.2e-16 ***
knowledge_proximity_mean                     4.9814e-06 ***
lnlast_before_year_prod_fac                   < 2.2e-16 ***
last_before_year_with_ih_binTrue              < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          4.1259e-03 **
Chemical.Engineering                          < 2.2e-16 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            2.6361e-09 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          1.9608e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                   < 2.2e-16 ***
Materials.Science                            3.8000e-08 ***
Mathematics                                  3.5542e-06 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   1.0855e-02 *
Social.Sciences                              8.2256e-01
Veterinary                                   1.7501e-02 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -166,718.0   Adj. Pseudo R2: 0.057968
           BIC:  334,587.6     Squared Cor.: 0.073811

In [59]:
# library(marginaleffects)
# # 设置 draw = FALSE，直接拦截绘图数据
# plot_data <- plot_predictions(model_h3_pratio, condition = "ratio_fac_scientist", draw = FALSE)
# # 选出我们最需要的几列：x轴变量、预测值(estimate)、置信区间下限(conf.low)、上限(conf.high)
# export_data <- plot_data[, c("ratio_fac_scientist", "estimate", "conf.low", "conf.high")]
# # # 导出为 CSV 文件，给 Python 准备
# write.csv(export_data, "R_ex_ld_h3_pred_pratio.csv", row.names = FALSE)
# export_data
# # print("数据已成功导出！")
# # head(export_data)

In [60]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_h3_pratio,
                           keep = c("ratio_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   ratio\_fac\_scientist                        & 0.296$^{***}$\\
                                                & (0.059)\\
   ratio\_fac\_scientist square                 & -0.146$^{**}$\\
                                                & (0.071)\\
   lnnum\_author                                & -0.118$^{***}$\\
                                                & (0.007)\\
   internationalinternational                   & -0.044$^{***}$\\
                                                & (0.010)\\
   lnnum\_reference                             & 0.058$^{***}$\\
                                                & (0.009)\\
   num\_fac                                     & 0.076$^{***}$\\
                                                & (0.007)\\
   SDGTrue                                      & 0.074$^{***}$\\
                                                & (0.009)\\
   lnmean\_career\_age                          & -0.017\\
                                                & (0.013)\\
   lnlast\_avgimpact                            & -0.245$^{***}$\\
                                                & (0.006)\\
   lnlast\_insthindex                           & -0.024$^{***}$\\
                                                & (0.006)\\
   last\_GlobalSouthGlobalNorth                 & 0.304$^{***}$\\
                                                & (0.018)\\
   last\_SameCountrySame                        & -0.080$^{***}$\\
                                                & (0.010)\\
   knowledge\_proximity\_mean                   & -0.700$^{***}$\\
                                                & (0.153)\\
   lnlast\_before\_year\_prod\_fac              & -0.044$^{***}$\\
                                                & (0.004)\\
   last\_before\_year\_with\_ih\_binTrue        & 0.214$^{***}$\\
                                                & (0.011)\\
   Agricultural.and.Biological.Sciences         & 0.790$^{***}$\\
                                                & (0.026)\\
   Arts.and.Humanities                          & 1.81$^{***}$\\
                                                & (0.080)\\
   Biochemistry..Genetics.and.Molecular.Biology & 0.629$^{***}$\\
                                                & (0.013)\\
   Business..Management.and.Accounting          & -0.253$^{***}$\\
                                                & (0.088)\\
   Chemical.Engineering                         & 0.195$^{***}$\\
                                                & (0.022)\\
   Chemistry                                    & 0.477$^{***}$\\
                                                & (0.012)\\
   Computer.Science                             & 0.927$^{***}$\\
                                                & (0.043)\\
   Decision.Sciences                            & 1.20$^{***}$\\
                                                & (0.201)\\
   Dentistry                                    & 1.96$^{***}$\\
                                                & (0.143)\\
   Earth.and.Planetary.Sciences                 & 0.760$^{***}$\\
                                                & (0.016)\\
   Economics..Econometrics.and.Finance          & -0.511\\
                                                & (0.395)\\
   Energy                                       & 0.268$^{***}$\\
                                                & (0.019)\\
   Engineering                                  & 0.332$^{***}$\\
                                                & (0.011)\\
   Immunology.and.Microbiology                  & 0.249$^{***}$\\
                                                & (0.029)\\
   Materials.Science                            & 0.057$^{***}$\\
                                                & (0.010)\\
   Mathematics                                  & 0.602$^{***}$\\
                                                & (0.130)\\
   Medicine                                     & 0.849$^{***}$\\
                                                & (0.016)\\
   Neuroscience                                 & 0.504$^{***}$\\
                                                & (0.035)\\
   Nursing                                      & 1.07$^{***}$\\
                                                & (0.047)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 0.880$^{***}$\\
                                                & (0.051)\\
   Physics.and.Astronomy                        & -0.253$^{***}$\\
                                                & (0.012)\\
   Psychology                                   & 0.424$^{**}$\\
                                                & (0.166)\\
   Social.Sciences                              & -0.039\\
                                                & (0.175)\\
   Veterinary                                   & 0.550$^{**}$\\
                                                & (0.231)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 273,125\\
   Squared Correlation                          & 0.07381\\
   Pseudo R$^2$                                 & 0.05848\\
   BIC                                          & 334,587.6\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

# H3b: Lead too much not good

In [61]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ fac_scientist_lead_ratio + I(fac_scientist_lead_ratio^2) +  ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_h3_lratio <- feglm(fml, data = data[(data$paper_type =='article')&(data$CoType_Service==0)&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_h3_lratio)

NOTE: 11,714 observations removed because of NA values (LHS: 11,714, RHS: 11,714, Fixed-effects: 11,714).

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 79,026
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
fac_scientist_lead_ratio                      0.155046   0.085590   1.811493
I(fac_scientist_lead_ratio^2)                -0.115490   0.087596  -1.318435
lnnum_author                                 -0.292740   0.014790 -19.793746
internationalinternational                   -0.094049   0.020934  -4.492646
lnnum_reference                               0.121685   0.017538   6.938450
num_fac                                       0.110344   0.010491  10.518264
SDGTrue                                       0.079599   0.016496   4.825440
lnmean_career_age                            -0.156374   0.029119  -5.370200
lnlast_avgimpact                             -0.160841   0.012664 -12.700495
lnlast_insthindex                            -0.057822   0.011084  -5.216628
last_GlobalSouthGlobalNorth                   0.513425   0.036015  14.256052
last_SameCountrySame                         -0.142582   0.019278  -7.396018
knowledge_proximity_mean                     -0.132880   0.293957  -0.452038
lnlast_before_year_prod_fac                  -0.005355   0.007967  -0.672145
last_before_year_with_ih_binTrue             -0.052571   0.028880  -1.820318
Agricultural.and.Biological.Sciences          0.546778   0.052924  10.331358
Arts.and.Humanities                           2.194766   0.132806  16.526167
Biochemistry..Genetics.and.Molecular.Biology  0.869196   0.026679  32.579183
Business..Management.and.Accounting          -0.346014   0.140367  -2.465071
Chemical.Engineering                          0.271003   0.045104   6.008420
Chemistry                                     0.449304   0.023015  19.522181
Computer.Science                              0.867547   0.090018   9.637536
Decision.Sciences                             1.252863   0.328603   3.812696
Dentistry                                     1.804960   0.260642   6.925043
Earth.and.Planetary.Sciences                  0.940734   0.028264  33.283342
Economics..Econometrics.and.Finance          -0.345561   0.598523  -0.577356
Energy                                        0.318634   0.037177   8.570638
Engineering                                   0.345112   0.020201  17.083576
Environmental.Science                         0.736631   0.040825  18.043838
Health.Professions                            1.615730   0.244345   6.612493
Immunology.and.Microbiology                   0.136327   0.108874   1.252159
Materials.Science                            -0.078887   0.019637  -4.017192
Mathematics                                   0.323930   0.215067   1.506178
Medicine                                      1.287568   0.040984  31.416333
Neuroscience                                  0.590651   0.085538   6.905167
Nursing                                       1.807597   0.147293  12.272076
Pharmacology..Toxicology.and.Pharmaceutics    1.097065   0.150913   7.269528
Physics.and.Astronomy                        -0.343948   0.020558 -16.730435
Psychology                                   -0.619739   0.384007  -1.613874
Social.Sciences                              -0.348233   0.261675  -1.330783
Veterinary                                    0.241375   0.734936   0.328430
                                               Pr(>|z|)
fac_scientist_lead_ratio                     7.0065e-02 .
I(fac_scientist_lead_ratio^2)                1.8736e-01
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   7.0344e-06 ***
lnnum_reference                              3.9642e-12 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                      1.3969e-06 ***
lnmean_career_age                            7.8649e-08 ***
lnlast_avgimpact                              < 2.2e-16 ***
lnlast_insthindex                            1.8221e-07 ***
last_GlobalSouthGlobalNorth                   < 2.2e-16 ***
last_SameCountrySame                         1.4033e-13 ***
knowledge_proximity_mean                     6.5124e-01
lnlast_before_year_prod_fac                  5.0149e-01
last_before_year_with_ih_binTrue             6.8711e-02 .
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          1.3699e-02 *
Chemical.Engineering                         1.8734e-09 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            1.3746e-04 ***
Dentistry                                    4.3584e-12 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          5.6370e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                           3.7790e-11 ***
Immunology.and.Microbiology                  2.1051e-01
Materials.Science                            5.8896e-05 ***
Mathematics                                  1.3202e-01
Medicine                                      < 2.2e-16 ***
Neuroscience                                 5.0144e-12 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics   3.6074e-13 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   1.0655e-01
Social.Sciences                              1.8326e-01
Veterinary                                   7.4259e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -46,005.4   Adj. Pseudo R2: 0.094569
           BIC:  93,048.4     Squared Cor.: 0.119361

In [62]:
# library(marginaleffects)
# # 设置 draw = FALSE，直接拦截绘图数据
# plot_data <- plot_predictions(model_h3_lratio, condition = "fac_scientist_lead_ratio", draw = FALSE)
# # 选出我们最需要的几列：x轴变量、预测值(estimate)、置信区间下限(conf.low)、上限(conf.high)
# export_data <- plot_data[, c("fac_scientist_lead_ratio", "estimate", "conf.low", "conf.high")]
# # # 导出为 CSV 文件，给 Python 准备
# write.csv(export_data, "R_ex_ld_h3_pred_lratio.csv", row.names = FALSE)
# export_data
# # print("数据已成功导出！")
# # head(export_data)

In [63]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_h3_lratio,
                           keep = c("fac_scientist_lead_ratio", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   fac\_scientist\_lead\_ratio                  & 0.155$^{*}$\\
                                                & (0.086)\\
   fac\_scientist\_lead\_ratio square           & -0.115\\
                                                & (0.088)\\
   lnnum\_author                                & -0.293$^{***}$\\
                                                & (0.015)\\
   internationalinternational                   & -0.094$^{***}$\\
                                                & (0.021)\\
   lnnum\_reference                             & 0.122$^{***}$\\
                                                & (0.018)\\
   num\_fac                                     & 0.110$^{***}$\\
                                                & (0.011)\\
   SDGTrue                                      & 0.080$^{***}$\\
                                                & (0.017)\\
   lnmean\_career\_age                          & -0.156$^{***}$\\
                                                & (0.029)\\
   lnlast\_avgimpact                            & -0.161$^{***}$\\
                                                & (0.013)\\
   lnlast\_insthindex                           & -0.058$^{***}$\\
                                                & (0.011)\\
   last\_GlobalSouthGlobalNorth                 & 0.513$^{***}$\\
                                                & (0.036)\\
   last\_SameCountrySame                        & -0.143$^{***}$\\
                                                & (0.019)\\
   knowledge\_proximity\_mean                   & -0.133\\
                                                & (0.294)\\
   lnlast\_before\_year\_prod\_fac              & -0.005\\
                                                & (0.008)\\
   last\_before\_year\_with\_ih\_binTrue        & -0.053$^{*}$\\
                                                & (0.029)\\
   Agricultural.and.Biological.Sciences         & 0.547$^{***}$\\
                                                & (0.053)\\
   Arts.and.Humanities                          & 2.19$^{***}$\\
                                                & (0.133)\\
   Biochemistry..Genetics.and.Molecular.Biology & 0.869$^{***}$\\
                                                & (0.027)\\
   Business..Management.and.Accounting          & -0.346$^{**}$\\
                                                & (0.140)\\
   Chemical.Engineering                         & 0.271$^{***}$\\
                                                & (0.045)\\
   Chemistry                                    & 0.449$^{***}$\\
                                                & (0.023)\\
   Computer.Science                             & 0.868$^{***}$\\
                                                & (0.090)\\
   Decision.Sciences                            & 1.25$^{***}$\\
                                                & (0.329)\\
   Dentistry                                    & 1.80$^{***}$\\
                                                & (0.261)\\
   Earth.and.Planetary.Sciences                 & 0.941$^{***}$\\
                                                & (0.028)\\
   Economics..Econometrics.and.Finance          & -0.346\\
                                                & (0.599)\\
   Energy                                       & 0.319$^{***}$\\
                                                & (0.037)\\
   Engineering                                  & 0.345$^{***}$\\
                                                & (0.020)\\
   Immunology.and.Microbiology                  & 0.136\\
                                                & (0.109)\\
   Materials.Science                            & -0.079$^{***}$\\
                                                & (0.020)\\
   Mathematics                                  & 0.324\\
                                                & (0.215)\\
   Medicine                                     & 1.29$^{***}$\\
                                                & (0.041)\\
   Neuroscience                                 & 0.591$^{***}$\\
                                                & (0.086)\\
   Nursing                                      & 1.81$^{***}$\\
                                                & (0.147)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 1.10$^{***}$\\
                                                & (0.151)\\
   Physics.and.Astronomy                        & -0.344$^{***}$\\
                                                & (0.021)\\
   Psychology                                   & -0.620\\
                                                & (0.384)\\
   Social.Sciences                              & -0.348\\
                                                & (0.262)\\
   Veterinary                                   & 0.241\\
                                                & (0.735)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 79,026\\
   Squared Correlation                          & 0.11936\\
   Pseudo R$^2$                                 & 0.09636\\
   BIC                                          & 93,048.4\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

# Moderating

In [64]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType*lnlast_before_year_prod_fac  + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_pre_facpub <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_pre_facpub)

NOTE: 42,366 observations removed because of NA values (LHS: 42,366, RHS: 42,366, Fixed-effects: 42,366).

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 273,125
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                                 Estimate Std. Error    z value
CoTypeCollaboration                              0.076306   0.024685   3.091205
CoTypeParticipation                              0.117481   0.033229   3.535496
lnlast_before_year_prod_fac                     -0.042988   0.004662  -9.221010
lnnum_author                                    -0.118879   0.007626 -15.589392
internationalinternational                      -0.046631   0.009771  -4.772249
lnnum_reference                                  0.057209   0.009042   6.327173
num_fac                                          0.076996   0.006929  11.111954
SDGTrue                                          0.074033   0.008523   8.686566
lnmean_career_age                               -0.019992   0.013453  -1.486101
lnlast_avgimpact                                -0.244792   0.006356 -38.513641
lnlast_insthindex                               -0.023389   0.005966  -3.920755
last_GlobalSouthGlobalNorth                      0.303390   0.017880  16.968141
last_SameCountrySame                            -0.081333   0.009602  -8.470721
knowledge_proximity_mean                        -0.700619   0.153149  -4.574742
last_before_year_with_ih_binTrue                 0.211481   0.011403  18.545421
Agricultural.and.Biological.Sciences             0.789087   0.025551  30.882609
Arts.and.Humanities                              1.810534   0.079868  22.669127
Biochemistry..Genetics.and.Molecular.Biology     0.628678   0.013175  47.718064
Business..Management.and.Accounting             -0.256987   0.088352  -2.908667
Chemical.Engineering                             0.195577   0.021685   9.019068
Chemistry                                        0.476806   0.011621  41.029909
Computer.Science                                 0.926747   0.042685  21.711412
Decision.Sciences                                1.193668   0.200863   5.942710
Dentistry                                        1.958599   0.142753  13.720162
Earth.and.Planetary.Sciences                     0.759515   0.016274  46.670056
Economics..Econometrics.and.Finance             -0.511892   0.394734  -1.296801
Energy                                           0.267310   0.018639  14.341591
Engineering                                      0.331990   0.010944  30.336259
Environmental.Science                            0.537197   0.018748  28.653500
Health.Professions                               1.586952   0.138413  11.465304
Immunology.and.Microbiology                      0.248919   0.028953   8.597355
Materials.Science                                0.056556   0.010342   5.468700
Mathematics                                      0.603403   0.129719   4.651619
Medicine                                         0.849417   0.015714  54.056352
Neuroscience                                     0.503015   0.034481  14.588056
Nursing                                          1.070846   0.046599  22.979876
Pharmacology..Toxicology.and.Pharmaceutics       0.880329   0.050980  17.268199
Physics.and.Astronomy                           -0.252412   0.011935 -21.148207
Psychology                                       0.423708   0.166391   2.546463
Social.Sciences                                 -0.045646   0.174661  -0.261341
Veterinary                                       0.552840   0.231426   2.388842
CoTypeCollaboration:lnlast_before_year_prod_fac  0.012083   0.007812   1.546741
CoTypeParticipation:lnlast_before_year_prod_fac -0.042164   0.011062  -3.811451
                                                  Pr(>|z|)
CoTypeCollaboration                             1.9935e-03 **
CoTypeParticipation                             4.0701e-04 ***
lnlast_before_year_prod_fac                      < 2.2e-16 ***
lnnum_author                                     < 2.2e-16 ***
internationalinternational                      1.8218e-06 ***
lnnum_reference                                 2.4969e-10 ***
num_fac                                          < 2.2e-16 ***
SDGTrue                                          < 2.2e-16 ***
lnmean_career_age                               1.3725e-01
lnlast_avgimpact                                 < 2.2e-16 ***
lnlast_insthindex                               8.8272e-05 ***
last_GlobalSouthGlobalNorth                      < 2.2e-16 ***
last_SameCountrySame                             < 2.2e-16 ***
knowledge_proximity_mean                        4.7681e-06 ***
last_before_year_with_ih_binTrue                 < 2.2e-16 ***
Agricultural.and.Biological.Sciences             < 2.2e-16 ***
Arts.and.Humanities                              < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology     < 2.2e-16 ***
Business..Management.and.Accounting             3.6297e-03 **
Chemical.Engineering                             < 2.2e-16 ***
Chemistry                                        < 2.2e-16 ***
Computer.Science                                 < 2.2e-16 ***
Decision.Sciences                               2.8035e-09 ***
Dentistry                                        < 2.2e-16 ***
Earth.and.Planetary.Sciences                     < 2.2e-16 ***
Economics..Econometrics.and.Finance             1.9470e-01
Energy                                           < 2.2e-16 ***
Engineering                                      < 2.2e-16 ***
Environmental.Science                            < 2.2e-16 ***
Health.Professions                               < 2.2e-16 ***
Immunology.and.Microbiology                      < 2.2e-16 ***
Materials.Science                               4.5335e-08 ***
Mathematics                                     3.2934e-06 ***
Medicine                                         < 2.2e-16 ***
Neuroscience                                     < 2.2e-16 ***
Nursing                                          < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics       < 2.2e-16 ***
Physics.and.Astronomy                            < 2.2e-16 ***
Psychology                                      1.0882e-02 *
Social.Sciences                                 7.9383e-01
Veterinary                                      1.6902e-02 *
CoTypeCollaboration:lnlast_before_year_prod_fac 1.2193e-01
CoTypeParticipation:lnlast_before_year_prod_fac 1.3815e-04 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -166,695.8   Adj. Pseudo R2: 0.058082
           BIC:  334,568.2     Squared Cor.: 0.073952

In [65]:
# # 1. 找到你这个连续变量的实际最小值和最大值（假设是 0 和 10，你需要改成你的实际极值）
# min_val <- min(data$lnex_ld_avg_before_year_prod_fac, na.rm=TRUE)
# max_val <- max(data$lnex_ld_avg_before_year_prod_fac, na.rm=TRUE)
# # 2. 运行估计
# res_pre_facpub <- avg_comparisons(
#     model_pre_facpub,
#     variables = "CoType",
#     comparison = "ratio",
#     newdata = datagrid(
#     model = model_pre_facpub,
#     lnex_ld_avg_before_year_prod_fac = seq(min_val, max_val, length.out = 50) # 这里的 10 可以改成任意你想要的数字
#   ),
#     by = "lnex_ld_avg_before_year_prod_fac"
# )
# res_pre_facpub

In [66]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h4_comp_pre_facpub.csv")
# write.csv(res_pre_facpub, fname, row.names = FALSE)

In [67]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_pre_facpub,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                               & novel\_uzzi\_bin\\
   Model:                                                            & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                                               & 0.076$^{***}$\\
                                                                     & (0.025)\\
   CoTypeParticipation                                               & 0.117$^{***}$\\
                                                                     & (0.033)\\
   lnlast\_before\_year\_prod\_fac                                   & -0.043$^{***}$\\
                                                                     & (0.005)\\
   lnnum\_author                                                     & -0.119$^{***}$\\
                                                                     & (0.008)\\
   internationalinternational                                        & -0.047$^{***}$\\
                                                                     & (0.010)\\
   lnnum\_reference                                                  & 0.057$^{***}$\\
                                                                     & (0.009)\\
   num\_fac                                                          & 0.077$^{***}$\\
                                                                     & (0.007)\\
   SDGTrue                                                           & 0.074$^{***}$\\
                                                                     & (0.009)\\
   lnmean\_career\_age                                               & -0.020\\
                                                                     & (0.013)\\
   lnlast\_avgimpact                                                 & -0.245$^{***}$\\
                                                                     & (0.006)\\
   lnlast\_insthindex                                                & -0.023$^{***}$\\
                                                                     & (0.006)\\
   last\_GlobalSouthGlobalNorth                                      & 0.303$^{***}$\\
                                                                     & (0.018)\\
   last\_SameCountrySame                                             & -0.081$^{***}$\\
                                                                     & (0.010)\\
   knowledge\_proximity\_mean                                        & -0.701$^{***}$\\
                                                                     & (0.153)\\
   last\_before\_year\_with\_ih\_binTrue                             & 0.211$^{***}$\\
                                                                     & (0.011)\\
   Agricultural.and.Biological.Sciences                              & 0.789$^{***}$\\
                                                                     & (0.026)\\
   Arts.and.Humanities                                               & 1.81$^{***}$\\
                                                                     & (0.080)\\
   Biochemistry..Genetics.and.Molecular.Biology                      & 0.629$^{***}$\\
                                                                     & (0.013)\\
   Business..Management.and.Accounting                               & -0.257$^{***}$\\
                                                                     & (0.088)\\
   Chemical.Engineering                                              & 0.196$^{***}$\\
                                                                     & (0.022)\\
   Chemistry                                                         & 0.477$^{***}$\\
                                                                     & (0.012)\\
   Computer.Science                                                  & 0.927$^{***}$\\
                                                                     & (0.043)\\
   Decision.Sciences                                                 & 1.19$^{***}$\\
                                                                     & (0.201)\\
   Dentistry                                                         & 1.96$^{***}$\\
                                                                     & (0.143)\\
   Earth.and.Planetary.Sciences                                      & 0.760$^{***}$\\
                                                                     & (0.016)\\
   Economics..Econometrics.and.Finance                               & -0.512\\
                                                                     & (0.395)\\
   Energy                                                            & 0.267$^{***}$\\
                                                                     & (0.019)\\
   Engineering                                                       & 0.332$^{***}$\\
                                                                     & (0.011)\\
   Immunology.and.Microbiology                                       & 0.249$^{***}$\\
                                                                     & (0.029)\\
   Materials.Science                                                 & 0.057$^{***}$\\
                                                                     & (0.010)\\
   Mathematics                                                       & 0.603$^{***}$\\
                                                                     & (0.130)\\
   Medicine                                                          & 0.849$^{***}$\\
                                                                     & (0.016)\\
   Neuroscience                                                      & 0.503$^{***}$\\
                                                                     & (0.035)\\
   Nursing                                                           & 1.07$^{***}$\\
                                                                     & (0.047)\\
   Pharmacology..Toxicology.and.Pharmaceutics                        & 0.880$^{***}$\\
                                                                     & (0.051)\\
   Physics.and.Astronomy                                             & -0.252$^{***}$\\
                                                                     & (0.012)\\
   Psychology                                                        & 0.424$^{**}$\\
                                                                     & (0.166)\\
   Social.Sciences                                                   & -0.046\\
                                                                     & (0.175)\\
   Veterinary                                                        & 0.553$^{**}$\\
                                                                     & (0.231)\\
   CoTypeCollaboration $\times$ lnlast\_before\_year\_prod\_fac      & 0.012\\
                                                                     & (0.008)\\
   CoTypeParticipation $\times$ lnlast\_before\_year\_prod\_fac      & -0.042$^{***}$\\
                                                                     & (0.011)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                                     & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                                      & 273,125\\
   Squared Correlation                                               & 0.07395\\
   Pseudo R$^2$                                                      & 0.05861\\
   BIC                                                               & 334,568.2\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [68]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType*last_before_year_with_ih_bin  + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_pre_withih <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_pre_withih)

NOTE: 42,366 observations removed because of NA values (LHS: 42,366, RHS: 42,366, Fixed-effects: 42,366).

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 273,125
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                                      Estimate Std. Error
CoTypeCollaboration                                   0.249419   0.026883
CoTypeParticipation                                   0.289234   0.034839
last_before_year_with_ih_binTrue                      0.244757   0.011864
lnnum_author                                         -0.117487   0.007632
internationalinternational                           -0.048562   0.009772
lnnum_reference                                       0.057623   0.009043
num_fac                                               0.077171   0.006907
SDGTrue                                               0.073949   0.008524
lnmean_career_age                                    -0.021512   0.013455
lnlast_avgimpact                                     -0.245370   0.006358
lnlast_insthindex                                    -0.025488   0.005955
last_GlobalSouthGlobalNorth                           0.305511   0.017874
last_SameCountrySame                                 -0.081143   0.009596
knowledge_proximity_mean                             -0.669177   0.153253
lnlast_before_year_prod_fac                          -0.039888   0.004089
Agricultural.and.Biological.Sciences                  0.786197   0.025555
Arts.and.Humanities                                   1.806954   0.079996
Biochemistry..Genetics.and.Molecular.Biology          0.630790   0.013179
Business..Management.and.Accounting                  -0.257907   0.088178
Chemical.Engineering                                  0.195588   0.021679
Chemistry                                             0.475757   0.011624
Computer.Science                                      0.926755   0.042688
Decision.Sciences                                     1.190739   0.200849
Dentistry                                             1.955134   0.142805
Earth.and.Planetary.Sciences                          0.759866   0.016267
Economics..Econometrics.and.Finance                  -0.511826   0.395449
Energy                                                0.266112   0.018642
Engineering                                           0.330404   0.010947
Environmental.Science                                 0.538023   0.018742
Health.Professions                                    1.584242   0.138832
Immunology.and.Microbiology                           0.251108   0.028983
Materials.Science                                     0.055351   0.010346
Mathematics                                           0.606843   0.130039
Medicine                                              0.851633   0.015728
Neuroscience                                          0.503205   0.034517
Nursing                                               1.070980   0.046622
Pharmacology..Toxicology.and.Pharmaceutics            0.882762   0.051025
Physics.and.Astronomy                                -0.252668   0.011931
Psychology                                            0.436083   0.166277
Social.Sciences                                      -0.055987   0.174802
Veterinary                                            0.555237   0.232119
CoTypeCollaboration:last_before_year_with_ih_binTrue -0.174788   0.029349
CoTypeParticipation:last_before_year_with_ih_binTrue -0.357039   0.038458
                                                        z value   Pr(>|z|)
CoTypeCollaboration                                    9.277952  < 2.2e-16 ***
CoTypeParticipation                                    8.301983  < 2.2e-16 ***
last_before_year_with_ih_binTrue                      20.630462  < 2.2e-16 ***
lnnum_author                                         -15.394089  < 2.2e-16 ***
internationalinternational                            -4.969301 6.7195e-07 ***
lnnum_reference                                        6.372170 1.8637e-10 ***
num_fac                                               11.172169  < 2.2e-16 ***
SDGTrue                                                8.675082  < 2.2e-16 ***
lnmean_career_age                                     -1.598750 1.0988e-01
lnlast_avgimpact                                     -38.592953  < 2.2e-16 ***
lnlast_insthindex                                     -4.280283 1.8666e-05 ***
last_GlobalSouthGlobalNorth                           17.092436  < 2.2e-16 ***
last_SameCountrySame                                  -8.455906  < 2.2e-16 ***
knowledge_proximity_mean                              -4.366486 1.2626e-05 ***
lnlast_before_year_prod_fac                           -9.755496  < 2.2e-16 ***
Agricultural.and.Biological.Sciences                  30.764752  < 2.2e-16 ***
Arts.and.Humanities                                   22.588087  < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology          47.862459  < 2.2e-16 ***
Business..Management.and.Accounting                   -2.924852 3.4462e-03 **
Chemical.Engineering                                   9.022148  < 2.2e-16 ***
Chemistry                                             40.929913  < 2.2e-16 ***
Computer.Science                                      21.710064  < 2.2e-16 ***
Decision.Sciences                                      5.928539 3.0564e-09 ***
Dentistry                                             13.690912  < 2.2e-16 ***
Earth.and.Planetary.Sciences                          46.712477  < 2.2e-16 ***
Economics..Econometrics.and.Finance                   -1.294289 1.9557e-01
Energy                                                14.274922  < 2.2e-16 ***
Engineering                                           30.183190  < 2.2e-16 ***
Environmental.Science                                 28.706724  < 2.2e-16 ***
Health.Professions                                    11.411245  < 2.2e-16 ***
Immunology.and.Microbiology                            8.663990  < 2.2e-16 ***
Materials.Science                                      5.349975 8.7967e-08 ***
Mathematics                                            4.666637 3.0617e-06 ***
Medicine                                              54.148241  < 2.2e-16 ***
Neuroscience                                          14.578500  < 2.2e-16 ***
Nursing                                               22.971772  < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics            17.300540  < 2.2e-16 ***
Physics.and.Astronomy                                -21.177004  < 2.2e-16 ***
Psychology                                             2.622630 8.7254e-03 **
Social.Sciences                                       -0.320290 7.4875e-01
Veterinary                                             2.392036 1.6755e-02 *
CoTypeCollaboration:last_before_year_with_ih_binTrue  -5.955485 2.5930e-09 ***
CoTypeParticipation:last_before_year_with_ih_binTrue  -9.283864  < 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -166,651.2   Adj. Pseudo R2: 0.058334
           BIC:  334,479.1     Squared Cor.: 0.074276

In [70]:
# 每组 reg_class 的平均预测概率
# res_pre_withih <- avg_comparisons(model_pre_withih, variables = "CoType", comparison = 'ratio', by = 'ex_ld_max_before_year_with_ih_bin')
# res_pre_withih

In [71]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h4_comp_pre_withih.csv")
# write.csv(res_pre_withih, fname, row.names = FALSE)

In [72]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_pre_withih,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                                      & novel\_uzzi\_bin\\
   Model:                                                                   & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                                                      & 0.249$^{***}$\\
                                                                            & (0.027)\\
   CoTypeParticipation                                                      & 0.289$^{***}$\\
                                                                            & (0.035)\\
   last\_before\_year\_with\_ih\_binTrue                                    & 0.245$^{***}$\\
                                                                            & (0.012)\\
   lnnum\_author                                                            & -0.117$^{***}$\\
                                                                            & (0.008)\\
   internationalinternational                                               & -0.049$^{***}$\\
                                                                            & (0.010)\\
   lnnum\_reference                                                         & 0.058$^{***}$\\
                                                                            & (0.009)\\
   num\_fac                                                                 & 0.077$^{***}$\\
                                                                            & (0.007)\\
   SDGTrue                                                                  & 0.074$^{***}$\\
                                                                            & (0.009)\\
   lnmean\_career\_age                                                      & -0.021\\
                                                                            & (0.013)\\
   lnlast\_avgimpact                                                        & -0.245$^{***}$\\
                                                                            & (0.006)\\
   lnlast\_insthindex                                                       & -0.025$^{***}$\\
                                                                            & (0.006)\\
   last\_GlobalSouthGlobalNorth                                             & 0.306$^{***}$\\
                                                                            & (0.018)\\
   last\_SameCountrySame                                                    & -0.081$^{***}$\\
                                                                            & (0.010)\\
   knowledge\_proximity\_mean                                               & -0.669$^{***}$\\
                                                                            & (0.153)\\
   lnlast\_before\_year\_prod\_fac                                          & -0.040$^{***}$\\
                                                                            & (0.004)\\
   Agricultural.and.Biological.Sciences                                     & 0.786$^{***}$\\
                                                                            & (0.026)\\
   Arts.and.Humanities                                                      & 1.81$^{***}$\\
                                                                            & (0.080)\\
   Biochemistry..Genetics.and.Molecular.Biology                             & 0.631$^{***}$\\
                                                                            & (0.013)\\
   Business..Management.and.Accounting                                      & -0.258$^{***}$\\
                                                                            & (0.088)\\
   Chemical.Engineering                                                     & 0.196$^{***}$\\
                                                                            & (0.022)\\
   Chemistry                                                                & 0.476$^{***}$\\
                                                                            & (0.012)\\
   Computer.Science                                                         & 0.927$^{***}$\\
                                                                            & (0.043)\\
   Decision.Sciences                                                        & 1.19$^{***}$\\
                                                                            & (0.201)\\
   Dentistry                                                                & 1.96$^{***}$\\
                                                                            & (0.143)\\
   Earth.and.Planetary.Sciences                                             & 0.760$^{***}$\\
                                                                            & (0.016)\\
   Economics..Econometrics.and.Finance                                      & -0.512\\
                                                                            & (0.395)\\
   Energy                                                                   & 0.266$^{***}$\\
                                                                            & (0.019)\\
   Engineering                                                              & 0.330$^{***}$\\
                                                                            & (0.011)\\
   Immunology.and.Microbiology                                              & 0.251$^{***}$\\
                                                                            & (0.029)\\
   Materials.Science                                                        & 0.055$^{***}$\\
                                                                            & (0.010)\\
   Mathematics                                                              & 0.607$^{***}$\\
                                                                            & (0.130)\\
   Medicine                                                                 & 0.852$^{***}$\\
                                                                            & (0.016)\\
   Neuroscience                                                             & 0.503$^{***}$\\
                                                                            & (0.035)\\
   Nursing                                                                  & 1.07$^{***}$\\
                                                                            & (0.047)\\
   Pharmacology..Toxicology.and.Pharmaceutics                               & 0.883$^{***}$\\
                                                                            & (0.051)\\
   Physics.and.Astronomy                                                    & -0.253$^{***}$\\
                                                                            & (0.012)\\
   Psychology                                                               & 0.436$^{***}$\\
                                                                            & (0.166)\\
   Social.Sciences                                                          & -0.056\\
                                                                            & (0.175)\\
   Veterinary                                                               & 0.555$^{**}$\\
                                                                            & (0.232)\\
   CoTypeCollaboration $\times$ last\_before\_year\_with\_ih\_binTrue       & -0.175$^{***}$\\
                                                                            & (0.029)\\
   CoTypeParticipation $\times$ last\_before\_year\_with\_ih\_binTrue       & -0.357$^{***}$\\
                                                                            & (0.038)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                                            & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                                             & 273,125\\
   Squared Correlation                                                      & 0.07428\\
   Pseudo R$^2$                                                             & 0.05886\\
   BIC                                                                      & 334,479.1\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [73]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType*last_before_year_participation_bin  + ", paper_level, "+", ex_controls, "+", moderating2, "+",disciplines, " | PublishedYear")
)
model_pre_partic <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_pre_partic)

NOTE: 42,366 observations removed because of NA values (LHS: 42,366, RHS: 42,366, Fixed-effects: 42,366).

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 273,125
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                                            Estimate Std. Error
CoTypeCollaboration                                         0.186346   0.015898
CoTypeParticipation                                         0.213766   0.026615
last_before_year_participation_binTrue                      0.163061   0.012486
lnnum_author                                               -0.119524   0.007653
internationalinternational                                 -0.047122   0.009774
lnnum_reference                                             0.058090   0.009039
num_fac                                                     0.075449   0.006914
SDGTrue                                                     0.074118   0.008521
lnmean_career_age                                          -0.017495   0.013452
lnlast_avgimpact                                           -0.242966   0.006359
lnlast_insthindex                                          -0.024013   0.005949
last_GlobalSouthGlobalNorth                                 0.307609   0.017865
last_SameCountrySame                                       -0.085118   0.009613
knowledge_proximity_mean                                   -0.680990   0.153169
lnlast_before_year_prod_fac                                -0.022049   0.003905
Agricultural.and.Biological.Sciences                        0.794287   0.025525
Arts.and.Humanities                                         1.816088   0.079697
Biochemistry..Genetics.and.Molecular.Biology                0.623756   0.013177
Business..Management.and.Accounting                        -0.259712   0.088314
Chemical.Engineering                                        0.190378   0.021683
Chemistry                                                   0.481382   0.011612
Computer.Science                                            0.923434   0.042636
Decision.Sciences                                           1.194412   0.201011
Dentistry                                                   1.960137   0.142132
Earth.and.Planetary.Sciences                                0.761494   0.016279
Economics..Econometrics.and.Finance                        -0.519609   0.397370
Energy                                                      0.269856   0.018629
Engineering                                                 0.337984   0.010933
Environmental.Science                                       0.536450   0.018765
Health.Professions                                          1.591167   0.139032
Immunology.and.Microbiology                                 0.238666   0.028910
Materials.Science                                           0.061494   0.010334
Mathematics                                                 0.616756   0.129001
Medicine                                                    0.844973   0.015695
Neuroscience                                                0.502207   0.034429
Nursing                                                     1.076497   0.046651
Pharmacology..Toxicology.and.Pharmaceutics                  0.874133   0.050949
Physics.and.Astronomy                                      -0.246291   0.011930
Psychology                                                  0.415822   0.165554
Social.Sciences                                            -0.032390   0.175017
Veterinary                                                  0.558170   0.228696
CoTypeCollaboration:last_before_year_participation_binTrue -0.098285   0.021656
CoTypeParticipation:last_before_year_participation_binTrue -0.305365   0.032460
                                                              z value
CoTypeCollaboration                                         11.721104
CoTypeParticipation                                          8.031691
last_before_year_participation_binTrue                      13.059212
lnnum_author                                               -15.617035
internationalinternational                                  -4.821181
lnnum_reference                                              6.426930
num_fac                                                     10.913244
SDGTrue                                                      8.697847
lnmean_career_age                                           -1.300573
lnlast_avgimpact                                           -38.206309
lnlast_insthindex                                           -4.036327
last_GlobalSouthGlobalNorth                                 17.218611
last_SameCountrySame                                        -8.854850
knowledge_proximity_mean                                    -4.446017
lnlast_before_year_prod_fac                                 -5.646486
Agricultural.and.Biological.Sciences                        31.118574
Arts.and.Humanities                                         22.787287
Biochemistry..Genetics.and.Molecular.Biology                47.337726
Business..Management.and.Accounting                         -2.940776
Chemical.Engineering                                         8.780196
Chemistry                                                   41.455445
Computer.Science                                            21.658400
Decision.Sciences                                            5.942008
Dentistry                                                   13.790947
Earth.and.Planetary.Sciences                                46.776828
Economics..Econometrics.and.Finance                         -1.307619
Energy                                                      14.485877
Engineering                                                 30.915390
Environmental.Science                                       28.588295
Health.Professions                                          11.444586
Immunology.and.Microbiology                                  8.255524
Materials.Science                                            5.950464
Mathematics                                                  4.781029
Medicine                                                    53.838429
Neuroscience                                                14.586695
Nursing                                                     23.075678
Pharmacology..Toxicology.and.Pharmaceutics                  17.157103
Physics.and.Astronomy                                      -20.645552
Psychology                                                   2.511697
Social.Sciences                                             -0.185068
Veterinary                                                   2.440661
CoTypeCollaboration:last_before_year_participation_binTrue  -4.538479
CoTypeParticipation:last_before_year_participation_binTrue  -9.407315
                                                             Pr(>|z|)
CoTypeCollaboration                                         < 2.2e-16 ***
CoTypeParticipation                                        9.6138e-16 ***
last_before_year_participation_binTrue                      < 2.2e-16 ***
lnnum_author                                                < 2.2e-16 ***
internationalinternational                                 1.4271e-06 ***
lnnum_reference                                            1.3021e-10 ***
num_fac                                                     < 2.2e-16 ***
SDGTrue                                                     < 2.2e-16 ***
lnmean_career_age                                          1.9340e-01
lnlast_avgimpact                                            < 2.2e-16 ***
lnlast_insthindex                                          5.4295e-05 ***
last_GlobalSouthGlobalNorth                                 < 2.2e-16 ***
last_SameCountrySame                                        < 2.2e-16 ***
knowledge_proximity_mean                                   8.7477e-06 ***
lnlast_before_year_prod_fac                                1.6376e-08 ***
Agricultural.and.Biological.Sciences                        < 2.2e-16 ***
Arts.and.Humanities                                         < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology                < 2.2e-16 ***
Business..Management.and.Accounting                        3.2739e-03 **
Chemical.Engineering                                        < 2.2e-16 ***
Chemistry                                                   < 2.2e-16 ***
Computer.Science                                            < 2.2e-16 ***
Decision.Sciences                                          2.8155e-09 ***
Dentistry                                                   < 2.2e-16 ***
Earth.and.Planetary.Sciences                                < 2.2e-16 ***
Economics..Econometrics.and.Finance                        1.9100e-01
Energy                                                      < 2.2e-16 ***
Engineering                                                 < 2.2e-16 ***
Environmental.Science                                       < 2.2e-16 ***
Health.Professions                                          < 2.2e-16 ***
Immunology.and.Microbiology                                 < 2.2e-16 ***
Materials.Science                                          2.6738e-09 ***
Mathematics                                                1.7440e-06 ***
Medicine                                                    < 2.2e-16 ***
Neuroscience                                                < 2.2e-16 ***
Nursing                                                     < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics                  < 2.2e-16 ***
Physics.and.Astronomy                                       < 2.2e-16 ***
Psychology                                                 1.2015e-02 *
Social.Sciences                                            8.5318e-01
Veterinary                                                 1.4660e-02 *
CoTypeCollaboration:last_before_year_participation_binTrue 5.6662e-06 ***
CoTypeParticipation:last_before_year_participation_binTrue  < 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -166,777.8   Adj. Pseudo R2: 0.057619
           BIC:  334,732.2     Squared Cor.: 0.073351

In [ ]:
# 每组 reg_class 的平均预测概率
res_pre_partic <- avg_comparisons(model_pre_partic, variables = "CoType", comparison = 'ratio', by = 'ex_ld_max_before_year_participation_bin')
res_pre_partic

In [ ]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h4_comp_pre_partic.csv")
# write.csv(res_pre_partic, fname, row.names = FALSE)

In [ ]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_pre_partic,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

In [ ]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType*last_before_year_co_lead_bin  + ", paper_level, "+", ex_controls, "+", moderating3, "+",disciplines, " | PublishedYear")
)
model_pre_co_lead <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_pre_co_lead)

In [ ]:
# 每组 reg_class 的平均预测概率
res_pre_co_lead <- avg_comparisons(model_pre_co_lead, variables = "CoType", comparison = 'ratio', by = 'ex_ld_max_before_year_co_lead_bin')
res_pre_co_lead

In [ ]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h4_comp_pre_co_lead.csv")
# write.csv(res_pre_co_lead, fname, row.names = FALSE)

In [ ]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_pre_co_lead,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

# 补充一个更deep的point，曾经开展过“Co-lead”,后续合作/参与的收益受损更严重

In [88]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", disciplines, " | PublishedYear")
)
model1 <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model1)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
CoTypeCollaboration                           0.168124   0.010601  15.859520
CoTypeParticipation                           0.047151   0.014212   3.317634
Arts.and.Humanities                           1.837644   0.072240  25.438148
Biochemistry..Genetics.and.Molecular.Biology  0.498277   0.012207  40.818163
Business..Management.and.Accounting          -0.428431   0.087633  -4.888910
Chemical.Engineering                          0.131064   0.020722   6.324869
Chemistry                                     0.458689   0.010925  41.986380
Computer.Science                              0.896830   0.039192  22.883139
Decision.Sciences                             1.233745   0.187252   6.588695
Dentistry                                     1.993278   0.134826  14.784118
Earth.and.Planetary.Sciences                  0.736660   0.015022  49.039048
Economics..Econometrics.and.Finance          -0.125156   0.298301  -0.419561
Energy                                        0.173190   0.017787   9.737107
Engineering                                   0.339560   0.010213  33.249267
Environmental.Science                         0.570669   0.017255  33.072600
Health.Professions                            1.407273   0.128367  10.962920
Immunology.and.Microbiology                   0.100053   0.026312   3.802612
Materials.Science                             0.025108   0.009434   2.661385
Mathematics                                   0.563191   0.123799   4.549254
Medicine                                      0.768655   0.014474  53.104109
Neuroscience                                  0.459560   0.031942  14.387405
Nursing                                       1.152191   0.043429  26.530236
Pharmacology..Toxicology.and.Pharmaceutics    0.918273   0.047863  19.185553
Physics.and.Astronomy                        -0.258106   0.010956 -23.557539
Psychology                                    0.350436   0.151391   2.314773
Social.Sciences                               0.190551   0.160549   1.186869
Veterinary                                    0.572486   0.204304   2.802123
                                               Pr(>|z|)
CoTypeCollaboration                           < 2.2e-16 ***
CoTypeParticipation                          9.0783e-04 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          1.0140e-06 ***
Chemical.Engineering                         2.5345e-10 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            4.4371e-11 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          6.7481e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                  1.4318e-04 ***
Materials.Science                            7.7820e-03 **
Mathematics                                  5.3836e-06 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   2.0625e-02 *
Social.Sciences                              2.3528e-01
Veterinary                                   5.0767e-03 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -183,760.0   Adj. Pseudo R2: 0.047631
           BIC:  368,502.4     Squared Cor.: 0.061434

In [89]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+",disciplines, " | PublishedYear")
)
model2 <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model2)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
CoTypeCollaboration                           0.176029   0.010963  16.055991
CoTypeParticipation                           0.095087   0.014820   6.416025
lnnum_author                                 -0.130941   0.007103 -18.433963
internationalinternational                   -0.007958   0.008684  -0.916399
lnnum_reference                              -0.005923   0.008397  -0.705350
num_fac                                       0.050942   0.006548   7.779950
SDGTrue                                       0.087651   0.008086  10.840337
lnmean_career_age                            -0.007336   0.012674  -0.578814
Arts.and.Humanities                           1.805187   0.072180  25.009688
Biochemistry..Genetics.and.Molecular.Biology  0.488323   0.012268  39.804343
Business..Management.and.Accounting          -0.391345   0.087633  -4.465750
Chemical.Engineering                          0.118096   0.020734   5.695810
Chemistry                                     0.444182   0.010966  40.504784
Computer.Science                              0.885696   0.039163  22.615553
Decision.Sciences                             1.238200   0.185634   6.670124
Dentistry                                     1.986729   0.134600  14.760297
Earth.and.Planetary.Sciences                  0.718174   0.015107  47.537625
Economics..Econometrics.and.Finance          -0.174566   0.297157  -0.587455
Energy                                        0.167031   0.017788   9.390262
Engineering                                   0.327907   0.010299  31.839979
Environmental.Science                         0.543065   0.017326  31.344035
Health.Professions                            1.400534   0.127912  10.949218
Immunology.and.Microbiology                   0.103796   0.026436   3.926278
Materials.Science                             0.017062   0.009536   1.789206
Mathematics                                   0.544282   0.123426   4.409785
Medicine                                      0.770899   0.014524  53.076124
Neuroscience                                  0.459724   0.032017  14.358708
Nursing                                       1.138679   0.043461  26.199802
Pharmacology..Toxicology.and.Pharmaceutics    0.897898   0.047950  18.725619
Physics.and.Astronomy                        -0.245058   0.011148 -21.982119
Psychology                                    0.333723   0.152340   2.190644
Social.Sciences                               0.199570   0.159341   1.252474
Veterinary                                    0.583049   0.205573   2.836216
                                               Pr(>|z|)
CoTypeCollaboration                           < 2.2e-16 ***
CoTypeParticipation                          1.3988e-10 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   3.5946e-01
lnnum_reference                              4.8059e-01
num_fac                                      7.2553e-15 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            5.6271e-01
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          7.9789e-06 ***
Chemical.Engineering                         1.2279e-08 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            2.5559e-11 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          5.5690e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                  8.6270e-05 ***
Materials.Science                            7.3582e-02 .
Mathematics                                  1.0347e-05 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   2.8478e-02 *
Social.Sciences                              2.1040e-01
Veterinary                                   4.5652e-03 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -183,528.9   Adj. Pseudo R2: 0.048797
           BIC:  368,115.7     Squared Cor.: 0.062365

In [90]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+",disciplines, " | PublishedYear")
)
model3 <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model3)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
CoTypeCollaboration                           0.143687   0.011097  12.948869
CoTypeParticipation                           0.047011   0.014969   3.140640
lnnum_author                                 -0.068658   0.007116  -9.648419
internationalinternational                   -0.031089   0.009559  -3.252299
lnnum_reference                               0.061520   0.008603   7.150632
num_fac                                       0.059498   0.006605   9.007958
SDGTrue                                       0.092371   0.008114  11.384687
lnmean_career_age                             0.033050   0.012852   2.571617
lnex_ld_avg_avgimpact                        -0.264828   0.007259 -36.483771
lnex_ld_avg_insthindex                       -0.049529   0.007468  -6.632131
ex_ld_bin_gsGlobalNorth                       0.319559   0.017431  18.332975
ex_ld_bin_sameCSame                          -0.088044   0.009395  -9.371276
knowledge_proximity_mean                     -0.536984   0.156999  -3.420305
Arts.and.Humanities                           1.761999   0.072602  24.269151
Biochemistry..Genetics.and.Molecular.Biology  0.560437   0.012537  44.703274
Business..Management.and.Accounting          -0.344905   0.088174  -3.911635
Chemical.Engineering                          0.127998   0.020763   6.164848
Chemistry                                     0.436398   0.011069  39.426244
Computer.Science                              0.885328   0.039395  22.473379
Decision.Sciences                             1.205541   0.188256   6.403744
Dentistry                                     1.932497   0.135449  14.267307
Earth.and.Planetary.Sciences                  0.707815   0.015281  46.318485
Economics..Econometrics.and.Finance          -0.146465   0.292554  -0.500642
Energy                                        0.215856   0.017843  12.097741
Engineering                                   0.301371   0.010388  29.012331
Environmental.Science                         0.556121   0.017498  31.781864
Health.Professions                            1.376601   0.128348  10.725554
Immunology.and.Microbiology                   0.170265   0.026632   6.393299
Materials.Science                             0.001639   0.009727   0.168540
Mathematics                                   0.566115   0.123863   4.570476
Medicine                                      0.805057   0.014620  55.064785
Neuroscience                                  0.513867   0.032067  16.024855
Nursing                                       1.142418   0.043670  26.160014
Pharmacology..Toxicology.and.Pharmaceutics    0.891611   0.047942  18.597867
Physics.and.Astronomy                        -0.293480   0.011296 -25.979886
Psychology                                    0.370676   0.153231   2.419069
Social.Sciences                               0.155397   0.156885   0.990516
Veterinary                                    0.592872   0.205209   2.889114
                                               Pr(>|z|)
CoTypeCollaboration                           < 2.2e-16 ***
CoTypeParticipation                          1.6858e-03 **
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   1.1448e-03 **
lnnum_reference                              8.6379e-13 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            1.0122e-02 *
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                       3.3087e-11 ***
ex_ld_bin_gsGlobalNorth                       < 2.2e-16 ***
ex_ld_bin_sameCSame                           < 2.2e-16 ***
knowledge_proximity_mean                     6.2551e-04 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          9.1674e-05 ***
Chemical.Engineering                         7.0551e-10 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            1.5161e-10 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          6.1662e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                  1.6234e-10 ***
Materials.Science                            8.6616e-01
Mathematics                                  4.8662e-06 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   1.5560e-02 *
Social.Sciences                              3.2192e-01
Veterinary                                   3.8633e-03 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -182,548.0   Adj. Pseudo R2: 0.053853
           BIC:  366,216.9     Squared Cor.: 0.068979

In [91]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model4 <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model4)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
CoTypeCollaboration                           0.099926   0.011245   8.886446
CoTypeParticipation                           0.010299   0.015044   0.684582
lnnum_author                                 -0.087020   0.007328 -11.874570
internationalinternational                   -0.045118   0.009576  -4.711696
lnnum_reference                               0.059057   0.008633   6.841129
num_fac                                       0.062924   0.006715   9.369983
SDGTrue                                       0.093974   0.008128  11.561174
lnmean_career_age                             0.012005   0.013072   0.918354
lnex_ld_avg_avgimpact                        -0.269872   0.007355 -36.690437
lnex_ld_avg_insthindex                       -0.051397   0.007510  -6.844259
ex_ld_bin_gsGlobalNorth                       0.309880   0.017490  17.717256
ex_ld_bin_sameCSame                          -0.063400   0.009432  -6.721559
knowledge_proximity_mean                     -0.519050   0.159415  -3.255960
lnex_ld_avg_before_year_prod_fac             -0.049429   0.004953  -9.979480
ex_ld_max_before_year_with_ih_binTrue         0.341342   0.011341  30.097556
Arts.and.Humanities                           1.739659   0.073159  23.779227
Biochemistry..Genetics.and.Molecular.Biology  0.581832   0.012607  46.150420
Business..Management.and.Accounting          -0.356803   0.087998  -4.054647
Chemical.Engineering                          0.134750   0.020810   6.475235
Chemistry                                     0.423471   0.011105  38.132697
Computer.Science                              0.895903   0.039528  22.665211
Decision.Sciences                             1.190685   0.189362   6.287886
Dentistry                                     1.903426   0.136163  13.979002
Earth.and.Planetary.Sciences                  0.710429   0.015254  46.572210
Economics..Econometrics.and.Finance          -0.112709   0.295110  -0.381923
Energy                                        0.199571   0.017872  11.166486
Engineering                                   0.283702   0.010425  27.213022
Environmental.Science                         0.563181   0.017461  32.253949
Health.Professions                            1.369455   0.128704  10.640324
Immunology.and.Microbiology                   0.192720   0.026784   7.195428
Materials.Science                            -0.021025   0.009864  -2.131434
Mathematics                                   0.545550   0.125475   4.347874
Medicine                                      0.823541   0.014724  55.930203
Neuroscience                                  0.518029   0.032283  16.046508
Nursing                                       1.134037   0.043674  25.965997
Pharmacology..Toxicology.and.Pharmaceutics    0.892005   0.048193  18.509024
Physics.and.Astronomy                        -0.309036   0.011406 -27.095196
Psychology                                    0.395773   0.155025   2.552955
Social.Sciences                               0.123036   0.157185   0.782746
Veterinary                                    0.590046   0.206852   2.852509
                                               Pr(>|z|)
CoTypeCollaboration                           < 2.2e-16 ***
CoTypeParticipation                          4.9361e-01
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   2.4566e-06 ***
lnnum_reference                              7.8571e-12 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            3.5843e-01
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                       7.6873e-12 ***
ex_ld_bin_gsGlobalNorth                       < 2.2e-16 ***
ex_ld_bin_sameCSame                          1.7979e-11 ***
knowledge_proximity_mean                     1.1301e-03 **
lnex_ld_avg_before_year_prod_fac              < 2.2e-16 ***
ex_ld_max_before_year_with_ih_binTrue         < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          5.0210e-05 ***
Chemical.Engineering                         9.4665e-11 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            3.2182e-10 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          7.0252e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                  6.2265e-13 ***
Materials.Science                            3.3053e-02 *
Mathematics                                  1.3746e-05 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   1.0681e-02 *
Social.Sciences                              4.3378e-01
Veterinary                                   4.3376e-03 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -182,077.2   Adj. Pseudo R2: 0.056282
           BIC:  365,300.4     Squared Cor.: 0.072158

In [92]:
# 直接把 4 个模型并排放在一起
tab_latex <- etable(model1, model2, model3, model4,
                    keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                    se = "hetero",
                    tex = TRUE,
                    digits = 3,
                    fitstat = ~ n + r2 + ar2) # 可选：指定要在底部报告的统计量（如样本量、R方、调整R方）

# 打印出可以直接复制到 LaTeX 的代码
cat(tab_latex)

\begingroup \centering \begin{tabular}{lcccc}    \tabularnewline \midrule \midrule    Dependent Variable: & \multicolumn{4}{c}{novel\_uzzi\_bin}\\    Model:                                              & (1)            & (2)            & (3)            & (4)\\      \midrule    \emph{Variables}\\    CoTypeCollaboration                                 & 0.168$^{***}$  & 0.176$^{***}$  & 0.144$^{***}$  & 0.100$^{***}$\\                                                           & (0.011)        & (0.011)        & (0.011)        & (0.011)\\       CoTypeParticipation                                 & 0.047$^{***}$  & 0.095$^{***}$  & 0.047$^{***}$  & 0.010\\                                                           & (0.014)        & (0.015)        & (0.015)        & (0.015)\\       Arts.and.Humanities                                 & 1.84$^{***}$   & 1.81$^{***}$   & 1.76$^{***}$   & 1.74$^{***}$\\                                                           & (0.072)        & (0.072)        & (0.073)        & (0.073)\\       Biochemistry..Genetics.and.Molecular.Biology        & 0.498$^{***}$  & 0.488$^{***}$  & 0.560$^{***}$  & 0.582$^{***}$\\                                                           & (0.012)        & (0.012)        & (0.013)        & (0.013)\\       Business..Management.and.Accounting                 & -0.428$^{***}$ & -0.391$^{***}$ & -0.345$^{***}$ & -0.357$^{***}$\\                                                           & (0.088)        & (0.088)        & (0.088)        & (0.088)\\       Chemical.Engineering                                & 0.131$^{***}$  & 0.118$^{***}$  & 0.128$^{***}$  & 0.135$^{***}$\\                                                           & (0.021)        & (0.021)        & (0.021)        & (0.021)\\       Chemistry                                           & 0.459$^{***}$  & 0.444$^{***}$  & 0.436$^{***}$  & 0.423$^{***}$\\                                                           & (0.011)        & (0.011)        & (0.011)        & (0.011)\\       Computer.Science                                    & 0.897$^{***}$  & 0.886$^{***}$  & 0.885$^{***}$  & 0.896$^{***}$\\                                                           & (0.039)        & (0.039)        & (0.039)        & (0.040)\\       Decision.Sciences                                   & 1.23$^{***}$   & 1.24$^{***}$   & 1.21$^{***}$   & 1.19$^{***}$\\                                                           & (0.187)        & (0.186)        & (0.188)        & (0.189)\\       Dentistry                                           & 1.99$^{***}$   & 1.99$^{***}$   & 1.93$^{***}$   & 1.90$^{***}$\\                                                           & (0.135)        & (0.135)        & (0.135)        & (0.136)\\       Earth.and.Planetary.Sciences                        & 0.737$^{***}$  & 0.718$^{***}$  & 0.708$^{***}$  & 0.710$^{***}$\\                                                           & (0.015)        & (0.015)        & (0.015)        & (0.015)\\       Economics..Econometrics.and.Finance                 & -0.125         & -0.175         & -0.146         & -0.113\\                                                           & (0.298)        & (0.297)        & (0.293)        & (0.295)\\       Energy                                              & 0.173$^{***}$  & 0.167$^{***}$  & 0.216$^{***}$  & 0.200$^{***}$\\                                                           & (0.018)        & (0.018)        & (0.018)        & (0.018)\\       Engineering                                         & 0.340$^{***}$  & 0.328$^{***}$  & 0.301$^{***}$  & 0.284$^{***}$\\                                                           & (0.010)        & (0.010)        & (0.010)        & (0.010)\\       Immunology.and.Microbiology                         & 0.100$^{***}$  & 0.104$^{***}$  & 0.170$^{***}$  & 0.193$^{***}$\\                                                           & (0.026)        & (0.026)        & (0.027)        & (0.027)\\       Materials.Science                                   & 0.025$^{***}$  & 0.017$^{*}$    & 0.002          & -0.021$^{**}$\\                                                           & (0.009)        & (0.010)        & (0.010)        & (0.010)\\       Mathematics                                         & 0.563$^{***}$  & 0.544$^{***}$  & 0.566$^{***}$  & 0.546$^{***}$\\                                                           & (0.124)        & (0.123)        & (0.124)        & (0.125)\\       Medicine                                            & 0.769$^{***}$  & 0.771$^{***}$  & 0.805$^{***}$  & 0.824$^{***}$\\                                                           & (0.015)        & (0.015)        & (0.015)        & (0.015)\\       Neuroscience                                        & 0.460$^{***}$  & 0.460$^{***}$  & 0.514$^{***}$  & 0.518$^{***}$\\                                                           & (0.032)        & (0.032)        & (0.032)        & (0.032)\\       Nursing                                             & 1.15$^{***}$   & 1.14$^{***}$   & 1.14$^{***}$   & 1.13$^{***}$\\                                                           & (0.043)        & (0.043)        & (0.044)        & (0.044)\\       Pharmacology..Toxicology.and.Pharmaceutics          & 0.918$^{***}$  & 0.898$^{***}$  & 0.892$^{***}$  & 0.892$^{***}$\\                                                           & (0.048)        & (0.048)        & (0.048)        & (0.048)\\       Physics.and.Astronomy                               & -0.258$^{***}$ & -0.245$^{***}$ & -0.293$^{***}$ & -0.309$^{***}$\\                                                           & (0.011)        & (0.011)        & (0.011)        & (0.011)\\       Psychology                                          & 0.350$^{**}$   & 0.334$^{**}$   & 0.371$^{**}$   & 0.396$^{**}$\\                                                           & (0.151)        & (0.152)        & (0.153)        & (0.155)\\       Social.Sciences                                     & 0.191          & 0.200          & 0.155          & 0.123\\                                                           & (0.161)        & (0.159)        & (0.157)        & (0.157)\\       Veterinary                                          & 0.572$^{***}$  & 0.583$^{***}$  & 0.593$^{***}$  & 0.590$^{***}$\\                                                           & (0.204)        & (0.206)        & (0.205)        & (0.207)\\       lnnum\_author                                       &                & -0.131$^{***}$ & -0.069$^{***}$ & -0.087$^{***}$\\                                                           &                & (0.007)        & (0.007)        & (0.007)\\       internationalinternational                          &                & -0.008         & -0.031$^{***}$ & -0.045$^{***}$\\                                                           &                & (0.009)        & (0.010)        & (0.010)\\       lnnum\_reference                                    &                & -0.006         & 0.061$^{***}$  & 0.059$^{***}$\\                                                           &                & (0.008)        & (0.009)        & (0.009)\\       num\_fac                                            &                & 0.051$^{***}$  & 0.059$^{***}$  & 0.063$^{***}$\\                                                           &                & (0.007)        & (0.007)        & (0.007)\\       SDGTrue                                             &                & 0.088$^{***}$  & 0.092$^{***}$  & 0.094$^{***}$\\                                                           &                & (0.008)        & (0.008)        & (0.008)\\       lnmean\_career\_age                                 &                & -0.007         & 0.033$^{**}$   & 0.012\\                                                           &                & (0.013)        & (0.013)        & (0.013)\\       lnex\_ld\_avg\_avgimpact                            &                &                & -0.265$^{***}$ & -0.270$^{***}$\\                                                           &                &                & (0.007)        & (0.007)\\       lnex\_ld\_avg\_insthindex                           &                &                & -0.050$^{***}$ & -0.051$^{***}$\\                                                           &                &                & (0.007)        & (0.008)\\       ex\_ld\_bin\_gsGlobalNorth                          &                &                & 0.320$^{***}$  & 0.310$^{***}$\\                                                           &                &                & (0.017)        & (0.018)\\       ex\_ld\_bin\_sameCSame                              &                &                & -0.088$^{***}$ & -0.063$^{***}$\\                                                           &                &                & (0.009)        & (0.009)\\       knowledge\_proximity\_mean                          &                &                & -0.537$^{***}$ & -0.519$^{***}$\\                                                           &                &                & (0.157)        & (0.159)\\       lnex\_ld\_avg\_before\_year\_prod\_fac              &                &                &                & -0.049$^{***}$\\                                                           &                &                &                & (0.005)\\       ex\_ld\_max\_before\_year\_with\_ih\_binTrue        &                &                &                & 0.341$^{***}$\\                                                           &                &                &                & (0.011)\\       \midrule    \emph{Fixed-effects}\\    PublishedYear                                       & Yes            & Yes            & Yes            & Yes\\      \midrule    \emph{Fit statistics}\\    Observations                                        & 294,879        & 294,879        & 294,879        & 294,879\\      \midrule \midrule    \multicolumn{5}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\    \multicolumn{5}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\ \end{tabular} \par\endgroup